.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.16.1.dev0 */

.align 2
dlabel D_80012650
/* 2E50 80012650 */ .asciz "COST=%3d,%3d\n"
.align 2
.size D_80012650, . - D_80012650

.align 2
dlabel D_80012660
/* 2E60 80012660 */ .asciz "Assertion failed: file \"%s\", line %d\n"
.align 2
.align 2
/* 2E88 80012688 */ .asciz "m:\\AZ\\prog\\include\\gpuman.h"
.align 2
.size D_80012660, . - D_80012660

.align 2
dlabel D_800126A4
/* 2EA4 800126A4 */ .asciz "./REBOOT.C"
.align 2
.align 2
/* 2EB0 800126B0 */ .asciz "Assertion failed: file \"%s\", line %d\n"
.align 2
.align 2
/* 2ED8 800126D8 */ .asciz "m:\\AZ\\prog\\include\\gpuman.h"
.align 2
.size D_800126A4, . - D_800126A4

.align 2
dlabel D_800126F4
/* 2EF4 800126F4 */ .asciz "Sio Mode = ON\n"
.align 2
.size D_800126F4, . - D_800126F4

.align 2
dlabel D_80012704
/* 2F04 80012704 */ .asciz "PCinit\r"
.align 2
.size D_80012704, . - D_80012704

.align 2
dlabel D_8001270C
/* 2F0C 8001270C */ .asciz "break $%lx\r"
.align 2
.align 2
/* 2F18 80012718 */ .asciz ""
.align 2
.size D_8001270C, . - D_8001270C

dlabel jtbl_8001271C
/* 2F1C 8001271C B4EE0480 */ .word .L8004EEB4
/* 2F20 80012720 D0EE0480 */ .word .L8004EED0
/* 2F24 80012724 E0EE0480 */ .word .L8004EEE0
/* 2F28 80012728 F0EE0480 */ .word .L8004EEF0
/* 2F2C 8001272C 00EF0480 */ .word .L8004EF00
/* 2F30 80012730 10EF0480 */ .word .L8004EF10
/* 2F34 80012734 20EF0480 */ .word .L8004EF20
/* 2F38 80012738 00000000 */ .word 0x00000000
.size jtbl_8001271C, . - jtbl_8001271C

dlabel jtbl_8001273C
/* 2F3C 8001273C F0F10480 */ .word .L8004F1F0
/* 2F40 80012740 00F20480 */ .word .L8004F200
/* 2F44 80012744 14F20480 */ .word .L8004F214
/* 2F48 80012748 3CF20480 */ .word .L8004F23C
/* 2F4C 8001274C 5CF20480 */ .word .L8004F25C
/* 2F50 80012750 4CF20480 */ .word .L8004F24C
/* 2F54 80012754 C8F20480 */ .word .L8004F2C8
/* 2F58 80012758 6CF20480 */ .word .L8004F26C
/* 2F5C 8001275C 7CF20480 */ .word .L8004F27C
/* 2F60 80012760 90F20480 */ .word .L8004F290
/* 2F64 80012764 90F20480 */ .word .L8004F290
/* 2F68 80012768 C8F20480 */ .word .L8004F2C8
/* 2F6C 8001276C A0F20480 */ .word .L8004F2A0
/* 2F70 80012770 A0F20480 */ .word .L8004F2A0
/* 2F74 80012774 B0F20480 */ .word .L8004F2B0
/* 2F78 80012778 28F20480 */ .word .L8004F228
/* 2F7C 8001277C C0F20480 */ .word .L8004F2C0
.size jtbl_8001273C, . - jtbl_8001273C

.align 2
dlabel D_80012780
/* 2F80 80012780 */ .asciz "Assertion failed: file \"%s\", line %d\n"
.align 2
.align 2
/* 2FA8 800127A8 */ .asciz "m:\\AZ\\prog\\include\\gpuman.h"
.align 2
.size D_80012780, . - D_80012780

.align 2
dlabel D_800127C4
/* 2FC4 800127C4 */ .asciz "./TEXMAN.C"
.align 2
.align 2
/* 2FD0 800127D0 */ .asciz "Assertion failed: file \"%s\", line %d\n"
.align 2
.align 2
/* 2FF8 800127F8 */ .asciz "m:\\AZ\\prog\\include\\gpuman.h"
.align 2
.size D_800127C4, . - D_800127C4

.align 2
dlabel D_80012814
/* 3014 80012814 */ .asciz "Assertion failed: file \"%s\", line %d\n"
.align 2
.align 2
/* 303C 8001283C */ .asciz "m:\\AZ\\prog\\include\\gpuman.h"
.align 2
.size D_80012814, . - D_80012814

.align 2
dlabel D_80012858
/* 3058 80012858 */ .asciz "VH_FILE_SIZE"
.align 2
.size D_80012858, . - D_80012858

.align 2
dlabel D_80012868
/* 3068 80012868 */ .asciz "./MAINSUB.C"
.align 2
.size D_80012868, . - D_80012868

.align 2
dlabel D_80012874
/* 3074 80012874 */ .asciz "AZ.APF Dummy"
.align 2
.size D_80012874, . - D_80012874

.align 2
dlabel D_80012884
/* 3084 80012884 */ .asciz "Xap DumyTable"
.align 2
.size D_80012884, . - D_80012884

.align 2
dlabel D_80012894
/* 3094 80012894 */ .asciz "system/system.pac"
.align 2
.align 2
/* 30A8 800128A8 */ .asciz "CHAR VIEW"
.align 2
.align 2
/* 30B4 800128B4 */ .asciz "Char Viewer"
.align 2
.align 2
/* 30C0 800128C0 */ .asciz ""
.align 2
.size D_80012894, . - D_80012894

dlabel jtbl_800128C4
/* 30C4 800128C4 88140580 */ .word .L80051488
/* 30C8 800128C8 A0140580 */ .word .L800514A0
/* 30CC 800128CC E0140580 */ .word .L800514E0
/* 30D0 800128D0 14150580 */ .word .L80051514
/* 30D4 800128D4 24150580 */ .word .L80051524
/* 30D8 800128D8 58150580 */ .word .L80051558
/* 30DC 800128DC 8C150580 */ .word .L8005158C
/* 30E0 800128E0 00000000 */ .word 0x00000000
.size jtbl_800128C4, . - jtbl_800128C4

dlabel jtbl_800128E4
/* 30E4 800128E4 60160580 */ .word .L80051660
/* 30E8 800128E8 60160580 */ .word .L80051660
/* 30EC 800128EC BC160580 */ .word .L800516BC
/* 30F0 800128F0 F0160580 */ .word .L800516F0
/* 30F4 800128F4 2C170580 */ .word .L8005172C
/* 30F8 800128F8 60170580 */ .word .L80051760
/* 30FC 800128FC 70170580 */ .word .L80051770
.size jtbl_800128E4, . - jtbl_800128E4

.align 2
dlabel D_80012900
/* 3100 80012900 */ .asciz "CD001"
.align 2
.align 2
/* 3108 80012908 */ .asciz ""
.align 2
.align 2
/* 310C 8001290C */ .asciz ""
.align 2
.size D_80012900, . - D_80012900
