.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

# Handwritten function
glabel MulMatrix0
/* EED8 8001E6D8 0000888C */  lw         $t0, 0x0($a0)
/* EEDC 8001E6DC 0400898C */  lw         $t1, 0x4($a0)
/* EEE0 8001E6E0 08008A8C */  lw         $t2, 0x8($a0)
/* EEE4 8001E6E4 0C008B8C */  lw         $t3, 0xC($a0)
/* EEE8 8001E6E8 10008C8C */  lw         $t4, 0x10($a0)
/* EEEC 8001E6EC 0000C848 */  ctc2       $t0, $0 # handwritten instruction
/* EEF0 8001E6F0 0008C948 */  ctc2       $t1, $1 # handwritten instruction
/* EEF4 8001E6F4 0010CA48 */  ctc2       $t2, $2 # handwritten instruction
/* EEF8 8001E6F8 0018CB48 */  ctc2       $t3, $3 # handwritten instruction
/* EEFC 8001E6FC 0020CC48 */  ctc2       $t4, $4 # handwritten instruction
/* EF00 8001E700 0000A894 */  lhu        $t0, 0x0($a1)
/* EF04 8001E704 0400A98C */  lw         $t1, 0x4($a1)
/* EF08 8001E708 0C00AA8C */  lw         $t2, 0xC($a1)
/* EF0C 8001E70C FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
/* EF10 8001E710 24482101 */  and        $t1, $t1, $at
/* EF14 8001E714 25400901 */  or         $t0, $t0, $t1
/* EF18 8001E718 00008848 */  mtc2       $t0, $0 # handwritten instruction
/* EF1C 8001E71C 00088A48 */  mtc2       $t2, $1 # handwritten instruction
/* EF20 8001E720 00000000 */  nop
/* EF24 8001E724 1260484A */  MVMVA      1, 0, 0, 3, 0
/* EF28 8001E728 0200A894 */  lhu        $t0, 0x2($a1)
/* EF2C 8001E72C 0800A98C */  lw         $t1, 0x8($a1)
/* EF30 8001E730 0E00AA84 */  lh         $t2, 0xE($a1)
/* EF34 8001E734 004C0900 */  sll        $t1, $t1, 16
/* EF38 8001E738 25400901 */  or         $t0, $t0, $t1
/* EF3C 8001E73C 00480B48 */  mfc2       $t3, $9 # handwritten instruction
/* EF40 8001E740 00500C48 */  mfc2       $t4, $10 # handwritten instruction
/* EF44 8001E744 00580D48 */  mfc2       $t5, $11 # handwritten instruction
/* EF48 8001E748 00008848 */  mtc2       $t0, $0 # handwritten instruction
/* EF4C 8001E74C 00088A48 */  mtc2       $t2, $1 # handwritten instruction
/* EF50 8001E750 00000000 */  nop
/* EF54 8001E754 1260484A */  MVMVA      1, 0, 0, 3, 0
/* EF58 8001E758 0400A894 */  lhu        $t0, 0x4($a1)
/* EF5C 8001E75C 0800A98C */  lw         $t1, 0x8($a1)
/* EF60 8001E760 1000AA8C */  lw         $t2, 0x10($a1)
/* EF64 8001E764 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
/* EF68 8001E768 24482101 */  and        $t1, $t1, $at
/* EF6C 8001E76C 25400901 */  or         $t0, $t0, $t1
/* EF70 8001E770 00480E48 */  mfc2       $t6, $9 # handwritten instruction
/* EF74 8001E774 00500F48 */  mfc2       $t7, $10 # handwritten instruction
/* EF78 8001E778 00581848 */  mfc2       $t8, $11 # handwritten instruction
/* EF7C 8001E77C 00008848 */  mtc2       $t0, $0 # handwritten instruction
/* EF80 8001E780 00088A48 */  mtc2       $t2, $1 # handwritten instruction
/* EF84 8001E784 00000000 */  nop
/* EF88 8001E788 1260484A */  MVMVA      1, 0, 0, 3, 0
/* EF8C 8001E78C FFFF6B31 */  andi       $t3, $t3, 0xFFFF
/* EF90 8001E790 00740E00 */  sll        $t6, $t6, 16
/* EF94 8001E794 2570CB01 */  or         $t6, $t6, $t3
/* EF98 8001E798 0000CEAC */  sw         $t6, 0x0($a2)
/* EF9C 8001E79C FFFFAD31 */  andi       $t5, $t5, 0xFFFF
/* EFA0 8001E7A0 00C41800 */  sll        $t8, $t8, 16
/* EFA4 8001E7A4 25C00D03 */  or         $t8, $t8, $t5
/* EFA8 8001E7A8 0C00D8AC */  sw         $t8, 0xC($a2)
/* EFAC 8001E7AC 00480848 */  mfc2       $t0, $9 # handwritten instruction
/* EFB0 8001E7B0 00500948 */  mfc2       $t1, $10 # handwritten instruction
/* EFB4 8001E7B4 FFFF0831 */  andi       $t0, $t0, 0xFFFF
/* EFB8 8001E7B8 00640C00 */  sll        $t4, $t4, 16
/* EFBC 8001E7BC 25400C01 */  or         $t0, $t0, $t4
/* EFC0 8001E7C0 0400C8AC */  sw         $t0, 0x4($a2)
/* EFC4 8001E7C4 FFFFEF31 */  andi       $t7, $t7, 0xFFFF
/* EFC8 8001E7C8 004C0900 */  sll        $t1, $t1, 16
/* EFCC 8001E7CC 25482F01 */  or         $t1, $t1, $t7
/* EFD0 8001E7D0 0800C9AC */  sw         $t1, 0x8($a2)
/* EFD4 8001E7D4 1000CBE8 */  swc2       $11, 0x10($a2)
/* EFD8 8001E7D8 2110C000 */  addu       $v0, $a2, $zero
/* EFDC 8001E7DC 0800E003 */  jr         $ra
/* EFE0 8001E7E0 00000000 */   nop
/* EFE4 8001E7E4 00000000 */  nop
.size MulMatrix0, . - MulMatrix0
