.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

# Handwritten function
glabel SetRotMatrix
/* F378 8001EB78 0000888C */  lw         $t0, 0x0($a0)
/* F37C 8001EB7C 0400898C */  lw         $t1, 0x4($a0)
/* F380 8001EB80 08008A8C */  lw         $t2, 0x8($a0)
/* F384 8001EB84 0C008B8C */  lw         $t3, 0xC($a0)
/* F388 8001EB88 10008C8C */  lw         $t4, 0x10($a0)
/* F38C 8001EB8C 0000C848 */  ctc2       $t0, $0 # handwritten instruction
/* F390 8001EB90 0008C948 */  ctc2       $t1, $1 # handwritten instruction
/* F394 8001EB94 0010CA48 */  ctc2       $t2, $2 # handwritten instruction
/* F398 8001EB98 0018CB48 */  ctc2       $t3, $3 # handwritten instruction
/* F39C 8001EB9C 0020CC48 */  ctc2       $t4, $4 # handwritten instruction
/* F3A0 8001EBA0 0800E003 */  jr         $ra
/* F3A4 8001EBA4 00000000 */   nop
.size SetRotMatrix, . - SetRotMatrix
