.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

# Handwritten function
glabel RotTrans
/* 114B4 80020CB4 000080C8 */  lwc2       $0, 0x0($a0)
/* 114B8 80020CB8 040081C8 */  lwc2       $1, 0x4($a0)
/* 114BC 80020CBC 00000000 */  nop
/* 114C0 80020CC0 1200484A */  MVMVA      1, 0, 0, 0, 0
/* 114C4 80020CC4 0000B9E8 */  swc2       $25, 0x0($a1)
/* 114C8 80020CC8 0400BAE8 */  swc2       $26, 0x4($a1) # handwritten instruction
/* 114CC 80020CCC 0800BBE8 */  swc2       $27, 0x8($a1) # handwritten instruction
/* 114D0 80020CD0 00F84248 */  cfc2       $v0, $31 # handwritten instruction
/* 114D4 80020CD4 0800E003 */  jr         $ra
/* 114D8 80020CD8 0000C2AC */   sw        $v0, 0x0($a2)
/* 114DC 80020CDC 00000000 */  nop
/* 114E0 80020CE0 00000000 */  nop
.size RotTrans, . - RotTrans
