.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel setjmp
/* 5F2C 8001572C A0000A24 */  addiu      $t2, $zero, 0xA0
/* 5F30 80015730 08004001 */  jr         $t2
/* 5F34 80015734 13000924 */   addiu     $t1, $zero, 0x13
/* 5F38 80015738 00000000 */  nop
.size setjmp, . - setjmp
