.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel PadSetMainMode
/* 1EDD8 8002E5D8 0780023C */  lui        $v0, %hi(D_80069068)
/* 1EDDC 8002E5DC 6890428C */  lw         $v0, %lo(D_80069068)($v0)
/* 1EDE0 8002E5E0 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 1EDE4 8002E5E4 1800B2AF */  sw         $s2, 0x18($sp)
/* 1EDE8 8002E5E8 2190A000 */  addu       $s2, $a1, $zero
/* 1EDEC 8002E5EC 1400B1AF */  sw         $s1, 0x14($sp)
/* 1EDF0 8002E5F0 2188C000 */  addu       $s1, $a2, $zero
/* 1EDF4 8002E5F4 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 1EDF8 8002E5F8 09F84000 */  jalr       $v0
/* 1EDFC 8002E5FC 1000B0AF */   sw        $s0, 0x10($sp)
/* 1EE00 8002E600 21804000 */  addu       $s0, $v0, $zero
/* 1EE04 8002E604 0780023C */  lui        $v0, %hi(D_80069070)
/* 1EE08 8002E608 7090428C */  lw         $v0, %lo(D_80069070)($v0)
/* 1EE0C 8002E60C 00000000 */  nop
/* 1EE10 8002E610 09F84000 */  jalr       $v0
/* 1EE14 8002E614 21200002 */   addu      $a0, $s0, $zero
/* 1EE18 8002E618 10004014 */  bnez       $v0, .L8002E65C
/* 1EE1C 8002E61C 21100000 */   addu      $v0, $zero, $zero
/* 1EE20 8002E620 01000224 */  addiu      $v0, $zero, 0x1
/* 1EE24 8002E624 01000324 */  addiu      $v1, $zero, 0x1
/* 1EE28 8002E628 460003A2 */  sb         $v1, 0x46($s0)
/* 1EE2C 8002E62C 0380033C */  lui        $v1, %hi(PDCMD3_OBJ_9C)
/* 1EE30 8002E630 74E66324 */  addiu      $v1, $v1, %lo(PDCMD3_OBJ_9C)
/* 1EE34 8002E634 140003AE */  sw         $v1, 0x14($s0)
/* 1EE38 8002E638 E4000392 */  lbu        $v1, 0xE4($s0)
/* 1EE3C 8002E63C 0380043C */  lui        $a0, %hi(PDCMD3_OBJ_F4)
/* 1EE40 8002E640 CCE68424 */  addiu      $a0, $a0, %lo(PDCMD3_OBJ_F4)
/* 1EE44 8002E644 510012A2 */  sb         $s2, 0x51($s0)
/* 1EE48 8002E648 520011A2 */  sb         $s1, 0x52($s0)
/* 1EE4C 8002E64C 180004AE */  sw         $a0, 0x18($s0)
/* 1EE50 8002E650 26184302 */  xor        $v1, $s2, $v1
/* 1EE54 8002E654 0100632C */  sltiu      $v1, $v1, 0x1
/* 1EE58 8002E658 530003A2 */  sb         $v1, 0x53($s0)
.L8002E65C:
/* 1EE5C 8002E65C 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 1EE60 8002E660 1800B28F */  lw         $s2, 0x18($sp)
/* 1EE64 8002E664 1400B18F */  lw         $s1, 0x14($sp)
/* 1EE68 8002E668 1000B08F */  lw         $s0, 0x10($sp)
/* 1EE6C 8002E66C 0800E003 */  jr         $ra
/* 1EE70 8002E670 2000BD27 */   addiu     $sp, $sp, 0x20
.size PadSetMainMode, . - PadSetMainMode

glabel PDCMD3_OBJ_9C
/* 1EE74 8002E674 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1EE78 8002E678 1000BFAF */  sw         $ra, 0x10($sp)
/* 1EE7C 8002E67C 46008390 */  lbu        $v1, 0x46($a0)
/* 1EE80 8002E680 02000224 */  addiu      $v0, $zero, 0x2
/* 1EE84 8002E684 05006210 */  beq        $v1, $v0, .L8002E69C
/* 1EE88 8002E688 03000224 */   addiu     $v0, $zero, 0x3
/* 1EE8C 8002E68C 07006210 */  beq        $v1, $v0, .L8002E6AC
/* 1EE90 8002E690 4D000524 */   addiu     $a1, $zero, 0x4D
/* 1EE94 8002E694 AFB90008 */  j          PDCMD3_OBJ_E4
/* 1EE98 8002E698 00000000 */   nop
.L8002E69C:
/* 1EE9C 8002E69C 44000524 */  addiu      $a1, $zero, 0x44
/* 1EEA0 8002E6A0 51008624 */  addiu      $a2, $a0, 0x51
/* 1EEA4 8002E6A4 ADB90008 */  j          PDCMD3_OBJ_DC
/* 1EEA8 8002E6A8 02000724 */   addiu     $a3, $zero, 0x2
.L8002E6AC:
/* 1EEAC 8002E6AC 5D008624 */  addiu      $a2, $a0, 0x5D
/* 1EEB0 8002E6B0 06000724 */  addiu      $a3, $zero, 0x6
.size PDCMD3_OBJ_9C, . - PDCMD3_OBJ_9C

glabel PDCMD3_OBJ_DC
/* 1EEB4 8002E6B4 1FC0000C */  jal        _padSetCmd
/* 1EEB8 8002E6B8 00000000 */   nop
.size PDCMD3_OBJ_DC, . - PDCMD3_OBJ_DC

glabel PDCMD3_OBJ_E4
/* 1EEBC 8002E6BC 1000BF8F */  lw         $ra, 0x10($sp)
/* 1EEC0 8002E6C0 1800BD27 */  addiu      $sp, $sp, 0x18
/* 1EEC4 8002E6C4 0800E003 */  jr         $ra
/* 1EEC8 8002E6C8 00000000 */   nop
.size PDCMD3_OBJ_E4, . - PDCMD3_OBJ_E4

glabel PDCMD3_OBJ_F4
/* 1EECC 8002E6CC E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1EED0 8002E6D0 1000BFAF */  sw         $ra, 0x10($sp)
/* 1EED4 8002E6D4 53008290 */  lbu        $v0, 0x53($a0)
/* 1EED8 8002E6D8 00000000 */  nop
/* 1EEDC 8002E6DC 09004010 */  beqz       $v0, .L8002E704
/* 1EEE0 8002E6E0 02000224 */   addiu     $v0, $zero, 0x2
/* 1EEE4 8002E6E4 46008390 */  lbu        $v1, 0x46($a0)
/* 1EEE8 8002E6E8 00000000 */  nop
/* 1EEEC 8002E6EC 03006214 */  bne        $v1, $v0, .L8002E6FC
/* 1EEF0 8002E6F0 FE000224 */   addiu     $v0, $zero, 0xFE
/* 1EEF4 8002E6F4 C7B90008 */  j          PDCMD3_OBJ_144
/* 1EEF8 8002E6F8 01000224 */   addiu     $v0, $zero, 0x1
.L8002E6FC:
/* 1EEFC 8002E6FC C6B90008 */  j          PDCMD3_OBJ_140
/* 1EF00 8002E700 460082A0 */   sb        $v0, 0x46($a0)
.L8002E704:
/* 1EF04 8002E704 0780023C */  lui        $v0, %hi(D_80069058)
/* 1EF08 8002E708 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1EF0C 8002E70C 00000000 */  nop
/* 1EF10 8002E710 09F84000 */  jalr       $v0
/* 1EF14 8002E714 00000000 */   nop
.size PDCMD3_OBJ_F4, . - PDCMD3_OBJ_F4

glabel PDCMD3_OBJ_140
/* 1EF18 8002E718 21100000 */  addu       $v0, $zero, $zero
glabel PDCMD3_OBJ_144
/* 1EF1C 8002E71C 1000BF8F */  lw         $ra, 0x10($sp)
/* 1EF20 8002E720 1800BD27 */  addiu      $sp, $sp, 0x18
/* 1EF24 8002E724 0800E003 */  jr         $ra
/* 1EF28 8002E728 00000000 */   nop
/* 1EF2C 8002E72C 00000000 */  nop
/* 1EF30 8002E730 00000000 */  nop
/* 1EF34 8002E734 00000000 */  nop
.size PDCMD3_OBJ_140, . - PDCMD3_OBJ_140
