.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel PadGetState
/* 1EF38 8002E738 0780023C */  lui        $v0, %hi(D_80069068)
/* 1EF3C 8002E73C 6890428C */  lw         $v0, %lo(D_80069068)($v0)
/* 1EF40 8002E740 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1EF44 8002E744 1000BFAF */  sw         $ra, 0x10($sp)
/* 1EF48 8002E748 09F84000 */  jalr       $v0
/* 1EF4C 8002E74C 00000000 */   nop
/* 1EF50 8002E750 21184000 */  addu       $v1, $v0, $zero
/* 1EF54 8002E754 37006290 */  lbu        $v0, 0x37($v1)
/* 1EF58 8002E758 00000000 */  nop
/* 1EF5C 8002E75C 13004014 */  bnez       $v0, .L8002E7AC
/* 1EF60 8002E760 00000000 */   nop
/* 1EF64 8002E764 38006290 */  lbu        $v0, 0x38($v1)
/* 1EF68 8002E768 00000000 */  nop
/* 1EF6C 8002E76C 0F004014 */  bnez       $v0, .L8002E7AC
/* 1EF70 8002E770 00000000 */   nop
/* 1EF74 8002E774 1000628C */  lw         $v0, 0x10($v1)
/* 1EF78 8002E778 00000000 */  nop
/* 1EF7C 8002E77C 05006210 */  beq        $v1, $v0, .L8002E794
/* 1EF80 8002E780 00000000 */   nop
/* 1EF84 8002E784 39006290 */  lbu        $v0, 0x39($v1)
/* 1EF88 8002E788 00000000 */  nop
/* 1EF8C 8002E78C 07004014 */  bnez       $v0, .L8002E7AC
/* 1EF90 8002E790 00000000 */   nop
.L8002E794:
/* 1EF94 8002E794 3000628C */  lw         $v0, 0x30($v1)
/* 1EF98 8002E798 00000000 */  nop
/* 1EF9C 8002E79C 00004290 */  lbu        $v0, 0x0($v0)
/* 1EFA0 8002E7A0 00000000 */  nop
/* 1EFA4 8002E7A4 12004010 */  beqz       $v0, PDENT2_OBJ_B8
/* 1EFA8 8002E7A8 00000000 */   nop
.L8002E7AC:
/* 1EFAC 8002E7AC 49006490 */  lbu        $a0, 0x49($v1)
/* 1EFB0 8002E7B0 03000224 */  addiu      $v0, $zero, 0x3
/* 1EFB4 8002E7B4 0C008210 */  beq        $a0, $v0, .L8002E7E8
/* 1EFB8 8002E7B8 04008228 */   slti      $v0, $a0, 0x4
/* 1EFBC 8002E7BC 05004010 */  beqz       $v0, .L8002E7D4
/* 1EFC0 8002E7C0 02000224 */   addiu     $v0, $zero, 0x2
/* 1EFC4 8002E7C4 0B008210 */  beq        $a0, $v0, PDENT2_OBJ_BC
/* 1EFC8 8002E7C8 01000224 */   addiu     $v0, $zero, 0x1
/* 1EFCC 8002E7CC FCB90008 */  j          PDENT2_OBJ_B8
/* 1EFD0 8002E7D0 00000000 */   nop
.L8002E7D4:
/* 1EFD4 8002E7D4 06000224 */  addiu      $v0, $zero, 0x6
/* 1EFD8 8002E7D8 06008210 */  beq        $a0, $v0, PDENT2_OBJ_BC
/* 1EFDC 8002E7DC 04000224 */   addiu     $v0, $zero, 0x4
/* 1EFE0 8002E7E0 FCB90008 */  j          PDENT2_OBJ_B8
/* 1EFE4 8002E7E4 00000000 */   nop
.L8002E7E8:
/* 1EFE8 8002E7E8 FDB90008 */  j          PDENT2_OBJ_BC
/* 1EFEC 8002E7EC 01000224 */   addiu     $v0, $zero, 0x1
.size PadGetState, . - PadGetState

glabel PDENT2_OBJ_B8
/* 1EFF0 8002E7F0 49006290 */  lbu        $v0, 0x49($v1)
glabel PDENT2_OBJ_BC
/* 1EFF4 8002E7F4 1000BF8F */  lw         $ra, 0x10($sp)
/* 1EFF8 8002E7F8 1800BD27 */  addiu      $sp, $sp, 0x18
/* 1EFFC 8002E7FC 0800E003 */  jr         $ra
/* 1F000 8002E800 00000000 */   nop
/* 1F004 8002E804 00000000 */  nop
.size PDENT2_OBJ_B8, . - PDENT2_OBJ_B8
