.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel PadStartCom
/* 1F108 8002E908 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1F10C 8002E90C 1400BFAF */  sw         $ra, 0x14($sp)
/* 1F110 8002E910 1000B0AF */  sw         $s0, 0x10($sp)
/* 1F114 8002E914 0780013C */  lui        $at, %hi(D_8006908C)
/* 1F118 8002E918 9B61000C */  jal        EnterCriticalSection
/* 1F11C 8002E91C 8C9020AC */   sw        $zero, %lo(D_8006908C)($at)
/* 1F120 8002E920 02000424 */  addiu      $a0, $zero, 0x2
/* 1F124 8002E924 0780103C */  lui        $s0, %hi(D_800690B4)
/* 1F128 8002E928 B4901026 */  addiu      $s0, $s0, %lo(D_800690B4)
/* 1F12C 8002E92C 7972000C */  jal        SysDeqIntRP
/* 1F130 8002E930 21280002 */   addu      $a1, $s0, $zero
/* 1F134 8002E934 02000424 */  addiu      $a0, $zero, 0x2
/* 1F138 8002E938 7572000C */  jal        SysEnqIntRP
/* 1F13C 8002E93C 21280002 */   addu      $a1, $s0, $zero
/* 1F140 8002E940 03000424 */  addiu      $a0, $zero, 0x3
/* 1F144 8002E944 0780033C */  lui        $v1, %hi(D_8006902C)
/* 1F148 8002E948 2C90638C */  lw         $v1, %lo(D_8006902C)($v1)
/* 1F14C 8002E94C FEFF0224 */  addiu      $v0, $zero, -0x2
/* 1F150 8002E950 000062AC */  sw         $v0, 0x0($v1)
/* 1F154 8002E954 0400628C */  lw         $v0, 0x4($v1)
/* 1F158 8002E958 21280000 */  addu       $a1, $zero, $zero
/* 1F15C 8002E95C 01004234 */  ori        $v0, $v0, 0x1
/* 1F160 8002E960 3762000C */  jal        ChangeClearRCnt
/* 1F164 8002E964 040062AC */   sw        $v0, 0x4($v1)
/* 1F168 8002E968 9F61000C */  jal        ExitCriticalSection
/* 1F16C 8002E96C 00000000 */   nop
/* 1F170 8002E970 0780043C */  lui        $a0, %hi(D_80069088)
/* 1F174 8002E974 8890848C */  lw         $a0, %lo(D_80069088)($a0)
/* 1F178 8002E978 0780023C */  lui        $v0, %hi(D_80069058)
/* 1F17C 8002E97C 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1F180 8002E980 00000000 */  nop
/* 1F184 8002E984 09F84000 */  jalr       $v0
/* 1F188 8002E988 00000000 */   nop
/* 1F18C 8002E98C 0780043C */  lui        $a0, %hi(D_80069088)
/* 1F190 8002E990 8890848C */  lw         $a0, %lo(D_80069088)($a0)
/* 1F194 8002E994 0780023C */  lui        $v0, %hi(D_80069058)
/* 1F198 8002E998 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1F19C 8002E99C 00000000 */  nop
/* 1F1A0 8002E9A0 09F84000 */  jalr       $v0
/* 1F1A4 8002E9A4 F0008424 */   addiu     $a0, $a0, 0xF0
/* 1F1A8 8002E9A8 0780023C */  lui        $v0, %hi(D_80072F00)
/* 1F1AC 8002E9AC 002F4224 */  addiu      $v0, $v0, %lo(D_80072F00)
/* 1F1B0 8002E9B0 040040AC */  sw         $zero, 0x4($v0)
/* 1F1B4 8002E9B4 000040AC */  sw         $zero, 0x0($v0)
/* 1F1B8 8002E9B8 01000224 */  addiu      $v0, $zero, 0x1
/* 1F1BC 8002E9BC 0780013C */  lui        $at, %hi(D_8006908C)
/* 1F1C0 8002E9C0 8C9022AC */  sw         $v0, %lo(D_8006908C)($at)
/* 1F1C4 8002E9C4 1400BF8F */  lw         $ra, 0x14($sp)
/* 1F1C8 8002E9C8 1000B08F */  lw         $s0, 0x10($sp)
/* 1F1CC 8002E9CC 0800E003 */  jr         $ra
/* 1F1D0 8002E9D0 1800BD27 */   addiu     $sp, $sp, 0x18
.size PadStartCom, . - PadStartCom

glabel PadStopCom
/* 1F1D4 8002E9D4 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1F1D8 8002E9D8 1000BFAF */  sw         $ra, 0x10($sp)
/* 1F1DC 8002E9DC 9B61000C */  jal        EnterCriticalSection
/* 1F1E0 8002E9E0 00000000 */   nop
/* 1F1E4 8002E9E4 03000424 */  addiu      $a0, $zero, 0x3
/* 1F1E8 8002E9E8 3762000C */  jal        ChangeClearRCnt
/* 1F1EC 8002E9EC 01000524 */   addiu     $a1, $zero, 0x1
/* 1F1F0 8002E9F0 0780053C */  lui        $a1, %hi(D_800690B4)
/* 1F1F4 8002E9F4 B490A524 */  addiu      $a1, $a1, %lo(D_800690B4)
/* 1F1F8 8002E9F8 7972000C */  jal        SysDeqIntRP
/* 1F1FC 8002E9FC 02000424 */   addiu     $a0, $zero, 0x2
/* 1F200 8002EA00 9F61000C */  jal        ExitCriticalSection
/* 1F204 8002EA04 00000000 */   nop
/* 1F208 8002EA08 1000BF8F */  lw         $ra, 0x10($sp)
/* 1F20C 8002EA0C 1800BD27 */  addiu      $sp, $sp, 0x18
/* 1F210 8002EA10 0800E003 */  jr         $ra
/* 1F214 8002EA14 00000000 */   nop
.size PadStopCom, . - PadStopCom

glabel PadInitDirect
/* 1F218 8002EA18 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 1F21C 8002EA1C 1000B0AF */  sw         $s0, 0x10($sp)
/* 1F220 8002EA20 21808000 */  addu       $s0, $a0, $zero
/* 1F224 8002EA24 1400B1AF */  sw         $s1, 0x14($sp)
/* 1F228 8002EA28 1800BFAF */  sw         $ra, 0x18($sp)
/* 1F22C 8002EA2C 0780013C */  lui        $at, %hi(D_8006908C)
/* 1F230 8002EA30 8C9020AC */  sw         $zero, %lo(D_8006908C)($at)
/* 1F234 8002EA34 0780013C */  lui        $at, %hi(D_800690A0)
/* 1F238 8002EA38 A09020AC */  sw         $zero, %lo(D_800690A0)($at)
/* 1F23C 8002EA3C B2BA000C */  jal        _padInitDirPort
/* 1F240 8002EA40 2188A000 */   addu      $s1, $a1, $zero
/* 1F244 8002EA44 21380000 */  addu       $a3, $zero, $zero
/* 1F248 8002EA48 0780023C */  lui        $v0, %hi(D_80069088)
/* 1F24C 8002EA4C 8890428C */  lw         $v0, %lo(D_80069088)($v0)
/* 1F250 8002EA50 FF000824 */  addiu      $t0, $zero, 0xFF
/* 1F254 8002EA54 21304000 */  addu       $a2, $v0, $zero
/* 1F258 8002EA58 3000C524 */  addiu      $a1, $a2, 0x30
/* 1F25C 8002EA5C 3000D0AC */  sw         $s0, 0x30($a2)
/* 1F260 8002EA60 2001D1AC */  sw         $s1, 0x120($a2)
.L8002EA64:
/* 1F264 8002EA64 0000A28C */  lw         $v0, 0x0($a1)
/* 1F268 8002EA68 5D00C424 */  addiu      $a0, $a2, 0x5D
/* 1F26C 8002EA6C DCFFA0AC */  sw         $zero, -0x24($a1)
/* 1F270 8002EA70 E0FFA6AC */  sw         $a2, -0x20($a1)
/* 1F274 8002EA74 000048A0 */  sb         $t0, 0x0($v0)
/* 1F278 8002EA78 0000A28C */  lw         $v0, 0x0($a1)
/* 1F27C 8002EA7C 05000324 */  addiu      $v1, $zero, 0x5
/* 1F280 8002EA80 010040A0 */  sb         $zero, 0x1($v0)
.L8002EA84:
/* 1F284 8002EA84 000088A0 */  sb         $t0, 0x0($a0)
/* 1F288 8002EA88 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1F28C 8002EA8C FDFF6104 */  bgez       $v1, .L8002EA84
/* 1F290 8002EA90 01008424 */   addiu     $a0, $a0, 0x1
/* 1F294 8002EA94 0100E724 */  addiu      $a3, $a3, 0x1
/* 1F298 8002EA98 F000A524 */  addiu      $a1, $a1, 0xF0
/* 1F29C 8002EA9C 0200E228 */  slti       $v0, $a3, 0x2
/* 1F2A0 8002EAA0 F0FF4014 */  bnez       $v0, .L8002EA64
/* 1F2A4 8002EAA4 F000C624 */   addiu     $a2, $a2, 0xF0
/* 1F2A8 8002EAA8 01000224 */  addiu      $v0, $zero, 0x1
/* 1F2AC 8002EAAC 0780013C */  lui        $at, %hi(D_8006908C)
/* 1F2B0 8002EAB0 8C9022AC */  sw         $v0, %lo(D_8006908C)($at)
/* 1F2B4 8002EAB4 1800BF8F */  lw         $ra, 0x18($sp)
/* 1F2B8 8002EAB8 1400B18F */  lw         $s1, 0x14($sp)
/* 1F2BC 8002EABC 1000B08F */  lw         $s0, 0x10($sp)
/* 1F2C0 8002EAC0 0800E003 */  jr         $ra
/* 1F2C4 8002EAC4 2000BD27 */   addiu     $sp, $sp, 0x20
.size PadInitDirect, . - PadInitDirect

glabel _padInitDirPort
/* 1F2C8 8002EAC8 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1F2CC 8002EACC 1000B0AF */  sw         $s0, 0x10($sp)
/* 1F2D0 8002EAD0 0780103C */  lui        $s0, %hi(D_80072C80)
/* 1F2D4 8002EAD4 802C1026 */  addiu      $s0, $s0, %lo(D_80072C80)
/* 1F2D8 8002EAD8 21200002 */  addu       $a0, $s0, $zero
/* 1F2DC 8002EADC 1400BFAF */  sw         $ra, 0x14($sp)
/* 1F2E0 8002EAE0 F976000C */  jal        bzero
/* 1F2E4 8002EAE4 E0010524 */   addiu     $a1, $zero, 0x1E0
/* 1F2E8 8002EAE8 0780023C */  lui        $v0, %hi(D_80072E60)
/* 1F2EC 8002EAEC 602E4224 */  addiu      $v0, $v0, %lo(D_80072E60)
/* 1F2F0 8002EAF0 0780033C */  lui        $v1, %hi(D_80072EA8)
/* 1F2F4 8002EAF4 A82E6324 */  addiu      $v1, $v1, %lo(D_80072EA8)
/* 1F2F8 8002EAF8 3C0002AE */  sw         $v0, 0x3C($s0)
/* 1F2FC 8002EAFC 23004224 */  addiu      $v0, $v0, 0x23
/* 1F300 8002EB00 400003AE */  sw         $v1, 0x40($s0)
/* 1F304 8002EB04 23006324 */  addiu      $v1, $v1, 0x23
/* 1F308 8002EB08 2C0102AE */  sw         $v0, 0x12C($s0)
/* 1F30C 8002EB0C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_158)
/* 1F310 8002EB10 20EC4224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_158)
/* 1F314 8002EB14 0780013C */  lui        $at, %hi(D_80069054)
/* 1F318 8002EB18 549022AC */  sw         $v0, %lo(D_80069054)($at)
/* 1F31C 8002EB1C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_F0)
/* 1F320 8002EB20 B8EB4224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_F0)
/* 1F324 8002EB24 0780013C */  lui        $at, %hi(D_80069058)
/* 1F328 8002EB28 589022AC */  sw         $v0, %lo(D_80069058)($at)
/* 1F32C 8002EB2C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_25C)
/* 1F330 8002EB30 24ED4224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_25C)
/* 1F334 8002EB34 0780013C */  lui        $at, %hi(D_8006905C)
/* 1F338 8002EB38 5C9022AC */  sw         $v0, %lo(D_8006905C)($at)
/* 1F33C 8002EB3C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_318)
/* 1F340 8002EB40 E0ED4224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_318)
/* 1F344 8002EB44 0780013C */  lui        $at, %hi(D_80069060)
/* 1F348 8002EB48 609022AC */  sw         $v0, %lo(D_80069060)($at)
/* 1F34C 8002EB4C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_594)
/* 1F350 8002EB50 5CF04224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_594)
/* 1F354 8002EB54 0780013C */  lui        $at, %hi(D_80069068)
/* 1F358 8002EB58 689022AC */  sw         $v0, %lo(D_80069068)($at)
/* 1F35C 8002EB5C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_24C)
/* 1F360 8002EB60 14ED4224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_24C)
/* 1F364 8002EB64 0780013C */  lui        $at, %hi(D_80069078)
/* 1F368 8002EB68 789022AC */  sw         $v0, %lo(D_80069078)($at)
/* 1F36C 8002EB6C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_5B4)
/* 1F370 8002EB70 7CF04224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_5B4)
/* 1F374 8002EB74 0780013C */  lui        $at, %hi(D_8006906C)
/* 1F378 8002EB78 6C9022AC */  sw         $v0, %lo(D_8006906C)($at)
/* 1F37C 8002EB7C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_A10)
/* 1F380 8002EB80 D8F44224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_A10)
/* 1F384 8002EB84 0780013C */  lui        $at, %hi(D_80069070)
/* 1F388 8002EB88 709022AC */  sw         $v0, %lo(D_80069070)($at)
/* 1F38C 8002EB8C 0380023C */  lui        $v0, %hi(PDDIRRES_OBJ_6C4)
/* 1F390 8002EB90 8CF14224 */  addiu      $v0, $v0, %lo(PDDIRRES_OBJ_6C4)
/* 1F394 8002EB94 0780013C */  lui        $at, %hi(D_80069088)
/* 1F398 8002EB98 889030AC */  sw         $s0, %lo(D_80069088)($at)
/* 1F39C 8002EB9C 300103AE */  sw         $v1, 0x130($s0)
/* 1F3A0 8002EBA0 0780013C */  lui        $at, %hi(D_80069074)
/* 1F3A4 8002EBA4 749022AC */  sw         $v0, %lo(D_80069074)($at)
/* 1F3A8 8002EBA8 1400BF8F */  lw         $ra, 0x14($sp)
/* 1F3AC 8002EBAC 1000B08F */  lw         $s0, 0x10($sp)
/* 1F3B0 8002EBB0 0800E003 */  jr         $ra
/* 1F3B4 8002EBB4 1800BD27 */   addiu     $sp, $sp, 0x18
.size _padInitDirPort, . - _padInitDirPort

glabel PDDIRRES_OBJ_F0
/* 1F3B8 8002EBB8 49008290 */  lbu        $v0, 0x49($a0)
/* 1F3BC 8002EBBC 00000000 */  nop
/* 1F3C0 8002EBC0 15004010 */  beqz       $v0, .L8002EC18
/* 1F3C4 8002EBC4 00000000 */   nop
/* 1F3C8 8002EBC8 5D008324 */  addiu      $v1, $a0, 0x5D
/* 1F3CC 8002EBCC FF000524 */  addiu      $a1, $zero, 0xFF
/* 1F3D0 8002EBD0 05000224 */  addiu      $v0, $zero, 0x5
/* 1F3D4 8002EBD4 490080A0 */  sb         $zero, 0x49($a0)
/* 1F3D8 8002EBD8 460080A0 */  sb         $zero, 0x46($a0)
/* 1F3DC 8002EBDC E60080A4 */  sh         $zero, 0xE6($a0)
/* 1F3E0 8002EBE0 140080AC */  sw         $zero, 0x14($a0)
/* 1F3E4 8002EBE4 180080AC */  sw         $zero, 0x18($a0)
/* 1F3E8 8002EBE8 E30080A0 */  sb         $zero, 0xE3($a0)
/* 1F3EC 8002EBEC E40080A0 */  sb         $zero, 0xE4($a0)
/* 1F3F0 8002EBF0 E60080A4 */  sh         $zero, 0xE6($a0)
/* 1F3F4 8002EBF4 E90080A0 */  sb         $zero, 0xE9($a0)
/* 1F3F8 8002EBF8 EA0080A0 */  sb         $zero, 0xEA($a0)
/* 1F3FC 8002EBFC 000080AC */  sw         $zero, 0x0($a0)
/* 1F400 8002EC00 040080AC */  sw         $zero, 0x4($a0)
/* 1F404 8002EC04 080080AC */  sw         $zero, 0x8($a0)
.L8002EC08:
/* 1F408 8002EC08 000065A0 */  sb         $a1, 0x0($v1)
/* 1F40C 8002EC0C FFFF4224 */  addiu      $v0, $v0, -0x1
/* 1F410 8002EC10 FDFF4104 */  bgez       $v0, .L8002EC08
/* 1F414 8002EC14 01006324 */   addiu     $v1, $v1, 0x1
.L8002EC18:
/* 1F418 8002EC18 0800E003 */  jr         $ra
/* 1F41C 8002EC1C 00000000 */   nop
.size PDDIRRES_OBJ_F0, . - PDDIRRES_OBJ_F0

glabel PDDIRRES_OBJ_158
/* 1F420 8002EC20 D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 1F424 8002EC24 21288000 */  addu       $a1, $a0, $zero
/* 1F428 8002EC28 1400B1AF */  sw         $s1, 0x14($sp)
/* 1F42C 8002EC2C 0780113C */  lui        $s1, %hi(D_80072C80)
/* 1F430 8002EC30 802C3126 */  addiu      $s1, $s1, %lo(D_80072C80)
/* 1F434 8002EC34 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 1F438 8002EC38 F7FF1324 */  addiu      $s3, $zero, -0x9
/* 1F43C 8002EC3C 1800B2AF */  sw         $s2, 0x18($sp)
/* 1F440 8002EC40 0780123C */  lui        $s2, %hi(D_800690AC)
/* 1F444 8002EC44 AC905226 */  addiu      $s2, $s2, %lo(D_800690AC)
/* 1F448 8002EC48 2000BFAF */  sw         $ra, 0x20($sp)
/* 1F44C 8002EC4C 1000B0AF */  sw         $s0, 0x10($sp)
.L8002EC50:
/* 1F450 8002EC50 0780033C */  lui        $v1, %hi(D_80069094)
/* 1F454 8002EC54 9490638C */  lw         $v1, %lo(D_80069094)($v1)
/* 1F458 8002EC58 00000000 */  nop
/* 1F45C 8002EC5C 00110300 */  sll        $v0, $v1, 4
/* 1F460 8002EC60 23104300 */  subu       $v0, $v0, $v1
/* 1F464 8002EC64 00110200 */  sll        $v0, $v0, 4
/* 1F468 8002EC68 0A00B310 */  beq        $a1, $s3, PDDIRRES_OBJ_1CC
/* 1F46C 8002EC6C 21805100 */   addu      $s0, $v0, $s1
/* 1F470 8002EC70 0400A014 */  bnez       $a1, .L8002EC84
/* 1F474 8002EC74 80100300 */   sll       $v0, $v1, 2
/* 1F478 8002EC78 21105200 */  addu       $v0, $v0, $s2
/* 1F47C 8002EC7C 25BB0008 */  j          PDDIRRES_OBJ_1CC
/* 1F480 8002EC80 000040AC */   sw        $zero, 0x0($v0)
.L8002EC84:
/* 1F484 8002EC84 FEBC000C */  jal        _dirFailAuto
/* 1F488 8002EC88 21200002 */   addu      $a0, $s0, $zero
/* 1F48C 8002EC8C 45BB000C */  jal        PDDIRRES_OBJ_24C
/* 1F490 8002EC90 21200002 */   addu      $a0, $s0, $zero
.size PDDIRRES_OBJ_158, . - PDDIRRES_OBJ_158

glabel PDDIRRES_OBJ_1CC
/* 1F494 8002EC94 0780023C */  lui        $v0, %hi(D_8006903C)
/* 1F498 8002EC98 3C90428C */  lw         $v0, %lo(D_8006903C)($v0)
/* 1F49C 8002EC9C 0780033C */  lui        $v1, %hi(D_80069094)
/* 1F4A0 8002ECA0 9490638C */  lw         $v1, %lo(D_80069094)($v1)
/* 1F4A4 8002ECA4 0780013C */  lui        $at, %hi(D_80069098)
/* 1F4A8 8002ECA8 989020AC */  sw         $zero, %lo(D_80069098)($at)
/* 1F4AC 8002ECAC 0A0040A4 */  sh         $zero, 0xA($v0)
/* 1F4B0 8002ECB0 0780023C */  lui        $v0, %hi(D_800690A8)
/* 1F4B4 8002ECB4 A890428C */  lw         $v0, %lo(D_800690A8)($v0)
/* 1F4B8 8002ECB8 01006324 */  addiu      $v1, $v1, 0x1
/* 1F4BC 8002ECBC 0780013C */  lui        $at, %hi(D_80069094)
/* 1F4C0 8002ECC0 949023AC */  sw         $v1, %lo(D_80069094)($at)
/* 1F4C4 8002ECC4 2A104300 */  slt        $v0, $v0, $v1
/* 1F4C8 8002ECC8 08004014 */  bnez       $v0, .L8002ECEC
/* 1F4CC 8002ECCC 01000224 */   addiu     $v0, $zero, 0x1
/* 1F4D0 8002ECD0 00210300 */  sll        $a0, $v1, 4
/* 1F4D4 8002ECD4 23208300 */  subu       $a0, $a0, $v1
/* 1F4D8 8002ECD8 00210400 */  sll        $a0, $a0, 4
/* 1F4DC 8002ECDC C0BD000C */  jal        _padInitSioMode
/* 1F4E0 8002ECE0 21209100 */   addu      $a0, $a0, $s1
/* 1F4E4 8002ECE4 3CBB0008 */  j          PDDIRRES_OBJ_228
/* 1F4E8 8002ECE8 FFFF0534 */   ori       $a1, $zero, 0xFFFF
.L8002ECEC:
/* 1F4EC 8002ECEC FFFF0534 */  ori        $a1, $zero, 0xFFFF
.size PDDIRRES_OBJ_1CC, . - PDDIRRES_OBJ_1CC

glabel PDDIRRES_OBJ_228
/* 1F4F0 8002ECF0 D7FF4010 */  beqz       $v0, .L8002EC50
/* 1F4F4 8002ECF4 00000000 */   nop
/* 1F4F8 8002ECF8 2000BF8F */  lw         $ra, 0x20($sp)
/* 1F4FC 8002ECFC 1C00B38F */  lw         $s3, 0x1C($sp)
/* 1F500 8002ED00 1800B28F */  lw         $s2, 0x18($sp)
/* 1F504 8002ED04 1400B18F */  lw         $s1, 0x14($sp)
/* 1F508 8002ED08 1000B08F */  lw         $s0, 0x10($sp)
/* 1F50C 8002ED0C 0800E003 */  jr         $ra
/* 1F510 8002ED10 2800BD27 */   addiu     $sp, $sp, 0x28
.size PDDIRRES_OBJ_228, . - PDDIRRES_OBJ_228

glabel PDDIRRES_OBJ_24C
/* 1F514 8002ED14 37008290 */  lbu        $v0, 0x37($a0)
/* 1F518 8002ED18 370080A0 */  sb         $zero, 0x37($a0)
/* 1F51C 8002ED1C 0800E003 */  jr         $ra
/* 1F520 8002ED20 380082A0 */   sb        $v0, 0x38($a0)
.size PDDIRRES_OBJ_24C, . - PDDIRRES_OBJ_24C

glabel PDDIRRES_OBJ_25C
/* 1F524 8002ED24 45008290 */  lbu        $v0, 0x45($a0)
/* 1F528 8002ED28 37008590 */  lbu        $a1, 0x37($a0)
/* 1F52C 8002ED2C 00000000 */  nop
/* 1F530 8002ED30 0600A010 */  beqz       $a1, .L8002ED4C
/* 1F534 8002ED34 FDFF4324 */   addiu     $v1, $v0, -0x3
/* 1F538 8002ED38 4D000224 */  addiu      $v0, $zero, 0x4D
/* 1F53C 8002ED3C 1500A210 */  beq        $a1, $v0, .L8002ED94
/* 1F540 8002ED40 00000000 */   nop
/* 1F544 8002ED44 6DBB0008 */  j          PDDIRRES_OBJ_2EC
/* 1F548 8002ED48 00000000 */   nop
.L8002ED4C:
/* 1F54C 8002ED4C 06006228 */  slti       $v0, $v1, 0x6
/* 1F550 8002ED50 05004010 */  beqz       $v0, .L8002ED68
/* 1F554 8002ED54 21108300 */   addu      $v0, $a0, $v1
/* 1F558 8002ED58 57004290 */  lbu        $v0, 0x57($v0)
/* 1F55C 8002ED5C 00000000 */  nop
/* 1F560 8002ED60 1D004010 */  beqz       $v0, PDDIRRES_OBJ_310
/* 1F564 8002ED64 21100000 */   addu      $v0, $zero, $zero
.L8002ED68:
/* 1F568 8002ED68 34008290 */  lbu        $v0, 0x34($a0)
/* 1F56C 8002ED6C 00000000 */  nop
/* 1F570 8002ED70 2A106200 */  slt        $v0, $v1, $v0
/* 1F574 8002ED74 18004010 */  beqz       $v0, PDDIRRES_OBJ_310
/* 1F578 8002ED78 21100000 */   addu      $v0, $zero, $zero
/* 1F57C 8002ED7C 2800828C */  lw         $v0, 0x28($a0)
/* 1F580 8002ED80 00000000 */  nop
/* 1F584 8002ED84 21104300 */  addu       $v0, $v0, $v1
.size PDDIRRES_OBJ_25C, . - PDDIRRES_OBJ_25C

glabel PDDIRRES_OBJ_2C0
/* 1F588 8002ED88 00004290 */  lbu        $v0, 0x0($v0)
/* 1F58C 8002ED8C 76BB0008 */  j          PDDIRRES_OBJ_310
/* 1F590 8002ED90 00000000 */   nop
.L8002ED94:
/* 1F594 8002ED94 36008290 */  lbu        $v0, 0x36($a0)
/* 1F598 8002ED98 00000000 */  nop
/* 1F59C 8002ED9C 2A106200 */  slt        $v0, $v1, $v0
/* 1F5A0 8002EDA0 0D004010 */  beqz       $v0, PDDIRRES_OBJ_310
/* 1F5A4 8002EDA4 FF000224 */   addiu     $v0, $zero, 0xFF
/* 1F5A8 8002EDA8 2C00828C */  lw         $v0, 0x2C($a0)
/* 1F5AC 8002EDAC 62BB0008 */  j          PDDIRRES_OBJ_2C0
/* 1F5B0 8002EDB0 21104300 */   addu      $v0, $v0, $v1
.size PDDIRRES_OBJ_2C0, . - PDDIRRES_OBJ_2C0

glabel PDDIRRES_OBJ_2EC
/* 1F5B4 8002EDB4 36008290 */  lbu        $v0, 0x36($a0)
/* 1F5B8 8002EDB8 00000000 */  nop
/* 1F5BC 8002EDBC 2A106200 */  slt        $v0, $v1, $v0
/* 1F5C0 8002EDC0 05004010 */  beqz       $v0, PDDIRRES_OBJ_310
/* 1F5C4 8002EDC4 21100000 */   addu      $v0, $zero, $zero
/* 1F5C8 8002EDC8 2C00828C */  lw         $v0, 0x2C($a0)
/* 1F5CC 8002EDCC 00000000 */  nop
/* 1F5D0 8002EDD0 21104300 */  addu       $v0, $v0, $v1
/* 1F5D4 8002EDD4 00004290 */  lbu        $v0, 0x0($v0)
.size PDDIRRES_OBJ_2EC, . - PDDIRRES_OBJ_2EC

glabel PDDIRRES_OBJ_310
/* 1F5D8 8002EDD8 0800E003 */  jr         $ra
/* 1F5DC 8002EDDC 00000000 */   nop
.size PDDIRRES_OBJ_310, . - PDDIRRES_OBJ_310

glabel PDDIRRES_OBJ_318
/* 1F5E0 8002EDE0 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1F5E4 8002EDE4 1000B0AF */  sw         $s0, 0x10($sp)
/* 1F5E8 8002EDE8 21808000 */  addu       $s0, $a0, $zero
/* 1F5EC 8002EDEC 57000426 */  addiu      $a0, $s0, 0x57
/* 1F5F0 8002EDF0 1400BFAF */  sw         $ra, 0x14($sp)
/* 1F5F4 8002EDF4 F976000C */  jal        bzero
/* 1F5F8 8002EDF8 06000524 */   addiu     $a1, $zero, 0x6
/* 1F5FC 8002EDFC E6000296 */  lhu        $v0, 0xE6($s0)
/* 1F600 8002EE00 00000000 */  nop
/* 1F604 8002EE04 54004010 */  beqz       $v0, .L8002EF58
/* 1F608 8002EE08 00000000 */   nop
/* 1F60C 8002EE0C 2800028E */  lw         $v0, 0x28($s0)
/* 1F610 8002EE10 00000000 */  nop
/* 1F614 8002EE14 50004010 */  beqz       $v0, .L8002EF58
/* 1F618 8002EE18 00000000 */   nop
/* 1F61C 8002EE1C 34000292 */  lbu        $v0, 0x34($s0)
/* 1F620 8002EE20 00000000 */  nop
/* 1F624 8002EE24 0700422C */  sltiu      $v0, $v0, 0x7
/* 1F628 8002EE28 02004010 */  beqz       $v0, .L8002EE34
/* 1F62C 8002EE2C 06000924 */   addiu     $t1, $zero, 0x6
/* 1F630 8002EE30 34000992 */  lbu        $t1, 0x34($s0)
.L8002EE34:
/* 1F634 8002EE34 E9000292 */  lbu        $v0, 0xE9($s0)
/* 1F638 8002EE38 00000000 */  nop
/* 1F63C 8002EE3C 83004010 */  beqz       $v0, PDDIRRES_OBJ_584
/* 1F640 8002EE40 21400000 */   addu      $t0, $zero, $zero
/* 1F644 8002EE44 01000B24 */  addiu      $t3, $zero, 0x1
/* 1F648 8002EE48 21500000 */  addu       $t2, $zero, $zero
.L8002EE4C:
/* 1F64C 8002EE4C 0400028E */  lw         $v0, 0x4($s0)
/* 1F650 8002EE50 21300000 */  addu       $a2, $zero, $zero
/* 1F654 8002EE54 21104201 */  addu       $v0, $t2, $v0
/* 1F658 8002EE58 02004290 */  lbu        $v0, 0x2($v0)
/* 1F65C 8002EE5C 00000000 */  nop
/* 1F660 8002EE60 02004010 */  beqz       $v0, .L8002EE6C
/* 1F664 8002EE64 01000724 */   addiu     $a3, $zero, 0x1
/* 1F668 8002EE68 FF000724 */  addiu      $a3, $zero, 0xFF
.L8002EE6C:
/* 1F66C 8002EE6C 5D000526 */  addiu      $a1, $s0, 0x5D
/* 1F670 8002EE70 2800048E */  lw         $a0, 0x28($s0)
/* 1F674 8002EE74 0F002011 */  beqz       $t1, .L8002EEB4
/* 1F678 8002EE78 21180000 */   addu      $v1, $zero, $zero
.L8002EE7C:
/* 1F67C 8002EE7C 0000A290 */  lbu        $v0, 0x0($a1)
/* 1F680 8002EE80 00000000 */  nop
/* 1F684 8002EE84 06004814 */  bne        $v0, $t0, .L8002EEA0
/* 1F688 8002EE88 00000000 */   nop
/* 1F68C 8002EE8C 00008290 */  lbu        $v0, 0x0($a0)
/* 1F690 8002EE90 00000000 */  nop
/* 1F694 8002EE94 24104700 */  and        $v0, $v0, $a3
/* 1F698 8002EE98 16004014 */  bnez       $v0, .L8002EEF4
/* 1F69C 8002EE9C 00000000 */   nop
.L8002EEA0:
/* 1F6A0 8002EEA0 0100A524 */  addiu      $a1, $a1, 0x1
/* 1F6A4 8002EEA4 01006324 */  addiu      $v1, $v1, 0x1
/* 1F6A8 8002EEA8 2A106900 */  slt        $v0, $v1, $t1
/* 1F6AC 8002EEAC F3FF4014 */  bnez       $v0, .L8002EE7C
/* 1F6B0 8002EEB0 01008424 */   addiu     $a0, $a0, 0x1
.L8002EEB4:
/* 1F6B4 8002EEB4 2100C010 */  beqz       $a2, .L8002EF3C
/* 1F6B8 8002EEB8 00000000 */   nop
/* 1F6BC 8002EEBC 0400028E */  lw         $v0, 0x4($s0)
/* 1F6C0 8002EEC0 00000000 */  nop
/* 1F6C4 8002EEC4 21104201 */  addu       $v0, $t2, $v0
/* 1F6C8 8002EEC8 03004390 */  lbu        $v1, 0x3($v0)
/* 1F6CC 8002EECC 0780023C */  lui        $v0, %hi(D_8006909C)
/* 1F6D0 8002EED0 9C90428C */  lw         $v0, %lo(D_8006909C)($v0)
/* 1F6D4 8002EED4 00000000 */  nop
/* 1F6D8 8002EED8 21184300 */  addu       $v1, $v0, $v1
/* 1F6DC 8002EEDC 3D006228 */  slti       $v0, $v1, 0x3D
/* 1F6E0 8002EEE0 06004010 */  beqz       $v0, .L8002EEFC
/* 1F6E4 8002EEE4 00000000 */   nop
/* 1F6E8 8002EEE8 0780013C */  lui        $at, %hi(D_8006909C)
/* 1F6EC 8002EEEC C0BB0008 */  j          .L8002EF00
/* 1F6F0 8002EEF0 9C9023AC */   sw        $v1, %lo(D_8006909C)($at)
.L8002EEF4:
/* 1F6F4 8002EEF4 ADBB0008 */  j          .L8002EEB4
/* 1F6F8 8002EEF8 01000624 */   addiu     $a2, $zero, 0x1
.L8002EEFC:
/* 1F6FC 8002EEFC 21300000 */  addu       $a2, $zero, $zero
.L8002EF00:
/* 1F700 8002EF00 0E00C010 */  beqz       $a2, .L8002EF3C
/* 1F704 8002EF04 00000000 */   nop
/* 1F708 8002EF08 5D000526 */  addiu      $a1, $s0, 0x5D
/* 1F70C 8002EF0C 57000426 */  addiu      $a0, $s0, 0x57
/* 1F710 8002EF10 0A002011 */  beqz       $t1, .L8002EF3C
/* 1F714 8002EF14 21180000 */   addu      $v1, $zero, $zero
.L8002EF18:
/* 1F718 8002EF18 0000A290 */  lbu        $v0, 0x0($a1)
/* 1F71C 8002EF1C 00000000 */  nop
/* 1F720 8002EF20 02004814 */  bne        $v0, $t0, .L8002EF2C
/* 1F724 8002EF24 0100A524 */   addiu     $a1, $a1, 0x1
/* 1F728 8002EF28 00008BA0 */  sb         $t3, 0x0($a0)
.L8002EF2C:
/* 1F72C 8002EF2C 01006324 */  addiu      $v1, $v1, 0x1
/* 1F730 8002EF30 2A106900 */  slt        $v0, $v1, $t1
/* 1F734 8002EF34 F8FF4014 */  bnez       $v0, .L8002EF18
/* 1F738 8002EF38 01008424 */   addiu     $a0, $a0, 0x1
.L8002EF3C:
/* 1F73C 8002EF3C E9000292 */  lbu        $v0, 0xE9($s0)
/* 1F740 8002EF40 01000825 */  addiu      $t0, $t0, 0x1
/* 1F744 8002EF44 2A100201 */  slt        $v0, $t0, $v0
/* 1F748 8002EF48 C0FF4014 */  bnez       $v0, .L8002EE4C
/* 1F74C 8002EF4C 05004A25 */   addiu     $t2, $t2, 0x5
/* 1F750 8002EF50 13BC0008 */  j          PDDIRRES_OBJ_584
/* 1F754 8002EF54 00000000 */   nop
.L8002EF58:
/* 1F758 8002EF58 E8000392 */  lbu        $v1, 0xE8($s0)
/* 1F75C 8002EF5C 00000000 */  nop
/* 1F760 8002EF60 FCFF6224 */  addiu      $v0, $v1, -0x4
/* 1F764 8002EF64 0200422C */  sltiu      $v0, $v0, 0x2
/* 1F768 8002EF68 03004014 */  bnez       $v0, .L8002EF78
/* 1F76C 8002EF6C 07000224 */   addiu     $v0, $zero, 0x7
/* 1F770 8002EF70 26006214 */  bne        $v1, $v0, .L8002F00C
/* 1F774 8002EF74 00000000 */   nop
.L8002EF78:
/* 1F778 8002EF78 E6000296 */  lhu        $v0, 0xE6($s0)
/* 1F77C 8002EF7C 00000000 */  nop
/* 1F780 8002EF80 22004014 */  bnez       $v0, .L8002F00C
/* 1F784 8002EF84 00000000 */   nop
/* 1F788 8002EF88 34000292 */  lbu        $v0, 0x34($s0)
/* 1F78C 8002EF8C 00000000 */  nop
/* 1F790 8002EF90 0200422C */  sltiu      $v0, $v0, 0x2
/* 1F794 8002EF94 1D004014 */  bnez       $v0, .L8002F00C
/* 1F798 8002EF98 40000324 */   addiu     $v1, $zero, 0x40
/* 1F79C 8002EF9C 2800048E */  lw         $a0, 0x28($s0)
/* 1F7A0 8002EFA0 00000000 */  nop
/* 1F7A4 8002EFA4 00008290 */  lbu        $v0, 0x0($a0)
/* 1F7A8 8002EFA8 00000000 */  nop
/* 1F7AC 8002EFAC C0004230 */  andi       $v0, $v0, 0xC0
/* 1F7B0 8002EFB0 26004314 */  bne        $v0, $v1, PDDIRRES_OBJ_584
/* 1F7B4 8002EFB4 00000000 */   nop
/* 1F7B8 8002EFB8 01008290 */  lbu        $v0, 0x1($a0)
/* 1F7BC 8002EFBC 00000000 */  nop
/* 1F7C0 8002EFC0 01004230 */  andi       $v0, $v0, 0x1
/* 1F7C4 8002EFC4 21004010 */  beqz       $v0, PDDIRRES_OBJ_584
/* 1F7C8 8002EFC8 00000000 */   nop
/* 1F7CC 8002EFCC 0780023C */  lui        $v0, %hi(D_8006909C)
/* 1F7D0 8002EFD0 9C90428C */  lw         $v0, %lo(D_8006909C)($v0)
/* 1F7D4 8002EFD4 00000000 */  nop
/* 1F7D8 8002EFD8 0A004224 */  addiu      $v0, $v0, 0xA
/* 1F7DC 8002EFDC 3D004228 */  slti       $v0, $v0, 0x3D
/* 1F7E0 8002EFE0 1A004010 */  beqz       $v0, PDDIRRES_OBJ_584
/* 1F7E4 8002EFE4 01000224 */   addiu     $v0, $zero, 0x1
/* 1F7E8 8002EFE8 580002A2 */  sb         $v0, 0x58($s0)
/* 1F7EC 8002EFEC 570002A2 */  sb         $v0, 0x57($s0)
/* 1F7F0 8002EFF0 0780023C */  lui        $v0, %hi(D_8006909C)
/* 1F7F4 8002EFF4 9C90428C */  lw         $v0, %lo(D_8006909C)($v0)
/* 1F7F8 8002EFF8 00000000 */  nop
/* 1F7FC 8002EFFC 0A004224 */  addiu      $v0, $v0, 0xA
/* 1F800 8002F000 0780013C */  lui        $at, %hi(D_8006909C)
/* 1F804 8002F004 13BC0008 */  j          PDDIRRES_OBJ_584
/* 1F808 8002F008 9C9022AC */   sw        $v0, %lo(D_8006909C)($at)
.L8002F00C:
/* 1F80C 8002F00C E8000392 */  lbu        $v1, 0xE8($s0)
/* 1F810 8002F010 03000224 */  addiu      $v0, $zero, 0x3
/* 1F814 8002F014 03006214 */  bne        $v1, $v0, .L8002F024
/* 1F818 8002F018 01000224 */   addiu     $v0, $zero, 0x1
/* 1F81C 8002F01C 13BC0008 */  j          PDDIRRES_OBJ_584
/* 1F820 8002F020 570002A2 */   sb        $v0, 0x57($s0)
.L8002F024:
/* 1F824 8002F024 E6000296 */  lhu        $v0, 0xE6($s0)
/* 1F828 8002F028 00000000 */  nop
/* 1F82C 8002F02C 07004014 */  bnez       $v0, PDDIRRES_OBJ_584
/* 1F830 8002F030 01000224 */   addiu     $v0, $zero, 0x1
/* 1F834 8002F034 05000324 */  addiu      $v1, $zero, 0x5
/* 1F838 8002F038 05000426 */  addiu      $a0, $s0, 0x5
.L8002F03C:
/* 1F83C 8002F03C 570082A0 */  sb         $v0, 0x57($a0)
/* 1F840 8002F040 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1F844 8002F044 FDFF6104 */  bgez       $v1, .L8002F03C
/* 1F848 8002F048 FFFF8424 */   addiu     $a0, $a0, -0x1
.size PDDIRRES_OBJ_318, . - PDDIRRES_OBJ_318

glabel PDDIRRES_OBJ_584
/* 1F84C 8002F04C 1400BF8F */  lw         $ra, 0x14($sp)
/* 1F850 8002F050 1000B08F */  lw         $s0, 0x10($sp)
/* 1F854 8002F054 0800E003 */  jr         $ra
/* 1F858 8002F058 1800BD27 */   addiu     $sp, $sp, 0x18
.size PDDIRRES_OBJ_584, . - PDDIRRES_OBJ_584

glabel PDDIRRES_OBJ_594
/* 1F85C 8002F05C 0780023C */  lui        $v0, %hi(D_80072C80)
/* 1F860 8002F060 802C4224 */  addiu      $v0, $v0, %lo(D_80072C80)
/* 1F864 8002F064 F0008430 */  andi       $a0, $a0, 0xF0
/* 1F868 8002F068 02008010 */  beqz       $a0, .L8002F074
/* 1F86C 8002F06C 00000000 */   nop
/* 1F870 8002F070 F0004224 */  addiu      $v0, $v0, 0xF0
.L8002F074:
/* 1F874 8002F074 0800E003 */  jr         $ra
/* 1F878 8002F078 00000000 */   nop
.size PDDIRRES_OBJ_594, . - PDDIRRES_OBJ_594

glabel PDDIRRES_OBJ_5B4
/* 1F87C 8002F07C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1F880 8002F080 1000B0AF */  sw         $s0, 0x10($sp)
/* 1F884 8002F084 21808000 */  addu       $s0, $a0, $zero
/* 1F888 8002F088 1400BFAF */  sw         $ra, 0x14($sp)
/* 1F88C 8002F08C 3C00028E */  lw         $v0, 0x3C($s0)
/* 1F890 8002F090 00000000 */  nop
/* 1F894 8002F094 00004390 */  lbu        $v1, 0x0($v0)
/* 1F898 8002F098 F3000224 */  addiu      $v0, $zero, 0xF3
/* 1F89C 8002F09C 12006214 */  bne        $v1, $v0, .L8002F0E8
/* 1F8A0 8002F0A0 00000000 */   nop
/* 1F8A4 8002F0A4 E8000292 */  lbu        $v0, 0xE8($s0)
/* 1F8A8 8002F0A8 00000000 */  nop
/* 1F8AC 8002F0AC 24004010 */  beqz       $v0, .L8002F140
/* 1F8B0 8002F0B0 FF000224 */   addiu     $v0, $zero, 0xFF
/* 1F8B4 8002F0B4 46000392 */  lbu        $v1, 0x46($s0)
/* 1F8B8 8002F0B8 00000000 */  nop
/* 1F8BC 8002F0BC 1F006210 */  beq        $v1, $v0, .L8002F13C
/* 1F8C0 8002F0C0 02000224 */   addiu     $v0, $zero, 0x2
/* 1F8C4 8002F0C4 49000392 */  lbu        $v1, 0x49($s0)
/* 1F8C8 8002F0C8 00000000 */  nop
/* 1F8CC 8002F0CC 06006214 */  bne        $v1, $v0, .L8002F0E8
/* 1F8D0 8002F0D0 00000000 */   nop
/* 1F8D4 8002F0D4 0780023C */  lui        $v0, %hi(D_80069058)
/* 1F8D8 8002F0D8 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1F8DC 8002F0DC 00000000 */  nop
/* 1F8E0 8002F0E0 09F84000 */  jalr       $v0
/* 1F8E4 8002F0E4 21200002 */   addu      $a0, $s0, $zero
.L8002F0E8:
/* 1F8E8 8002F0E8 46000392 */  lbu        $v1, 0x46($s0)
/* 1F8EC 8002F0EC 01000224 */  addiu      $v0, $zero, 0x1
/* 1F8F0 8002F0F0 0D006210 */  beq        $v1, $v0, .L8002F128
/* 1F8F4 8002F0F4 02006228 */   slti      $v0, $v1, 0x2
/* 1F8F8 8002F0F8 05004010 */  beqz       $v0, .L8002F110
/* 1F8FC 8002F0FC FE000224 */   addiu     $v0, $zero, 0xFE
/* 1F900 8002F100 1E006010 */  beqz       $v1, PDDIRRES_OBJ_6B4
/* 1F904 8002F104 21100000 */   addu      $v0, $zero, $zero
/* 1F908 8002F108 54BC0008 */  j          PDDIRRES_OBJ_688
/* 1F90C 8002F10C 00000000 */   nop
.L8002F110:
/* 1F910 8002F110 0A006210 */  beq        $v1, $v0, .L8002F13C
/* 1F914 8002F114 FF000224 */   addiu     $v0, $zero, 0xFF
/* 1F918 8002F118 18006210 */  beq        $v1, $v0, PDDIRRES_OBJ_6B4
/* 1F91C 8002F11C 21100000 */   addu      $v0, $zero, $zero
/* 1F920 8002F120 54BC0008 */  j          PDDIRRES_OBJ_688
/* 1F924 8002F124 00000000 */   nop
.L8002F128:
/* 1F928 8002F128 21200002 */  addu       $a0, $s0, $zero
/* 1F92C 8002F12C 4BC2000C */  jal        _padCmdParaMode
/* 1F930 8002F130 01000524 */   addiu     $a1, $zero, 0x1
/* 1F934 8002F134 5FBC0008 */  j          PDDIRRES_OBJ_6B4
/* 1F938 8002F138 21100000 */   addu      $v0, $zero, $zero
.L8002F13C:
/* 1F93C 8002F13C 21200002 */  addu       $a0, $s0, $zero
.L8002F140:
/* 1F940 8002F140 4BC2000C */  jal        _padCmdParaMode
/* 1F944 8002F144 21280000 */   addu      $a1, $zero, $zero
/* 1F948 8002F148 5FBC0008 */  j          PDDIRRES_OBJ_6B4
/* 1F94C 8002F14C 21100000 */   addu      $v0, $zero, $zero
.size PDDIRRES_OBJ_5B4, . - PDDIRRES_OBJ_5B4

glabel PDDIRRES_OBJ_688
/* 1F950 8002F150 1400028E */  lw         $v0, 0x14($s0)
/* 1F954 8002F154 00000000 */  nop
/* 1F958 8002F158 05004010 */  beqz       $v0, .L8002F170
/* 1F95C 8002F15C 00000000 */   nop
/* 1F960 8002F160 09F84000 */  jalr       $v0
/* 1F964 8002F164 21200002 */   addu      $a0, $s0, $zero
/* 1F968 8002F168 5FBC0008 */  j          PDDIRRES_OBJ_6B4
/* 1F96C 8002F16C 21100000 */   addu      $v0, $zero, $zero
.L8002F170:
/* 1F970 8002F170 23C0000C */  jal        _padSendAtLoadInfo
/* 1F974 8002F174 21200002 */   addu      $a0, $s0, $zero
/* 1F978 8002F178 21100000 */  addu       $v0, $zero, $zero
.size PDDIRRES_OBJ_688, . - PDDIRRES_OBJ_688

glabel PDDIRRES_OBJ_6B4
/* 1F97C 8002F17C 1400BF8F */  lw         $ra, 0x14($sp)
/* 1F980 8002F180 1000B08F */  lw         $s0, 0x10($sp)
/* 1F984 8002F184 0800E003 */  jr         $ra
/* 1F988 8002F188 1800BD27 */   addiu     $sp, $sp, 0x18
.size PDDIRRES_OBJ_6B4, . - PDDIRRES_OBJ_6B4

glabel PDDIRRES_OBJ_6C4
/* 1F98C 8002F18C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1F990 8002F190 1000B0AF */  sw         $s0, 0x10($sp)
/* 1F994 8002F194 21808000 */  addu       $s0, $a0, $zero
/* 1F998 8002F198 1400BFAF */  sw         $ra, 0x14($sp)
/* 1F99C 8002F19C 3C00038E */  lw         $v1, 0x3C($s0)
/* 1F9A0 8002F1A0 00000000 */  nop
/* 1F9A4 8002F1A4 00006290 */  lbu        $v0, 0x0($v1)
/* 1F9A8 8002F1A8 00000000 */  nop
/* 1F9AC 8002F1AC F0004230 */  andi       $v0, $v0, 0xF0
/* 1F9B0 8002F1B0 10004014 */  bnez       $v0, .L8002F1F4
/* 1F9B4 8002F1B4 FF000224 */   addiu     $v0, $zero, 0xFF
/* 1F9B8 8002F1B8 3000038E */  lw         $v1, 0x30($s0)
/* 1F9BC 8002F1BC 00000000 */  nop
/* 1F9C0 8002F1C0 000062A0 */  sb         $v0, 0x0($v1)
/* 1F9C4 8002F1C4 3000028E */  lw         $v0, 0x30($s0)
/* 1F9C8 8002F1C8 00000000 */  nop
/* 1F9CC 8002F1CC 010040A0 */  sb         $zero, 0x1($v0)
/* 1F9D0 8002F1D0 E80000A2 */  sb         $zero, 0xE8($s0)
/* 1F9D4 8002F1D4 350000A2 */  sb         $zero, 0x35($s0)
/* 1F9D8 8002F1D8 0780023C */  lui        $v0, %hi(D_80069058)
/* 1F9DC 8002F1DC 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1F9E0 8002F1E0 00000000 */  nop
/* 1F9E4 8002F1E4 09F84000 */  jalr       $v0
/* 1F9E8 8002F1E8 00000000 */   nop
/* 1F9EC 8002F1EC FABC0008 */  j          PDDIRRES_OBJ_920
/* 1F9F0 8002F1F0 00000000 */   nop
.L8002F1F4:
/* 1F9F4 8002F1F4 00006290 */  lbu        $v0, 0x0($v1)
/* 1F9F8 8002F1F8 0F000324 */  addiu      $v1, $zero, 0xF
/* 1F9FC 8002F1FC E8000592 */  lbu        $a1, 0xE8($s0)
/* 1FA00 8002F200 02110200 */  srl        $v0, $v0, 4
/* 1FA04 8002F204 03004314 */  bne        $v0, $v1, .L8002F214
/* 1FA08 8002F208 E80002A2 */   sb        $v0, 0xE8($s0)
/* 1FA0C 8002F20C 9DBC0008 */  j          PDDIRRES_OBJ_7AC
/* 1FA10 8002F210 E80005A2 */   sb        $a1, 0xE8($s0)
.L8002F214:
/* 1FA14 8002F214 3000028E */  lw         $v0, 0x30($s0)
/* 1FA18 8002F218 00000000 */  nop
/* 1FA1C 8002F21C 000040A0 */  sb         $zero, 0x0($v0)
/* 1FA20 8002F220 3C00028E */  lw         $v0, 0x3C($s0)
/* 1FA24 8002F224 3000038E */  lw         $v1, 0x30($s0)
/* 1FA28 8002F228 00004290 */  lbu        $v0, 0x0($v0)
/* 1FA2C 8002F22C 02000424 */  addiu      $a0, $zero, 0x2
/* 1FA30 8002F230 010062A0 */  sb         $v0, 0x1($v1)
/* 1FA34 8002F234 44000292 */  lbu        $v0, 0x44($s0)
/* 1FA38 8002F238 44000392 */  lbu        $v1, 0x44($s0)
/* 1FA3C 8002F23C 2A108200 */  slt        $v0, $a0, $v0
/* 1FA40 8002F240 0C004010 */  beqz       $v0, PDDIRRES_OBJ_7AC
/* 1FA44 8002F244 350003A2 */   sb        $v1, 0x35($s0)
.L8002F248:
/* 1FA48 8002F248 3C00028E */  lw         $v0, 0x3C($s0)
/* 1FA4C 8002F24C 3000038E */  lw         $v1, 0x30($s0)
/* 1FA50 8002F250 21104400 */  addu       $v0, $v0, $a0
/* 1FA54 8002F254 00004290 */  lbu        $v0, 0x0($v0)
/* 1FA58 8002F258 21186400 */  addu       $v1, $v1, $a0
/* 1FA5C 8002F25C 000062A0 */  sb         $v0, 0x0($v1)
/* 1FA60 8002F260 44000292 */  lbu        $v0, 0x44($s0)
/* 1FA64 8002F264 01008424 */  addiu      $a0, $a0, 0x1
/* 1FA68 8002F268 2A108200 */  slt        $v0, $a0, $v0
/* 1FA6C 8002F26C F6FF4014 */  bnez       $v0, .L8002F248
/* 1FA70 8002F270 00000000 */   nop
.size PDDIRRES_OBJ_6C4, . - PDDIRRES_OBJ_6C4

glabel PDDIRRES_OBJ_7AC
/* 1FA74 8002F274 3C00028E */  lw         $v0, 0x3C($s0)
/* 1FA78 8002F278 00000000 */  nop
/* 1FA7C 8002F27C 01004290 */  lbu        $v0, 0x1($v0)
/* 1FA80 8002F280 00000000 */  nop
/* 1FA84 8002F284 0D004014 */  bnez       $v0, .L8002F2BC
/* 1FA88 8002F288 01000224 */   addiu     $v0, $zero, 0x1
/* 1FA8C 8002F28C 46000392 */  lbu        $v1, 0x46($s0)
/* 1FA90 8002F290 00000000 */  nop
/* 1FA94 8002F294 05006214 */  bne        $v1, $v0, .L8002F2AC
/* 1FA98 8002F298 00000000 */   nop
/* 1FA9C 8002F29C 1400028E */  lw         $v0, 0x14($s0)
/* 1FAA0 8002F2A0 00000000 */  nop
/* 1FAA4 8002F2A4 05004010 */  beqz       $v0, .L8002F2BC
/* 1FAA8 8002F2A8 00000000 */   nop
.L8002F2AC:
/* 1FAAC 8002F2AC 50000292 */  lbu        $v0, 0x50($s0)
/* 1FAB0 8002F2B0 00000000 */  nop
/* 1FAB4 8002F2B4 05004010 */  beqz       $v0, .L8002F2CC
/* 1FAB8 8002F2B8 00000000 */   nop
.L8002F2BC:
/* 1FABC 8002F2BC E8000292 */  lbu        $v0, 0xE8($s0)
/* 1FAC0 8002F2C0 00000000 */  nop
/* 1FAC4 8002F2C4 06004510 */  beq        $v0, $a1, .L8002F2E0
/* 1FAC8 8002F2C8 00000000 */   nop
.L8002F2CC:
/* 1FACC 8002F2CC 0780023C */  lui        $v0, %hi(D_80069058)
/* 1FAD0 8002F2D0 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1FAD4 8002F2D4 00000000 */  nop
/* 1FAD8 8002F2D8 09F84000 */  jalr       $v0
/* 1FADC 8002F2DC 21200002 */   addu      $a0, $s0, $zero
.L8002F2E0:
/* 1FAE0 8002F2E0 46000492 */  lbu        $a0, 0x46($s0)
/* 1FAE4 8002F2E4 FF000224 */  addiu      $v0, $zero, 0xFF
/* 1FAE8 8002F2E8 FF008330 */  andi       $v1, $a0, 0xFF
/* 1FAEC 8002F2EC 3E006210 */  beq        $v1, $v0, PDDIRRES_OBJ_920
/* 1FAF0 8002F2F0 4A0000A2 */   sb        $zero, 0x4A($s0)
/* 1FAF4 8002F2F4 05006010 */  beqz       $v1, .L8002F30C
/* 1FAF8 8002F2F8 FEFF8224 */   addiu     $v0, $a0, -0x2
/* 1FAFC 8002F2FC 37000292 */  lbu        $v0, 0x37($s0)
/* 1FB00 8002F300 00000000 */  nop
/* 1FB04 8002F304 38004010 */  beqz       $v0, PDDIRRES_OBJ_920
/* 1FB08 8002F308 FEFF8224 */   addiu     $v0, $a0, -0x2
.L8002F30C:
/* 1FB0C 8002F30C FF004230 */  andi       $v0, $v0, 0xFF
/* 1FB10 8002F310 FC00422C */  sltiu      $v0, $v0, 0xFC
/* 1FB14 8002F314 0E004010 */  beqz       $v0, .L8002F350
/* 1FB18 8002F318 00000000 */   nop
/* 1FB1C 8002F31C 3C00028E */  lw         $v0, 0x3C($s0)
/* 1FB20 8002F320 00000000 */  nop
/* 1FB24 8002F324 00004390 */  lbu        $v1, 0x0($v0)
/* 1FB28 8002F328 F3000224 */  addiu      $v0, $zero, 0xF3
/* 1FB2C 8002F32C 08006210 */  beq        $v1, $v0, .L8002F350
/* 1FB30 8002F330 00000000 */   nop
/* 1FB34 8002F334 0780023C */  lui        $v0, %hi(D_80069058)
/* 1FB38 8002F338 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1FB3C 8002F33C 00000000 */  nop
/* 1FB40 8002F340 09F84000 */  jalr       $v0
/* 1FB44 8002F344 21200002 */   addu      $a0, $s0, $zero
/* 1FB48 8002F348 FABC0008 */  j          PDDIRRES_OBJ_920
/* 1FB4C 8002F34C 00000000 */   nop
.L8002F350:
/* 1FB50 8002F350 46000392 */  lbu        $v1, 0x46($s0)
/* 1FB54 8002F354 01000424 */  addiu      $a0, $zero, 0x1
/* 1FB58 8002F358 0E006410 */  beq        $v1, $a0, .L8002F394
/* 1FB5C 8002F35C 02006228 */   slti      $v0, $v1, 0x2
/* 1FB60 8002F360 05004010 */  beqz       $v0, .L8002F378
/* 1FB64 8002F364 FE000224 */   addiu     $v0, $zero, 0xFE
/* 1FB68 8002F368 07006010 */  beqz       $v1, .L8002F388
/* 1FB6C 8002F36C 00000000 */   nop
/* 1FB70 8002F370 ECBC0008 */  j          PDDIRRES_OBJ_8E8
/* 1FB74 8002F374 00000000 */   nop
.L8002F378:
/* 1FB78 8002F378 0B006210 */  beq        $v1, $v0, .L8002F3A8
/* 1FB7C 8002F37C FF000224 */   addiu     $v0, $zero, 0xFF
/* 1FB80 8002F380 ECBC0008 */  j          PDDIRRES_OBJ_8E8
/* 1FB84 8002F384 00000000 */   nop
.L8002F388:
/* 1FB88 8002F388 46000292 */  lbu        $v0, 0x46($s0)
/* 1FB8C 8002F38C E7BC0008 */  j          PDDIRRES_OBJ_8D4
/* 1FB90 8002F390 490004A2 */   sb        $a0, 0x49($s0)
.L8002F394:
/* 1FB94 8002F394 46000292 */  lbu        $v0, 0x46($s0)
/* 1FB98 8002F398 470000A2 */  sb         $zero, 0x47($s0)
.size PDDIRRES_OBJ_7AC, . - PDDIRRES_OBJ_7AC

glabel PDDIRRES_OBJ_8D4
/* 1FB9C 8002F39C 01004224 */  addiu      $v0, $v0, 0x1
/* 1FBA0 8002F3A0 FABC0008 */  j          PDDIRRES_OBJ_920
/* 1FBA4 8002F3A4 460002A2 */   sb        $v0, 0x46($s0)
.L8002F3A8:
/* 1FBA8 8002F3A8 FABC0008 */  j          PDDIRRES_OBJ_920
/* 1FBAC 8002F3AC 460002A2 */   sb        $v0, 0x46($s0)
.size PDDIRRES_OBJ_8D4, . - PDDIRRES_OBJ_8D4

glabel PDDIRRES_OBJ_8E8
/* 1FBB0 8002F3B0 1800028E */  lw         $v0, 0x18($s0)
/* 1FBB4 8002F3B4 00000000 */  nop
/* 1FBB8 8002F3B8 05004010 */  beqz       $v0, .L8002F3D0
/* 1FBBC 8002F3BC 00000000 */   nop
/* 1FBC0 8002F3C0 09F84000 */  jalr       $v0
/* 1FBC4 8002F3C4 21200002 */   addu      $a0, $s0, $zero
/* 1FBC8 8002F3C8 F6BC0008 */  j          PDDIRRES_OBJ_910
/* 1FBCC 8002F3CC 00000000 */   nop
.L8002F3D0:
/* 1FBD0 8002F3D0 44C0000C */  jal        _padRecvAtLoadInfo
/* 1FBD4 8002F3D4 21200002 */   addu      $a0, $s0, $zero
.size PDDIRRES_OBJ_8E8, . - PDDIRRES_OBJ_8E8

glabel PDDIRRES_OBJ_910
/* 1FBD8 8002F3D8 46000392 */  lbu        $v1, 0x46($s0)
/* 1FBDC 8002F3DC 00000000 */  nop
/* 1FBE0 8002F3E0 21186200 */  addu       $v1, $v1, $v0
/* 1FBE4 8002F3E4 460003A2 */  sb         $v1, 0x46($s0)
.size PDDIRRES_OBJ_910, . - PDDIRRES_OBJ_910

glabel PDDIRRES_OBJ_920
/* 1FBE8 8002F3E8 1400BF8F */  lw         $ra, 0x14($sp)
/* 1FBEC 8002F3EC 1000B08F */  lw         $s0, 0x10($sp)
/* 1FBF0 8002F3F0 0800E003 */  jr         $ra
/* 1FBF4 8002F3F4 1800BD27 */   addiu     $sp, $sp, 0x18
.size PDDIRRES_OBJ_920, . - PDDIRRES_OBJ_920

glabel _dirFailAuto
/* 1FBF8 8002F3F8 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 1FBFC 8002F3FC 1000B0AF */  sw         $s0, 0x10($sp)
/* 1FC00 8002F400 21808000 */  addu       $s0, $a0, $zero
/* 1FC04 8002F404 1400BFAF */  sw         $ra, 0x14($sp)
/* 1FC08 8002F408 4C00028E */  lw         $v0, 0x4C($s0)
/* 1FC0C 8002F40C 46000392 */  lbu        $v1, 0x46($s0)
/* 1FC10 8002F410 01004224 */  addiu      $v0, $v0, 0x1
/* 1FC14 8002F414 1E006010 */  beqz       $v1, .L8002F490
/* 1FC18 8002F418 4C0002AE */   sw        $v0, 0x4C($s0)
/* 1FC1C 8002F41C 01000224 */  addiu      $v0, $zero, 0x1
/* 1FC20 8002F420 0B006214 */  bne        $v1, $v0, .L8002F450
/* 1FC24 8002F424 00000000 */   nop
/* 1FC28 8002F428 4A000392 */  lbu        $v1, 0x4A($s0)
/* 1FC2C 8002F42C 00000000 */  nop
/* 1FC30 8002F430 0B00622C */  sltiu      $v0, $v1, 0xB
/* 1FC34 8002F434 0B004014 */  bnez       $v0, .L8002F464
/* 1FC38 8002F438 01006224 */   addiu     $v0, $v1, 0x1
/* 1FC3C 8002F43C 02000224 */  addiu      $v0, $zero, 0x2
/* 1FC40 8002F440 490002A2 */  sb         $v0, 0x49($s0)
/* 1FC44 8002F444 FF000224 */  addiu      $v0, $zero, 0xFF
/* 1FC48 8002F448 32BD0008 */  j          PDDIRRES_OBJ_A00
/* 1FC4C 8002F44C 460002A2 */   sb        $v0, 0x46($s0)
.L8002F450:
/* 1FC50 8002F450 4A000392 */  lbu        $v1, 0x4A($s0)
/* 1FC54 8002F454 00000000 */  nop
/* 1FC58 8002F458 0B00622C */  sltiu      $v0, $v1, 0xB
/* 1FC5C 8002F45C 03004010 */  beqz       $v0, .L8002F46C
/* 1FC60 8002F460 01006224 */   addiu     $v0, $v1, 0x1
.L8002F464:
/* 1FC64 8002F464 32BD0008 */  j          PDDIRRES_OBJ_A00
/* 1FC68 8002F468 4A0002A2 */   sb        $v0, 0x4A($s0)
.L8002F46C:
/* 1FC6C 8002F46C 49000292 */  lbu        $v0, 0x49($s0)
/* 1FC70 8002F470 00000000 */  nop
/* 1FC74 8002F474 06004010 */  beqz       $v0, .L8002F490
/* 1FC78 8002F478 00000000 */   nop
/* 1FC7C 8002F47C 0780023C */  lui        $v0, %hi(D_80069058)
/* 1FC80 8002F480 5890428C */  lw         $v0, %lo(D_80069058)($v0)
/* 1FC84 8002F484 00000000 */  nop
/* 1FC88 8002F488 09F84000 */  jalr       $v0
/* 1FC8C 8002F48C 21200002 */   addu      $a0, $s0, $zero
.L8002F490:
/* 1FC90 8002F490 3C00028E */  lw         $v0, 0x3C($s0)
/* 1FC94 8002F494 00000000 */  nop
/* 1FC98 8002F498 00004390 */  lbu        $v1, 0x0($v0)
/* 1FC9C 8002F49C F3000224 */  addiu      $v0, $zero, 0xF3
/* 1FCA0 8002F4A0 09006210 */  beq        $v1, $v0, PDDIRRES_OBJ_A00
/* 1FCA4 8002F4A4 FF000324 */   addiu     $v1, $zero, 0xFF
/* 1FCA8 8002F4A8 3000028E */  lw         $v0, 0x30($s0)
/* 1FCAC 8002F4AC 00000000 */  nop
/* 1FCB0 8002F4B0 000043A0 */  sb         $v1, 0x0($v0)
/* 1FCB4 8002F4B4 3000028E */  lw         $v0, 0x30($s0)
/* 1FCB8 8002F4B8 00000000 */  nop
/* 1FCBC 8002F4BC 010040A0 */  sb         $zero, 0x1($v0)
/* 1FCC0 8002F4C0 E80000A2 */  sb         $zero, 0xE8($s0)
/* 1FCC4 8002F4C4 350000A2 */  sb         $zero, 0x35($s0)
.size _dirFailAuto, . - _dirFailAuto

glabel PDDIRRES_OBJ_A00
/* 1FCC8 8002F4C8 1400BF8F */  lw         $ra, 0x14($sp)
/* 1FCCC 8002F4CC 1000B08F */  lw         $s0, 0x10($sp)
/* 1FCD0 8002F4D0 0800E003 */  jr         $ra
/* 1FCD4 8002F4D4 1800BD27 */   addiu     $sp, $sp, 0x18
.size PDDIRRES_OBJ_A00, . - PDDIRRES_OBJ_A00

glabel PDDIRRES_OBJ_A10
/* 1FCD8 8002F4D8 E6008294 */  lhu        $v0, 0xE6($a0)
/* 1FCDC 8002F4DC 00000000 */  nop
/* 1FCE0 8002F4E0 05004010 */  beqz       $v0, .L8002F4F8
/* 1FCE4 8002F4E4 FF000224 */   addiu     $v0, $zero, 0xFF
/* 1FCE8 8002F4E8 46008390 */  lbu        $v1, 0x46($a0)
/* 1FCEC 8002F4EC 00000000 */  nop
/* 1FCF0 8002F4F0 02006210 */  beq        $v1, $v0, .L8002F4FC
/* 1FCF4 8002F4F4 21100000 */   addu      $v0, $zero, $zero
.L8002F4F8:
/* 1FCF8 8002F4F8 01000224 */  addiu      $v0, $zero, 0x1
.L8002F4FC:
/* 1FCFC 8002F4FC 0800E003 */  jr         $ra
/* 1FD00 8002F500 00000000 */   nop
/* 1FD04 8002F504 00000000 */  nop
.size PDDIRRES_OBJ_A10, . - PDDIRRES_OBJ_A10
