.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel func_8003F694
/* 2FE94 8003F694 0400A010 */  beqz       $a1, .L8003F6A8
/* 2FE98 8003F698 00000000 */   nop
/* 2FE9C 8003F69C 07008290 */  lbu        $v0, 0x7($a0)
/* 2FEA0 8003F6A0 ADFD0008 */  j          .L8003F6B4
/* 2FEA4 8003F6A4 01004234 */   ori       $v0, $v0, 0x1
.L8003F6A8:
/* 2FEA8 8003F6A8 07008290 */  lbu        $v0, 0x7($a0)
/* 2FEAC 8003F6AC 00000000 */  nop
/* 2FEB0 8003F6B0 FE004230 */  andi       $v0, $v0, 0xFE
.L8003F6B4:
/* 2FEB4 8003F6B4 0800E003 */  jr         $ra
/* 2FEB8 8003F6B8 070082A0 */   sb        $v0, 0x7($a0)
/* 2FEBC 8003F6BC 00000000 */  nop
/* 2FEC0 8003F6C0 00000000 */  nop
.size func_8003F694, . - func_8003F694
