.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel func_8003F6C4
/* 2FEC4 8003F6C4 04000224 */  addiu      $v0, $zero, 0x4
/* 2FEC8 8003F6C8 030082A0 */  sb         $v0, 0x3($a0)
/* 2FECC 8003F6CC 64000224 */  addiu      $v0, $zero, 0x64
/* 2FED0 8003F6D0 0800E003 */  jr         $ra
/* 2FED4 8003F6D4 070082A0 */   sb        $v0, 0x7($a0)
/* 2FED8 8003F6D8 00000000 */  nop
/* 2FEDC 8003F6DC 00000000 */  nop
/* 2FEE0 8003F6E0 00000000 */  nop
.size func_8003F6C4, . - func_8003F6C4
