.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel func_8004D650
/* 3DE50 8004D650 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3DE54 8004D654 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 3DE58 8004D658 0880023C */  lui        $v0, %hi(D_80078948)
/* 3DE5C 8004D65C 4889438C */  lw         $v1, %lo(D_80078948)($v0)
/* 3DE60 8004D660 C0200400 */  sll        $a0, $a0, 3
/* 3DE64 8004D664 1800BFAF */  sw         $ra, 0x18($sp)
/* 3DE68 8004D668 1400B1AF */  sw         $s1, 0x14($sp)
/* 3DE6C 8004D66C 1000B0AF */  sw         $s0, 0x10($sp)
/* 3DE70 8004D670 21886400 */  addu       $s1, $v1, $a0
/* 3DE74 8004D674 10006010 */  beqz       $v1, .L8004D6B8
/* 3DE78 8004D678 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 3DE7C 8004D67C 06002286 */  lh         $v0, 0x6($s1)
/* 3DE80 8004D680 00000000 */  nop
/* 3DE84 8004D684 0C004104 */  bgez       $v0, .L8004D6B8
/* 3DE88 8004D688 00000000 */   nop
/* 3DE8C 8004D68C 2120A000 */  addu       $a0, $a1, $zero
/* 3DE90 8004D690 B335010C */  jal        SsVabOpenHead
/* 3DE94 8004D694 FFFF0524 */   addiu     $a1, $zero, -0x1
/* 3DE98 8004D698 21804000 */  addu       $s0, $v0, $zero
/* 3DE9C 8004D69C 03000006 */  bltz       $s0, .L8004D6AC
/* 3DEA0 8004D6A0 0180043C */   lui       $a0, %hi(D_80012610)
/* 3DEA4 8004D6A4 AE350108 */  j          .L8004D6B8
/* 3DEA8 8004D6A8 060030A6 */   sh        $s0, 0x6($s1)
.L8004D6AC:
/* 3DEAC 8004D6AC 9361000C */  jal        printf
/* 3DEB0 8004D6B0 10268424 */   addiu     $a0, $a0, %lo(D_80012610)
/* 3DEB4 8004D6B4 21100002 */  addu       $v0, $s0, $zero
.L8004D6B8:
/* 3DEB8 8004D6B8 1800BF8F */  lw         $ra, 0x18($sp)
/* 3DEBC 8004D6BC 1400B18F */  lw         $s1, 0x14($sp)
/* 3DEC0 8004D6C0 1000B08F */  lw         $s0, 0x10($sp)
/* 3DEC4 8004D6C4 0800E003 */  jr         $ra
/* 3DEC8 8004D6C8 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004D650, . - func_8004D650

glabel SsVabOpenHead
/* 3DECC 8004D6CC E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3DED0 8004D6D0 1000BFAF */  sw         $ra, 0x10($sp)
/* 3DED4 8004D6D4 002C0500 */  sll        $a1, $a1, 16
/* 3DED8 8004D6D8 032C0500 */  sra        $a1, $a1, 16
/* 3DEDC 8004D6DC 0580063C */  lui        $a2, %hi(VS_VH2_OBJ_34)
/* 3DEE0 8004D6E0 00D7C624 */  addiu      $a2, $a2, %lo(VS_VH2_OBJ_34)
/* 3DEE4 8004D6E4 F735010C */  jal        _SsVabOpenHeadWithMode
/* 3DEE8 8004D6E8 21380000 */   addu      $a3, $zero, $zero
/* 3DEEC 8004D6EC 00140200 */  sll        $v0, $v0, 16
/* 3DEF0 8004D6F0 1000BF8F */  lw         $ra, 0x10($sp)
/* 3DEF4 8004D6F4 03140200 */  sra        $v0, $v0, 16
/* 3DEF8 8004D6F8 0800E003 */  jr         $ra
/* 3DEFC 8004D6FC 1800BD27 */   addiu     $sp, $sp, 0x18
.size SsVabOpenHead, . - SsVabOpenHead

glabel VS_VH2_OBJ_34
/* 3DF00 8004D700 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3DF04 8004D704 1000B0AF */  sw         $s0, 0x10($sp)
/* 3DF08 8004D708 1400BFAF */  sw         $ra, 0x14($sp)
/* 3DF0C 8004D70C 5710010C */  jal        SpuMalloc
/* 3DF10 8004D710 2180C000 */   addu      $s0, $a2, $zero
/* 3DF14 8004D714 21184000 */  addu       $v1, $v0, $zero
/* 3DF18 8004D718 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 3DF1C 8004D71C 0E006214 */  bne        $v1, $v0, .L8004D758
/* 3DF20 8004D720 21106000 */   addu      $v0, $v1, $zero
/* 3DF24 8004D724 00141000 */  sll        $v0, $s0, 16
/* 3DF28 8004D728 03140200 */  sra        $v0, $v0, 16
/* 3DF2C 8004D72C 0880013C */  lui        $at, %hi(D_80078790)
/* 3DF30 8004D730 21082200 */  addu       $at, $at, $v0
/* 3DF34 8004D734 908720A0 */  sb         $zero, %lo(D_80078790)($at)
/* 3DF38 8004D738 4713010C */  jal        func_80044D1C
/* 3DF3C 8004D73C 21200000 */   addu      $a0, $zero, $zero
/* 3DF40 8004D740 0880033C */  lui        $v1, %hi(D_800787E8)
/* 3DF44 8004D744 E8876394 */  lhu        $v1, %lo(D_800787E8)($v1)
/* 3DF48 8004D748 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 3DF4C 8004D74C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 3DF50 8004D750 0880013C */  lui        $at, %hi(D_800787E8)
/* 3DF54 8004D754 E88723A4 */  sh         $v1, %lo(D_800787E8)($at)
.L8004D758:
/* 3DF58 8004D758 1400BF8F */  lw         $ra, 0x14($sp)
/* 3DF5C 8004D75C 1000B08F */  lw         $s0, 0x10($sp)
/* 3DF60 8004D760 0800E003 */  jr         $ra
/* 3DF64 8004D764 1800BD27 */   addiu     $sp, $sp, 0x18
/* 3DF68 8004D768 00000000 */  nop
.size VS_VH2_OBJ_34, . - VS_VH2_OBJ_34

glabel SsVabOpenHeadSticky
/* 3DF6C 8004D76C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3DF70 8004D770 1000BFAF */  sw         $ra, 0x10($sp)
/* 3DF74 8004D774 2138C000 */  addu       $a3, $a2, $zero
/* 3DF78 8004D778 002C0500 */  sll        $a1, $a1, 16
/* 3DF7C 8004D77C 0580063C */  lui        $a2, %hi(VS_VH_OBJ_68)
/* 3DF80 8004D780 D4D7C624 */  addiu      $a2, $a2, %lo(VS_VH_OBJ_68)
/* 3DF84 8004D784 F735010C */  jal        _SsVabOpenHeadWithMode
/* 3DF88 8004D788 032C0500 */   sra       $a1, $a1, 16
/* 3DF8C 8004D78C 00140200 */  sll        $v0, $v0, 16
/* 3DF90 8004D790 1000BF8F */  lw         $ra, 0x10($sp)
/* 3DF94 8004D794 03140200 */  sra        $v0, $v0, 16
/* 3DF98 8004D798 0800E003 */  jr         $ra
/* 3DF9C 8004D79C 1800BD27 */   addiu     $sp, $sp, 0x18
.size SsVabOpenHeadSticky, . - SsVabOpenHeadSticky

glabel SsVabFakeHead
/* 3DFA0 8004D7A0 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3DFA4 8004D7A4 1000BFAF */  sw         $ra, 0x10($sp)
/* 3DFA8 8004D7A8 2138C000 */  addu       $a3, $a2, $zero
/* 3DFAC 8004D7AC 002C0500 */  sll        $a1, $a1, 16
/* 3DFB0 8004D7B0 0580063C */  lui        $a2, %hi(VS_VH_OBJ_68)
/* 3DFB4 8004D7B4 D4D7C624 */  addiu      $a2, $a2, %lo(VS_VH_OBJ_68)
/* 3DFB8 8004D7B8 F735010C */  jal        _SsVabOpenHeadWithMode
/* 3DFBC 8004D7BC 032C0500 */   sra       $a1, $a1, 16
/* 3DFC0 8004D7C0 00140200 */  sll        $v0, $v0, 16
/* 3DFC4 8004D7C4 1000BF8F */  lw         $ra, 0x10($sp)
/* 3DFC8 8004D7C8 03140200 */  sra        $v0, $v0, 16
/* 3DFCC 8004D7CC 0800E003 */  jr         $ra
/* 3DFD0 8004D7D0 1800BD27 */   addiu     $sp, $sp, 0x18
.size SsVabFakeHead, . - SsVabFakeHead

glabel VS_VH_OBJ_68
/* 3DFD4 8004D7D4 0800E003 */  jr         $ra
/* 3DFD8 8004D7D8 2110A000 */   addu      $v0, $a1, $zero
.size VS_VH_OBJ_68, . - VS_VH_OBJ_68

glabel _SsVabOpenHeadWithMode
/* 3DFDC 8004D7DC D0FBBD27 */  addiu      $sp, $sp, -0x430
/* 3DFE0 8004D7E0 1C04B3AF */  sw         $s3, 0x41C($sp)
/* 3DFE4 8004D7E4 21988000 */  addu       $s3, $a0, $zero
/* 3DFE8 8004D7E8 1004B0AF */  sw         $s0, 0x410($sp)
/* 3DFEC 8004D7EC 2180A000 */  addu       $s0, $a1, $zero
/* 3DFF0 8004D7F0 2804B6AF */  sw         $s6, 0x428($sp)
/* 3DFF4 8004D7F4 21B0C000 */  addu       $s6, $a2, $zero
/* 3DFF8 8004D7F8 2404B5AF */  sw         $s5, 0x424($sp)
/* 3DFFC 8004D7FC 21A8E000 */  addu       $s5, $a3, $zero
/* 3E000 8004D800 1804B2AF */  sw         $s2, 0x418($sp)
/* 3E004 8004D804 10001224 */  addiu      $s2, $zero, 0x10
/* 3E008 8004D808 2C04BFAF */  sw         $ra, 0x42C($sp)
/* 3E00C 8004D80C 2004B4AF */  sw         $s4, 0x420($sp)
/* 3E010 8004D810 5113010C */  jal        func_80044D44
/* 3E014 8004D814 1404B1AF */   sw        $s1, 0x414($sp)
/* 3E018 8004D818 01001124 */  addiu      $s1, $zero, 0x1
/* 3E01C 8004D81C E0005110 */  beq        $v0, $s1, VS_VH_OBJ_434
/* 3E020 8004D820 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 3E024 8004D824 4713010C */  jal        func_80044D1C
/* 3E028 8004D828 01000424 */   addiu     $a0, $zero, 0x1
/* 3E02C 8004D82C 00141000 */  sll        $v0, $s0, 16
/* 3E030 8004D830 031C0200 */  sra        $v1, $v0, 16
/* 3E034 8004D834 10006228 */  slti       $v0, $v1, 0x10
/* 3E038 8004D838 2A004010 */  beqz       $v0, .L8004D8E4
/* 3E03C 8004D83C FFFF0224 */   addiu     $v0, $zero, -0x1
/* 3E040 8004D840 14006214 */  bne        $v1, $v0, .L8004D894
/* 3E044 8004D844 21280000 */   addu      $a1, $zero, $zero
.L8004D848:
/* 3E048 8004D848 0880023C */  lui        $v0, %hi(D_80078790)
/* 3E04C 8004D84C 21104500 */  addu       $v0, $v0, $a1
/* 3E050 8004D850 90874290 */  lbu        $v0, %lo(D_80078790)($v0)
/* 3E054 8004D854 00000000 */  nop
/* 3E058 8004D858 07004010 */  beqz       $v0, .L8004D878
/* 3E05C 8004D85C 01000224 */   addiu     $v0, $zero, 0x1
/* 3E060 8004D860 0100A524 */  addiu      $a1, $a1, 0x1
/* 3E064 8004D864 1000A228 */  slti       $v0, $a1, 0x10
/* 3E068 8004D868 F7FF4014 */  bnez       $v0, .L8004D848
/* 3E06C 8004D86C 00141200 */   sll       $v0, $s2, 16
/* 3E070 8004D870 36360108 */  j          VS_VH_OBJ_16C
/* 3E074 8004D874 03340200 */   sra       $a2, $v0, 16
.L8004D878:
/* 3E078 8004D878 0880013C */  lui        $at, %hi(D_80078790)
/* 3E07C 8004D87C 21082500 */  addu       $at, $at, $a1
/* 3E080 8004D880 908722A0 */  sb         $v0, %lo(D_80078790)($at)
/* 3E084 8004D884 0880023C */  lui        $v0, %hi(D_800787E8)
/* 3E088 8004D888 E8874294 */  lhu        $v0, %lo(D_800787E8)($v0)
/* 3E08C 8004D88C 31360108 */  j          VS_VH_OBJ_158
/* 3E090 8004D890 2190A000 */   addu      $s2, $a1, $zero
.L8004D894:
/* 3E094 8004D894 0880023C */  lui        $v0, %hi(D_80078790)
/* 3E098 8004D898 21104300 */  addu       $v0, $v0, $v1
/* 3E09C 8004D89C 90874290 */  lbu        $v0, %lo(D_80078790)($v0)
/* 3E0A0 8004D8A0 00000000 */  nop
/* 3E0A4 8004D8A4 0B004014 */  bnez       $v0, .L8004D8D4
/* 3E0A8 8004D8A8 00141200 */   sll       $v0, $s2, 16
/* 3E0AC 8004D8AC 0880013C */  lui        $at, %hi(D_80078790)
/* 3E0B0 8004D8B0 21082300 */  addu       $at, $at, $v1
/* 3E0B4 8004D8B4 908731A0 */  sb         $s1, %lo(D_80078790)($at)
/* 3E0B8 8004D8B8 0880023C */  lui        $v0, %hi(D_800787E8)
/* 3E0BC 8004D8BC E8874294 */  lhu        $v0, %lo(D_800787E8)($v0)
/* 3E0C0 8004D8C0 21900002 */  addu       $s2, $s0, $zero
.size _SsVabOpenHeadWithMode, . - _SsVabOpenHeadWithMode

glabel VS_VH_OBJ_158
/* 3E0C4 8004D8C4 01004224 */  addiu      $v0, $v0, 0x1
/* 3E0C8 8004D8C8 0880013C */  lui        $at, %hi(D_800787E8)
/* 3E0CC 8004D8CC E88722A4 */  sh         $v0, %lo(D_800787E8)($at)
/* 3E0D0 8004D8D0 00141200 */  sll        $v0, $s2, 16
.L8004D8D4:
/* 3E0D4 8004D8D4 03340200 */  sra        $a2, $v0, 16
.size VS_VH_OBJ_158, . - VS_VH_OBJ_158

glabel VS_VH_OBJ_16C
/* 3E0D8 8004D8D8 1000C228 */  slti       $v0, $a2, 0x10
/* 3E0DC 8004D8DC 05004014 */  bnez       $v0, .L8004D8F4
/* 3E0E0 8004D8E0 21386002 */   addu      $a3, $s3, $zero
.L8004D8E4:
/* 3E0E4 8004D8E4 4713010C */  jal        func_80044D1C
/* 3E0E8 8004D8E8 21200000 */   addu      $a0, $zero, $zero
/* 3E0EC 8004D8EC E8360108 */  j          VS_VH_OBJ_434
/* 3E0F0 8004D8F0 FFFF0224 */   addiu     $v0, $zero, -0x1
.L8004D8F4:
/* 3E0F4 8004D8F4 80100600 */  sll        $v0, $a2, 2
/* 3E0F8 8004D8F8 0880013C */  lui        $at, %hi(D_800786C8)
/* 3E0FC 8004D8FC 21082200 */  addu       $at, $at, $v0
/* 3E100 8004D900 C88627AC */  sw         $a3, %lo(D_800786C8)($at)
/* 3E104 8004D904 5600033C */  lui        $v1, (0x564142 >> 16)
/* 3E108 8004D908 21206002 */  addu       $a0, $s3, $zero
/* 3E10C 8004D90C 0000858C */  lw         $a1, 0x0($a0)
/* 3E110 8004D910 42416334 */  ori        $v1, $v1, (0x564142 & 0xFFFF)
/* 3E114 8004D914 0880013C */  lui        $at, %hi(D_80078768)
/* 3E118 8004D918 688720AC */  sw         $zero, %lo(D_80078768)($at)
/* 3E11C 8004D91C 02120500 */  srl        $v0, $a1, 8
/* 3E120 8004D920 06004310 */  beq        $v0, $v1, .L8004D93C
/* 3E124 8004D924 2000E724 */   addiu     $a3, $a3, 0x20
/* 3E128 8004D928 0880013C */  lui        $at, %hi(D_80078790)
/* 3E12C 8004D92C 21082600 */  addu       $at, $at, $a2
/* 3E130 8004D930 908720A0 */  sb         $zero, %lo(D_80078790)($at)
/* 3E134 8004D934 B1360108 */  j          VS_VH_OBJ_358
/* 3E138 8004D938 21200000 */   addu      $a0, $zero, $zero
.L8004D93C:
/* 3E13C 8004D93C FF00A330 */  andi       $v1, $a1, 0xFF
/* 3E140 8004D940 70000224 */  addiu      $v0, $zero, 0x70
/* 3E144 8004D944 07006214 */  bne        $v1, $v0, VS_VH_OBJ_1F8
/* 3E148 8004D948 40000224 */   addiu     $v0, $zero, 0x40
/* 3E14C 8004D94C 0400828C */  lw         $v0, 0x4($a0)
/* 3E150 8004D950 00000000 */  nop
/* 3E154 8004D954 05004228 */  slti       $v0, $v0, 0x5
/* 3E158 8004D958 02004014 */  bnez       $v0, VS_VH_OBJ_1F8
/* 3E15C 8004D95C 40000224 */   addiu     $v0, $zero, 0x40
/* 3E160 8004D960 80000224 */  addiu      $v0, $zero, 0x80
.size VS_VH_OBJ_16C, . - VS_VH_OBJ_16C

glabel VS_VH_OBJ_1F8
/* 3E164 8004D964 0880013C */  lui        $at, %hi(D_80078752)
/* 3E168 8004D968 528722A4 */  sh         $v0, %lo(D_80078752)($at)
/* 3E16C 8004D96C 12008294 */  lhu        $v0, 0x12($a0)
/* 3E170 8004D970 0880033C */  lui        $v1, %hi(D_80078752)
/* 3E174 8004D974 52876384 */  lh         $v1, %lo(D_80078752)($v1)
/* 3E178 8004D978 00000000 */  nop
/* 3E17C 8004D97C 2A106200 */  slt        $v0, $v1, $v0
/* 3E180 8004D980 07004010 */  beqz       $v0, .L8004D9A0
/* 3E184 8004D984 00141200 */   sll       $v0, $s2, 16
/* 3E188 8004D988 03140200 */  sra        $v0, $v0, 16
/* 3E18C 8004D98C 0880013C */  lui        $at, %hi(D_80078790)
/* 3E190 8004D990 21082200 */  addu       $at, $at, $v0
/* 3E194 8004D994 908720A0 */  sb         $zero, %lo(D_80078790)($at)
/* 3E198 8004D998 B1360108 */  j          VS_VH_OBJ_358
/* 3E19C 8004D99C 21200000 */   addu      $a0, $zero, $zero
.L8004D9A0:
/* 3E1A0 8004D9A0 83130200 */  sra        $v0, $v0, 14
/* 3E1A4 8004D9A4 0880013C */  lui        $at, %hi(D_80078688)
/* 3E1A8 8004D9A8 21082200 */  addu       $at, $at, $v0
/* 3E1AC 8004D9AC 888627AC */  sw         $a3, %lo(D_80078688)($at)
/* 3E1B0 8004D9B0 2198E000 */  addu       $s3, $a3, $zero
/* 3E1B4 8004D9B4 00110300 */  sll        $v0, $v1, 4
/* 3E1B8 8004D9B8 21386202 */  addu       $a3, $s3, $v0
/* 3E1BC 8004D9BC 21280000 */  addu       $a1, $zero, $zero
/* 3E1C0 8004D9C0 0C006018 */  blez       $v1, .L8004D9F4
/* 3E1C4 8004D9C4 21800000 */   addu      $s0, $zero, $zero
/* 3E1C8 8004D9C8 21306000 */  addu       $a2, $v1, $zero
/* 3E1CC 8004D9CC 21186002 */  addu       $v1, $s3, $zero
.size VS_VH_OBJ_1F8, . - VS_VH_OBJ_1F8

glabel VS_VH_OBJ_264
/* 3E1D0 8004D9D0 00006290 */  lbu        $v0, 0x0($v1)
/* 3E1D4 8004D9D4 00000000 */  nop
/* 3E1D8 8004D9D8 02004010 */  beqz       $v0, .L8004D9E4
/* 3E1DC 8004D9DC 080070AC */   sw        $s0, 0x8($v1)
/* 3E1E0 8004D9E0 01001026 */  addiu      $s0, $s0, 0x1
.L8004D9E4:
/* 3E1E4 8004D9E4 0100A524 */  addiu      $a1, $a1, 0x1
/* 3E1E8 8004D9E8 2A10A600 */  slt        $v0, $a1, $a2
/* 3E1EC 8004D9EC F8FF4014 */  bnez       $v0, VS_VH_OBJ_264
/* 3E1F0 8004D9F0 10006324 */   addiu     $v1, $v1, 0x10
.L8004D9F4:
/* 3E1F4 8004D9F4 21800000 */  addu       $s0, $zero, $zero
/* 3E1F8 8004D9F8 21280000 */  addu       $a1, $zero, $zero
/* 3E1FC 8004D9FC 00141200 */  sll        $v0, $s2, 16
/* 3E200 8004DA00 83130200 */  sra        $v0, $v0, 14
/* 3E204 8004DA04 1000A627 */  addiu      $a2, $sp, 0x10
/* 3E208 8004DA08 0880013C */  lui        $at, %hi(D_80078710)
/* 3E20C 8004DA0C 21082200 */  addu       $at, $at, $v0
/* 3E210 8004DA10 108727AC */  sw         $a3, %lo(D_80078710)($at)
/* 3E214 8004DA14 12008294 */  lhu        $v0, 0x12($a0)
/* 3E218 8004DA18 16009490 */  lbu        $s4, 0x16($a0)
/* 3E21C 8004DA1C 40120200 */  sll        $v0, $v0, 9
/* 3E220 8004DA20 2138E200 */  addu       $a3, $a3, $v0
/* 3E224 8004DA24 FF008832 */  andi       $t0, $s4, 0xFF
.L8004DA28:
/* 3E228 8004DA28 2A100501 */  slt        $v0, $t0, $a1
/* 3E22C 8004DA2C 0B004014 */  bnez       $v0, .L8004DA5C
/* 3E230 8004DA30 00000000 */   nop
/* 3E234 8004DA34 0400828C */  lw         $v0, 0x4($a0)
/* 3E238 8004DA38 0000E394 */  lhu        $v1, 0x0($a3)
/* 3E23C 8004DA3C 05004228 */  slti       $v0, $v0, 0x5
/* 3E240 8004DA40 02004014 */  bnez       $v0, .L8004DA4C
/* 3E244 8004DA44 80100300 */   sll       $v0, $v1, 2
/* 3E248 8004DA48 C0100300 */  sll        $v0, $v1, 3
.L8004DA4C:
/* 3E24C 8004DA4C 0000C2AC */  sw         $v0, 0x0($a2)
/* 3E250 8004DA50 0000C28C */  lw         $v0, 0x0($a2)
/* 3E254 8004DA54 00000000 */  nop
/* 3E258 8004DA58 21800202 */  addu       $s0, $s0, $v0
.L8004DA5C:
/* 3E25C 8004DA5C 0200E724 */  addiu      $a3, $a3, 0x2
/* 3E260 8004DA60 0100A524 */  addiu      $a1, $a1, 0x1
/* 3E264 8004DA64 0001A228 */  slti       $v0, $a1, 0x100
/* 3E268 8004DA68 EFFF4014 */  bnez       $v0, .L8004DA28
/* 3E26C 8004DA6C 0400C624 */   addiu     $a2, $a2, 0x4
/* 3E270 8004DA70 3F000326 */  addiu      $v1, $s0, 0x3F
/* 3E274 8004DA74 C0FF0224 */  addiu      $v0, $zero, -0x40
/* 3E278 8004DA78 24806200 */  and        $s0, $v1, $v0
/* 3E27C 8004DA7C 21200002 */  addu       $a0, $s0, $zero
/* 3E280 8004DA80 00141200 */  sll        $v0, $s2, 16
/* 3E284 8004DA84 038C0200 */  sra        $s1, $v0, 16
/* 3E288 8004DA88 2128A002 */  addu       $a1, $s5, $zero
/* 3E28C 8004DA8C 09F8C002 */  jalr       $s6
/* 3E290 8004DA90 21302002 */   addu      $a2, $s1, $zero
/* 3E294 8004DA94 21204000 */  addu       $a0, $v0, $zero
/* 3E298 8004DA98 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 3E29C 8004DA9C 40008210 */  beq        $a0, $v0, VS_VH_OBJ_434
/* 3E2A0 8004DAA0 21189000 */   addu      $v1, $a0, $s0
/* 3E2A4 8004DAA4 0800023C */  lui        $v0, (0x80000 >> 16)
/* 3E2A8 8004DAA8 2B104300 */  sltu       $v0, $v0, $v1
/* 3E2AC 8004DAAC 0F004010 */  beqz       $v0, .L8004DAEC
/* 3E2B0 8004DAB0 80101100 */   sll       $v0, $s1, 2
/* 3E2B4 8004DAB4 21200000 */  addu       $a0, $zero, $zero
/* 3E2B8 8004DAB8 0880013C */  lui        $at, %hi(D_80078790)
/* 3E2BC 8004DABC 21083100 */  addu       $at, $at, $s1
/* 3E2C0 8004DAC0 908720A0 */  sb         $zero, %lo(D_80078790)($at)
.size VS_VH_OBJ_264, . - VS_VH_OBJ_264

glabel VS_VH_OBJ_358
/* 3E2C4 8004DAC4 4713010C */  jal        func_80044D1C
/* 3E2C8 8004DAC8 00000000 */   nop
/* 3E2CC 8004DACC 0880033C */  lui        $v1, %hi(D_800787E8)
/* 3E2D0 8004DAD0 E8876394 */  lhu        $v1, %lo(D_800787E8)($v1)
/* 3E2D4 8004DAD4 00000000 */  nop
/* 3E2D8 8004DAD8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 3E2DC 8004DADC 0880013C */  lui        $at, %hi(D_800787E8)
/* 3E2E0 8004DAE0 E88723A4 */  sh         $v1, %lo(D_800787E8)($at)
/* 3E2E4 8004DAE4 E8360108 */  j          VS_VH_OBJ_434
/* 3E2E8 8004DAE8 FFFF0224 */   addiu     $v0, $zero, -0x1
.L8004DAEC:
/* 3E2EC 8004DAEC 0880013C */  lui        $at, %hi(D_800787F0)
/* 3E2F0 8004DAF0 21082200 */  addu       $at, $at, $v0
/* 3E2F4 8004DAF4 F08724AC */  sw         $a0, %lo(D_800787F0)($at)
/* 3E2F8 8004DAF8 21800000 */  addu       $s0, $zero, $zero
/* 3E2FC 8004DAFC FF008332 */  andi       $v1, $s4, 0xFF
/* 3E300 8004DB00 00006228 */  slti       $v0, $v1, 0x0
/* 3E304 8004DB04 1C004014 */  bnez       $v0, .L8004DB78
/* 3E308 8004DB08 21280000 */   addu      $a1, $zero, $zero
/* 3E30C 8004DB0C 21386000 */  addu       $a3, $v1, $zero
/* 3E310 8004DB10 1000A627 */  addiu      $a2, $sp, 0x10
.L8004DB14:
/* 3E314 8004DB14 0000C28C */  lw         $v0, 0x0($a2)
/* 3E318 8004DB18 00000000 */  nop
/* 3E31C 8004DB1C 21800202 */  addu       $s0, $s0, $v0
/* 3E320 8004DB20 0100A230 */  andi       $v0, $a1, 0x1
/* 3E324 8004DB24 09004014 */  bnez       $v0, .L8004DB4C
/* 3E328 8004DB28 C21F0500 */   srl       $v1, $a1, 31
/* 3E32C 8004DB2C 2118A300 */  addu       $v1, $a1, $v1
/* 3E330 8004DB30 43180300 */  sra        $v1, $v1, 1
/* 3E334 8004DB34 00190300 */  sll        $v1, $v1, 4
/* 3E338 8004DB38 21187300 */  addu       $v1, $v1, $s3
/* 3E33C 8004DB3C 21109000 */  addu       $v0, $a0, $s0
/* 3E340 8004DB40 C2100200 */  srl        $v0, $v0, 3
/* 3E344 8004DB44 DA360108 */  j          VS_VH_OBJ_3FC
/* 3E348 8004DB48 0C0062A4 */   sh        $v0, 0xC($v1)
.L8004DB4C:
/* 3E34C 8004DB4C 2118A300 */  addu       $v1, $a1, $v1
/* 3E350 8004DB50 43180300 */  sra        $v1, $v1, 1
/* 3E354 8004DB54 00190300 */  sll        $v1, $v1, 4
/* 3E358 8004DB58 21187300 */  addu       $v1, $v1, $s3
/* 3E35C 8004DB5C 21109000 */  addu       $v0, $a0, $s0
/* 3E360 8004DB60 C2100200 */  srl        $v0, $v0, 3
/* 3E364 8004DB64 0E0062A4 */  sh         $v0, 0xE($v1)
.size VS_VH_OBJ_358, . - VS_VH_OBJ_358

glabel VS_VH_OBJ_3FC
/* 3E368 8004DB68 0100A524 */  addiu      $a1, $a1, 0x1
/* 3E36C 8004DB6C 2A10E500 */  slt        $v0, $a3, $a1
/* 3E370 8004DB70 E8FF4010 */  beqz       $v0, .L8004DB14
/* 3E374 8004DB74 0400C624 */   addiu     $a2, $a2, 0x4
.L8004DB78:
/* 3E378 8004DB78 00141200 */  sll        $v0, $s2, 16
/* 3E37C 8004DB7C 03140200 */  sra        $v0, $v0, 16
/* 3E380 8004DB80 80180200 */  sll        $v1, $v0, 2
/* 3E384 8004DB84 0880013C */  lui        $at, %hi(D_800787A8)
/* 3E388 8004DB88 21082300 */  addu       $at, $at, $v1
/* 3E38C 8004DB8C A88730AC */  sw         $s0, %lo(D_800787A8)($at)
/* 3E390 8004DB90 02000324 */  addiu      $v1, $zero, 0x2
/* 3E394 8004DB94 0880013C */  lui        $at, %hi(D_80078790)
/* 3E398 8004DB98 21082200 */  addu       $at, $at, $v0
/* 3E39C 8004DB9C 908723A0 */  sb         $v1, %lo(D_80078790)($at)
.size VS_VH_OBJ_3FC, . - VS_VH_OBJ_3FC

glabel VS_VH_OBJ_434
/* 3E3A0 8004DBA0 2C04BF8F */  lw         $ra, 0x42C($sp)
/* 3E3A4 8004DBA4 2804B68F */  lw         $s6, 0x428($sp)
/* 3E3A8 8004DBA8 2404B58F */  lw         $s5, 0x424($sp)
/* 3E3AC 8004DBAC 2004B48F */  lw         $s4, 0x420($sp)
/* 3E3B0 8004DBB0 1C04B38F */  lw         $s3, 0x41C($sp)
/* 3E3B4 8004DBB4 1804B28F */  lw         $s2, 0x418($sp)
/* 3E3B8 8004DBB8 1404B18F */  lw         $s1, 0x414($sp)
/* 3E3BC 8004DBBC 1004B08F */  lw         $s0, 0x410($sp)
/* 3E3C0 8004DBC0 0800E003 */  jr         $ra
/* 3E3C4 8004DBC4 3004BD27 */   addiu     $sp, $sp, 0x430
/* 3E3C8 8004DBC8 00000000 */  nop
.size VS_VH_OBJ_434, . - VS_VH_OBJ_434

glabel func_8004DBCC
/* 3E3CC 8004DBCC E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3E3D0 8004DBD0 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 3E3D4 8004DBD4 0880023C */  lui        $v0, %hi(D_80078948)
/* 3E3D8 8004DBD8 4889438C */  lw         $v1, %lo(D_80078948)($v0)
/* 3E3DC 8004DBDC C0200400 */  sll        $a0, $a0, 3
/* 3E3E0 8004DBE0 1800BFAF */  sw         $ra, 0x18($sp)
/* 3E3E4 8004DBE4 1400B1AF */  sw         $s1, 0x14($sp)
/* 3E3E8 8004DBE8 1000B0AF */  sw         $s0, 0x10($sp)
/* 3E3EC 8004DBEC 21886400 */  addu       $s1, $v1, $a0
/* 3E3F0 8004DBF0 10006010 */  beqz       $v1, .L8004DC34
/* 3E3F4 8004DBF4 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 3E3F8 8004DBF8 06002286 */  lh         $v0, 0x6($s1)
/* 3E3FC 8004DBFC 00000000 */  nop
/* 3E400 8004DC00 0C004104 */  bgez       $v0, .L8004DC34
/* 3E404 8004DC04 00000000 */   nop
/* 3E408 8004DC08 2120A000 */  addu       $a0, $a1, $zero
/* 3E40C 8004DC0C DB35010C */  jal        SsVabOpenHeadSticky
/* 3E410 8004DC10 FFFF0524 */   addiu     $a1, $zero, -0x1
/* 3E414 8004DC14 21804000 */  addu       $s0, $v0, $zero
/* 3E418 8004DC18 03000006 */  bltz       $s0, .L8004DC28
/* 3E41C 8004DC1C 0180043C */   lui       $a0, %hi(D_80012630)
/* 3E420 8004DC20 0D370108 */  j          .L8004DC34
/* 3E424 8004DC24 060030A6 */   sh        $s0, 0x6($s1)
.L8004DC28:
/* 3E428 8004DC28 9361000C */  jal        printf
/* 3E42C 8004DC2C 30268424 */   addiu     $a0, $a0, %lo(D_80012630)
/* 3E430 8004DC30 21100002 */  addu       $v0, $s0, $zero
.L8004DC34:
/* 3E434 8004DC34 1800BF8F */  lw         $ra, 0x18($sp)
/* 3E438 8004DC38 1400B18F */  lw         $s1, 0x14($sp)
/* 3E43C 8004DC3C 1000B08F */  lw         $s0, 0x10($sp)
/* 3E440 8004DC40 0800E003 */  jr         $ra
/* 3E444 8004DC44 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004DBCC, . - func_8004DBCC

glabel func_8004DC48
/* 3E448 8004DC48 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3E44C 8004DC4C 0880033C */  lui        $v1, %hi(D_80078940)
/* 3E450 8004DC50 40896324 */  addiu      $v1, $v1, %lo(D_80078940)
/* 3E454 8004DC54 1000BFAF */  sw         $ra, 0x10($sp)
/* 3E458 8004DC58 1C006294 */  lhu        $v0, 0x1C($v1)
/* 3E45C 8004DC5C FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 3E460 8004DC60 2B108200 */  sltu       $v0, $a0, $v0
/* 3E464 8004DC64 0D004010 */  beqz       $v0, .L8004DC9C
/* 3E468 8004DC68 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 3E46C 8004DC6C 1000638C */  lw         $v1, 0x10($v1)
/* 3E470 8004DC70 00000000 */  nop
/* 3E474 8004DC74 08006010 */  beqz       $v1, .L8004DC98
/* 3E478 8004DC78 00110400 */   sll       $v0, $a0, 4
/* 3E47C 8004DC7C 21106200 */  addu       $v0, $v1, $v0
/* 3E480 8004DC80 08004590 */  lbu        $a1, 0x8($v0)
/* 3E484 8004DC84 09004690 */  lbu        $a2, 0x9($v0)
/* 3E488 8004DC88 2B37010C */  jal        func_8004DCAC
/* 3E48C 8004DC8C 00000000 */   nop
/* 3E490 8004DC90 27370108 */  j          .L8004DC9C
/* 3E494 8004DC94 00000000 */   nop
.L8004DC98:
/* 3E498 8004DC98 FFFF0224 */  addiu      $v0, $zero, -0x1
.L8004DC9C:
/* 3E49C 8004DC9C 1000BF8F */  lw         $ra, 0x10($sp)
/* 3E4A0 8004DCA0 00000000 */  nop
/* 3E4A4 8004DCA4 0800E003 */  jr         $ra
/* 3E4A8 8004DCA8 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004DC48, . - func_8004DC48

glabel func_8004DCAC
/* 3E4AC 8004DCAC E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3E4B0 8004DCB0 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 3E4B4 8004DCB4 1800B2AF */  sw         $s2, 0x18($sp)
/* 3E4B8 8004DCB8 FF00B230 */  andi       $s2, $a1, 0xFF
/* 3E4BC 8004DCBC 0880033C */  lui        $v1, %hi(D_80078940)
/* 3E4C0 8004DCC0 40896324 */  addiu      $v1, $v1, %lo(D_80078940)
/* 3E4C4 8004DCC4 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 3E4C8 8004DCC8 1400B1AF */  sw         $s1, 0x14($sp)
/* 3E4CC 8004DCCC 1000B0AF */  sw         $s0, 0x10($sp)
/* 3E4D0 8004DCD0 1C006294 */  lhu        $v0, 0x1C($v1)
/* 3E4D4 8004DCD4 00000000 */  nop
/* 3E4D8 8004DCD8 2B108200 */  sltu       $v0, $a0, $v0
/* 3E4DC 8004DCDC 39004010 */  beqz       $v0, .L8004DDC4
/* 3E4E0 8004DCE0 FF00D130 */   andi      $s1, $a2, 0xFF
/* 3E4E4 8004DCE4 1000628C */  lw         $v0, 0x10($v1)
/* 3E4E8 8004DCE8 00000000 */  nop
/* 3E4EC 8004DCEC 3B004010 */  beqz       $v0, .L8004DDDC
/* 3E4F0 8004DCF0 21100000 */   addu      $v0, $zero, $zero
/* 3E4F4 8004DCF4 4000658C */  lw         $a1, 0x40($v1)
/* 3E4F8 8004DCF8 00000000 */  nop
/* 3E4FC 8004DCFC 0E00A010 */  beqz       $a1, .L8004DD38
/* 3E500 8004DD00 00000000 */   nop
.L8004DD04:
/* 3E504 8004DD04 1000A290 */  lbu        $v0, 0x10($a1)
/* 3E508 8004DD08 00000000 */  nop
/* 3E50C 8004DD0C 80004230 */  andi       $v0, $v0, 0x80
/* 3E510 8004DD10 05004014 */  bnez       $v0, .L8004DD28
/* 3E514 8004DD14 00000000 */   nop
/* 3E518 8004DD18 0C00A294 */  lhu        $v0, 0xC($a1)
/* 3E51C 8004DD1C 00000000 */  nop
/* 3E520 8004DD20 2E004410 */  beq        $v0, $a0, .L8004DDDC
/* 3E524 8004DD24 21100000 */   addu      $v0, $zero, $zero
.L8004DD28:
/* 3E528 8004DD28 0000A58C */  lw         $a1, 0x0($a1)
/* 3E52C 8004DD2C 00000000 */  nop
/* 3E530 8004DD30 F4FFA014 */  bnez       $a1, .L8004DD04
/* 3E534 8004DD34 00000000 */   nop
.L8004DD38:
/* 3E538 8004DD38 7D37010C */  jal        func_8004DDF4
/* 3E53C 8004DD3C 00000000 */   nop
/* 3E540 8004DD40 21804000 */  addu       $s0, $v0, $zero
/* 3E544 8004DD44 1F000012 */  beqz       $s0, .L8004DDC4
/* 3E548 8004DD48 0880023C */   lui       $v0, %hi(D_80078980)
/* 3E54C 8004DD4C 8089458C */  lw         $a1, %lo(D_80078980)($v0)
/* 3E550 8004DD50 00000000 */  nop
/* 3E554 8004DD54 1000A010 */  beqz       $a1, .L8004DD98
/* 3E558 8004DD58 21204000 */   addu      $a0, $v0, $zero
/* 3E55C 8004DD5C 1000A290 */  lbu        $v0, 0x10($a1)
/* 3E560 8004DD60 10000392 */  lbu        $v1, 0x10($s0)
/* 3E564 8004DD64 00000000 */  nop
/* 3E568 8004DD68 2B106200 */  sltu       $v0, $v1, $v0
/* 3E56C 8004DD6C 0A004010 */  beqz       $v0, .L8004DD98
/* 3E570 8004DD70 00000000 */   nop
.L8004DD74:
/* 3E574 8004DD74 0000A58C */  lw         $a1, 0x0($a1)
/* 3E578 8004DD78 00000000 */  nop
/* 3E57C 8004DD7C 0600A010 */  beqz       $a1, .L8004DD98
/* 3E580 8004DD80 00000000 */   nop
/* 3E584 8004DD84 1000A290 */  lbu        $v0, 0x10($a1)
/* 3E588 8004DD88 00000000 */  nop
/* 3E58C 8004DD8C 2B106200 */  sltu       $v0, $v1, $v0
/* 3E590 8004DD90 F8FF4014 */  bnez       $v0, .L8004DD74
/* 3E594 8004DD94 00000000 */   nop
.L8004DD98:
/* 3E598 8004DD98 120012A2 */  sb         $s2, 0x12($s0)
/* 3E59C 8004DD9C 0B00A014 */  bnez       $a1, .L8004DDCC
/* 3E5A0 8004DDA0 130011A2 */   sb        $s1, 0x13($s0)
/* 3E5A4 8004DDA4 0880023C */  lui        $v0, %hi(D_8007897C)
/* 3E5A8 8004DDA8 7C894224 */  addiu      $v0, $v0, %lo(D_8007897C)
/* 3E5AC 8004DDAC 04004424 */  addiu      $a0, $v0, 0x4
/* 3E5B0 8004DDB0 0800458C */  lw         $a1, 0x8($v0)
/* 3E5B4 8004DDB4 01F0000C */  jal        func_8003C004
/* 3E5B8 8004DDB8 21300002 */   addu      $a2, $s0, $zero
/* 3E5BC 8004DDBC 76370108 */  j          .L8004DDD8
/* 3E5C0 8004DDC0 00000000 */   nop
.L8004DDC4:
/* 3E5C4 8004DDC4 77370108 */  j          .L8004DDDC
/* 3E5C8 8004DDC8 21100000 */   addu      $v0, $zero, $zero
.L8004DDCC:
/* 3E5CC 8004DDCC 80898424 */  addiu      $a0, $a0, %lo(D_80078980)
/* 3E5D0 8004DDD0 81EF000C */  jal        func_8003BE04
/* 3E5D4 8004DDD4 21300002 */   addu      $a2, $s0, $zero
.L8004DDD8:
/* 3E5D8 8004DDD8 0800028E */  lw         $v0, 0x8($s0)
.L8004DDDC:
/* 3E5DC 8004DDDC 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 3E5E0 8004DDE0 1800B28F */  lw         $s2, 0x18($sp)
/* 3E5E4 8004DDE4 1400B18F */  lw         $s1, 0x14($sp)
/* 3E5E8 8004DDE8 1000B08F */  lw         $s0, 0x10($sp)
/* 3E5EC 8004DDEC 0800E003 */  jr         $ra
/* 3E5F0 8004DDF0 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004DCAC, . - func_8004DCAC

glabel func_8004DDF4
/* 3E5F4 8004DDF4 D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 3E5F8 8004DDF8 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 3E5FC 8004DDFC 21988000 */  addu       $s3, $a0, $zero
/* 3E600 8004DE00 0880023C */  lui        $v0, %hi(D_80078940)
/* 3E604 8004DE04 40894524 */  addiu      $a1, $v0, %lo(D_80078940)
/* 3E608 8004DE08 2000BFAF */  sw         $ra, 0x20($sp)
/* 3E60C 8004DE0C 1800B2AF */  sw         $s2, 0x18($sp)
/* 3E610 8004DE10 1400B1AF */  sw         $s1, 0x14($sp)
/* 3E614 8004DE14 1000B0AF */  sw         $s0, 0x10($sp)
/* 3E618 8004DE18 1000A48C */  lw         $a0, 0x10($a1)
/* 3E61C 8004DE1C 00191300 */  sll        $v1, $s3, 4
/* 3E620 8004DE20 21208300 */  addu       $a0, $a0, $v1
/* 3E624 8004DE24 00008294 */  lhu        $v0, 0x0($a0)
/* 3E628 8004DE28 0800A38C */  lw         $v1, 0x8($a1)
/* 3E62C 8004DE2C C0100200 */  sll        $v0, $v0, 3
/* 3E630 8004DE30 21104300 */  addu       $v0, $v0, $v1
/* 3E634 8004DE34 06005284 */  lh         $s2, 0x6($v0)
/* 3E638 8004DE38 00000000 */  nop
/* 3E63C 8004DE3C 38004006 */  bltz       $s2, .L8004DF20
/* 3E640 8004DE40 21100000 */   addu      $v0, $zero, $zero
/* 3E644 8004DE44 03008290 */  lbu        $v0, 0x3($a0)
/* 3E648 8004DE48 02008390 */  lbu        $v1, 0x2($a0)
/* 3E64C 8004DE4C 00000000 */  nop
/* 3E650 8004DE50 02006010 */  beqz       $v1, .L8004DE5C
/* 3E654 8004DE54 7F005130 */   andi      $s1, $v0, 0x7F
/* 3E658 8004DE58 80003136 */  ori        $s1, $s1, 0x80
.L8004DE5C:
/* 3E65C 8004DE5C 2000A394 */  lhu        $v1, 0x20($a1)
/* 3E660 8004DE60 4800A28C */  lw         $v0, 0x48($a1)
/* 3E664 8004DE64 00000000 */  nop
/* 3E668 8004DE68 18004314 */  bne        $v0, $v1, .L8004DECC
/* 3E66C 8004DE6C 00000000 */   nop
/* 3E670 8004DE70 4400B08C */  lw         $s0, 0x44($a1)
/* 3E674 8004DE74 00000000 */  nop
/* 3E678 8004DE78 10000392 */  lbu        $v1, 0x10($s0)
/* 3E67C 8004DE7C 00000000 */  nop
/* 3E680 8004DE80 2B102302 */  sltu       $v0, $s1, $v1
/* 3E684 8004DE84 26004014 */  bnez       $v0, .L8004DF20
/* 3E688 8004DE88 21100000 */   addu      $v0, $zero, $zero
/* 3E68C 8004DE8C 80006230 */  andi       $v0, $v1, 0x80
/* 3E690 8004DE90 09004010 */  beqz       $v0, .L8004DEB8
/* 3E694 8004DE94 0880043C */   lui       $a0, %hi(D_80078980)
/* 3E698 8004DE98 11000492 */  lbu        $a0, 0x11($s0)
/* 3E69C 8004DE9C 00000000 */  nop
/* 3E6A0 8004DEA0 80008230 */  andi       $v0, $a0, 0x80
/* 3E6A4 8004DEA4 03004010 */  beqz       $v0, .L8004DEB4
/* 3E6A8 8004DEA8 00000000 */   nop
/* 3E6AC 8004DEAC 2735010C */  jal        SsUtKeyOffV
/* 3E6B0 8004DEB0 1F008430 */   andi      $a0, $a0, 0x1F
.L8004DEB4:
/* 3E6B4 8004DEB4 0880043C */  lui        $a0, %hi(D_80078980)
.L8004DEB8:
/* 3E6B8 8004DEB8 80898424 */  addiu      $a0, $a0, %lo(D_80078980)
/* 3E6BC 8004DEBC 98EF000C */  jal        func_8003BE60
/* 3E6C0 8004DEC0 21280002 */   addu      $a1, $s0, $zero
/* 3E6C4 8004DEC4 BD370108 */  j          .L8004DEF4
/* 3E6C8 8004DEC8 21280002 */   addu      $a1, $s0, $zero
.L8004DECC:
/* 3E6CC 8004DECC 3C00A38C */  lw         $v1, 0x3C($a1)
/* 3E6D0 8004DED0 00000000 */  nop
/* 3E6D4 8004DED4 03006014 */  bnez       $v1, .L8004DEE4
/* 3E6D8 8004DED8 00000000 */   nop
/* 3E6DC 8004DEDC BC370108 */  j          .L8004DEF0
/* 3E6E0 8004DEE0 21180000 */   addu      $v1, $zero, $zero
.L8004DEE4:
/* 3E6E4 8004DEE4 0000628C */  lw         $v0, 0x0($v1)
/* 3E6E8 8004DEE8 00000000 */  nop
/* 3E6EC 8004DEEC 3C00A2AC */  sw         $v0, 0x3C($a1)
.L8004DEF0:
/* 3E6F0 8004DEF0 21286000 */  addu       $a1, $v1, $zero
.L8004DEF4:
/* 3E6F4 8004DEF4 2110A000 */  addu       $v0, $a1, $zero
/* 3E6F8 8004DEF8 1000B1A0 */  sb         $s1, 0x10($a1)
/* 3E6FC 8004DEFC A400848F */  lw         $a0, (0xA4 & 0xFFFF)($gp)
/* 3E700 8004DF00 0080033C */  lui        $v1, (0x80000000 >> 16)
/* 3E704 8004DF04 0C00B3A4 */  sh         $s3, 0xC($a1)
/* 3E708 8004DF08 0E00B2A4 */  sh         $s2, 0xE($a1)
/* 3E70C 8004DF0C 25188300 */  or         $v1, $a0, $v1
/* 3E710 8004DF10 01008424 */  addiu      $a0, $a0, 0x1
/* 3E714 8004DF14 0800A3AC */  sw         $v1, 0x8($a1)
/* 3E718 8004DF18 A40084AF */  sw         $a0, (0xA4 & 0xFFFF)($gp)
/* 3E71C 8004DF1C 1100A0A0 */  sb         $zero, 0x11($a1)
.L8004DF20:
/* 3E720 8004DF20 2000BF8F */  lw         $ra, 0x20($sp)
/* 3E724 8004DF24 1C00B38F */  lw         $s3, 0x1C($sp)
/* 3E728 8004DF28 1800B28F */  lw         $s2, 0x18($sp)
/* 3E72C 8004DF2C 1400B18F */  lw         $s1, 0x14($sp)
/* 3E730 8004DF30 1000B08F */  lw         $s0, 0x10($sp)
/* 3E734 8004DF34 0800E003 */  jr         $ra
/* 3E738 8004DF38 2800BD27 */   addiu     $sp, $sp, 0x28
.size func_8004DDF4, . - func_8004DDF4

glabel func_8004DF3C
/* 3E73C 8004DF3C 0880023C */  lui        $v0, %hi(D_80078980)
/* 3E740 8004DF40 8089438C */  lw         $v1, %lo(D_80078980)($v0)
/* 3E744 8004DF44 00000000 */  nop
/* 3E748 8004DF48 0C006010 */  beqz       $v1, .L8004DF7C
/* 3E74C 8004DF4C 00000000 */   nop
.L8004DF50:
/* 3E750 8004DF50 0800628C */  lw         $v0, 0x8($v1)
/* 3E754 8004DF54 00000000 */  nop
/* 3E758 8004DF58 04004414 */  bne        $v0, $a0, .L8004DF6C
/* 3E75C 8004DF5C 00000000 */   nop
/* 3E760 8004DF60 11006290 */  lbu        $v0, 0x11($v1)
/* 3E764 8004DF64 0800E003 */  jr         $ra
/* 3E768 8004DF68 1F004230 */   andi      $v0, $v0, 0x1F
.L8004DF6C:
/* 3E76C 8004DF6C 0000638C */  lw         $v1, 0x0($v1)
/* 3E770 8004DF70 00000000 */  nop
/* 3E774 8004DF74 F6FF6014 */  bnez       $v1, .L8004DF50
/* 3E778 8004DF78 00000000 */   nop
.L8004DF7C:
/* 3E77C 8004DF7C 0800E003 */  jr         $ra
/* 3E780 8004DF80 FFFF0224 */   addiu     $v0, $zero, -0x1
.size func_8004DF3C, . - func_8004DF3C

glabel func_8004DF84
/* 3E784 8004DF84 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3E788 8004DF88 0880023C */  lui        $v0, %hi(D_80078980)
/* 3E78C 8004DF8C 1000B0AF */  sw         $s0, 0x10($sp)
/* 3E790 8004DF90 8089508C */  lw         $s0, %lo(D_80078980)($v0)
/* 3E794 8004DF94 1400B1AF */  sw         $s1, 0x14($sp)
/* 3E798 8004DF98 0880113C */  lui        $s1, %hi(D_8007897C)
/* 3E79C 8004DF9C 08000012 */  beqz       $s0, .L8004DFC0
/* 3E7A0 8004DFA0 1800BFAF */   sw        $ra, 0x18($sp)
.L8004DFA4:
/* 3E7A4 8004DFA4 11000492 */  lbu        $a0, 0x11($s0)
/* 3E7A8 8004DFA8 2735010C */  jal        SsUtKeyOffV
/* 3E7AC 8004DFAC 1F008430 */   andi      $a0, $a0, 0x1F
/* 3E7B0 8004DFB0 0000108E */  lw         $s0, 0x0($s0)
/* 3E7B4 8004DFB4 00000000 */  nop
/* 3E7B8 8004DFB8 FAFF0016 */  bnez       $s0, .L8004DFA4
/* 3E7BC 8004DFBC 00000000 */   nop
.L8004DFC0:
/* 3E7C0 8004DFC0 7C892526 */  addiu      $a1, $s1, %lo(D_8007897C)
/* 3E7C4 8004DFC4 0C00A28C */  lw         $v0, 0xC($a1)
/* 3E7C8 8004DFC8 00000000 */  nop
/* 3E7CC 8004DFCC 0A004010 */  beqz       $v0, .L8004DFF8
/* 3E7D0 8004DFD0 00000000 */   nop
/* 3E7D4 8004DFD4 0800A28C */  lw         $v0, 0x8($a1)
/* 3E7D8 8004DFD8 7C89238E */  lw         $v1, %lo(D_8007897C)($s1)
/* 3E7DC 8004DFDC 00000000 */  nop
/* 3E7E0 8004DFE0 000043AC */  sw         $v1, 0x0($v0)
/* 3E7E4 8004DFE4 0400A48C */  lw         $a0, 0x4($a1)
/* 3E7E8 8004DFE8 0400A0AC */  sw         $zero, 0x4($a1)
/* 3E7EC 8004DFEC 0800A0AC */  sw         $zero, 0x8($a1)
/* 3E7F0 8004DFF0 0C00A0AC */  sw         $zero, 0xC($a1)
/* 3E7F4 8004DFF4 7C8924AE */  sw         $a0, %lo(D_8007897C)($s1)
.L8004DFF8:
/* 3E7F8 8004DFF8 1800BF8F */  lw         $ra, 0x18($sp)
/* 3E7FC 8004DFFC 1400B18F */  lw         $s1, 0x14($sp)
/* 3E800 8004E000 1000B08F */  lw         $s0, 0x10($sp)
/* 3E804 8004E004 0800E003 */  jr         $ra
/* 3E808 8004E008 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004DF84, . - func_8004DF84

glabel func_8004E00C
/* 3E80C 8004E00C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3E810 8004E010 FFFF8230 */  andi       $v0, $a0, 0xFFFF
/* 3E814 8004E014 2120A000 */  addu       $a0, $a1, $zero
/* 3E818 8004E018 0880033C */  lui        $v1, %hi(D_80078948)
/* 3E81C 8004E01C 4889658C */  lw         $a1, %lo(D_80078948)($v1)
/* 3E820 8004E020 C0100200 */  sll        $v0, $v0, 3
/* 3E824 8004E024 1400BFAF */  sw         $ra, 0x14($sp)
/* 3E828 8004E028 1000B0AF */  sw         $s0, 0x10($sp)
/* 3E82C 8004E02C 21104500 */  addu       $v0, $v0, $a1
/* 3E830 8004E030 06004584 */  lh         $a1, 0x6($v0)
/* 3E834 8004E034 1738010C */  jal        SsVabTransBody
/* 3E838 8004E038 00000000 */   nop
/* 3E83C 8004E03C 01000424 */  addiu      $a0, $zero, 0x1
/* 3E840 8004E040 4738010C */  jal        SsVabTransCompleted
/* 3E844 8004E044 21804000 */   addu      $s0, $v0, $zero
/* 3E848 8004E048 21100002 */  addu       $v0, $s0, $zero
/* 3E84C 8004E04C 1400BF8F */  lw         $ra, 0x14($sp)
/* 3E850 8004E050 1000B08F */  lw         $s0, 0x10($sp)
/* 3E854 8004E054 0800E003 */  jr         $ra
/* 3E858 8004E058 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004E00C, . - func_8004E00C

glabel SsVabTransBody
/* 3E85C 8004E05C D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 3E860 8004E060 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 3E864 8004E064 21988000 */  addu       $s3, $a0, $zero
/* 3E868 8004E068 FFFFA230 */  andi       $v0, $a1, 0xFFFF
/* 3E86C 8004E06C 1100422C */  sltiu      $v0, $v0, 0x11
/* 3E870 8004E070 2000BFAF */  sw         $ra, 0x20($sp)
/* 3E874 8004E074 1800B2AF */  sw         $s2, 0x18($sp)
/* 3E878 8004E078 1400B1AF */  sw         $s1, 0x14($sp)
/* 3E87C 8004E07C 1D004010 */  beqz       $v0, .L8004E0F4
/* 3E880 8004E080 1000B0AF */   sw        $s0, 0x10($sp)
/* 3E884 8004E084 00140500 */  sll        $v0, $a1, 16
/* 3E888 8004E088 038C0200 */  sra        $s1, $v0, 16
/* 3E88C 8004E08C 0880033C */  lui        $v1, %hi(D_80078790)
/* 3E890 8004E090 21187100 */  addu       $v1, $v1, $s1
/* 3E894 8004E094 90876390 */  lbu        $v1, %lo(D_80078790)($v1)
/* 3E898 8004E098 02000224 */  addiu      $v0, $zero, 0x2
/* 3E89C 8004E09C 15006214 */  bne        $v1, $v0, .L8004E0F4
/* 3E8A0 8004E0A0 80901100 */   sll       $s2, $s1, 2
/* 3E8A4 8004E0A4 0880103C */  lui        $s0, %hi(D_800787F0)
/* 3E8A8 8004E0A8 21801202 */  addu       $s0, $s0, $s2
/* 3E8AC 8004E0AC F087108E */  lw         $s0, %lo(D_800787F0)($s0)
/* 3E8B0 8004E0B0 8338010C */  jal        SpuSetTransferMode
/* 3E8B4 8004E0B4 21200000 */   addu      $a0, $zero, $zero
/* 3E8B8 8004E0B8 6B38010C */  jal        SpuSetTransferStartAddr
/* 3E8BC 8004E0BC 21200002 */   addu      $a0, $s0, $zero
/* 3E8C0 8004E0C0 0C004010 */  beqz       $v0, .L8004E0F4
/* 3E8C4 8004E0C4 00000000 */   nop
/* 3E8C8 8004E0C8 0880053C */  lui        $a1, %hi(D_800787A8)
/* 3E8CC 8004E0CC 2128B200 */  addu       $a1, $a1, $s2
/* 3E8D0 8004E0D0 A887A58C */  lw         $a1, %lo(D_800787A8)($a1)
/* 3E8D4 8004E0D4 5338010C */  jal        SpuRead
/* 3E8D8 8004E0D8 21206002 */   addu      $a0, $s3, $zero
/* 3E8DC 8004E0DC 21102002 */  addu       $v0, $s1, $zero
/* 3E8E0 8004E0E0 01000324 */  addiu      $v1, $zero, 0x1
/* 3E8E4 8004E0E4 0880013C */  lui        $at, %hi(D_80078790)
/* 3E8E8 8004E0E8 21082200 */  addu       $at, $at, $v0
/* 3E8EC 8004E0EC 40380108 */  j          VS_VTB_OBJ_A4
/* 3E8F0 8004E0F0 908723A0 */   sb        $v1, %lo(D_80078790)($at)
.L8004E0F4:
/* 3E8F4 8004E0F4 4713010C */  jal        func_80044D1C
/* 3E8F8 8004E0F8 21200000 */   addu      $a0, $zero, $zero
/* 3E8FC 8004E0FC FFFF0224 */  addiu      $v0, $zero, -0x1
.size SsVabTransBody, . - SsVabTransBody

glabel VS_VTB_OBJ_A4
/* 3E900 8004E100 2000BF8F */  lw         $ra, 0x20($sp)
/* 3E904 8004E104 1C00B38F */  lw         $s3, 0x1C($sp)
/* 3E908 8004E108 1800B28F */  lw         $s2, 0x18($sp)
/* 3E90C 8004E10C 1400B18F */  lw         $s1, 0x14($sp)
/* 3E910 8004E110 1000B08F */  lw         $s0, 0x10($sp)
/* 3E914 8004E114 0800E003 */  jr         $ra
/* 3E918 8004E118 2800BD27 */   addiu     $sp, $sp, 0x28
.size VS_VTB_OBJ_A4, . - VS_VTB_OBJ_A4

glabel SsVabTransCompleted
/* 3E91C 8004E11C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3E920 8004E120 1000BFAF */  sw         $ra, 0x10($sp)
/* 3E924 8004E124 00240400 */  sll        $a0, $a0, 16
/* 3E928 8004E128 8F38010C */  jal        SpuIsTransferCompleted
/* 3E92C 8004E12C 03240400 */   sra       $a0, $a0, 16
/* 3E930 8004E130 00140200 */  sll        $v0, $v0, 16
/* 3E934 8004E134 1000BF8F */  lw         $ra, 0x10($sp)
/* 3E938 8004E138 03140200 */  sra        $v0, $v0, 16
/* 3E93C 8004E13C 0800E003 */  jr         $ra
/* 3E940 8004E140 1800BD27 */   addiu     $sp, $sp, 0x18
/* 3E944 8004E144 00000000 */  nop
/* 3E948 8004E148 00000000 */  nop
.size SsVabTransCompleted, . - SsVabTransCompleted

glabel SpuRead
/* 3E94C 8004E14C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3E950 8004E150 1000B0AF */  sw         $s0, 0x10($sp)
/* 3E954 8004E154 2180A000 */  addu       $s0, $a1, $zero
/* 3E958 8004E158 0700023C */  lui        $v0, (0x7EFF0 >> 16)
/* 3E95C 8004E15C F0EF4234 */  ori        $v0, $v0, (0x7EFF0 & 0xFFFF)
/* 3E960 8004E160 2B105000 */  sltu       $v0, $v0, $s0
/* 3E964 8004E164 03004010 */  beqz       $v0, .L8004E174
/* 3E968 8004E168 1400BFAF */   sw        $ra, 0x14($sp)
/* 3E96C 8004E16C 0700103C */  lui        $s0, (0x7EFF0 >> 16)
/* 3E970 8004E170 F0EF1036 */  ori        $s0, $s0, (0x7EFF0 & 0xFFFF)
.L8004E174:
/* 3E974 8004E174 0CCD000C */  jal        _spu_Fw
/* 3E978 8004E178 21280002 */   addu      $a1, $s0, $zero
/* 3E97C 8004E17C 0780023C */  lui        $v0, %hi(D_80069144)
/* 3E980 8004E180 4491428C */  lw         $v0, %lo(D_80069144)($v0)
/* 3E984 8004E184 00000000 */  nop
/* 3E988 8004E188 03004014 */  bnez       $v0, .L8004E198
/* 3E98C 8004E18C 21100002 */   addu      $v0, $s0, $zero
/* 3E990 8004E190 0780013C */  lui        $at, %hi(D_80069140)
/* 3E994 8004E194 409120AC */  sw         $zero, %lo(D_80069140)($at)
.L8004E198:
/* 3E998 8004E198 1400BF8F */  lw         $ra, 0x14($sp)
/* 3E99C 8004E19C 1000B08F */  lw         $s0, 0x10($sp)
/* 3E9A0 8004E1A0 0800E003 */  jr         $ra
/* 3E9A4 8004E1A4 1800BD27 */   addiu     $sp, $sp, 0x18
/* 3E9A8 8004E1A8 00000000 */  nop
.size SpuRead, . - SpuRead

glabel SpuSetTransferStartAddr
/* 3E9AC 8004E1AC E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3E9B0 8004E1B0 21288000 */  addu       $a1, $a0, $zero
/* 3E9B4 8004E1B4 0700023C */  lui        $v0, (0x7EFE8 >> 16)
/* 3E9B8 8004E1B8 E8EF4234 */  ori        $v0, $v0, (0x7EFE8 & 0xFFFF)
/* 3E9BC 8004E1BC F0EFA324 */  addiu      $v1, $a1, -0x1010
/* 3E9C0 8004E1C0 2B104300 */  sltu       $v0, $v0, $v1
/* 3E9C4 8004E1C4 0B004014 */  bnez       $v0, .L8004E1F4
/* 3E9C8 8004E1C8 1000BFAF */   sw        $ra, 0x10($sp)
/* 3E9CC 8004E1CC 57CD000C */  jal        _spu_FsetRXXa
/* 3E9D0 8004E1D0 FFFF0424 */   addiu     $a0, $zero, -0x1
/* 3E9D4 8004E1D4 0780013C */  lui        $at, %hi(D_80069124)
/* 3E9D8 8004E1D8 249122A4 */  sh         $v0, %lo(D_80069124)($at)
/* 3E9DC 8004E1DC 0780033C */  lui        $v1, %hi(D_80069124)
/* 3E9E0 8004E1E0 24916394 */  lhu        $v1, %lo(D_80069124)($v1)
/* 3E9E4 8004E1E4 0780023C */  lui        $v0, %hi(D_80069134)
/* 3E9E8 8004E1E8 3491428C */  lw         $v0, %lo(D_80069134)($v0)
/* 3E9EC 8004E1EC 7E380108 */  j          S_STSA_OBJ_4C
/* 3E9F0 8004E1F0 04104300 */   sllv      $v0, $v1, $v0
.L8004E1F4:
/* 3E9F4 8004E1F4 21100000 */  addu       $v0, $zero, $zero
.size SpuSetTransferStartAddr, . - SpuSetTransferStartAddr

glabel S_STSA_OBJ_4C
/* 3E9F8 8004E1F8 1000BF8F */  lw         $ra, 0x10($sp)
/* 3E9FC 8004E1FC 1800BD27 */  addiu      $sp, $sp, 0x18
/* 3EA00 8004E200 0800E003 */  jr         $ra
/* 3EA04 8004E204 00000000 */   nop
/* 3EA08 8004E208 00000000 */  nop
.size S_STSA_OBJ_4C, . - S_STSA_OBJ_4C

glabel SpuSetTransferMode
/* 3EA0C 8004E20C 05008010 */  beqz       $a0, .L8004E224
/* 3EA10 8004E210 01000224 */   addiu     $v0, $zero, 0x1
/* 3EA14 8004E214 04008214 */  bne        $a0, $v0, S_STM_OBJ_1C
/* 3EA18 8004E218 21100000 */   addu      $v0, $zero, $zero
/* 3EA1C 8004E21C 8A380108 */  j          S_STM_OBJ_1C
/* 3EA20 8004E220 01000224 */   addiu     $v0, $zero, 0x1
.L8004E224:
/* 3EA24 8004E224 21100000 */  addu       $v0, $zero, $zero
.size SpuSetTransferMode, . - SpuSetTransferMode

glabel S_STM_OBJ_1C
/* 3EA28 8004E228 0780013C */  lui        $at, %hi(D_8006987C)
/* 3EA2C 8004E22C 7C9824AC */  sw         $a0, %lo(D_8006987C)($at)
/* 3EA30 8004E230 0780013C */  lui        $at, %hi(D_80069128)
/* 3EA34 8004E234 0800E003 */  jr         $ra
/* 3EA38 8004E238 289122AC */   sw        $v0, %lo(D_80069128)($at)
.size S_STM_OBJ_1C, . - S_STM_OBJ_1C

glabel SpuIsTransferCompleted
/* 3EA3C 8004E23C 0780023C */  lui        $v0, %hi(D_8006987C)
/* 3EA40 8004E240 7C98428C */  lw         $v0, %lo(D_8006987C)($v0)
/* 3EA44 8004E244 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3EA48 8004E248 1400B1AF */  sw         $s1, 0x14($sp)
/* 3EA4C 8004E24C 21888000 */  addu       $s1, $a0, $zero
/* 3EA50 8004E250 1000B0AF */  sw         $s0, 0x10($sp)
/* 3EA54 8004E254 01001024 */  addiu      $s0, $zero, 0x1
/* 3EA58 8004E258 06005010 */  beq        $v0, $s0, .L8004E274
/* 3EA5C 8004E25C 1800BFAF */   sw        $ra, 0x18($sp)
/* 3EA60 8004E260 0780023C */  lui        $v0, %hi(D_80069140)
/* 3EA64 8004E264 4091428C */  lw         $v0, %lo(D_80069140)($v0)
/* 3EA68 8004E268 00000000 */  nop
/* 3EA6C 8004E26C 03005014 */  bne        $v0, $s0, .L8004E27C
/* 3EA70 8004E270 00000000 */   nop
.L8004E274:
/* 3EA74 8004E274 B3380108 */  j          S_ITC_OBJ_90
/* 3EA78 8004E278 01000224 */   addiu     $v0, $zero, 0x1
.L8004E27C:
/* 3EA7C 8004E27C 0780043C */  lui        $a0, %hi(D_80069874)
/* 3EA80 8004E280 7498848C */  lw         $a0, %lo(D_80069874)($a0)
/* 3EA84 8004E284 BB38010C */  jal        TestEvent
/* 3EA88 8004E288 00000000 */   nop
/* 3EA8C 8004E28C 0B003016 */  bne        $s1, $s0, .L8004E2BC
/* 3EA90 8004E290 00000000 */   nop
/* 3EA94 8004E294 0B004014 */  bnez       $v0, S_ITC_OBJ_88
/* 3EA98 8004E298 01000224 */   addiu     $v0, $zero, 0x1
.L8004E29C:
/* 3EA9C 8004E29C 0780043C */  lui        $a0, %hi(D_80069874)
/* 3EAA0 8004E2A0 7498848C */  lw         $a0, %lo(D_80069874)($a0)
/* 3EAA4 8004E2A4 BB38010C */  jal        TestEvent
/* 3EAA8 8004E2A8 00000000 */   nop
/* 3EAAC 8004E2AC FBFF4010 */  beqz       $v0, .L8004E29C
/* 3EAB0 8004E2B0 01000224 */   addiu     $v0, $zero, 0x1
/* 3EAB4 8004E2B4 B1380108 */  j          S_ITC_OBJ_88
/* 3EAB8 8004E2B8 00000000 */   nop
.L8004E2BC:
/* 3EABC 8004E2BC 03005014 */  bne        $v0, $s0, S_ITC_OBJ_90
/* 3EAC0 8004E2C0 00000000 */   nop
.size SpuIsTransferCompleted, . - SpuIsTransferCompleted

glabel S_ITC_OBJ_88
/* 3EAC4 8004E2C4 0780013C */  lui        $at, %hi(D_80069140)
/* 3EAC8 8004E2C8 409122AC */  sw         $v0, %lo(D_80069140)($at)
.size S_ITC_OBJ_88, . - S_ITC_OBJ_88

glabel S_ITC_OBJ_90
/* 3EACC 8004E2CC 1800BF8F */  lw         $ra, 0x18($sp)
/* 3EAD0 8004E2D0 1400B18F */  lw         $s1, 0x14($sp)
/* 3EAD4 8004E2D4 1000B08F */  lw         $s0, 0x10($sp)
/* 3EAD8 8004E2D8 0800E003 */  jr         $ra
/* 3EADC 8004E2DC 2000BD27 */   addiu     $sp, $sp, 0x20
/* 3EAE0 8004E2E0 00000000 */  nop
/* 3EAE4 8004E2E4 00000000 */  nop
/* 3EAE8 8004E2E8 00000000 */  nop
.size S_ITC_OBJ_90, . - S_ITC_OBJ_90

glabel TestEvent
/* 3EAEC 8004E2EC B0000A24 */  addiu      $t2, $zero, 0xB0
/* 3EAF0 8004E2F0 08004001 */  jr         $t2
/* 3EAF4 8004E2F4 0B000924 */   addiu     $t1, $zero, 0xB
/* 3EAF8 8004E2F8 00000000 */  nop
.size TestEvent, . - TestEvent

glabel func_8004E2FC
/* 3EAFC 8004E2FC E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3EB00 8004E300 0880023C */  lui        $v0, %hi(D_80078980)
/* 3EB04 8004E304 002C0500 */  sll        $a1, $a1, 16
/* 3EB08 8004E308 8089468C */  lw         $a2, %lo(D_80078980)($v0)
/* 3EB0C 8004E30C 03440500 */  sra        $t0, $a1, 16
/* 3EB10 8004E310 1800C010 */  beqz       $a2, .L8004E374
/* 3EB14 8004E314 1800BFAF */   sw        $ra, 0x18($sp)
/* 3EB18 8004E318 0880023C */  lui        $v0, %hi(D_80078940)
/* 3EB1C 8004E31C 40894324 */  addiu      $v1, $v0, %lo(D_80078940)
.L8004E320:
/* 3EB20 8004E320 0800C28C */  lw         $v0, 0x8($a2)
/* 3EB24 8004E324 00000000 */  nop
/* 3EB28 8004E328 0E004414 */  bne        $v0, $a0, .L8004E364
/* 3EB2C 8004E32C 00000000 */   nop
/* 3EB30 8004E330 0C00C294 */  lhu        $v0, 0xC($a2)
/* 3EB34 8004E334 1000638C */  lw         $v1, 0x10($v1)
/* 3EB38 8004E338 1100C490 */  lbu        $a0, 0x11($a2)
/* 3EB3C 8004E33C 0E00C584 */  lh         $a1, 0xE($a2)
/* 3EB40 8004E340 00110200 */  sll        $v0, $v0, 4
/* 3EB44 8004E344 21186200 */  addu       $v1, $v1, $v0
/* 3EB48 8004E348 04006690 */  lbu        $a2, 0x4($v1)
/* 3EB4C 8004E34C 06006790 */  lbu        $a3, 0x6($v1)
/* 3EB50 8004E350 1F008430 */  andi       $a0, $a0, 0x1F
/* 3EB54 8004E354 E138010C */  jal        SsUtPitchBend
/* 3EB58 8004E358 1000A8AF */   sw        $t0, 0x10($sp)
/* 3EB5C 8004E35C DD380108 */  j          .L8004E374
/* 3EB60 8004E360 00000000 */   nop
.L8004E364:
/* 3EB64 8004E364 0000C68C */  lw         $a2, 0x0($a2)
/* 3EB68 8004E368 00000000 */  nop
/* 3EB6C 8004E36C ECFFC014 */  bnez       $a2, .L8004E320
/* 3EB70 8004E370 00000000 */   nop
.L8004E374:
/* 3EB74 8004E374 1800BF8F */  lw         $ra, 0x18($sp)
/* 3EB78 8004E378 00000000 */  nop
/* 3EB7C 8004E37C 0800E003 */  jr         $ra
/* 3EB80 8004E380 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004E2FC, . - func_8004E2FC

glabel SsUtPitchBend
/* 3EB84 8004E384 D0FFBD27 */  addiu      $sp, $sp, -0x30
/* 3EB88 8004E388 1C00B1AF */  sw         $s1, 0x1C($sp)
/* 3EB8C 8004E38C 21888000 */  addu       $s1, $a0, $zero
/* 3EB90 8004E390 2000B2AF */  sw         $s2, 0x20($sp)
/* 3EB94 8004E394 00940500 */  sll        $s2, $a1, 16
/* 3EB98 8004E398 03941200 */  sra        $s2, $s2, 16
/* 3EB9C 8004E39C 21204002 */  addu       $a0, $s2, $zero
/* 3EBA0 8004E3A0 1800B0AF */  sw         $s0, 0x18($sp)
/* 3EBA4 8004E3A4 00840600 */  sll        $s0, $a2, 16
/* 3EBA8 8004E3A8 03841000 */  sra        $s0, $s0, 16
/* 3EBAC 8004E3AC 2400B3AF */  sw         $s3, 0x24($sp)
/* 3EBB0 8004E3B0 4000B397 */  lhu        $s3, 0x40($sp)
/* 3EBB4 8004E3B4 2800BFAF */  sw         $ra, 0x28($sp)
/* 3EBB8 8004E3B8 730F010C */  jal        _SsVmVSetUp
/* 3EBBC 8004E3BC 21280002 */   addu      $a1, $s0, $zero
/* 3EBC0 8004E3C0 008C1100 */  sll        $s1, $s1, 16
/* 3EBC4 8004E3C4 03241100 */  sra        $a0, $s1, 16
/* 3EBC8 8004E3C8 21000524 */  addiu      $a1, $zero, 0x21
/* 3EBCC 8004E3CC 21000224 */  addiu      $v0, $zero, 0x21
/* 3EBD0 8004E3D0 21304002 */  addu       $a2, $s2, $zero
/* 3EBD4 8004E3D4 21380002 */  addu       $a3, $s0, $zero
/* 3EBD8 8004E3D8 0880013C */  lui        $at, %hi(D_80078784)
/* 3EBDC 8004E3DC 848722A4 */  sh         $v0, %lo(D_80078784)($at)
/* 3EBE0 8004E3E0 5D2F010C */  jal        _SsVmPBVoice
/* 3EBE4 8004E3E4 1000B3AF */   sw        $s3, 0x10($sp)
/* 3EBE8 8004E3E8 001C0200 */  sll        $v1, $v0, 16
/* 3EBEC 8004E3EC 02006010 */  beqz       $v1, .L8004E3F8
/* 3EBF0 8004E3F0 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 3EBF4 8004E3F4 21100000 */  addu       $v0, $zero, $zero
.L8004E3F8:
/* 3EBF8 8004E3F8 2800BF8F */  lw         $ra, 0x28($sp)
/* 3EBFC 8004E3FC 2400B38F */  lw         $s3, 0x24($sp)
/* 3EC00 8004E400 2000B28F */  lw         $s2, 0x20($sp)
/* 3EC04 8004E404 1C00B18F */  lw         $s1, 0x1C($sp)
/* 3EC08 8004E408 1800B08F */  lw         $s0, 0x18($sp)
/* 3EC0C 8004E40C 0800E003 */  jr         $ra
/* 3EC10 8004E410 3000BD27 */   addiu     $sp, $sp, 0x30
.size SsUtPitchBend, . - SsUtPitchBend

glabel func_8004E414
/* 3EC14 8004E414 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3EC18 8004E418 0880023C */  lui        $v0, %hi(D_80078980)
/* 3EC1C 8004E41C 1000B0AF */  sw         $s0, 0x10($sp)
/* 3EC20 8004E420 8089508C */  lw         $s0, %lo(D_80078980)($v0)
/* 3EC24 8004E424 1400B1AF */  sw         $s1, 0x14($sp)
/* 3EC28 8004E428 21888000 */  addu       $s1, $a0, $zero
/* 3EC2C 8004E42C 17000012 */  beqz       $s0, .L8004E48C
/* 3EC30 8004E430 1800BFAF */   sw        $ra, 0x18($sp)
.L8004E434:
/* 3EC34 8004E434 10000292 */  lbu        $v0, 0x10($s0)
/* 3EC38 8004E438 00000000 */  nop
/* 3EC3C 8004E43C 80004230 */  andi       $v0, $v0, 0x80
/* 3EC40 8004E440 0E004010 */  beqz       $v0, .L8004E47C
/* 3EC44 8004E444 00000000 */   nop
/* 3EC48 8004E448 07002012 */  beqz       $s1, .L8004E468
/* 3EC4C 8004E44C 21280000 */   addu      $a1, $zero, $zero
/* 3EC50 8004E450 11000492 */  lbu        $a0, 0x11($s0)
/* 3EC54 8004E454 21300000 */  addu       $a2, $zero, $zero
/* 3EC58 8004E458 4435010C */  jal        SsUtSetVVol
/* 3EC5C 8004E45C 1F008430 */   andi      $a0, $a0, 0x1F
/* 3EC60 8004E460 1F390108 */  j          .L8004E47C
/* 3EC64 8004E464 00000000 */   nop
.L8004E468:
/* 3EC68 8004E468 12000592 */  lbu        $a1, 0x12($s0)
/* 3EC6C 8004E46C 11000492 */  lbu        $a0, 0x11($s0)
/* 3EC70 8004E470 13000692 */  lbu        $a2, 0x13($s0)
/* 3EC74 8004E474 4435010C */  jal        SsUtSetVVol
/* 3EC78 8004E478 1F008430 */   andi      $a0, $a0, 0x1F
.L8004E47C:
/* 3EC7C 8004E47C 0000108E */  lw         $s0, 0x0($s0)
/* 3EC80 8004E480 00000000 */  nop
/* 3EC84 8004E484 EBFF0016 */  bnez       $s0, .L8004E434
/* 3EC88 8004E488 00000000 */   nop
.L8004E48C:
/* 3EC8C 8004E48C 1800BF8F */  lw         $ra, 0x18($sp)
/* 3EC90 8004E490 1400B18F */  lw         $s1, 0x14($sp)
/* 3EC94 8004E494 1000B08F */  lw         $s0, 0x10($sp)
/* 3EC98 8004E498 0800E003 */  jr         $ra
/* 3EC9C 8004E49C 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004E414, . - func_8004E414

glabel func_8004E4A0
/* 3ECA0 8004E4A0 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3ECA4 8004E4A4 0880023C */  lui        $v0, %hi(D_80078980)
/* 3ECA8 8004E4A8 1000B0AF */  sw         $s0, 0x10($sp)
/* 3ECAC 8004E4AC 8089508C */  lw         $s0, %lo(D_80078980)($v0)
/* 3ECB0 8004E4B0 21188000 */  addu       $v1, $a0, $zero
/* 3ECB4 8004E4B4 1800BFAF */  sw         $ra, 0x18($sp)
/* 3ECB8 8004E4B8 1B000012 */  beqz       $s0, .L8004E528
/* 3ECBC 8004E4BC 1400B1AF */   sw        $s1, 0x14($sp)
/* 3ECC0 8004E4C0 0880113C */  lui        $s1, %hi(D_8007897C)
/* 3ECC4 8004E4C4 7C892426 */  addiu      $a0, $s1, %lo(D_8007897C)
.L8004E4C8:
/* 3ECC8 8004E4C8 0800028E */  lw         $v0, 0x8($s0)
/* 3ECCC 8004E4CC 00000000 */  nop
/* 3ECD0 8004E4D0 11004314 */  bne        $v0, $v1, .L8004E518
/* 3ECD4 8004E4D4 00000000 */   nop
/* 3ECD8 8004E4D8 04008424 */  addiu      $a0, $a0, 0x4
/* 3ECDC 8004E4DC 98EF000C */  jal        func_8003BE60
/* 3ECE0 8004E4E0 21280002 */   addu      $a1, $s0, $zero
/* 3ECE4 8004E4E4 7C89228E */  lw         $v0, %lo(D_8007897C)($s1)
/* 3ECE8 8004E4E8 00000000 */  nop
/* 3ECEC 8004E4EC 000002AE */  sw         $v0, 0x0($s0)
/* 3ECF0 8004E4F0 7C8930AE */  sw         $s0, %lo(D_8007897C)($s1)
/* 3ECF4 8004E4F4 11000492 */  lbu        $a0, 0x11($s0)
/* 3ECF8 8004E4F8 00000000 */  nop
/* 3ECFC 8004E4FC 80008230 */  andi       $v0, $a0, 0x80
/* 3ED00 8004E500 09004010 */  beqz       $v0, .L8004E528
/* 3ED04 8004E504 00000000 */   nop
/* 3ED08 8004E508 2735010C */  jal        SsUtKeyOffV
/* 3ED0C 8004E50C 1F008430 */   andi      $a0, $a0, 0x1F
/* 3ED10 8004E510 4A390108 */  j          .L8004E528
/* 3ED14 8004E514 00000000 */   nop
.L8004E518:
/* 3ED18 8004E518 0000108E */  lw         $s0, 0x0($s0)
/* 3ED1C 8004E51C 00000000 */  nop
/* 3ED20 8004E520 E9FF0016 */  bnez       $s0, .L8004E4C8
/* 3ED24 8004E524 00000000 */   nop
.L8004E528:
/* 3ED28 8004E528 1800BF8F */  lw         $ra, 0x18($sp)
/* 3ED2C 8004E52C 1400B18F */  lw         $s1, 0x14($sp)
/* 3ED30 8004E530 1000B08F */  lw         $s0, 0x10($sp)
/* 3ED34 8004E534 0800E003 */  jr         $ra
/* 3ED38 8004E538 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004E4A0, . - func_8004E4A0

glabel func_8004E53C
/* 3ED3C 8004E53C E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3ED40 8004E540 0880023C */  lui        $v0, %hi(D_80078D14)
/* 3ED44 8004E544 0880033C */  lui        $v1, %hi(D_80078D20)
/* 3ED48 8004E548 1400B1AF */  sw         $s1, 0x14($sp)
/* 3ED4C 8004E54C 208D7124 */  addiu      $s1, $v1, %lo(D_80078D20)
/* 3ED50 8004E550 1000B0AF */  sw         $s0, 0x10($sp)
/* 3ED54 8004E554 01001024 */  addiu      $s0, $zero, 0x1
/* 3ED58 8004E558 1800BFAF */  sw         $ra, 0x18($sp)
/* 3ED5C 8004E55C 148D40AC */  sw         $zero, %lo(D_80078D14)($v0)
.L8004E560:
/* 3ED60 8004E560 F239010C */  jal        func_8004E7C8
/* 3ED64 8004E564 21202002 */   addu      $a0, $s1, $zero
/* 3ED68 8004E568 FFFF1026 */  addiu      $s0, $s0, -0x1
/* 3ED6C 8004E56C FCFF0106 */  bgez       $s0, .L8004E560
/* 3ED70 8004E570 44003126 */   addiu     $s1, $s1, 0x44
/* 3ED74 8004E574 9B61000C */  jal        EnterCriticalSection
/* 3ED78 8004E578 00000000 */   nop
/* 3ED7C 8004E57C A039010C */  jal        func_8004E680
/* 3ED80 8004E580 00000000 */   nop
/* 3ED84 8004E584 0580043C */  lui        $a0, %hi(func_8004E878)
/* 3ED88 8004E588 7056000C */  jal        DrawSyncCallback
/* 3ED8C 8004E58C 78E88424 */   addiu     $a0, $a0, %lo(func_8004E878)
/* 3ED90 8004E590 9F61000C */  jal        ExitCriticalSection
/* 3ED94 8004E594 00000000 */   nop
/* 3ED98 8004E598 01000324 */  addiu      $v1, $zero, 0x1
/* 3ED9C 8004E59C 1800BF8F */  lw         $ra, 0x18($sp)
/* 3EDA0 8004E5A0 1400B18F */  lw         $s1, 0x14($sp)
/* 3EDA4 8004E5A4 1000B08F */  lw         $s0, 0x10($sp)
/* 3EDA8 8004E5A8 0780023C */  lui        $v0, %hi(D_8006A21C)
/* 3EDAC 8004E5AC 1CA243AC */  sw         $v1, %lo(D_8006A21C)($v0)
/* 3EDB0 8004E5B0 0800E003 */  jr         $ra
/* 3EDB4 8004E5B4 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004E53C, . - func_8004E53C

glabel func_8004E5B8
/* 3EDB8 8004E5B8 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3EDBC 8004E5BC 1000B0AF */  sw         $s0, 0x10($sp)
/* 3EDC0 8004E5C0 0780103C */  lui        $s0, %hi(D_8006A21C)
/* 3EDC4 8004E5C4 1CA2028E */  lw         $v0, %lo(D_8006A21C)($s0)
/* 3EDC8 8004E5C8 00000000 */  nop
/* 3EDCC 8004E5CC 0A004010 */  beqz       $v0, .L8004E5F8
/* 3EDD0 8004E5D0 1400BFAF */   sw        $ra, 0x14($sp)
/* 3EDD4 8004E5D4 9B61000C */  jal        EnterCriticalSection
/* 3EDD8 8004E5D8 00000000 */   nop
/* 3EDDC 8004E5DC 7056000C */  jal        DrawSyncCallback
/* 3EDE0 8004E5E0 21200000 */   addu      $a0, $zero, $zero
/* 3EDE4 8004E5E4 E039010C */  jal        func_8004E780
/* 3EDE8 8004E5E8 00000000 */   nop
/* 3EDEC 8004E5EC 9F61000C */  jal        ExitCriticalSection
/* 3EDF0 8004E5F0 00000000 */   nop
/* 3EDF4 8004E5F4 1CA200AE */  sw         $zero, %lo(D_8006A21C)($s0)
.L8004E5F8:
/* 3EDF8 8004E5F8 1400BF8F */  lw         $ra, 0x14($sp)
/* 3EDFC 8004E5FC 1000B08F */  lw         $s0, 0x10($sp)
/* 3EE00 8004E600 0800E003 */  jr         $ra
/* 3EE04 8004E604 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004E5B8, . - func_8004E5B8

glabel func_8004E608
/* 3EE08 8004E608 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3EE0C 8004E60C 1000BFAF */  sw         $ra, 0x10($sp)
/* 3EE10 8004E610 00240400 */  sll        $a0, $a0, 16
/* 3EE14 8004E614 03240400 */  sra        $a0, $a0, 16
/* 3EE18 8004E618 04008018 */  blez       $a0, .L8004E62C
/* 3EE1C 8004E61C 0780033C */   lui       $v1, %hi(D_8006A220)
/* 3EE20 8004E620 09008228 */  slti       $v0, $a0, 0x9
/* 3EE24 8004E624 04004010 */  beqz       $v0, .L8004E638
/* 3EE28 8004E628 09000224 */   addiu     $v0, $zero, 0x9
.L8004E62C:
/* 3EE2C 8004E62C 0200801C */  bgtz       $a0, .L8004E638
/* 3EE30 8004E630 21108000 */   addu      $v0, $a0, $zero
/* 3EE34 8004E634 01000224 */  addiu      $v0, $zero, 0x1
.L8004E638:
/* 3EE38 8004E638 20A262A4 */  sh         $v0, %lo(D_8006A220)($v1)
/* 3EE3C 8004E63C 0780023C */  lui        $v0, %hi(D_8006A21C)
/* 3EE40 8004E640 1CA2438C */  lw         $v1, %lo(D_8006A21C)($v0)
/* 3EE44 8004E644 00000000 */  nop
/* 3EE48 8004E648 09006010 */  beqz       $v1, .L8004E670
/* 3EE4C 8004E64C 00000000 */   nop
/* 3EE50 8004E650 9B61000C */  jal        EnterCriticalSection
/* 3EE54 8004E654 00000000 */   nop
/* 3EE58 8004E658 E039010C */  jal        func_8004E780
/* 3EE5C 8004E65C 00000000 */   nop
/* 3EE60 8004E660 A039010C */  jal        func_8004E680
/* 3EE64 8004E664 00000000 */   nop
/* 3EE68 8004E668 9F61000C */  jal        ExitCriticalSection
/* 3EE6C 8004E66C 00000000 */   nop
.L8004E670:
/* 3EE70 8004E670 1000BF8F */  lw         $ra, 0x10($sp)
/* 3EE74 8004E674 00000000 */  nop
/* 3EE78 8004E678 0800E003 */  jr         $ra
/* 3EE7C 8004E67C 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004E608, . - func_8004E608

glabel func_8004E680
/* 3EE80 8004E680 D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 3EE84 8004E684 1800B2AF */  sw         $s2, 0x18($sp)
/* 3EE88 8004E688 0580123C */  lui        $s2, %hi(func_8004E814)
/* 3EE8C 8004E68C 1400B1AF */  sw         $s1, 0x14($sp)
/* 3EE90 8004E690 FFFF1124 */  addiu      $s1, $zero, -0x1
/* 3EE94 8004E694 1000B0AF */  sw         $s0, 0x10($sp)
/* 3EE98 8004E698 0880103C */  lui        $s0, %hi(D_80078D10)
/* 3EE9C 8004E69C 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 3EEA0 8004E6A0 21980002 */  addu       $s3, $s0, $zero
/* 3EEA4 8004E6A4 2000B4AF */  sw         $s4, 0x20($sp)
/* 3EEA8 8004E6A8 0780143C */  lui        $s4, %hi(D_8006A220)
/* 3EEAC 8004E6AC 2400BFAF */  sw         $ra, 0x24($sp)
.L8004E6B0:
/* 3EEB0 8004E6B0 00F2043C */  lui        $a0, (0xF2000002 >> 16)
/* 3EEB4 8004E6B4 02008434 */  ori        $a0, $a0, (0xF2000002 & 0xFFFF)
/* 3EEB8 8004E6B8 02000524 */  addiu      $a1, $zero, 0x2
/* 3EEBC 8004E6BC 00100624 */  addiu      $a2, $zero, 0x1000
/* 3EEC0 8004E6C0 3710010C */  jal        OpenEvent
/* 3EEC4 8004E6C4 14E84726 */   addiu     $a3, $s2, %lo(func_8004E814)
/* 3EEC8 8004E6C8 F9FF5110 */  beq        $v0, $s1, .L8004E6B0
/* 3EECC 8004E6CC 108D02AE */   sw        $v0, %lo(D_80078D10)($s0)
.L8004E6D0:
/* 3EED0 8004E6D0 108D648E */  lw         $a0, %lo(D_80078D10)($s3)
/* 3EED4 8004E6D4 3B10010C */  jal        EnableEvent
/* 3EED8 8004E6D8 00000000 */   nop
/* 3EEDC 8004E6DC FCFF4010 */  beqz       $v0, .L8004E6D0
/* 3EEE0 8004E6E0 00000000 */   nop
.L8004E6E4:
/* 3EEE4 8004E6E4 20A28486 */  lh         $a0, %lo(D_8006A220)($s4)
/* 3EEE8 8004E6E8 00000000 */  nop
/* 3EEEC 8004E6EC 02008228 */  slti       $v0, $a0, 0x2
/* 3EEF0 8004E6F0 08004010 */  beqz       $v0, .L8004E714
/* 3EEF4 8004E6F4 80100400 */   sll       $v0, $a0, 2
/* 3EEF8 8004E6F8 21104400 */  addu       $v0, $v0, $a0
/* 3EEFC 8004E6FC 00190200 */  sll        $v1, $v0, 4
/* 3EF00 8004E700 21104300 */  addu       $v0, $v0, $v1
/* 3EF04 8004E704 80100200 */  sll        $v0, $v0, 2
/* 3EF08 8004E708 23104400 */  subu       $v0, $v0, $a0
/* 3EF0C 8004E70C CC390108 */  j          .L8004E730
/* 3EF10 8004E710 C0100200 */   sll       $v0, $v0, 3
.L8004E714:
/* 3EF14 8004E714 40100400 */  sll        $v0, $a0, 1
/* 3EF18 8004E718 21104400 */  addu       $v0, $v0, $a0
/* 3EF1C 8004E71C 80100200 */  sll        $v0, $v0, 2
/* 3EF20 8004E720 23104400 */  subu       $v0, $v0, $a0
/* 3EF24 8004E724 C0100200 */  sll        $v0, $v0, 3
/* 3EF28 8004E728 23104400 */  subu       $v0, $v0, $a0
/* 3EF2C 8004E72C 40110200 */  sll        $v0, $v0, 5
.L8004E730:
/* 3EF30 8004E730 FFFF4530 */  andi       $a1, $v0, 0xFFFF
/* 3EF34 8004E734 00F2043C */  lui        $a0, (0xF2000002 >> 16)
/* 3EF38 8004E738 02008434 */  ori        $a0, $a0, (0xF2000002 & 0xFFFF)
/* 3EF3C 8004E73C C166000C */  jal        SetRCnt
/* 3EF40 8004E740 00100624 */   addiu     $a2, $zero, 0x1000
/* 3EF44 8004E744 E7FF4010 */  beqz       $v0, .L8004E6E4
/* 3EF48 8004E748 00000000 */   nop
.L8004E74C:
/* 3EF4C 8004E74C 00F2043C */  lui        $a0, (0xF2000002 >> 16)
/* 3EF50 8004E750 F666000C */  jal        StartRCnt
/* 3EF54 8004E754 02008434 */   ori       $a0, $a0, (0xF2000002 & 0xFFFF)
/* 3EF58 8004E758 FCFF4010 */  beqz       $v0, .L8004E74C
/* 3EF5C 8004E75C 00000000 */   nop
/* 3EF60 8004E760 2400BF8F */  lw         $ra, 0x24($sp)
/* 3EF64 8004E764 2000B48F */  lw         $s4, 0x20($sp)
/* 3EF68 8004E768 1C00B38F */  lw         $s3, 0x1C($sp)
/* 3EF6C 8004E76C 1800B28F */  lw         $s2, 0x18($sp)
/* 3EF70 8004E770 1400B18F */  lw         $s1, 0x14($sp)
/* 3EF74 8004E774 1000B08F */  lw         $s0, 0x10($sp)
/* 3EF78 8004E778 0800E003 */  jr         $ra
/* 3EF7C 8004E77C 2800BD27 */   addiu     $sp, $sp, 0x28
.size func_8004E680, . - func_8004E680

glabel func_8004E780
/* 3EF80 8004E780 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3EF84 8004E784 1000B0AF */  sw         $s0, 0x10($sp)
/* 3EF88 8004E788 0880103C */  lui        $s0, %hi(D_80078D10)
/* 3EF8C 8004E78C 1400BFAF */  sw         $ra, 0x14($sp)
/* 3EF90 8004E790 00F2043C */  lui        $a0, (0xF2000002 >> 16)
.L8004E794:
/* 3EF94 8004E794 0267000C */  jal        StopRCnt
/* 3EF98 8004E798 02008434 */   ori       $a0, $a0, (0xF2000002 & 0xFFFF)
/* 3EF9C 8004E79C FDFF4010 */  beqz       $v0, .L8004E794
/* 3EFA0 8004E7A0 00F2043C */   lui       $a0, (0xF2000002 >> 16)
.L8004E7A4:
/* 3EFA4 8004E7A4 108D048E */  lw         $a0, %lo(D_80078D10)($s0)
/* 3EFA8 8004E7A8 CB0F010C */  jal        CloseEvent
/* 3EFAC 8004E7AC 00000000 */   nop
/* 3EFB0 8004E7B0 FCFF4010 */  beqz       $v0, .L8004E7A4
/* 3EFB4 8004E7B4 00000000 */   nop
/* 3EFB8 8004E7B8 1400BF8F */  lw         $ra, 0x14($sp)
/* 3EFBC 8004E7BC 1000B08F */  lw         $s0, 0x10($sp)
/* 3EFC0 8004E7C0 0800E003 */  jr         $ra
/* 3EFC4 8004E7C4 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004E780, . - func_8004E780

glabel func_8004E7C8
/* 3EFC8 8004E7C8 1F000224 */  addiu      $v0, $zero, 0x1F
/* 3EFCC 8004E7CC 000080A4 */  sh         $zero, 0x0($a0)
/* 3EFD0 8004E7D0 020080A4 */  sh         $zero, 0x2($a0)
/* 3EFD4 8004E7D4 FFFF4224 */  addiu      $v0, $v0, -0x1
.L8004E7D8:
/* 3EFD8 8004E7D8 FFFF4104 */  bgez       $v0, .L8004E7D8
/* 3EFDC 8004E7DC FFFF4224 */   addiu     $v0, $v0, -0x1
/* 3EFE0 8004E7E0 0800E003 */  jr         $ra
/* 3EFE4 8004E7E4 00000000 */   nop
.size func_8004E7C8, . - func_8004E7C8

glabel func_8004E7E8
/* 3EFE8 8004E7E8 02008384 */  lh         $v1, 0x2($a0)
/* 3EFEC 8004E7EC FF00A530 */  andi       $a1, $a1, 0xFF
/* 3EFF0 8004E7F0 40180300 */  sll        $v1, $v1, 1
/* 3EFF4 8004E7F4 21188300 */  addu       $v1, $a0, $v1
/* 3EFF8 8004E7F8 040065A4 */  sh         $a1, 0x4($v1)
/* 3EFFC 8004E7FC 02008294 */  lhu        $v0, 0x2($a0)
/* 3F000 8004E800 00000000 */  nop
/* 3F004 8004E804 01004224 */  addiu      $v0, $v0, 0x1
/* 3F008 8004E808 1F004230 */  andi       $v0, $v0, 0x1F
/* 3F00C 8004E80C 0800E003 */  jr         $ra
/* 3F010 8004E810 020082A4 */   sh        $v0, 0x2($a0)
.size func_8004E7E8, . - func_8004E7E8

glabel func_8004E814
/* 3F014 8004E814 0880033C */  lui        $v1, %hi(D_80078D14)
/* 3F018 8004E818 148D6294 */  lhu        $v0, %lo(D_80078D14)($v1)
/* 3F01C 8004E81C 00000000 */  nop
/* 3F020 8004E820 01014224 */  addiu      $v0, $v0, 0x101
/* 3F024 8004E824 0800E003 */  jr         $ra
/* 3F028 8004E828 148D62A4 */   sh        $v0, %lo(D_80078D14)($v1)
.size func_8004E814, . - func_8004E814

glabel func_8004E82C
/* 3F02C 8004E82C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3F030 8004E830 03008014 */  bnez       $a0, .L8004E840
/* 3F034 8004E834 1000BFAF */   sw        $ra, 0x10($sp)
/* 3F038 8004E838 0880023C */  lui        $v0, %hi(D_80078D20)
/* 3F03C 8004E83C 208D4424 */  addiu      $a0, $v0, %lo(D_80078D20)
.L8004E840:
/* 3F040 8004E840 0880023C */  lui        $v0, %hi(D_80078D15)
/* 3F044 8004E844 158D4590 */  lbu        $a1, %lo(D_80078D15)($v0)
/* 3F048 8004E848 FA39010C */  jal        func_8004E7E8
/* 3F04C 8004E84C 00000000 */   nop
/* 3F050 8004E850 1000BF8F */  lw         $ra, 0x10($sp)
/* 3F054 8004E854 00000000 */  nop
/* 3F058 8004E858 0800E003 */  jr         $ra
/* 3F05C 8004E85C 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004E82C, . - func_8004E82C

glabel func_8004E860
/* 3F060 8004E860 0880023C */  lui        $v0, %hi(D_80078D15)
/* 3F064 8004E864 0800E003 */  jr         $ra
/* 3F068 8004E868 158D40A0 */   sb        $zero, %lo(D_80078D15)($v0)
.size func_8004E860, . - func_8004E860

glabel func_8004E86C
/* 3F06C 8004E86C 0880023C */  lui        $v0, %hi(D_80078D14)
/* 3F070 8004E870 0800E003 */  jr         $ra
/* 3F074 8004E874 148D40A0 */   sb        $zero, %lo(D_80078D14)($v0)
.size func_8004E86C, . - func_8004E86C

glabel func_8004E878
/* 3F078 8004E878 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3F07C 8004E87C 0880043C */  lui        $a0, %hi(D_80078D64)
/* 3F080 8004E880 0880023C */  lui        $v0, %hi(D_80078D14)
/* 3F084 8004E884 148D4590 */  lbu        $a1, %lo(D_80078D14)($v0)
/* 3F088 8004E888 1000BFAF */  sw         $ra, 0x10($sp)
/* 3F08C 8004E88C FA39010C */  jal        func_8004E7E8
/* 3F090 8004E890 648D8424 */   addiu     $a0, $a0, %lo(D_80078D64)
/* 3F094 8004E894 1000BF8F */  lw         $ra, 0x10($sp)
/* 3F098 8004E898 00000000 */  nop
/* 3F09C 8004E89C 0800E003 */  jr         $ra
/* 3F0A0 8004E8A0 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004E878, . - func_8004E878

glabel func_8004E8A4
/* 3F0A4 8004E8A4 21280000 */  addu       $a1, $zero, $zero
/* 3F0A8 8004E8A8 04008424 */  addiu      $a0, $a0, 0x4
/* 3F0AC 8004E8AC 1F000324 */  addiu      $v1, $zero, 0x1F
.L8004E8B0:
/* 3F0B0 8004E8B0 00008284 */  lh         $v0, 0x0($a0)
/* 3F0B4 8004E8B4 02008424 */  addiu      $a0, $a0, 0x2
/* 3F0B8 8004E8B8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 3F0BC 8004E8BC FCFF6104 */  bgez       $v1, .L8004E8B0
/* 3F0C0 8004E8C0 2128A200 */   addu      $a1, $a1, $v0
/* 3F0C4 8004E8C4 80100500 */  sll        $v0, $a1, 2
/* 3F0C8 8004E8C8 0800E003 */  jr         $ra
/* 3F0CC 8004E8CC 43110200 */   sra       $v0, $v0, 5
.size func_8004E8A4, . - func_8004E8A4

glabel func_8004E8D0
/* 3F0D0 8004E8D0 0780023C */  lui        $v0, %hi(D_8006A21C)
/* 3F0D4 8004E8D4 1CA2438C */  lw         $v1, %lo(D_8006A21C)($v0)
/* 3F0D8 8004E8D8 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3F0DC 8004E8DC 1800BFAF */  sw         $ra, 0x18($sp)
/* 3F0E0 8004E8E0 1400B1AF */  sw         $s1, 0x14($sp)
/* 3F0E4 8004E8E4 0F006010 */  beqz       $v1, .L8004E924
/* 3F0E8 8004E8E8 1000B0AF */   sw        $s0, 0x10($sp)
/* 3F0EC 8004E8EC 0880103C */  lui        $s0, %hi(D_80078D20)
/* 3F0F0 8004E8F0 208D1026 */  addiu      $s0, $s0, %lo(D_80078D20)
/* 3F0F4 8004E8F4 293A010C */  jal        func_8004E8A4
/* 3F0F8 8004E8F8 21200002 */   addu      $a0, $s0, $zero
/* 3F0FC 8004E8FC 44000426 */  addiu      $a0, $s0, 0x44
/* 3F100 8004E900 293A010C */  jal        func_8004E8A4
/* 3F104 8004E904 21884000 */   addu      $s1, $v0, $zero
/* 3F108 8004E908 0180043C */  lui        $a0, %hi(D_80012650)
/* 3F10C 8004E90C 50268424 */  addiu      $a0, $a0, %lo(D_80012650)
/* 3F110 8004E910 0780033C */  lui        $v1, %hi(D_8006DC84)
/* 3F114 8004E914 84DC678C */  lw         $a3, %lo(D_8006DC84)($v1)
/* 3F118 8004E918 21282002 */  addu       $a1, $s1, $zero
/* 3F11C 8004E91C 09F8E000 */  jalr       $a3
/* 3F120 8004E920 21304000 */   addu      $a2, $v0, $zero
.L8004E924:
/* 3F124 8004E924 1800BF8F */  lw         $ra, 0x18($sp)
/* 3F128 8004E928 1400B18F */  lw         $s1, 0x14($sp)
/* 3F12C 8004E92C 1000B08F */  lw         $s0, 0x10($sp)
/* 3F130 8004E930 0800E003 */  jr         $ra
/* 3F134 8004E934 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004E8D0, . - func_8004E8D0

glabel func_8004E938
/* 3F138 8004E938 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3F13C 8004E93C 1000BFAF */  sw         $ra, 0x10($sp)
/* 3F140 8004E940 0880023C */  lui        $v0, %hi(D_80078D20)
/* 3F144 8004E944 02008014 */  bnez       $a0, .L8004E950
/* 3F148 8004E948 208D4224 */   addiu     $v0, $v0, %lo(D_80078D20)
/* 3F14C 8004E94C 44004224 */  addiu      $v0, $v0, 0x44
.L8004E950:
/* 3F150 8004E950 293A010C */  jal        func_8004E8A4
/* 3F154 8004E954 21204000 */   addu      $a0, $v0, $zero
/* 3F158 8004E958 1000BF8F */  lw         $ra, 0x10($sp)
/* 3F15C 8004E95C 00000000 */  nop
/* 3F160 8004E960 0800E003 */  jr         $ra
/* 3F164 8004E964 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004E938, . - func_8004E938

glabel func_8004E968
/* 3F168 8004E968 01000224 */  addiu      $v0, $zero, 0x1
/* 3F16C 8004E96C A80082AF */  sw         $v0, (0xA8 & 0xFFFF)($gp)
/* 3F170 8004E970 0800E003 */  jr         $ra
/* 3F174 8004E974 00000000 */   nop
.size func_8004E968, . - func_8004E968

glabel func_8004E978
/* 3F178 8004E978 A80080AF */  sw         $zero, (0xA8 & 0xFFFF)($gp)
/* 3F17C 8004E97C 0800E003 */  jr         $ra
/* 3F180 8004E980 00000000 */   nop
.size func_8004E978, . - func_8004E978

glabel func_8004E984
/* 3F184 8004E984 A800828F */  lw         $v0, (0xA8 & 0xFFFF)($gp)
/* 3F188 8004E988 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 3F18C 8004E98C 1800BFAF */  sw         $ra, 0x18($sp)
/* 3F190 8004E990 1400B1AF */  sw         $s1, 0x14($sp)
/* 3F194 8004E994 16004010 */  beqz       $v0, .L8004E9F0
/* 3F198 8004E998 1000B0AF */   sw        $s0, 0x10($sp)
/* 3F19C 8004E99C 0780023C */  lui        $v0, %hi(D_8006A224)
/* 3F1A0 8004E9A0 24A25024 */  addiu      $s0, $v0, %lo(D_8006A224)
/* 3F1A4 8004E9A4 03001124 */  addiu      $s1, $zero, 0x3
.L8004E9A8:
/* 3F1A8 8004E9A8 0000028E */  lw         $v0, 0x0($s0)
/* 3F1AC 8004E9AC 00000000 */  nop
/* 3F1B0 8004E9B0 04004010 */  beqz       $v0, .L8004E9C4
/* 3F1B4 8004E9B4 00000000 */   nop
/* 3F1B8 8004E9B8 09F84000 */  jalr       $v0
/* 3F1BC 8004E9BC 00000000 */   nop
/* 3F1C0 8004E9C0 000000AE */  sw         $zero, 0x0($s0)
.L8004E9C4:
/* 3F1C4 8004E9C4 FFFF3126 */  addiu      $s1, $s1, -0x1
/* 3F1C8 8004E9C8 F7FF2106 */  bgez       $s1, .L8004E9A8
/* 3F1CC 8004E9CC 04001026 */   addiu     $s0, $s0, 0x4
/* 3F1D0 8004E9D0 AD68000C */  jal        func_8001A2B4
/* 3F1D4 8004E9D4 00000000 */   nop
/* 3F1D8 8004E9D8 9B61000C */  jal        EnterCriticalSection
/* 3F1DC 8004E9DC 00000000 */   nop
/* 3F1E0 8004E9E0 0880043C */  lui        $a0, %hi(D_80078DA8)
/* 3F1E4 8004E9E4 A88D8424 */  addiu      $a0, $a0, %lo(D_80078DA8)
/* 3F1E8 8004E9E8 A93A010C */  jal        longjmp
/* 3F1EC 8004E9EC FFFF0524 */   addiu     $a1, $zero, -0x1
.L8004E9F0:
/* 3F1F0 8004E9F0 1800BF8F */  lw         $ra, 0x18($sp)
/* 3F1F4 8004E9F4 1400B18F */  lw         $s1, 0x14($sp)
/* 3F1F8 8004E9F8 1000B08F */  lw         $s0, 0x10($sp)
/* 3F1FC 8004E9FC 0800E003 */  jr         $ra
/* 3F200 8004EA00 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8004E984, . - func_8004E984

glabel func_8004EA04
/* 3F204 8004EA04 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 3F208 8004EA08 1000BFAF */  sw         $ra, 0x10($sp)
/* 3F20C 8004EA0C 21280000 */  addu       $a1, $zero, $zero
/* 3F210 8004EA10 0780023C */  lui        $v0, %hi(D_8006A224)
/* 3F214 8004EA14 24A24324 */  addiu      $v1, $v0, %lo(D_8006A224)
.L8004EA18:
/* 3F218 8004EA18 0000628C */  lw         $v0, 0x0($v1)
/* 3F21C 8004EA1C 00000000 */  nop
/* 3F220 8004EA20 03004014 */  bnez       $v0, .L8004EA30
/* 3F224 8004EA24 0100A524 */   addiu     $a1, $a1, 0x1
/* 3F228 8004EA28 973A0108 */  j          .L8004EA5C
/* 3F22C 8004EA2C 000064AC */   sw        $a0, 0x0($v1)
.L8004EA30:
/* 3F230 8004EA30 0400A228 */  slti       $v0, $a1, 0x4
/* 3F234 8004EA34 F8FF4014 */  bnez       $v0, .L8004EA18
/* 3F238 8004EA38 04006324 */   addiu     $v1, $v1, 0x4
/* 3F23C 8004EA3C 0180043C */  lui        $a0, %hi(D_80012660)
/* 3F240 8004EA40 0180053C */  lui        $a1, %hi(D_800126A4)
/* 3F244 8004EA44 60268424 */  addiu      $a0, $a0, %lo(D_80012660)
/* 3F248 8004EA48 A426A524 */  addiu      $a1, $a1, %lo(D_800126A4)
/* 3F24C 8004EA4C 9361000C */  jal        printf
/* 3F250 8004EA50 3A000624 */   addiu     $a2, $zero, 0x3A
/* 3F254 8004EA54 FFFF0324 */  addiu      $v1, $zero, -0x1
/* 3F258 8004EA58 010003AC */  sw         $v1, 0x1($zero)
.L8004EA5C:
/* 3F25C 8004EA5C 1000BF8F */  lw         $ra, 0x10($sp)
/* 3F260 8004EA60 00000000 */  nop
/* 3F264 8004EA64 0800E003 */  jr         $ra
/* 3F268 8004EA68 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8004EA04, . - func_8004EA04

glabel func_8004EA6C
/* 3F26C 8004EA6C 21280000 */  addu       $a1, $zero, $zero
/* 3F270 8004EA70 0780023C */  lui        $v0, %hi(D_8006A224)
/* 3F274 8004EA74 24A24324 */  addiu      $v1, $v0, %lo(D_8006A224)
.L8004EA78:
/* 3F278 8004EA78 0000628C */  lw         $v0, 0x0($v1)
/* 3F27C 8004EA7C 00000000 */  nop
/* 3F280 8004EA80 03004414 */  bne        $v0, $a0, .L8004EA90
/* 3F284 8004EA84 0100A524 */   addiu     $a1, $a1, 0x1
/* 3F288 8004EA88 0800E003 */  jr         $ra
/* 3F28C 8004EA8C 000060AC */   sw        $zero, 0x0($v1)
.L8004EA90:
/* 3F290 8004EA90 0400A228 */  slti       $v0, $a1, 0x4
/* 3F294 8004EA94 F8FF4014 */  bnez       $v0, .L8004EA78
/* 3F298 8004EA98 04006324 */   addiu     $v1, $v1, 0x4
/* 3F29C 8004EA9C 0800E003 */  jr         $ra
/* 3F2A0 8004EAA0 00000000 */   nop
.size func_8004EA6C, . - func_8004EA6C
