.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel func_8001DC04
/* E404 8001DC04 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* E408 8001DC08 03000224 */  addiu      $v0, $zero, 0x3
/* E40C 8001DC0C 02000324 */  addiu      $v1, $zero, 0x2
/* E410 8001DC10 0180053C */  lui        $a1, %hi(D_800111C0)
/* E414 8001DC14 C011A524 */  addiu      $a1, $a1, %lo(D_800111C0)
/* E418 8001DC18 2130A000 */  addu       $a2, $a1, $zero
/* E41C 8001DC1C 00100724 */  addiu      $a3, $zero, 0x1000
/* E420 8001DC20 1000BFAF */  sw         $ra, 0x10($sp)
/* E424 8001DC24 060080A4 */  sh         $zero, 0x6($a0)
/* E428 8001DC28 000082A4 */  sh         $v0, 0x0($a0)
/* E42C 8001DC2C F577000C */  jal        func_8001DFD4
/* E430 8001DC30 040083A4 */   sh        $v1, 0x4($a0)
/* E434 8001DC34 1000BF8F */  lw         $ra, 0x10($sp)
/* E438 8001DC38 00000000 */  nop
/* E43C 8001DC3C 0800E003 */  jr         $ra
/* E440 8001DC40 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001DC04, . - func_8001DC04

glabel func_8001DC44
/* E444 8001DC44 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* E448 8001DC48 1800B0AF */  sw         $s0, 0x18($sp)
/* E44C 8001DC4C 21808000 */  addu       $s0, $a0, $zero
/* E450 8001DC50 002C0500 */  sll        $a1, $a1, 16
/* E454 8001DC54 032C0500 */  sra        $a1, $a1, 16
/* E458 8001DC58 00340600 */  sll        $a2, $a2, 16
/* E45C 8001DC5C 03340600 */  sra        $a2, $a2, 16
/* E460 8001DC60 1C00BFAF */  sw         $ra, 0x1C($sp)
/* E464 8001DC64 4177000C */  jal        func_8001DD04
/* E468 8001DC68 21380000 */   addu      $a3, $zero, $zero
/* E46C 8001DC6C FFFF0224 */  addiu      $v0, $zero, -0x1
/* E470 8001DC70 21200002 */  addu       $a0, $s0, $zero
/* E474 8001DC74 00100524 */  addiu      $a1, $zero, 0x1000
/* E478 8001DC78 00100624 */  addiu      $a2, $zero, 0x1000
/* E47C 8001DC7C FFFF0724 */  addiu      $a3, $zero, -0x1
/* E480 8001DC80 2677000C */  jal        func_8001DC98
/* E484 8001DC84 1000A2AF */   sw        $v0, 0x10($sp)
/* E488 8001DC88 1C00BF8F */  lw         $ra, 0x1C($sp)
/* E48C 8001DC8C 1800B08F */  lw         $s0, 0x18($sp)
/* E490 8001DC90 0800E003 */  jr         $ra
/* E494 8001DC94 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8001DC44, . - func_8001DC44

glabel func_8001DC98
/* E498 8001DC98 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* E49C 8001DC9C 003C0700 */  sll        $a3, $a3, 16
/* E4A0 8001DCA0 033C0700 */  sra        $a3, $a3, 16
/* E4A4 8001DCA4 002C0500 */  sll        $a1, $a1, 16
/* E4A8 8001DCA8 032C0500 */  sra        $a1, $a1, 16
/* E4AC 8001DCAC 00340600 */  sll        $a2, $a2, 16
/* E4B0 8001DCB0 2800A287 */  lh         $v0, 0x28($sp)
/* E4B4 8001DCB4 03340600 */  sra        $a2, $a2, 16
/* E4B8 8001DCB8 1000BFAF */  sw         $ra, 0x10($sp)
/* E4BC 8001DCBC 100085A4 */  sh         $a1, 0x10($a0)
/* E4C0 8001DCC0 0600E104 */  bgez       $a3, .L8001DCDC
/* E4C4 8001DCC4 120086A4 */   sh        $a2, 0x12($a0)
/* E4C8 8001DCC8 07004104 */  bgez       $v0, .L8001DCE8
/* E4CC 8001DCCC 21384000 */   addu      $a3, $v0, $zero
/* E4D0 8001DCD0 2138A000 */  addu       $a3, $a1, $zero
/* E4D4 8001DCD4 3A770008 */  j          .L8001DCE8
/* E4D8 8001DCD8 2110C000 */   addu      $v0, $a2, $zero
.L8001DCDC:
/* E4DC 8001DCDC 02004104 */  bgez       $v0, .L8001DCE8
/* E4E0 8001DCE0 00000000 */   nop
/* E4E4 8001DCE4 2110E000 */  addu       $v0, $a3, $zero
.L8001DCE8:
/* E4E8 8001DCE8 140087A4 */  sh         $a3, 0x14($a0)
/* E4EC 8001DCEC 6877000C */  jal        func_8001DDA0
/* E4F0 8001DCF0 160082A4 */   sh        $v0, 0x16($a0)
/* E4F4 8001DCF4 1000BF8F */  lw         $ra, 0x10($sp)
/* E4F8 8001DCF8 00000000 */  nop
/* E4FC 8001DCFC 0800E003 */  jr         $ra
/* E500 8001DD00 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001DC98, . - func_8001DC98

glabel func_8001DD04
/* E504 8001DD04 D8FFBD27 */  addiu      $sp, $sp, -0x28
/* E508 8001DD08 002C0500 */  sll        $a1, $a1, 16
/* E50C 8001DD0C 1000B0AF */  sw         $s0, 0x10($sp)
/* E510 8001DD10 03840500 */  sra        $s0, $a1, 16
/* E514 8001DD14 1400B1AF */  sw         $s1, 0x14($sp)
/* E518 8001DD18 21888000 */  addu       $s1, $a0, $zero
/* E51C 8001DD1C 00340600 */  sll        $a2, $a2, 16
/* E520 8001DD20 1C00B3AF */  sw         $s3, 0x1C($sp)
/* E524 8001DD24 039C0600 */  sra        $s3, $a2, 16
/* E528 8001DD28 003C0700 */  sll        $a3, $a3, 16
/* E52C 8001DD2C 1800B2AF */  sw         $s2, 0x18($sp)
/* E530 8001DD30 03940700 */  sra        $s2, $a3, 16
/* E534 8001DD34 FFFF4232 */  andi       $v0, $s2, 0xFFFF
/* E538 8001DD38 0200422C */  sltiu      $v0, $v0, 0x2
/* E53C 8001DD3C 09004014 */  bnez       $v0, .L8001DD64
/* E540 8001DD40 2000BFAF */   sw        $ra, 0x20($sp)
/* E544 8001DD44 0180043C */  lui        $a0, %hi(D_8001117C)
/* E548 8001DD48 7C118424 */  addiu      $a0, $a0, %lo(D_8001117C)
/* E54C 8001DD4C 0180053C */  lui        $a1, %hi(D_800111D0)
/* E550 8001DD50 D011A524 */  addiu      $a1, $a1, %lo(D_800111D0)
/* E554 8001DD54 9361000C */  jal        printf
/* E558 8001DD58 5C000624 */   addiu     $a2, $zero, 0x5C
/* E55C 8001DD5C FFFF0324 */  addiu      $v1, $zero, -0x1
/* E560 8001DD60 010003AC */  sw         $v1, 0x1($zero)
.L8001DD64:
/* E564 8001DD64 80010224 */  addiu      $v0, $zero, 0x180
/* E568 8001DD68 02000216 */  bne        $s0, $v0, .L8001DD74
/* E56C 8001DD6C 21202002 */   addu      $a0, $s1, $zero
/* E570 8001DD70 70011024 */  addiu      $s0, $zero, 0x170
.L8001DD74:
/* E574 8001DD74 060032A6 */  sh         $s2, 0x6($s1)
/* E578 8001DD78 080030A6 */  sh         $s0, 0x8($s1)
/* E57C 8001DD7C 6877000C */  jal        func_8001DDA0
/* E580 8001DD80 0A0033A6 */   sh        $s3, 0xA($s1)
/* E584 8001DD84 2000BF8F */  lw         $ra, 0x20($sp)
/* E588 8001DD88 1C00B38F */  lw         $s3, 0x1C($sp)
/* E58C 8001DD8C 1800B28F */  lw         $s2, 0x18($sp)
/* E590 8001DD90 1400B18F */  lw         $s1, 0x14($sp)
/* E594 8001DD94 1000B08F */  lw         $s0, 0x10($sp)
/* E598 8001DD98 0800E003 */  jr         $ra
/* E59C 8001DD9C 2800BD27 */   addiu     $sp, $sp, 0x28
.size func_8001DD04, . - func_8001DD04

glabel func_8001DDA0
/* E5A0 8001DDA0 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* E5A4 8001DDA4 1000B0AF */  sw         $s0, 0x10($sp)
/* E5A8 8001DDA8 21808000 */  addu       $s0, $a0, $zero
/* E5AC 8001DDAC 70010224 */  addiu      $v0, $zero, 0x170
/* E5B0 8001DDB0 1400BFAF */  sw         $ra, 0x14($sp)
/* E5B4 8001DDB4 08000486 */  lh         $a0, 0x8($s0)
/* E5B8 8001DDB8 10000386 */  lh         $v1, 0x10($s0)
/* E5BC 8001DDBC 04008210 */  beq        $a0, $v0, .L8001DDD0
/* E5C0 8001DDC0 18008300 */   mult      $a0, $v1
/* E5C4 8001DDC4 12100000 */  mflo       $v0
/* E5C8 8001DDC8 77770008 */  j          .L8001DDDC
/* E5CC 8001DDCC 02430200 */   srl       $t0, $v0, 12
.L8001DDD0:
/* E5D0 8001DDD0 40100300 */  sll        $v0, $v1, 1
/* E5D4 8001DDD4 21104300 */  addu       $v0, $v0, $v1
/* E5D8 8001DDD8 42410200 */  srl        $t0, $v0, 5
.L8001DDDC:
/* E5DC 8001DDDC 0A000486 */  lh         $a0, 0xA($s0)
/* E5E0 8001DDE0 12000586 */  lh         $a1, 0x12($s0)
/* E5E4 8001DDE4 00000000 */  nop
/* E5E8 8001DDE8 18008500 */  mult       $a0, $a1
/* E5EC 8001DDEC 08000786 */  lh         $a3, 0x8($s0)
/* E5F0 8001DDF0 12280000 */  mflo       $a1
/* E5F4 8001DDF4 14000286 */  lh         $v0, 0x14($s0)
/* E5F8 8001DDF8 00000000 */  nop
/* E5FC 8001DDFC 1800E200 */  mult       $a3, $v0
/* E600 8001DE00 06000686 */  lh         $a2, 0x6($s0)
/* E604 8001DE04 0C0008A6 */  sh         $t0, 0xC($s0)
/* E608 8001DE08 80300600 */  sll        $a2, $a2, 2
/* E60C 8001DE0C 032B0500 */  sra        $a1, $a1, 12
/* E610 8001DE10 18008227 */  addiu      $v0, $gp, %gp_rel(D_18)
/* E614 8001DE14 2110C200 */  addu       $v0, $a2, $v0
/* E618 8001DE18 0E0005A6 */  sh         $a1, 0xE($s0)
/* E61C 8001DE1C 12380000 */  mflo       $a3
/* E620 8001DE20 00004384 */  lh         $v1, 0x0($v0)
/* E624 8001DE24 00000000 */  nop
/* E628 8001DE28 1A00E300 */  div        $zero, $a3, $v1
/* E62C 8001DE2C 12380000 */  mflo       $a3
/* E630 8001DE30 02006014 */  bnez       $v1, .L8001DE3C
/* E634 8001DE34 00000000 */   nop
/* E638 8001DE38 CD010000 */  break      0, 7
.L8001DE3C:
/* E63C 8001DE3C 16000286 */  lh         $v0, 0x16($s0)
/* E640 8001DE40 00000000 */  nop
/* E644 8001DE44 18008200 */  mult       $a0, $v0
/* E648 8001DE48 1A008327 */  addiu      $v1, $gp, %gp_rel(D_1A)
/* E64C 8001DE4C 2130C300 */  addu       $a2, $a2, $v1
/* E650 8001DE50 180007A6 */  sh         $a3, 0x18($s0)
/* E654 8001DE54 12200000 */  mflo       $a0
/* E658 8001DE58 0000C284 */  lh         $v0, 0x0($a2)
/* E65C 8001DE5C 00000000 */  nop
/* E660 8001DE60 1A008200 */  div        $zero, $a0, $v0
/* E664 8001DE64 12200000 */  mflo       $a0
/* E668 8001DE68 02004014 */  bnez       $v0, .L8001DE74
/* E66C 8001DE6C 00000000 */   nop
/* E670 8001DE70 CD010000 */  break      0, 7
.L8001DE74:
/* E674 8001DE74 00100224 */  addiu      $v0, $zero, 0x1000
/* E678 8001DE78 1A0004A6 */  sh         $a0, 0x1A($s0)
/* E67C 8001DE7C 00240800 */  sll        $a0, $t0, 16
/* E680 8001DE80 002C0500 */  sll        $a1, $a1, 16
/* E684 8001DE84 43240400 */  sra        $a0, $a0, 17
/* E688 8001DE88 432C0500 */  sra        $a1, $a1, 17
/* E68C 8001DE8C F27A000C */  jal        func_8001EBC8
/* E690 8001DE90 1C0002A6 */   sh        $v0, 0x1C($s0)
/* E694 8001DE94 00000296 */  lhu        $v0, 0x0($s0)
/* E698 8001DE98 1400BF8F */  lw         $ra, 0x14($sp)
/* E69C 8001DE9C 02004234 */  ori        $v0, $v0, 0x2
/* E6A0 8001DEA0 000002A6 */  sh         $v0, 0x0($s0)
/* E6A4 8001DEA4 1000B08F */  lw         $s0, 0x10($sp)
/* E6A8 8001DEA8 0800E003 */  jr         $ra
/* E6AC 8001DEAC 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001DDA0, . - func_8001DDA0

glabel func_8001DEB0
/* E6B0 8001DEB0 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* E6B4 8001DEB4 21508000 */  addu       $t2, $a0, $zero
/* E6B8 8001DEB8 1000BFAF */  sw         $ra, 0x10($sp)
/* E6BC 8001DEBC 00004295 */  lhu        $v0, 0x0($t2)
/* E6C0 8001DEC0 2158A000 */  addu       $t3, $a1, $zero
/* E6C4 8001DEC4 020040A5 */  sh         $zero, 0x2($t2)
/* E6C8 8001DEC8 F8FF4430 */  andi       $a0, $v0, 0xFFF8
/* E6CC 8001DECC 1E00C010 */  beqz       $a2, .L8001DF48
/* E6D0 8001DED0 000044A5 */   sh        $a0, 0x0($t2)
/* E6D4 8001DED4 0000628D */  lw         $v0, 0x0($t3)
/* E6D8 8001DED8 00000000 */  nop
/* E6DC 8001DEDC 580042AD */  sw         $v0, 0x58($t2)
/* E6E0 8001DEE0 0400638D */  lw         $v1, 0x4($t3)
/* E6E4 8001DEE4 00000000 */  nop
/* E6E8 8001DEE8 5C0043AD */  sw         $v1, 0x5C($t2)
/* E6EC 8001DEEC 0800628D */  lw         $v0, 0x8($t3)
/* E6F0 8001DEF0 00000000 */  nop
/* E6F4 8001DEF4 600042AD */  sw         $v0, 0x60($t2)
/* E6F8 8001DEF8 0C00638D */  lw         $v1, 0xC($t3)
/* E6FC 8001DEFC 00000000 */  nop
/* E700 8001DF00 640043AD */  sw         $v1, 0x64($t2)
/* E704 8001DF04 1000628D */  lw         $v0, 0x10($t3)
/* E708 8001DF08 00000000 */  nop
/* E70C 8001DF0C 680042AD */  sw         $v0, 0x68($t2)
/* E710 8001DF10 1400638D */  lw         $v1, 0x14($t3)
/* E714 8001DF14 00000000 */  nop
/* E718 8001DF18 6C0043AD */  sw         $v1, 0x6C($t2)
/* E71C 8001DF1C 1800628D */  lw         $v0, 0x18($t3)
/* E720 8001DF20 00000000 */  nop
/* E724 8001DF24 700042AD */  sw         $v0, 0x70($t2)
/* E728 8001DF28 02008234 */  ori        $v0, $a0, 0x2
/* E72C 8001DF2C 1C00638D */  lw         $v1, 0x1C($t3)
/* E730 8001DF30 21204001 */  addu       $a0, $t2, $zero
/* E734 8001DF34 000042A5 */  sh         $v0, 0x0($t2)
/* E738 8001DF38 A578000C */  jal        func_8001E294
/* E73C 8001DF3C 740043AD */   sw        $v1, 0x74($t2)
/* E740 8001DF40 F1770008 */  j          .L8001DFC4
/* E744 8001DF44 00000000 */   nop
.L8001DF48:
/* E748 8001DF48 0000698D */  lw         $t1, 0x0($t3)
/* E74C 8001DF4C 00000000 */  nop
/* E750 8001DF50 780049AD */  sw         $t1, 0x78($t2)
/* E754 8001DF54 0400688D */  lw         $t0, 0x4($t3)
/* E758 8001DF58 00000000 */  nop
/* E75C 8001DF5C 7C0048AD */  sw         $t0, 0x7C($t2)
/* E760 8001DF60 0800678D */  lw         $a3, 0x8($t3)
/* E764 8001DF64 00000000 */  nop
/* E768 8001DF68 800047AD */  sw         $a3, 0x80($t2)
/* E76C 8001DF6C 0C00668D */  lw         $a2, 0xC($t3)
/* E770 8001DF70 00000000 */  nop
/* E774 8001DF74 840046AD */  sw         $a2, 0x84($t2)
/* E778 8001DF78 1000658D */  lw         $a1, 0x10($t3)
/* E77C 8001DF7C 00000000 */  nop
/* E780 8001DF80 880045AD */  sw         $a1, 0x88($t2)
/* E784 8001DF84 1400648D */  lw         $a0, 0x14($t3)
/* E788 8001DF88 00000000 */  nop
/* E78C 8001DF8C 8C0044AD */  sw         $a0, 0x8C($t2)
/* E790 8001DF90 1800628D */  lw         $v0, 0x18($t3)
/* E794 8001DF94 00000000 */  nop
/* E798 8001DF98 900042AD */  sw         $v0, 0x90($t2)
/* E79C 8001DF9C 1C00638D */  lw         $v1, 0x1C($t3)
/* E7A0 8001DFA0 580049AD */  sw         $t1, 0x58($t2)
/* E7A4 8001DFA4 5C0048AD */  sw         $t0, 0x5C($t2)
/* E7A8 8001DFA8 600047AD */  sw         $a3, 0x60($t2)
/* E7AC 8001DFAC 640046AD */  sw         $a2, 0x64($t2)
/* E7B0 8001DFB0 680045AD */  sw         $a1, 0x68($t2)
/* E7B4 8001DFB4 6C0044AD */  sw         $a0, 0x6C($t2)
/* E7B8 8001DFB8 700042AD */  sw         $v0, 0x70($t2)
/* E7BC 8001DFBC 940043AD */  sw         $v1, 0x94($t2)
/* E7C0 8001DFC0 740043AD */  sw         $v1, 0x74($t2)
.L8001DFC4:
/* E7C4 8001DFC4 1000BF8F */  lw         $ra, 0x10($sp)
/* E7C8 8001DFC8 00000000 */  nop
/* E7CC 8001DFCC 0800E003 */  jr         $ra
/* E7D0 8001DFD0 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001DEB0, . - func_8001DEB0

glabel func_8001DFD4
/* E7D4 8001DFD4 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* E7D8 8001DFD8 21408000 */  addu       $t0, $a0, $zero
/* E7DC 8001DFDC 1000BFAF */  sw         $ra, 0x10($sp)
/* E7E0 8001DFE0 00000395 */  lhu        $v1, 0x0($t0)
/* E7E4 8001DFE4 01000224 */  addiu      $v0, $zero, 0x1
/* E7E8 8001DFE8 020002A5 */  sh         $v0, 0x2($t0)
/* E7EC 8001DFEC 03006934 */  ori        $t1, $v1, 0x3
/* E7F0 8001DFF0 000009A5 */  sh         $t1, 0x0($t0)
/* E7F4 8001DFF4 0000A28C */  lw         $v0, 0x0($a1)
/* E7F8 8001DFF8 00000000 */  nop
/* E7FC 8001DFFC 240002AD */  sw         $v0, 0x24($t0)
/* E800 8001E000 0400A38C */  lw         $v1, 0x4($a1)
/* E804 8001E004 00000000 */  nop
/* E808 8001E008 280003AD */  sw         $v1, 0x28($t0)
/* E80C 8001E00C 0800A28C */  lw         $v0, 0x8($a1)
/* E810 8001E010 00000000 */  nop
/* E814 8001E014 2C0002AD */  sw         $v0, 0x2C($t0)
/* E818 8001E018 0000C294 */  lhu        $v0, 0x0($a2)
/* E81C 8001E01C 003C0700 */  sll        $a3, $a3, 16
/* E820 8001E020 440002A5 */  sh         $v0, 0x44($t0)
/* E824 8001E024 0200C394 */  lhu        $v1, 0x2($a2)
/* E828 8001E028 033C0700 */  sra        $a3, $a3, 16
/* E82C 8001E02C 460003A5 */  sh         $v1, 0x46($t0)
/* E830 8001E030 0400C494 */  lhu        $a0, 0x4($a2)
/* E834 8001E034 00100224 */  addiu      $v0, $zero, 0x1000
/* E838 8001E038 4E0002A5 */  sh         $v0, 0x4E($t0)
/* E83C 8001E03C 4C0002A5 */  sh         $v0, 0x4C($t0)
/* E840 8001E040 00100224 */  addiu      $v0, $zero, 0x1000
/* E844 8001E044 500007A5 */  sh         $a3, 0x50($t0)
/* E848 8001E048 540000A5 */  sh         $zero, 0x54($t0)
/* E84C 8001E04C 0300E210 */  beq        $a3, $v0, .L8001E05C
/* E850 8001E050 480004A5 */   sh        $a0, 0x48($t0)
/* E854 8001E054 18780008 */  j          .L8001E060
/* E858 8001E058 04002235 */   ori       $v0, $t1, 0x4
.L8001E05C:
/* E85C 8001E05C FBFF2231 */  andi       $v0, $t1, 0xFFFB
.L8001E060:
/* E860 8001E060 000002A5 */  sh         $v0, 0x0($t0)
/* E864 8001E064 A578000C */  jal        func_8001E294
/* E868 8001E068 21200001 */   addu      $a0, $t0, $zero
/* E86C 8001E06C 1000BF8F */  lw         $ra, 0x10($sp)
/* E870 8001E070 00000000 */  nop
/* E874 8001E074 0800E003 */  jr         $ra
/* E878 8001E078 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001DFD4, . - func_8001DFD4

glabel func_8001E07C
/* E87C 8001E07C E0FFBD27 */  addiu      $sp, $sp, -0x20
/* E880 8001E080 003C0700 */  sll        $a3, $a3, 16
/* E884 8001E084 033C0700 */  sra        $a3, $a3, 16
/* E888 8001E088 1800BFAF */  sw         $ra, 0x18($sp)
/* E88C 8001E08C 2978000C */  jal        func_8001E0A4
/* E890 8001E090 1000A0AF */   sw        $zero, 0x10($sp)
/* E894 8001E094 1800BF8F */  lw         $ra, 0x18($sp)
/* E898 8001E098 00000000 */  nop
/* E89C 8001E09C 0800E003 */  jr         $ra
/* E8A0 8001E0A0 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8001E07C, . - func_8001E07C

glabel func_8001E0A4
/* E8A4 8001E0A4 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* E8A8 8001E0A8 21408000 */  addu       $t0, $a0, $zero
/* E8AC 8001E0AC 1000BFAF */  sw         $ra, 0x10($sp)
/* E8B0 8001E0B0 00000395 */  lhu        $v1, 0x0($t0)
/* E8B4 8001E0B4 02000224 */  addiu      $v0, $zero, 0x2
/* E8B8 8001E0B8 020002A5 */  sh         $v0, 0x2($t0)
/* E8BC 8001E0BC 03006934 */  ori        $t1, $v1, 0x3
/* E8C0 8001E0C0 000009A5 */  sh         $t1, 0x0($t0)
/* E8C4 8001E0C4 0000A28C */  lw         $v0, 0x0($a1)
/* E8C8 8001E0C8 00000000 */  nop
/* E8CC 8001E0CC 240002AD */  sw         $v0, 0x24($t0)
/* E8D0 8001E0D0 0400A38C */  lw         $v1, 0x4($a1)
/* E8D4 8001E0D4 00000000 */  nop
/* E8D8 8001E0D8 280003AD */  sw         $v1, 0x28($t0)
/* E8DC 8001E0DC 0800A28C */  lw         $v0, 0x8($a1)
/* E8E0 8001E0E0 00000000 */  nop
/* E8E4 8001E0E4 2C0002AD */  sw         $v0, 0x2C($t0)
/* E8E8 8001E0E8 0000C28C */  lw         $v0, 0x0($a2)
/* E8EC 8001E0EC 00000000 */  nop
/* E8F0 8001E0F0 340002AD */  sw         $v0, 0x34($t0)
/* E8F4 8001E0F4 0400C38C */  lw         $v1, 0x4($a2)
/* E8F8 8001E0F8 003C0700 */  sll        $a3, $a3, 16
/* E8FC 8001E0FC 380003AD */  sw         $v1, 0x38($t0)
/* E900 8001E100 0800C48C */  lw         $a0, 0x8($a2)
/* E904 8001E104 00100224 */  addiu      $v0, $zero, 0x1000
/* E908 8001E108 4E0002A5 */  sh         $v0, 0x4E($t0)
/* E90C 8001E10C 4C0002A5 */  sh         $v0, 0x4C($t0)
/* E910 8001E110 2800A287 */  lh         $v0, 0x28($sp)
/* E914 8001E114 033C0700 */  sra        $a3, $a3, 16
/* E918 8001E118 500007A5 */  sh         $a3, 0x50($t0)
/* E91C 8001E11C 540002A5 */  sh         $v0, 0x54($t0)
/* E920 8001E120 00100224 */  addiu      $v0, $zero, 0x1000
/* E924 8001E124 0300E210 */  beq        $a3, $v0, .L8001E134
/* E928 8001E128 3C0004AD */   sw        $a0, 0x3C($t0)
/* E92C 8001E12C 4E780008 */  j          .L8001E138
/* E930 8001E130 04002235 */   ori       $v0, $t1, 0x4
.L8001E134:
/* E934 8001E134 FBFF2231 */  andi       $v0, $t1, 0xFFFB
.L8001E138:
/* E938 8001E138 000002A5 */  sh         $v0, 0x0($t0)
/* E93C 8001E13C A578000C */  jal        func_8001E294
/* E940 8001E140 21200001 */   addu      $a0, $t0, $zero
/* E944 8001E144 1000BF8F */  lw         $ra, 0x10($sp)
/* E948 8001E148 00000000 */  nop
/* E94C 8001E14C 0800E003 */  jr         $ra
/* E950 8001E150 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001E0A4, . - func_8001E0A4

glabel func_8001E154
/* E954 8001E154 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* E958 8001E158 1400BFAF */  sw         $ra, 0x14($sp)
/* E95C 8001E15C A578000C */  jal        func_8001E294
/* E960 8001E160 1000B0AF */   sw        $s0, 0x10($sp)
/* E964 8001E164 21804000 */  addu       $s0, $v0, $zero
/* E968 8001E168 DE7A000C */  jal        SetRotMatrix
/* E96C 8001E16C 21200002 */   addu      $a0, $s0, $zero
/* E970 8001E170 EA7A000C */  jal        SetTransMatrix
/* E974 8001E174 21200002 */   addu      $a0, $s0, $zero
/* E978 8001E178 21100002 */  addu       $v0, $s0, $zero
/* E97C 8001E17C 1400BF8F */  lw         $ra, 0x14($sp)
/* E980 8001E180 1000B08F */  lw         $s0, 0x10($sp)
/* E984 8001E184 0800E003 */  jr         $ra
/* E988 8001E188 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001E154, . - func_8001E154

glabel func_8001E18C
/* E98C 8001E18C B8FFBD27 */  addiu      $sp, $sp, -0x48
/* E990 8001E190 3800B0AF */  sw         $s0, 0x38($sp)
/* E994 8001E194 21808000 */  addu       $s0, $a0, $zero
/* E998 8001E198 4000BFAF */  sw         $ra, 0x40($sp)
/* E99C 8001E19C 3C00B1AF */  sw         $s1, 0x3C($sp)
/* E9A0 8001E1A0 00000296 */  lhu        $v0, 0x0($s0)
/* E9A4 8001E1A4 00000000 */  nop
/* E9A8 8001E1A8 01004230 */  andi       $v0, $v0, 0x1
/* E9AC 8001E1AC 33004010 */  beqz       $v0, .L8001E27C
/* E9B0 8001E1B0 01000224 */   addiu     $v0, $zero, 0x1
/* E9B4 8001E1B4 02000386 */  lh         $v1, 0x2($s0)
/* E9B8 8001E1B8 00000000 */  nop
/* E9BC 8001E1BC 0B006210 */  beq        $v1, $v0, .L8001E1EC
/* E9C0 8001E1C0 02006228 */   slti      $v0, $v1, 0x2
/* E9C4 8001E1C4 05004010 */  beqz       $v0, .L8001E1DC
/* E9C8 8001E1C8 02000224 */   addiu     $v0, $zero, 0x2
/* E9CC 8001E1CC 27006010 */  beqz       $v1, .L8001E26C
/* E9D0 8001E1D0 0180043C */   lui       $a0, %hi(D_8001117C)
/* E9D4 8001E1D4 95780008 */  j          .L8001E254
/* E9D8 8001E1D8 7C118424 */   addiu     $a0, $a0, %lo(D_8001117C)
.L8001E1DC:
/* E9DC 8001E1DC 0B006210 */  beq        $v1, $v0, .L8001E20C
/* E9E0 8001E1E0 0180043C */   lui       $a0, %hi(D_8001117C)
/* E9E4 8001E1E4 95780008 */  j          .L8001E254
/* E9E8 8001E1E8 7C118424 */   addiu     $a0, $a0, %lo(D_8001117C)
.L8001E1EC:
/* E9EC 8001E1EC 58001126 */  addiu      $s1, $s0, 0x58
/* E9F0 8001E1F0 21202002 */  addu       $a0, $s1, $zero
/* E9F4 8001E1F4 24000526 */  addiu      $a1, $s0, 0x24
/* E9F8 8001E1F8 04000786 */  lh         $a3, 0x4($s0)
/* E9FC 8001E1FC 2279000C */  jal        func_8001E488
/* EA00 8001E200 44000626 */   addiu     $a2, $s0, 0x44
/* EA04 8001E204 8B780008 */  j          .L8001E22C
/* EA08 8001E208 00000000 */   nop
.L8001E20C:
/* EA0C 8001E20C 58001126 */  addiu      $s1, $s0, 0x58
/* EA10 8001E210 21202002 */  addu       $a0, $s1, $zero
/* EA14 8001E214 24000526 */  addiu      $a1, $s0, 0x24
/* EA18 8001E218 34000626 */  addiu      $a2, $s0, 0x34
/* EA1C 8001E21C 54000786 */  lh         $a3, 0x54($s0)
/* EA20 8001E220 44000226 */  addiu      $v0, $s0, 0x44
/* EA24 8001E224 4479000C */  jal        func_8001E510
/* EA28 8001E228 1000A2AF */   sw        $v0, 0x10($sp)
.L8001E22C:
/* EA2C 8001E22C 00000296 */  lhu        $v0, 0x0($s0)
/* EA30 8001E230 00000000 */  nop
/* EA34 8001E234 04004230 */  andi       $v0, $v0, 0x4
/* EA38 8001E238 0C004010 */  beqz       $v0, .L8001E26C
/* EA3C 8001E23C 21202002 */   addu      $a0, $s1, $zero
/* EA40 8001E240 4C000526 */  addiu      $a1, $s0, 0x4C
/* EA44 8001E244 0E79000C */  jal        func_8001E438
/* EA48 8001E248 21308000 */   addu      $a2, $a0, $zero
/* EA4C 8001E24C 9B780008 */  j          .L8001E26C
/* EA50 8001E250 00000000 */   nop
.L8001E254:
/* EA54 8001E254 0180053C */  lui        $a1, %hi(D_800111D0)
/* EA58 8001E258 D011A524 */  addiu      $a1, $a1, %lo(D_800111D0)
/* EA5C 8001E25C 9361000C */  jal        printf
/* EA60 8001E260 D2000624 */   addiu     $a2, $zero, 0xD2
/* EA64 8001E264 FFFF0324 */  addiu      $v1, $zero, -0x1
/* EA68 8001E268 010003AC */  sw         $v1, 0x1($zero)
.L8001E26C:
/* EA6C 8001E26C 00000296 */  lhu        $v0, 0x0($s0)
/* EA70 8001E270 00000000 */  nop
/* EA74 8001E274 FEFF4230 */  andi       $v0, $v0, 0xFFFE
/* EA78 8001E278 000002A6 */  sh         $v0, 0x0($s0)
.L8001E27C:
/* EA7C 8001E27C 58000226 */  addiu      $v0, $s0, 0x58
/* EA80 8001E280 4000BF8F */  lw         $ra, 0x40($sp)
/* EA84 8001E284 3C00B18F */  lw         $s1, 0x3C($sp)
/* EA88 8001E288 3800B08F */  lw         $s0, 0x38($sp)
/* EA8C 8001E28C 0800E003 */  jr         $ra
/* EA90 8001E290 4800BD27 */   addiu     $sp, $sp, 0x48
.size func_8001E18C, . - func_8001E18C

glabel func_8001E294
/* EA94 8001E294 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* EA98 8001E298 1000B0AF */  sw         $s0, 0x10($sp)
/* EA9C 8001E29C 1400BFAF */  sw         $ra, 0x14($sp)
/* EAA0 8001E2A0 6378000C */  jal        func_8001E18C
/* EAA4 8001E2A4 21808000 */   addu      $s0, $a0, $zero
/* EAA8 8001E2A8 00000396 */  lhu        $v1, 0x0($s0)
/* EAAC 8001E2AC 00000000 */  nop
/* EAB0 8001E2B0 02006330 */  andi       $v1, $v1, 0x2
/* EAB4 8001E2B4 09006010 */  beqz       $v1, .L8001E2DC
/* EAB8 8001E2B8 78000426 */   addiu     $a0, $s0, 0x78
/* EABC 8001E2BC 58000526 */  addiu      $a1, $s0, 0x58
/* EAC0 8001E2C0 2000078E */  lw         $a3, 0x20($s0)
/* EAC4 8001E2C4 C878000C */  jal        func_8001E320
/* EAC8 8001E2C8 18000626 */   addiu     $a2, $s0, 0x18
/* EACC 8001E2CC 00000296 */  lhu        $v0, 0x0($s0)
/* EAD0 8001E2D0 00000000 */  nop
/* EAD4 8001E2D4 FDFF4230 */  andi       $v0, $v0, 0xFFFD
/* EAD8 8001E2D8 000002A6 */  sh         $v0, 0x0($s0)
.L8001E2DC:
/* EADC 8001E2DC 78000226 */  addiu      $v0, $s0, 0x78
/* EAE0 8001E2E0 1400BF8F */  lw         $ra, 0x14($sp)
/* EAE4 8001E2E4 1000B08F */  lw         $s0, 0x10($sp)
/* EAE8 8001E2E8 0800E003 */  jr         $ra
/* EAEC 8001E2EC 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001E294, . - func_8001E294

glabel func_8001E2F0
/* EAF0 8001E2F0 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* EAF4 8001E2F4 21108000 */  addu       $v0, $a0, $zero
/* EAF8 8001E2F8 2120A000 */  addu       $a0, $a1, $zero
/* EAFC 8001E2FC 2128C000 */  addu       $a1, $a2, $zero
/* EB00 8001E300 1000BFAF */  sw         $ra, 0x10($sp)
/* EB04 8001E304 2000478C */  lw         $a3, 0x20($v0)
/* EB08 8001E308 C878000C */  jal        func_8001E320
/* EB0C 8001E30C 18004624 */   addiu     $a2, $v0, 0x18
/* EB10 8001E310 1000BF8F */  lw         $ra, 0x10($sp)
/* EB14 8001E314 00000000 */  nop
/* EB18 8001E318 0800E003 */  jr         $ra
/* EB1C 8001E31C 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8001E2F0, . - func_8001E2F0

glabel func_8001E320
/* EB20 8001E320 C0FFBD27 */  addiu      $sp, $sp, -0x40
/* EB24 8001E324 3400B1AF */  sw         $s1, 0x34($sp)
/* EB28 8001E328 2188C000 */  addu       $s1, $a2, $zero
/* EB2C 8001E32C 3800B2AF */  sw         $s2, 0x38($sp)
/* EB30 8001E330 21908000 */  addu       $s2, $a0, $zero
/* EB34 8001E334 3000B0AF */  sw         $s0, 0x30($sp)
/* EB38 8001E338 2180A000 */  addu       $s0, $a1, $zero
/* EB3C 8001E33C 1000A427 */  addiu      $a0, $sp, 0x10
/* EB40 8001E340 3C00BFAF */  sw         $ra, 0x3C($sp)
/* EB44 8001E344 00002286 */  lh         $v0, 0x0($s1)
/* EB48 8001E348 02002386 */  lh         $v1, 0x2($s1)
/* EB4C 8001E34C 04002696 */  lhu        $a2, 0x4($s1)
/* EB50 8001E350 1400A0AF */  sw         $zero, 0x14($sp)
/* EB54 8001E354 1C00A0AF */  sw         $zero, 0x1C($sp)
/* EB58 8001E358 2000A6A7 */  sh         $a2, 0x20($sp)
/* EB5C 8001E35C 21304002 */  addu       $a2, $s2, $zero
/* EB60 8001E360 1000A2AF */  sw         $v0, 0x10($sp)
/* EB64 8001E364 B679000C */  jal        MulMatrix0
/* EB68 8001E368 1800A3AF */   sw        $v1, 0x18($sp)
/* EB6C 8001E36C 00002386 */  lh         $v1, 0x0($s1)
/* EB70 8001E370 1400028E */  lw         $v0, 0x14($s0)
/* EB74 8001E374 00000000 */  nop
/* EB78 8001E378 18004300 */  mult       $v0, $v1
/* EB7C 8001E37C 12100000 */  mflo       $v0
/* EB80 8001E380 03130200 */  sra        $v0, $v0, 12
/* EB84 8001E384 140042AE */  sw         $v0, 0x14($s2)
/* EB88 8001E388 02002386 */  lh         $v1, 0x2($s1)
/* EB8C 8001E38C 1800028E */  lw         $v0, 0x18($s0)
/* EB90 8001E390 00000000 */  nop
/* EB94 8001E394 18004300 */  mult       $v0, $v1
/* EB98 8001E398 3C00BF8F */  lw         $ra, 0x3C($sp)
/* EB9C 8001E39C 3400B18F */  lw         $s1, 0x34($sp)
/* EBA0 8001E3A0 12100000 */  mflo       $v0
/* EBA4 8001E3A4 03130200 */  sra        $v0, $v0, 12
/* EBA8 8001E3A8 180042AE */  sw         $v0, 0x18($s2)
/* EBAC 8001E3AC 1C00038E */  lw         $v1, 0x1C($s0)
/* EBB0 8001E3B0 3000B08F */  lw         $s0, 0x30($sp)
/* EBB4 8001E3B4 1C0043AE */  sw         $v1, 0x1C($s2)
/* EBB8 8001E3B8 3800B28F */  lw         $s2, 0x38($sp)
/* EBBC 8001E3BC 0800E003 */  jr         $ra
/* EBC0 8001E3C0 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_8001E320, . - func_8001E320

glabel func_8001E3C4
/* EBC4 8001E3C4 B0FFBD27 */  addiu      $sp, $sp, -0x50
/* EBC8 8001E3C8 4400B1AF */  sw         $s1, 0x44($sp)
/* EBCC 8001E3CC 21888000 */  addu       $s1, $a0, $zero
/* EBD0 8001E3D0 002C0500 */  sll        $a1, $a1, 16
/* EBD4 8001E3D4 032C0500 */  sra        $a1, $a1, 16
/* EBD8 8001E3D8 4800BFAF */  sw         $ra, 0x48($sp)
/* EBDC 8001E3DC 1100A010 */  beqz       $a1, .L8001E424
/* EBE0 8001E3E0 4000B0AF */   sw        $s0, 0x40($sp)
/* EBE4 8001E3E4 2000B027 */  addiu      $s0, $sp, 0x20
/* EBE8 8001E3E8 8190000C */  jal        func_80024204
/* EBEC 8001E3EC 21200002 */   addu      $a0, $s0, $zero
/* EBF0 8001E3F0 DE7A000C */  jal        SetRotMatrix
/* EBF4 8001E3F4 21200002 */   addu      $a0, $s0, $zero
/* EBF8 8001E3F8 1400228E */  lw         $v0, 0x14($s1)
/* EBFC 8001E3FC 1800238E */  lw         $v1, 0x18($s1)
/* EC00 8001E400 1C00258E */  lw         $a1, 0x1C($s1)
/* EC04 8001E404 21202002 */  addu       $a0, $s1, $zero
/* EC08 8001E408 1000A2AF */  sw         $v0, 0x10($sp)
/* EC0C 8001E40C 1400A3AF */  sw         $v1, 0x14($sp)
/* EC10 8001E410 FA79000C */  jal        MulRotMatrix
/* EC14 8001E414 1800A5AF */   sw        $a1, 0x18($sp)
/* EC18 8001E418 1000A427 */  addiu      $a0, $sp, 0x10
/* EC1C 8001E41C 8E7A000C */  jal        ApplyRotMatrixLV
/* EC20 8001E420 14002526 */   addiu     $a1, $s1, 0x14
.L8001E424:
/* EC24 8001E424 4800BF8F */  lw         $ra, 0x48($sp)
/* EC28 8001E428 4400B18F */  lw         $s1, 0x44($sp)
/* EC2C 8001E42C 4000B08F */  lw         $s0, 0x40($sp)
/* EC30 8001E430 0800E003 */  jr         $ra
/* EC34 8001E434 5000BD27 */   addiu     $sp, $sp, 0x50
.size func_8001E3C4, . - func_8001E3C4

glabel func_8001E438
/* EC38 8001E438 C8FFBD27 */  addiu      $sp, $sp, -0x38
/* EC3C 8001E43C 3000BFAF */  sw         $ra, 0x30($sp)
/* EC40 8001E440 0000A284 */  lh         $v0, 0x0($a1)
/* EC44 8001E444 0200A384 */  lh         $v1, 0x2($a1)
/* EC48 8001E448 0400A794 */  lhu        $a3, 0x4($a1)
/* EC4C 8001E44C 21288000 */  addu       $a1, $a0, $zero
/* EC50 8001E450 1000A427 */  addiu      $a0, $sp, 0x10
/* EC54 8001E454 1400A0AF */  sw         $zero, 0x14($sp)
/* EC58 8001E458 1C00A0AF */  sw         $zero, 0x1C($sp)
/* EC5C 8001E45C 2C00A0AF */  sw         $zero, 0x2C($sp)
/* EC60 8001E460 2800A0AF */  sw         $zero, 0x28($sp)
/* EC64 8001E464 2400A0AF */  sw         $zero, 0x24($sp)
/* EC68 8001E468 1000A2AF */  sw         $v0, 0x10($sp)
/* EC6C 8001E46C 1800A3AF */  sw         $v1, 0x18($sp)
/* EC70 8001E470 367A000C */  jal        CompMatrix
/* EC74 8001E474 2000A7A7 */   sh        $a3, 0x20($sp)
/* EC78 8001E478 3000BF8F */  lw         $ra, 0x30($sp)
/* EC7C 8001E47C 00000000 */  nop
/* EC80 8001E480 0800E003 */  jr         $ra
/* EC84 8001E484 3800BD27 */   addiu     $sp, $sp, 0x38
.size func_8001E438, . - func_8001E438

glabel func_8001E488
/* EC88 8001E488 B0FFBD27 */  addiu      $sp, $sp, -0x50
/* EC8C 8001E48C 4000B0AF */  sw         $s0, 0x40($sp)
/* EC90 8001E490 21808000 */  addu       $s0, $a0, $zero
/* EC94 8001E494 4400B1AF */  sw         $s1, 0x44($sp)
/* EC98 8001E498 2000B127 */  addiu      $s1, $sp, 0x20
/* EC9C 8001E49C 21202002 */  addu       $a0, $s1, $zero
/* ECA0 8001E4A0 2140A000 */  addu       $t0, $a1, $zero
/* ECA4 8001E4A4 2128C000 */  addu       $a1, $a2, $zero
/* ECA8 8001E4A8 00340700 */  sll        $a2, $a3, 16
/* ECAC 8001E4AC 4800BFAF */  sw         $ra, 0x48($sp)
/* ECB0 8001E4B0 0000028D */  lw         $v0, 0x0($t0)
/* ECB4 8001E4B4 03340600 */  sra        $a2, $a2, 16
/* ECB8 8001E4B8 23100200 */  negu       $v0, $v0
/* ECBC 8001E4BC 1000A2AF */  sw         $v0, 0x10($sp)
/* ECC0 8001E4C0 0400038D */  lw         $v1, 0x4($t0)
/* ECC4 8001E4C4 0800028D */  lw         $v0, 0x8($t0)
/* ECC8 8001E4C8 23180300 */  negu       $v1, $v1
/* ECCC 8001E4CC 23100200 */  negu       $v0, $v0
/* ECD0 8001E4D0 1400A3AF */  sw         $v1, 0x14($sp)
/* ECD4 8001E4D4 3391000C */  jal        func_800244CC
/* ECD8 8001E4D8 1800A2AF */   sw        $v0, 0x18($sp)
/* ECDC 8001E4DC 21202002 */  addu       $a0, $s1, $zero
/* ECE0 8001E4E0 BDF6000C */  jal        func_8003DAF4
/* ECE4 8001E4E4 21280002 */   addu      $a1, $s0, $zero
/* ECE8 8001E4E8 DE7A000C */  jal        SetRotMatrix
/* ECEC 8001E4EC 21200002 */   addu      $a0, $s0, $zero
/* ECF0 8001E4F0 1000A427 */  addiu      $a0, $sp, 0x10
/* ECF4 8001E4F4 8E7A000C */  jal        ApplyRotMatrixLV
/* ECF8 8001E4F8 14000526 */   addiu     $a1, $s0, 0x14
/* ECFC 8001E4FC 4800BF8F */  lw         $ra, 0x48($sp)
/* ED00 8001E500 4400B18F */  lw         $s1, 0x44($sp)
/* ED04 8001E504 4000B08F */  lw         $s0, 0x40($sp)
/* ED08 8001E508 0800E003 */  jr         $ra
/* ED0C 8001E50C 5000BD27 */   addiu     $sp, $sp, 0x50
.size func_8001E488, . - func_8001E488

glabel func_8001E510
/* ED10 8001E510 58FFBD27 */  addiu      $sp, $sp, -0xA8
/* ED14 8001E514 A000BFAF */  sw         $ra, 0xA0($sp)
/* ED18 8001E518 9C00B5AF */  sw         $s5, 0x9C($sp)
/* ED1C 8001E51C 9800B4AF */  sw         $s4, 0x98($sp)
/* ED20 8001E520 9400B3AF */  sw         $s3, 0x94($sp)
/* ED24 8001E524 9000B2AF */  sw         $s2, 0x90($sp)
/* ED28 8001E528 8C00B1AF */  sw         $s1, 0x8C($sp)
/* ED2C 8001E52C 8800B0AF */  sw         $s0, 0x88($sp)
/* ED30 8001E530 0000A38C */  lw         $v1, 0x0($a1)
/* ED34 8001E534 0000D38C */  lw         $s3, 0x0($a2)
/* ED38 8001E538 00000000 */  nop
/* ED3C 8001E53C 23986302 */  subu       $s3, $s3, $v1
/* ED40 8001E540 18007302 */  mult       $s3, $s3
/* ED44 8001E544 21A88000 */  addu       $s5, $a0, $zero
/* ED48 8001E548 0800A88C */  lw         $t0, 0x8($a1)
/* ED4C 8001E54C 0800D28C */  lw         $s2, 0x8($a2)
/* ED50 8001E550 12580000 */  mflo       $t3
/* ED54 8001E554 008C0700 */  sll        $s1, $a3, 16
/* ED58 8001E558 23904802 */  subu       $s2, $s2, $t0
/* ED5C 8001E55C 18005202 */  mult       $s2, $s2
/* ED60 8001E560 038C1100 */  sra        $s1, $s1, 16
/* ED64 8001E564 0400A98C */  lw         $t1, 0x4($a1)
/* ED68 8001E568 23180300 */  negu       $v1, $v1
/* ED6C 8001E56C 23100900 */  negu       $v0, $t1
/* ED70 8001E570 23400800 */  negu       $t0, $t0
/* ED74 8001E574 5000A3AF */  sw         $v1, 0x50($sp)
/* ED78 8001E578 5400A2AF */  sw         $v0, 0x54($sp)
/* ED7C 8001E57C 5800A8AF */  sw         $t0, 0x58($sp)
/* ED80 8001E580 0400D08C */  lw         $s0, 0x4($a2)
/* ED84 8001E584 B800B48F */  lw         $s4, 0xB8($sp)
/* ED88 8001E588 23800902 */  subu       $s0, $s0, $t1
/* ED8C 8001E58C 12500000 */  mflo       $t2
/* ED90 8001E590 9279000C */  jal        SquareRoot0
/* ED94 8001E594 21206A01 */   addu      $a0, $t3, $t2
/* ED98 8001E598 21200002 */  addu       $a0, $s0, $zero
/* ED9C 8001E59C FA7A000C */  jal        ratan2
/* EDA0 8001E5A0 21284000 */   addu      $a1, $v0, $zero
/* EDA4 8001E5A4 21206002 */  addu       $a0, $s3, $zero
/* EDA8 8001E5A8 21284002 */  addu       $a1, $s2, $zero
/* EDAC 8001E5AC 23100200 */  negu       $v0, $v0
/* EDB0 8001E5B0 FA7A000C */  jal        ratan2
/* EDB4 8001E5B4 6000A2A7 */   sh        $v0, 0x60($sp)
/* EDB8 8001E5B8 6800B027 */  addiu      $s0, $sp, 0x68
/* EDBC 8001E5BC 21200002 */  addu       $a0, $s0, $zero
/* EDC0 8001E5C0 6000A527 */  addiu      $a1, $sp, 0x60
/* EDC4 8001E5C4 23881100 */  negu       $s1, $s1
/* EDC8 8001E5C8 02000624 */  addiu      $a2, $zero, 0x2
/* EDCC 8001E5CC 6200A2A7 */  sh         $v0, 0x62($sp)
/* EDD0 8001E5D0 3391000C */  jal        func_800244CC
/* EDD4 8001E5D4 6400B1A7 */   sh        $s1, 0x64($sp)
/* EDD8 8001E5D8 0600A012 */  beqz       $s5, .L8001E5F4
/* EDDC 8001E5DC 00000000 */   nop
/* EDE0 8001E5E0 21200002 */  addu       $a0, $s0, $zero
/* EDE4 8001E5E4 BDF6000C */  jal        func_8003DAF4
/* EDE8 8001E5E8 2128A002 */   addu      $a1, $s5, $zero
/* EDEC 8001E5EC DE7A000C */  jal        SetRotMatrix
/* EDF0 8001E5F0 2120A002 */   addu      $a0, $s5, $zero
.L8001E5F4:
/* EDF4 8001E5F4 07008012 */  beqz       $s4, .L8001E614
/* EDF8 8001E5F8 00000000 */   nop
/* EDFC 8001E5FC 6000A297 */  lhu        $v0, 0x60($sp)
/* EE00 8001E600 6200A397 */  lhu        $v1, 0x62($sp)
/* EE04 8001E604 6400A497 */  lhu        $a0, 0x64($sp)
/* EE08 8001E608 000082A6 */  sh         $v0, 0x0($s4)
/* EE0C 8001E60C 020083A6 */  sh         $v1, 0x2($s4)
/* EE10 8001E610 040084A6 */  sh         $a0, 0x4($s4)
.L8001E614:
/* EE14 8001E614 0300A012 */  beqz       $s5, .L8001E624
/* EE18 8001E618 5000A427 */   addiu     $a0, $sp, 0x50
/* EE1C 8001E61C 8E7A000C */  jal        ApplyRotMatrixLV
/* EE20 8001E620 1400A526 */   addiu     $a1, $s5, 0x14
.L8001E624:
/* EE24 8001E624 A000BF8F */  lw         $ra, 0xA0($sp)
/* EE28 8001E628 9C00B58F */  lw         $s5, 0x9C($sp)
/* EE2C 8001E62C 9800B48F */  lw         $s4, 0x98($sp)
/* EE30 8001E630 9400B38F */  lw         $s3, 0x94($sp)
/* EE34 8001E634 9000B28F */  lw         $s2, 0x90($sp)
/* EE38 8001E638 8C00B18F */  lw         $s1, 0x8C($sp)
/* EE3C 8001E63C 8800B08F */  lw         $s0, 0x88($sp)
/* EE40 8001E640 0800E003 */  jr         $ra
/* EE44 8001E644 A800BD27 */   addiu     $sp, $sp, 0xA8
.size func_8001E510, . - func_8001E510
