.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel func_8005ABAC
/* 4B3AC 8005ABAC D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 4B3B0 8005ABB0 1C00B1AF */  sw         $s1, 0x1C($sp)
/* 4B3B4 8005ABB4 21888000 */  addu       $s1, $a0, $zero
/* 4B3B8 8005ABB8 1800B0AF */  sw         $s0, 0x18($sp)
/* 4B3BC 8005ABBC 2180A000 */  addu       $s0, $a1, $zero
/* 4B3C0 8005ABC0 2000BFAF */  sw         $ra, 0x20($sp)
/* 4B3C4 8005ABC4 FF6A010C */  jal        func_8005ABFC
/* 4B3C8 8005ABC8 21200002 */   addu      $a0, $s0, $zero
/* 4B3CC 8005ABCC 21204000 */  addu       $a0, $v0, $zero
/* 4B3D0 8005ABD0 0680073C */  lui        $a3, %hi(func_8005B5E0)
/* 4B3D4 8005ABD4 21282002 */  addu       $a1, $s1, $zero
/* 4B3D8 8005ABD8 21300002 */  addu       $a2, $s0, $zero
/* 4B3DC 8005ABDC E0B5E724 */  addiu      $a3, $a3, %lo(func_8005B5E0)
/* 4B3E0 8005ABE0 2C6B010C */  jal        func_8005ACB0
/* 4B3E4 8005ABE4 1000A0AF */   sw        $zero, 0x10($sp)
/* 4B3E8 8005ABE8 2000BF8F */  lw         $ra, 0x20($sp)
/* 4B3EC 8005ABEC 1C00B18F */  lw         $s1, 0x1C($sp)
/* 4B3F0 8005ABF0 1800B08F */  lw         $s0, 0x18($sp)
/* 4B3F4 8005ABF4 0800E003 */  jr         $ra
/* 4B3F8 8005ABF8 2800BD27 */   addiu     $sp, $sp, 0x28
.size func_8005ABAC, . - func_8005ABAC

glabel func_8005ABFC
/* 4B3FC 8005ABFC E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 4B400 8005AC00 1800BFAF */  sw         $ra, 0x18($sp)
/* 4B404 8005AC04 1400B1AF */  sw         $s1, 0x14($sp)
/* 4B408 8005AC08 9FF0000C */  jal        func_8003C27C
/* 4B40C 8005AC0C 1000B0AF */   sw        $s0, 0x10($sp)
/* 4B410 8005AC10 2C000424 */  addiu      $a0, $zero, 0x2C
/* 4B414 8005AC14 0180053C */  lui        $a1, %hi(D_800132C8)
/* 4B418 8005AC18 C832A524 */  addiu      $a1, $a1, %lo(D_800132C8)
/* 4B41C 8005AC1C 00140200 */  sll        $v0, $v0, 16
/* 4B420 8005AC20 63C5000C */  jal        func_8003158C
/* 4B424 8005AC24 03840200 */   sra       $s0, $v0, 16
/* 4B428 8005AC28 21884000 */  addu       $s1, $v0, $zero
/* 4B42C 8005AC2C 0A002016 */  bnez       $s1, .L8005AC58
/* 4B430 8005AC30 00211000 */   sll       $a0, $s0, 4
/* 4B434 8005AC34 0180043C */  lui        $a0, %hi(D_80013284)
/* 4B438 8005AC38 84328424 */  addiu      $a0, $a0, %lo(D_80013284)
/* 4B43C 8005AC3C 0180053C */  lui        $a1, %hi(D_800132D8)
/* 4B440 8005AC40 D832A524 */  addiu      $a1, $a1, %lo(D_800132D8)
/* 4B444 8005AC44 9361000C */  jal        printf
/* 4B448 8005AC48 4D000624 */   addiu     $a2, $zero, 0x4D
/* 4B44C 8005AC4C FFFF0324 */  addiu      $v1, $zero, -0x1
/* 4B450 8005AC50 010003AC */  sw         $v1, 0x1($zero)
/* 4B454 8005AC54 00211000 */  sll        $a0, $s0, 4
.L8005AC58:
/* 4B458 8005AC58 0180053C */  lui        $a1, %hi(D_800132E4)
/* 4B45C 8005AC5C 0000308E */  lw         $s0, 0x0($s1)
/* 4B460 8005AC60 63C5000C */  jal        func_8003158C
/* 4B464 8005AC64 E432A524 */   addiu     $a1, $a1, %lo(D_800132E4)
/* 4B468 8005AC68 09004014 */  bnez       $v0, .L8005AC90
/* 4B46C 8005AC6C 000002AE */   sw        $v0, 0x0($s0)
/* 4B470 8005AC70 0180043C */  lui        $a0, %hi(D_80013284)
/* 4B474 8005AC74 84328424 */  addiu      $a0, $a0, %lo(D_80013284)
/* 4B478 8005AC78 0180053C */  lui        $a1, %hi(D_800132D8)
/* 4B47C 8005AC7C D832A524 */  addiu      $a1, $a1, %lo(D_800132D8)
/* 4B480 8005AC80 9361000C */  jal        printf
/* 4B484 8005AC84 50000624 */   addiu     $a2, $zero, 0x50
/* 4B488 8005AC88 FFFF0324 */  addiu      $v1, $zero, -0x1
/* 4B48C 8005AC8C 010003AC */  sw         $v1, 0x1($zero)
.L8005AC90:
/* 4B490 8005AC90 21102002 */  addu       $v0, $s1, $zero
/* 4B494 8005AC94 1800BF8F */  lw         $ra, 0x18($sp)
/* 4B498 8005AC98 1400B18F */  lw         $s1, 0x14($sp)
/* 4B49C 8005AC9C 280000A6 */  sh         $zero, 0x28($s0)
/* 4B4A0 8005ACA0 2A0000A6 */  sh         $zero, 0x2A($s0)
/* 4B4A4 8005ACA4 1000B08F */  lw         $s0, 0x10($sp)
/* 4B4A8 8005ACA8 0800E003 */  jr         $ra
/* 4B4AC 8005ACAC 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8005ABFC, . - func_8005ABFC

glabel func_8005ACB0
/* 4B4B0 8005ACB0 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 4B4B4 8005ACB4 1800B2AF */  sw         $s2, 0x18($sp)
/* 4B4B8 8005ACB8 21908000 */  addu       $s2, $a0, $zero
/* 4B4BC 8005ACBC 1400B1AF */  sw         $s1, 0x14($sp)
/* 4B4C0 8005ACC0 2188A000 */  addu       $s1, $a1, $zero
/* 4B4C4 8005ACC4 21202002 */  addu       $a0, $s1, $zero
/* 4B4C8 8005ACC8 2128E000 */  addu       $a1, $a3, $zero
/* 4B4CC 8005ACCC 1000B0AF */  sw         $s0, 0x10($sp)
/* 4B4D0 8005ACD0 2180C000 */  addu       $s0, $a2, $zero
/* 4B4D4 8005ACD4 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 4B4D8 8005ACD8 0000428E */  lw         $v0, 0x0($s2)
/* 4B4DC 8005ACDC 3000A38F */  lw         $v1, 0x30($sp)
/* 4B4E0 8005ACE0 21304000 */  addu       $a2, $v0, $zero
/* 4B4E4 8005ACE4 280040A4 */  sh         $zero, 0x28($v0)
/* 4B4E8 8005ACE8 2A0040A4 */  sh         $zero, 0x2A($v0)
/* 4B4EC 8005ACEC 58F1000C */  jal        func_8003C560
/* 4B4F0 8005ACF0 240043AC */   sw        $v1, 0x24($v0)
/* 4B4F4 8005ACF4 F0F0000C */  jal        func_8003C3C0
/* 4B4F8 8005ACF8 21200002 */   addu      $a0, $s0, $zero
/* 4B4FC 8005ACFC 21202002 */  addu       $a0, $s1, $zero
/* 4B500 8005AD00 21280000 */  addu       $a1, $zero, $zero
/* 4B504 8005AD04 58F1000C */  jal        func_8003C560
/* 4B508 8005AD08 21300000 */   addu      $a2, $zero, $zero
/* 4B50C 8005AD0C 21104002 */  addu       $v0, $s2, $zero
/* 4B510 8005AD10 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 4B514 8005AD14 1800B28F */  lw         $s2, 0x18($sp)
/* 4B518 8005AD18 1400B18F */  lw         $s1, 0x14($sp)
/* 4B51C 8005AD1C 1000B08F */  lw         $s0, 0x10($sp)
/* 4B520 8005AD20 0800E003 */  jr         $ra
/* 4B524 8005AD24 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8005ACB0, . - func_8005ACB0

glabel func_8005AD28
/* 4B528 8005AD28 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 4B52C 8005AD2C 1000B0AF */  sw         $s0, 0x10($sp)
/* 4B530 8005AD30 21808000 */  addu       $s0, $a0, $zero
/* 4B534 8005AD34 1400BFAF */  sw         $ra, 0x14($sp)
/* 4B538 8005AD38 AE56000C */  jal        DrawSync
/* 4B53C 8005AD3C 21200000 */   addu      $a0, $zero, $zero
/* 4B540 8005AD40 0000038E */  lw         $v1, 0x0($s0)
/* 4B544 8005AD44 00000000 */  nop
/* 4B548 8005AD48 0000648C */  lw         $a0, 0x0($v1)
/* 4B54C 8005AD4C 00000000 */  nop
/* 4B550 8005AD50 03008010 */  beqz       $a0, .L8005AD60
/* 4B554 8005AD54 00000000 */   nop
/* 4B558 8005AD58 9AC5000C */  jal        func_80031668
/* 4B55C 8005AD5C 00000000 */   nop
.L8005AD60:
/* 4B560 8005AD60 9AC5000C */  jal        func_80031668
/* 4B564 8005AD64 21200002 */   addu      $a0, $s0, $zero
/* 4B568 8005AD68 1400BF8F */  lw         $ra, 0x14($sp)
/* 4B56C 8005AD6C 1000B08F */  lw         $s0, 0x10($sp)
/* 4B570 8005AD70 0800E003 */  jr         $ra
/* 4B574 8005AD74 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8005AD28, . - func_8005AD28

glabel func_8005AD78
/* 4B578 8005AD78 00008C8C */  lw         $t4, 0x0($a0)
/* 4B57C 8005AD7C F8FFBD27 */  addiu      $sp, $sp, -0x8
/* 4B580 8005AD80 0000828D */  lw         $v0, 0x0($t4)
/* 4B584 8005AD84 00000000 */  nop
/* 4B588 8005AD88 0000438C */  lw         $v1, 0x0($v0)
/* 4B58C 8005AD8C 0400C014 */  bnez       $a2, .L8005ADA0
/* 4B590 8005AD90 2170A000 */   addu      $t6, $a1, $zero
/* 4B594 8005AD94 8000023C */  lui        $v0, (0x808080 >> 16)
/* 4B598 8005AD98 696B0108 */  j          .L8005ADA4
/* 4B59C 8005AD9C 80804234 */   ori       $v0, $v0, (0x808080 & 0xFFFF)
.L8005ADA0:
/* 4B5A0 8005ADA0 0000C28C */  lw         $v0, 0x0($a2)
.L8005ADA4:
/* 4B5A4 8005ADA4 00000000 */  nop
/* 4B5A8 8005ADA8 0000A2AF */  sw         $v0, 0x0($sp)
/* 4B5AC 8005ADAC 28008285 */  lh         $v0, 0x28($t4)
/* 4B5B0 8005ADB0 00000000 */  nop
/* 4B5B4 8005ADB4 55004018 */  blez       $v0, .L8005AF0C
/* 4B5B8 8005ADB8 0780023C */   lui       $v0, %hi(D_80077260)
/* 4B5BC 8005ADBC 60724B24 */  addiu      $t3, $v0, %lo(D_80077260)
/* 4B5C0 8005ADC0 FF00093C */  lui        $t1, (0xFFFFFF >> 16)
/* 4B5C4 8005ADC4 FFFF2935 */  ori        $t1, $t1, (0xFFFFFF & 0xFFFF)
/* 4B5C8 8005ADC8 00FF0A3C */  lui        $t2, (0xFF000000 >> 16)
/* 4B5CC 8005ADCC 01000D3C */  lui        $t5, (0x10000 >> 16)
/* 4B5D0 8005ADD0 21406000 */  addu       $t0, $v1, $zero
.L8005ADD4:
/* 4B5D4 8005ADD4 1000658D */  lw         $a1, 0x10($t3)
/* 4B5D8 8005ADD8 0000A393 */  lbu        $v1, 0x0($sp)
/* 4B5DC 8005ADDC 1400A224 */  addiu      $v0, $a1, 0x14
/* 4B5E0 8005ADE0 100062AD */  sw         $v0, 0x10($t3)
/* 4B5E4 8005ADE4 0400A3A0 */  sb         $v1, 0x4($a1)
/* 4B5E8 8005ADE8 0100A293 */  lbu        $v0, 0x1($sp)
/* 4B5EC 8005ADEC 64000324 */  addiu      $v1, $zero, 0x64
/* 4B5F0 8005ADF0 0500A2A0 */  sb         $v0, 0x5($a1)
/* 4B5F4 8005ADF4 0200A493 */  lbu        $a0, 0x2($sp)
/* 4B5F8 8005ADF8 04000224 */  addiu      $v0, $zero, 0x4
/* 4B5FC 8005ADFC 0300A2A0 */  sb         $v0, 0x3($a1)
/* 4B600 8005AE00 0700A3A0 */  sb         $v1, 0x7($a1)
/* 4B604 8005AE04 0600A4A0 */  sb         $a0, 0x6($a1)
/* 4B608 8005AE08 0000C295 */  lhu        $v0, 0x0($t6)
/* 4B60C 8005AE0C 00000395 */  lhu        $v1, 0x0($t0)
/* 4B610 8005AE10 00000000 */  nop
/* 4B614 8005AE14 21104300 */  addu       $v0, $v0, $v1
/* 4B618 8005AE18 0800A2A4 */  sh         $v0, 0x8($a1)
/* 4B61C 8005AE1C 0200C395 */  lhu        $v1, 0x2($t6)
/* 4B620 8005AE20 02000295 */  lhu        $v0, 0x2($t0)
/* 4B624 8005AE24 00000000 */  nop
/* 4B628 8005AE28 21186200 */  addu       $v1, $v1, $v0
/* 4B62C 8005AE2C 0A00A3A4 */  sh         $v1, 0xA($a1)
/* 4B630 8005AE30 04000291 */  lbu        $v0, 0x4($t0)
/* 4B634 8005AE34 00000000 */  nop
/* 4B638 8005AE38 0C00A2A0 */  sb         $v0, 0xC($a1)
/* 4B63C 8005AE3C 05000391 */  lbu        $v1, 0x5($t0)
/* 4B640 8005AE40 00000000 */  nop
/* 4B644 8005AE44 0D00A3A0 */  sb         $v1, 0xD($a1)
/* 4B648 8005AE48 06000495 */  lhu        $a0, 0x6($t0)
/* 4B64C 8005AE4C 2130A001 */  addu       $a2, $t5, $zero
/* 4B650 8005AE50 0E00A4A4 */  sh         $a0, 0xE($a1)
/* 4B654 8005AE54 08000295 */  lhu        $v0, 0x8($t0)
/* 4B658 8005AE58 03340600 */  sra        $a2, $a2, 16
/* 4B65C 8005AE5C 01004224 */  addiu      $v0, $v0, 0x1
/* 4B660 8005AE60 1000A2A4 */  sh         $v0, 0x10($a1)
/* 4B664 8005AE64 0A000395 */  lhu        $v1, 0xA($t0)
/* 4B668 8005AE68 0000A48C */  lw         $a0, 0x0($a1)
/* 4B66C 8005AE6C 01006324 */  addiu      $v1, $v1, 0x1
/* 4B670 8005AE70 1200A3A4 */  sh         $v1, 0x12($a1)
/* 4B674 8005AE74 0000E28C */  lw         $v0, 0x0($a3)
/* 4B678 8005AE78 24208A00 */  and        $a0, $a0, $t2
/* 4B67C 8005AE7C 24104900 */  and        $v0, $v0, $t1
/* 4B680 8005AE80 25208200 */  or         $a0, $a0, $v0
/* 4B684 8005AE84 0000A4AC */  sw         $a0, 0x0($a1)
/* 4B688 8005AE88 0000E28C */  lw         $v0, 0x0($a3)
/* 4B68C 8005AE8C 2428A900 */  and        $a1, $a1, $t1
/* 4B690 8005AE90 24104A00 */  and        $v0, $v0, $t2
/* 4B694 8005AE94 25104500 */  or         $v0, $v0, $a1
/* 4B698 8005AE98 0000E2AC */  sw         $v0, 0x0($a3)
/* 4B69C 8005AE9C 1000658D */  lw         $a1, 0x10($t3)
/* 4B6A0 8005AEA0 01000324 */  addiu      $v1, $zero, 0x1
/* 4B6A4 8005AEA4 0800A224 */  addiu      $v0, $a1, 0x8
/* 4B6A8 8005AEA8 100062AD */  sw         $v0, 0x10($t3)
/* 4B6AC 8005AEAC 0100023C */  lui        $v0, (0x10000 >> 16)
/* 4B6B0 8005AEB0 2168A201 */  addu       $t5, $t5, $v0
/* 4B6B4 8005AEB4 00E1023C */  lui        $v0, (0xE1000000 >> 16)
/* 4B6B8 8005AEB8 0300A3A0 */  sb         $v1, 0x3($a1)
/* 4B6BC 8005AEBC 0C000395 */  lhu        $v1, 0xC($t0)
/* 4B6C0 8005AEC0 0000A48C */  lw         $a0, 0x0($a1)
/* 4B6C4 8005AEC4 FF096330 */  andi       $v1, $v1, 0x9FF
/* 4B6C8 8005AEC8 25186200 */  or         $v1, $v1, $v0
/* 4B6CC 8005AECC 0400A3AC */  sw         $v1, 0x4($a1)
/* 4B6D0 8005AED0 0000E28C */  lw         $v0, 0x0($a3)
/* 4B6D4 8005AED4 24208A00 */  and        $a0, $a0, $t2
/* 4B6D8 8005AED8 24104900 */  and        $v0, $v0, $t1
/* 4B6DC 8005AEDC 25208200 */  or         $a0, $a0, $v0
/* 4B6E0 8005AEE0 0000A4AC */  sw         $a0, 0x0($a1)
/* 4B6E4 8005AEE4 0000E38C */  lw         $v1, 0x0($a3)
/* 4B6E8 8005AEE8 2428A900 */  and        $a1, $a1, $t1
/* 4B6EC 8005AEEC 24186A00 */  and        $v1, $v1, $t2
/* 4B6F0 8005AEF0 25186500 */  or         $v1, $v1, $a1
/* 4B6F4 8005AEF4 0000E3AC */  sw         $v1, 0x0($a3)
/* 4B6F8 8005AEF8 28008285 */  lh         $v0, 0x28($t4)
/* 4B6FC 8005AEFC 00000000 */  nop
/* 4B700 8005AF00 2A10C200 */  slt        $v0, $a2, $v0
/* 4B704 8005AF04 B3FF4014 */  bnez       $v0, .L8005ADD4
/* 4B708 8005AF08 10000825 */   addiu     $t0, $t0, 0x10
.L8005AF0C:
/* 4B70C 8005AF0C 0800E003 */  jr         $ra
/* 4B710 8005AF10 0800BD27 */   addiu     $sp, $sp, 0x8
.size func_8005AD78, . - func_8005AD78

glabel func_8005AF14
/* 4B714 8005AF14 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 4B718 8005AF18 1000B0AF */  sw         $s0, 0x10($sp)
/* 4B71C 8005AF1C 2180C000 */  addu       $s0, $a2, $zero
/* 4B720 8005AF20 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 4B724 8005AF24 1800B2AF */  sw         $s2, 0x18($sp)
/* 4B728 8005AF28 1400B1AF */  sw         $s1, 0x14($sp)
/* 4B72C 8005AF2C 0000918C */  lw         $s1, 0x0($a0)
/* 4B730 8005AF30 21200002 */  addu       $a0, $s0, $zero
/* 4B734 8005AF34 2190A000 */  addu       $s2, $a1, $zero
/* 4B738 8005AF38 4FFB000C */  jal        func_8003ED3C
/* 4B73C 8005AF3C 21280000 */   addu      $a1, $zero, $zero
/* 4B740 8005AF40 FF00063C */  lui        $a2, (0xFFFFFF >> 16)
/* 4B744 8005AF44 FFFFC634 */  ori        $a2, $a2, (0xFFFFFF & 0xFFFF)
/* 4B748 8005AF48 0780053C */  lui        $a1, %hi(D_80077260)
/* 4B74C 8005AF4C 6072A524 */  addiu      $a1, $a1, %lo(D_80077260)
/* 4B750 8005AF50 21200002 */  addu       $a0, $s0, $zero
/* 4B754 8005AF54 0400A284 */  lh         $v0, 0x4($a1)
/* 4B758 8005AF58 00FF083C */  lui        $t0, (0xFF000000 >> 16)
/* 4B75C 8005AF5C 80100200 */  sll        $v0, $v0, 2
/* 4B760 8005AF60 21102202 */  addu       $v0, $s1, $v0
/* 4B764 8005AF64 1C00478C */  lw         $a3, 0x1C($v0)
/* 4B768 8005AF68 0000028E */  lw         $v0, 0x0($s0)
/* 4B76C 8005AF6C 0000E38C */  lw         $v1, 0x0($a3)
/* 4B770 8005AF70 24104600 */  and        $v0, $v0, $a2
/* 4B774 8005AF74 24186800 */  and        $v1, $v1, $t0
/* 4B778 8005AF78 25186200 */  or         $v1, $v1, $v0
/* 4B77C 8005AF7C 0000E3AC */  sw         $v1, 0x0($a3)
/* 4B780 8005AF80 0400A284 */  lh         $v0, 0x4($a1)
/* 4B784 8005AF84 21284002 */  addu       $a1, $s2, $zero
/* 4B788 8005AF88 0000038E */  lw         $v1, 0x0($s0)
/* 4B78C 8005AF8C 80100200 */  sll        $v0, $v0, 2
/* 4B790 8005AF90 21882202 */  addu       $s1, $s1, $v0
/* 4B794 8005AF94 1400228E */  lw         $v0, 0x14($s1)
/* 4B798 8005AF98 24186800 */  and        $v1, $v1, $t0
/* 4B79C 8005AF9C 24104600 */  and        $v0, $v0, $a2
/* 4B7A0 8005AFA0 25186200 */  or         $v1, $v1, $v0
/* 4B7A4 8005AFA4 4FFB000C */  jal        func_8003ED3C
/* 4B7A8 8005AFA8 000003AE */   sw        $v1, 0x0($s0)
/* 4B7AC 8005AFAC 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 4B7B0 8005AFB0 1800B28F */  lw         $s2, 0x18($sp)
/* 4B7B4 8005AFB4 1400B18F */  lw         $s1, 0x14($sp)
/* 4B7B8 8005AFB8 1000B08F */  lw         $s0, 0x10($sp)
/* 4B7BC 8005AFBC 0800E003 */  jr         $ra
/* 4B7C0 8005AFC0 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8005AF14, . - func_8005AF14

glabel func_8005AFC4
/* 4B7C4 8005AFC4 B0FFBD27 */  addiu      $sp, $sp, -0x50
/* 4B7C8 8005AFC8 4400B7AF */  sw         $s7, 0x44($sp)
/* 4B7CC 8005AFCC 21B8A000 */  addu       $s7, $a1, $zero
/* 4B7D0 8005AFD0 4000B6AF */  sw         $s6, 0x40($sp)
/* 4B7D4 8005AFD4 21B0C000 */  addu       $s6, $a2, $zero
/* 4B7D8 8005AFD8 4800BFAF */  sw         $ra, 0x48($sp)
/* 4B7DC 8005AFDC 3C00B5AF */  sw         $s5, 0x3C($sp)
/* 4B7E0 8005AFE0 3800B4AF */  sw         $s4, 0x38($sp)
/* 4B7E4 8005AFE4 3400B3AF */  sw         $s3, 0x34($sp)
/* 4B7E8 8005AFE8 3000B2AF */  sw         $s2, 0x30($sp)
/* 4B7EC 8005AFEC 2C00B1AF */  sw         $s1, 0x2C($sp)
/* 4B7F0 8005AFF0 2800B0AF */  sw         $s0, 0x28($sp)
/* 4B7F4 8005AFF4 0400E586 */  lh         $a1, 0x4($s7)
/* 4B7F8 8005AFF8 0400C386 */  lh         $v1, 0x4($s6)
/* 4B7FC 8005AFFC 002B0500 */  sll        $a1, $a1, 12
/* 4B800 8005B000 1A00A300 */  div        $zero, $a1, $v1
/* 4B804 8005B004 0000948C */  lw         $s4, 0x0($a0)
/* 4B808 8005B008 00000000 */  nop
/* 4B80C 8005B00C 0000828E */  lw         $v0, 0x0($s4)
/* 4B810 8005B010 00000000 */  nop
/* 4B814 8005B014 0000468C */  lw         $a2, 0x0($v0)
/* 4B818 8005B018 12280000 */  mflo       $a1
/* 4B81C 8005B01C 02006014 */  bnez       $v1, .L8005B028
/* 4B820 8005B020 00000000 */   nop
/* 4B824 8005B024 CD010000 */  break      0, 7
.L8005B028:
/* 4B828 8005B028 0600E286 */  lh         $v0, 0x6($s7)
/* 4B82C 8005B02C 0600C386 */  lh         $v1, 0x6($s6)
/* 4B830 8005B030 00130200 */  sll        $v0, $v0, 12
/* 4B834 8005B034 1A004300 */  div        $zero, $v0, $v1
/* 4B838 8005B038 2198A000 */  addu       $s3, $a1, $zero
/* 4B83C 8005B03C 12100000 */  mflo       $v0
/* 4B840 8005B040 02006014 */  bnez       $v1, .L8005B04C
/* 4B844 8005B044 00000000 */   nop
/* 4B848 8005B048 CD010000 */  break      0, 7
.L8005B04C:
/* 4B84C 8005B04C 28008486 */  lh         $a0, 0x28($s4)
/* 4B850 8005B050 00000000 */  nop
/* 4B854 8005B054 3C008018 */  blez       $a0, .L8005B148
/* 4B858 8005B058 21904000 */   addu      $s2, $v0, $zero
/* 4B85C 8005B05C 0100153C */  lui        $s5, (0x10000 >> 16)
/* 4B860 8005B060 0400D124 */  addiu      $s1, $a2, 0x4
/* 4B864 8005B064 2180C000 */  addu       $s0, $a2, $zero
.L8005B068:
/* 4B868 8005B068 00000586 */  lh         $a1, 0x0($s0)
/* 4B86C 8005B06C 00000000 */  nop
/* 4B870 8005B070 1800B300 */  mult       $a1, $s3
/* 4B874 8005B074 0000E896 */  lhu        $t0, 0x0($s7)
/* 4B878 8005B078 12280000 */  mflo       $a1
/* 4B87C 8005B07C 032B0500 */  sra        $a1, $a1, 12
/* 4B880 8005B080 21280501 */  addu       $a1, $t0, $a1
/* 4B884 8005B084 1800A5A7 */  sh         $a1, 0x18($sp)
/* 4B888 8005B088 02000486 */  lh         $a0, 0x2($s0)
/* 4B88C 8005B08C 00000000 */  nop
/* 4B890 8005B090 18009200 */  mult       $a0, $s2
/* 4B894 8005B094 0200E796 */  lhu        $a3, 0x2($s7)
/* 4B898 8005B098 12200000 */  mflo       $a0
/* 4B89C 8005B09C 03230400 */  sra        $a0, $a0, 12
/* 4B8A0 8005B0A0 2120E400 */  addu       $a0, $a3, $a0
/* 4B8A4 8005B0A4 1A00A4A7 */  sh         $a0, 0x1A($sp)
/* 4B8A8 8005B0A8 00000286 */  lh         $v0, 0x0($s0)
/* 4B8AC 8005B0AC 08000396 */  lhu        $v1, 0x8($s0)
/* 4B8B0 8005B0B0 00000000 */  nop
/* 4B8B4 8005B0B4 21104300 */  addu       $v0, $v0, $v1
/* 4B8B8 8005B0B8 01004224 */  addiu      $v0, $v0, 0x1
/* 4B8BC 8005B0BC 18005300 */  mult       $v0, $s3
/* 4B8C0 8005B0C0 1E00A4A7 */  sh         $a0, 0x1E($sp)
/* 4B8C4 8005B0C4 2000A5A7 */  sh         $a1, 0x20($sp)
/* 4B8C8 8005B0C8 12100000 */  mflo       $v0
/* 4B8CC 8005B0CC 03130200 */  sra        $v0, $v0, 12
/* 4B8D0 8005B0D0 21400201 */  addu       $t0, $t0, $v0
/* 4B8D4 8005B0D4 1C00A8A7 */  sh         $t0, 0x1C($sp)
/* 4B8D8 8005B0D8 02000386 */  lh         $v1, 0x2($s0)
/* 4B8DC 8005B0DC 0A000296 */  lhu        $v0, 0xA($s0)
/* 4B8E0 8005B0E0 00000000 */  nop
/* 4B8E4 8005B0E4 21186200 */  addu       $v1, $v1, $v0
/* 4B8E8 8005B0E8 01006324 */  addiu      $v1, $v1, 0x1
/* 4B8EC 8005B0EC 18007200 */  mult       $v1, $s2
/* 4B8F0 8005B0F0 21302002 */  addu       $a2, $s1, $zero
/* 4B8F4 8005B0F4 10003126 */  addiu      $s1, $s1, 0x10
/* 4B8F8 8005B0F8 1800A427 */  addiu      $a0, $sp, 0x18
/* 4B8FC 8005B0FC 2128C002 */  addu       $a1, $s6, $zero
/* 4B900 8005B100 0800C28E */  lw         $v0, 0x8($s6)
/* 4B904 8005B104 10001026 */  addiu      $s0, $s0, 0x10
/* 4B908 8005B108 2400A8A7 */  sh         $t0, 0x24($sp)
/* 4B90C 8005B10C 1000A2AF */  sw         $v0, 0x10($sp)
/* 4B910 8005B110 12180000 */  mflo       $v1
/* 4B914 8005B114 031B0300 */  sra        $v1, $v1, 12
/* 4B918 8005B118 2138E300 */  addu       $a3, $a3, $v1
/* 4B91C 8005B11C 2200A7A7 */  sh         $a3, 0x22($sp)
/* 4B920 8005B120 2600A7A7 */  sh         $a3, 0x26($sp)
/* 4B924 8005B124 C841010C */  jal        func_80050720
/* 4B928 8005B128 21380000 */   addu      $a3, $zero, $zero
/* 4B92C 8005B12C 2120A002 */  addu       $a0, $s5, $zero
/* 4B930 8005B130 0100023C */  lui        $v0, (0x10000 >> 16)
/* 4B934 8005B134 28008386 */  lh         $v1, 0x28($s4)
/* 4B938 8005B138 03240400 */  sra        $a0, $a0, 16
/* 4B93C 8005B13C 2A188300 */  slt        $v1, $a0, $v1
/* 4B940 8005B140 C9FF6014 */  bnez       $v1, .L8005B068
/* 4B944 8005B144 21A8A202 */   addu      $s5, $s5, $v0
.L8005B148:
/* 4B948 8005B148 4800BF8F */  lw         $ra, 0x48($sp)
/* 4B94C 8005B14C 4400B78F */  lw         $s7, 0x44($sp)
/* 4B950 8005B150 4000B68F */  lw         $s6, 0x40($sp)
/* 4B954 8005B154 3C00B58F */  lw         $s5, 0x3C($sp)
/* 4B958 8005B158 3800B48F */  lw         $s4, 0x38($sp)
/* 4B95C 8005B15C 3400B38F */  lw         $s3, 0x34($sp)
/* 4B960 8005B160 3000B28F */  lw         $s2, 0x30($sp)
/* 4B964 8005B164 2C00B18F */  lw         $s1, 0x2C($sp)
/* 4B968 8005B168 2800B08F */  lw         $s0, 0x28($sp)
/* 4B96C 8005B16C 0800E003 */  jr         $ra
/* 4B970 8005B170 5000BD27 */   addiu     $sp, $sp, 0x50
.size func_8005AFC4, . - func_8005AFC4

glabel func_8005B174
/* 4B974 8005B174 0000898C */  lw         $t1, 0x0($a0)
/* 4B978 8005B178 0400A014 */  bnez       $a1, .L8005B18C
/* 4B97C 8005B17C F8FFBD27 */   addiu     $sp, $sp, -0x8
/* 4B980 8005B180 8000023C */  lui        $v0, (0x808080 >> 16)
/* 4B984 8005B184 646C0108 */  j          .L8005B190
/* 4B988 8005B188 80804234 */   ori       $v0, $v0, (0x808080 & 0xFFFF)
.L8005B18C:
/* 4B98C 8005B18C 0000A28C */  lw         $v0, 0x0($a1)
.L8005B190:
/* 4B990 8005B190 00000000 */  nop
/* 4B994 8005B194 0000A2AF */  sw         $v0, 0x0($sp)
/* 4B998 8005B198 04002725 */  addiu      $a3, $t1, 0x4
/* 4B99C 8005B19C 21180000 */  addu       $v1, $zero, $zero
.L8005B1A0:
/* 4B9A0 8005B1A0 28002285 */  lh         $v0, 0x28($t1)
/* 4B9A4 8005B1A4 01006A24 */  addiu      $t2, $v1, 0x1
/* 4B9A8 8005B1A8 18004018 */  blez       $v0, .L8005B20C
/* 4B9AC 8005B1AC 0800EB24 */   addiu     $t3, $a3, 0x8
/* 4B9B0 8005B1B0 0100083C */  lui        $t0, (0x10000 >> 16)
/* 4B9B4 8005B1B4 21300000 */  addu       $a2, $zero, $zero
/* 4B9B8 8005B1B8 01000C3C */  lui        $t4, (0x10000 >> 16)
.L8005B1BC:
/* 4B9BC 8005B1BC 21280001 */  addu       $a1, $t0, $zero
/* 4B9C0 8005B1C0 21400C01 */  addu       $t0, $t0, $t4
/* 4B9C4 8005B1C4 032C0500 */  sra        $a1, $a1, 16
/* 4B9C8 8005B1C8 0000E28C */  lw         $v0, 0x0($a3)
/* 4B9CC 8005B1CC 0000A493 */  lbu        $a0, 0x0($sp)
/* 4B9D0 8005B1D0 2110C200 */  addu       $v0, $a2, $v0
/* 4B9D4 8005B1D4 040044A0 */  sb         $a0, 0x4($v0)
/* 4B9D8 8005B1D8 0000E38C */  lw         $v1, 0x0($a3)
/* 4B9DC 8005B1DC 0100A293 */  lbu        $v0, 0x1($sp)
/* 4B9E0 8005B1E0 2118C300 */  addu       $v1, $a2, $v1
/* 4B9E4 8005B1E4 050062A0 */  sb         $v0, 0x5($v1)
/* 4B9E8 8005B1E8 0000E38C */  lw         $v1, 0x0($a3)
/* 4B9EC 8005B1EC 0200A493 */  lbu        $a0, 0x2($sp)
/* 4B9F0 8005B1F0 2118C300 */  addu       $v1, $a2, $v1
/* 4B9F4 8005B1F4 060064A0 */  sb         $a0, 0x6($v1)
/* 4B9F8 8005B1F8 28002285 */  lh         $v0, 0x28($t1)
/* 4B9FC 8005B1FC 00000000 */  nop
/* 4BA00 8005B200 2A10A200 */  slt        $v0, $a1, $v0
/* 4BA04 8005B204 EDFF4014 */  bnez       $v0, .L8005B1BC
/* 4BA08 8005B208 1400C624 */   addiu     $a2, $a2, 0x14
.L8005B20C:
/* 4BA0C 8005B20C 00140A00 */  sll        $v0, $t2, 16
/* 4BA10 8005B210 031C0200 */  sra        $v1, $v0, 16
/* 4BA14 8005B214 02006228 */  slti       $v0, $v1, 0x2
/* 4BA18 8005B218 E1FF4014 */  bnez       $v0, .L8005B1A0
/* 4BA1C 8005B21C 21386001 */   addu      $a3, $t3, $zero
/* 4BA20 8005B220 0800E003 */  jr         $ra
/* 4BA24 8005B224 0800BD27 */   addiu     $sp, $sp, 0x8
.size func_8005B174, . - func_8005B174

glabel func_8005B228
/* 4BA28 8005B228 0000858C */  lw         $a1, 0x0($a0)
/* 4BA2C 8005B22C 00000000 */  nop
/* 4BA30 8005B230 2800A484 */  lh         $a0, 0x28($a1)
/* 4BA34 8005B234 2A00A384 */  lh         $v1, 0x2A($a1)
/* 4BA38 8005B238 80100400 */  sll        $v0, $a0, 2
/* 4BA3C 8005B23C 21104400 */  addu       $v0, $v0, $a0
/* 4BA40 8005B240 80100200 */  sll        $v0, $v0, 2
/* 4BA44 8005B244 C0180300 */  sll        $v1, $v1, 3
/* 4BA48 8005B248 21104300 */  addu       $v0, $v0, $v1
/* 4BA4C 8005B24C 0800E003 */  jr         $ra
/* 4BA50 8005B250 40100200 */   sll       $v0, $v0, 1
.size func_8005B228, . - func_8005B228

glabel func_8005B254
/* 4BA54 8005B254 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 4BA58 8005B258 2170C000 */  addu       $t6, $a2, $zero
/* 4BA5C 8005B25C 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 4BA60 8005B260 1800B2AF */  sw         $s2, 0x18($sp)
/* 4BA64 8005B264 1400B1AF */  sw         $s1, 0x14($sp)
/* 4BA68 8005B268 1000B0AF */  sw         $s0, 0x10($sp)
/* 4BA6C 8005B26C 0000908C */  lw         $s0, 0x0($a0)
/* 4BA70 8005B270 01000F3C */  lui        $t7, (0x10000 >> 16)
/* 4BA74 8005B274 04000926 */  addiu      $t1, $s0, 0x4
/* 4BA78 8005B278 21882001 */  addu       $s1, $t1, $zero
/* 4BA7C 8005B27C 28000386 */  lh         $v1, 0x28($s0)
/* 4BA80 8005B280 0000028E */  lw         $v0, 0x0($s0)
/* 4BA84 8005B284 80380300 */  sll        $a3, $v1, 2
/* 4BA88 8005B288 0000528C */  lw         $s2, 0x0($v0)
/* 4BA8C 8005B28C 2138E300 */  addu       $a3, $a3, $v1
/* 4BA90 8005B290 040005AE */  sw         $a1, 0x4($s0)
/* 4BA94 8005B294 0000828C */  lw         $v0, 0x0($a0)
/* 4BA98 8005B298 80180700 */  sll        $v1, $a3, 2
/* 4BA9C 8005B29C 28004884 */  lh         $t0, 0x28($v0)
/* 4BAA0 8005B2A0 2A004684 */  lh         $a2, 0x2A($v0)
/* 4BAA4 8005B2A4 2118A300 */  addu       $v1, $a1, $v1
/* 4BAA8 8005B2A8 080003AE */  sw         $v1, 0x8($s0)
/* 4BAAC 8005B2AC 80100800 */  sll        $v0, $t0, 2
/* 4BAB0 8005B2B0 21104800 */  addu       $v0, $v0, $t0
/* 4BAB4 8005B2B4 80100200 */  sll        $v0, $v0, 2
/* 4BAB8 8005B2B8 2110A200 */  addu       $v0, $a1, $v0
/* 4BABC 8005B2BC C0300600 */  sll        $a2, $a2, 3
/* 4BAC0 8005B2C0 21104600 */  addu       $v0, $v0, $a2
/* 4BAC4 8005B2C4 0C0002AE */  sw         $v0, 0xC($s0)
/* 4BAC8 8005B2C8 0000838C */  lw         $v1, 0x0($a0)
/* 4BACC 8005B2CC C0380700 */  sll        $a3, $a3, 3
/* 4BAD0 8005B2D0 2A006284 */  lh         $v0, 0x2A($v1)
/* 4BAD4 8005B2D4 2128A700 */  addu       $a1, $a1, $a3
/* 4BAD8 8005B2D8 C0100200 */  sll        $v0, $v0, 3
/* 4BADC 8005B2DC 2128A200 */  addu       $a1, $a1, $v0
/* 4BAE0 8005B2E0 100005AE */  sw         $a1, 0x10($s0)
.L8005B2E4:
/* 4BAE4 8005B2E4 21500000 */  addu       $t2, $zero, $zero
/* 4BAE8 8005B2E8 28000286 */  lh         $v0, 0x28($s0)
/* 4BAEC 8005B2EC 00000000 */  nop
/* 4BAF0 8005B2F0 5E004018 */  blez       $v0, .L8005B46C
/* 4BAF4 8005B2F4 21300000 */   addu      $a2, $zero, $zero
/* 4BAF8 8005B2F8 01000D24 */  addiu      $t5, $zero, 0x1
/* 4BAFC 8005B2FC 00E10C3C */  lui        $t4, (0xE1000000 >> 16)
/* 4BB00 8005B300 01000B3C */  lui        $t3, (0x10000 >> 16)
/* 4BB04 8005B304 21384002 */  addu       $a3, $s2, $zero
/* 4BB08 8005B308 21400000 */  addu       $t0, $zero, $zero
.L8005B30C:
/* 4BB0C 8005B30C 0B00C014 */  bnez       $a2, .L8005B33C
/* 4BB10 8005B310 C0280A00 */   sll       $a1, $t2, 3
/* 4BB14 8005B314 01004225 */  addiu      $v0, $t2, 0x1
/* 4BB18 8005B318 00140200 */  sll        $v0, $v0, 16
/* 4BB1C 8005B31C 0400238D */  lw         $v1, 0x4($t1)
/* 4BB20 8005B320 03540200 */  sra        $t2, $v0, 16
/* 4BB24 8005B324 2118A300 */  addu       $v1, $a1, $v1
/* 4BB28 8005B328 03006DA0 */  sb         $t5, 0x3($v1)
/* 4BB2C 8005B32C 0400248D */  lw         $a0, 0x4($t1)
/* 4BB30 8005B330 0C004296 */  lhu        $v0, 0xC($s2)
/* 4BB34 8005B334 DC6C0108 */  j          .L8005B370
/* 4BB38 8005B338 2128A400 */   addu      $a1, $a1, $a0
.L8005B33C:
/* 4BB3C 8005B33C 0C00E394 */  lhu        $v1, 0xC($a3)
/* 4BB40 8005B340 FCFFE294 */  lhu        $v0, -0x4($a3)
/* 4BB44 8005B344 00000000 */  nop
/* 4BB48 8005B348 0C006210 */  beq        $v1, $v0, .L8005B37C
/* 4BB4C 8005B34C 01004225 */   addiu     $v0, $t2, 0x1
/* 4BB50 8005B350 00140200 */  sll        $v0, $v0, 16
/* 4BB54 8005B354 0400238D */  lw         $v1, 0x4($t1)
/* 4BB58 8005B358 03540200 */  sra        $t2, $v0, 16
/* 4BB5C 8005B35C 2118A300 */  addu       $v1, $a1, $v1
/* 4BB60 8005B360 03006DA0 */  sb         $t5, 0x3($v1)
/* 4BB64 8005B364 0400248D */  lw         $a0, 0x4($t1)
/* 4BB68 8005B368 0C00E294 */  lhu        $v0, 0xC($a3)
/* 4BB6C 8005B36C 2128A400 */  addu       $a1, $a1, $a0
.L8005B370:
/* 4BB70 8005B370 FF094230 */  andi       $v0, $v0, 0x9FF
/* 4BB74 8005B374 25104C00 */  or         $v0, $v0, $t4
/* 4BB78 8005B378 0400A2AC */  sw         $v0, 0x4($a1)
.L8005B37C:
/* 4BB7C 8005B37C 21286001 */  addu       $a1, $t3, $zero
/* 4BB80 8005B380 03340500 */  sra        $a2, $a1, 16
/* 4BB84 8005B384 0000228D */  lw         $v0, 0x0($t1)
/* 4BB88 8005B388 0000C491 */  lbu        $a0, 0x0($t6)
/* 4BB8C 8005B38C 21100201 */  addu       $v0, $t0, $v0
/* 4BB90 8005B390 040044A0 */  sb         $a0, 0x4($v0)
/* 4BB94 8005B394 0000238D */  lw         $v1, 0x0($t1)
/* 4BB98 8005B398 0100C491 */  lbu        $a0, 0x1($t6)
/* 4BB9C 8005B39C 21180301 */  addu       $v1, $t0, $v1
/* 4BBA0 8005B3A0 050064A0 */  sb         $a0, 0x5($v1)
/* 4BBA4 8005B3A4 0000228D */  lw         $v0, 0x0($t1)
/* 4BBA8 8005B3A8 0200C391 */  lbu        $v1, 0x2($t6)
/* 4BBAC 8005B3AC 21100201 */  addu       $v0, $t0, $v0
/* 4BBB0 8005B3B0 060043A0 */  sb         $v1, 0x6($v0)
/* 4BBB4 8005B3B4 0100023C */  lui        $v0, (0x10000 >> 16)
/* 4BBB8 8005B3B8 21586201 */  addu       $t3, $t3, $v0
/* 4BBBC 8005B3BC 0000238D */  lw         $v1, 0x0($t1)
/* 4BBC0 8005B3C0 04000224 */  addiu      $v0, $zero, 0x4
/* 4BBC4 8005B3C4 21180301 */  addu       $v1, $t0, $v1
/* 4BBC8 8005B3C8 030062A0 */  sb         $v0, 0x3($v1)
/* 4BBCC 8005B3CC 0000248D */  lw         $a0, 0x0($t1)
/* 4BBD0 8005B3D0 64000224 */  addiu      $v0, $zero, 0x64
/* 4BBD4 8005B3D4 21200401 */  addu       $a0, $t0, $a0
/* 4BBD8 8005B3D8 070082A0 */  sb         $v0, 0x7($a0)
/* 4BBDC 8005B3DC 0000238D */  lw         $v1, 0x0($t1)
/* 4BBE0 8005B3E0 0000E494 */  lhu        $a0, 0x0($a3)
/* 4BBE4 8005B3E4 21180301 */  addu       $v1, $t0, $v1
/* 4BBE8 8005B3E8 080064A4 */  sh         $a0, 0x8($v1)
/* 4BBEC 8005B3EC 0000228D */  lw         $v0, 0x0($t1)
/* 4BBF0 8005B3F0 0200E494 */  lhu        $a0, 0x2($a3)
/* 4BBF4 8005B3F4 21100201 */  addu       $v0, $t0, $v0
/* 4BBF8 8005B3F8 0A0044A4 */  sh         $a0, 0xA($v0)
/* 4BBFC 8005B3FC 0000238D */  lw         $v1, 0x0($t1)
/* 4BC00 8005B400 0400E490 */  lbu        $a0, 0x4($a3)
/* 4BC04 8005B404 21180301 */  addu       $v1, $t0, $v1
/* 4BC08 8005B408 0C0064A0 */  sb         $a0, 0xC($v1)
/* 4BC0C 8005B40C 0000228D */  lw         $v0, 0x0($t1)
/* 4BC10 8005B410 0500E490 */  lbu        $a0, 0x5($a3)
/* 4BC14 8005B414 21100201 */  addu       $v0, $t0, $v0
/* 4BC18 8005B418 0D0044A0 */  sb         $a0, 0xD($v0)
/* 4BC1C 8005B41C 0000238D */  lw         $v1, 0x0($t1)
/* 4BC20 8005B420 0600E294 */  lhu        $v0, 0x6($a3)
/* 4BC24 8005B424 21180301 */  addu       $v1, $t0, $v1
/* 4BC28 8005B428 0E0062A4 */  sh         $v0, 0xE($v1)
/* 4BC2C 8005B42C 0000248D */  lw         $a0, 0x0($t1)
/* 4BC30 8005B430 0800E294 */  lhu        $v0, 0x8($a3)
/* 4BC34 8005B434 21200401 */  addu       $a0, $t0, $a0
/* 4BC38 8005B438 01004224 */  addiu      $v0, $v0, 0x1
/* 4BC3C 8005B43C 100082A4 */  sh         $v0, 0x10($a0)
/* 4BC40 8005B440 0000258D */  lw         $a1, 0x0($t1)
/* 4BC44 8005B444 0A00E394 */  lhu        $v1, 0xA($a3)
/* 4BC48 8005B448 1000E724 */  addiu      $a3, $a3, 0x10
/* 4BC4C 8005B44C 21280501 */  addu       $a1, $t0, $a1
/* 4BC50 8005B450 01006324 */  addiu      $v1, $v1, 0x1
/* 4BC54 8005B454 1200A3A4 */  sh         $v1, 0x12($a1)
/* 4BC58 8005B458 28000286 */  lh         $v0, 0x28($s0)
/* 4BC5C 8005B45C 00000000 */  nop
/* 4BC60 8005B460 2A10C200 */  slt        $v0, $a2, $v0
/* 4BC64 8005B464 A9FF4014 */  bnez       $v0, .L8005B30C
/* 4BC68 8005B468 14000825 */   addiu     $t0, $t0, 0x14
.L8005B46C:
/* 4BC6C 8005B46C 2110E001 */  addu       $v0, $t7, $zero
/* 4BC70 8005B470 0100033C */  lui        $v1, (0x10000 >> 16)
/* 4BC74 8005B474 2178E301 */  addu       $t7, $t7, $v1
/* 4BC78 8005B478 035C0200 */  sra        $t3, $v0, 16
/* 4BC7C 8005B47C 02006229 */  slti       $v0, $t3, 0x2
/* 4BC80 8005B480 98FF4014 */  bnez       $v0, .L8005B2E4
/* 4BC84 8005B484 08002925 */   addiu     $t1, $t1, 0x8
/* 4BC88 8005B488 21482002 */  addu       $t1, $s1, $zero
/* 4BC8C 8005B48C 21580000 */  addu       $t3, $zero, $zero
.L8005B490:
/* 4BC90 8005B490 21300000 */  addu       $a2, $zero, $zero
/* 4BC94 8005B494 01007925 */  addiu      $t9, $t3, 0x1
/* 4BC98 8005B498 00002A8D */  lw         $t2, 0x0($t1)
/* 4BC9C 8005B49C 28000286 */  lh         $v0, 0x28($s0)
/* 4BCA0 8005B4A0 0400278D */  lw         $a3, 0x4($t1)
/* 4BCA4 8005B4A4 3F004018 */  blez       $v0, .L8005B5A4
/* 4BCA8 8005B4A8 08003125 */   addiu     $s1, $t1, 0x8
/* 4BCAC 8005B4AC 80100B00 */  sll        $v0, $t3, 2
/* 4BCB0 8005B4B0 14000326 */  addiu      $v1, $s0, 0x14
/* 4BCB4 8005B4B4 21C06200 */  addu       $t8, $v1, $v0
/* 4BCB8 8005B4B8 1C000426 */  addiu      $a0, $s0, 0x1C
/* 4BCBC 8005B4BC 21688200 */  addu       $t5, $a0, $v0
/* 4BCC0 8005B4C0 FF00083C */  lui        $t0, (0xFFFFFF >> 16)
/* 4BCC4 8005B4C4 FFFF0835 */  ori        $t0, $t0, (0xFFFFFF & 0xFFFF)
/* 4BCC8 8005B4C8 00FF0E3C */  lui        $t6, (0xFF000000 >> 16)
/* 4BCCC 8005B4CC 01000F3C */  lui        $t7, (0x10000 >> 16)
/* 4BCD0 8005B4D0 21604002 */  addu       $t4, $s2, $zero
.L8005B4D4:
/* 4BCD4 8005B4D4 0500C014 */  bnez       $a2, .L8005B4EC
/* 4BCD8 8005B4D8 80480B00 */   sll       $t1, $t3, 2
/* 4BCDC 8005B4DC 1C000526 */  addiu      $a1, $s0, 0x1C
/* 4BCE0 8005B4E0 0000A7AD */  sw         $a3, 0x0($t5)
/* 4BCE4 8005B4E4 506D0108 */  j          .L8005B540
/* 4BCE8 8005B4E8 000007AF */   sw        $a3, 0x0($t8)
.L8005B4EC:
/* 4BCEC 8005B4EC 0C008395 */  lhu        $v1, 0xC($t4)
/* 4BCF0 8005B4F0 FCFF8295 */  lhu        $v0, -0x4($t4)
/* 4BCF4 8005B4F4 00000000 */  nop
/* 4BCF8 8005B4F8 11006210 */  beq        $v1, $v0, .L8005B540
/* 4BCFC 8005B4FC 1C000526 */   addiu     $a1, $s0, 0x1C
/* 4BD00 8005B500 0800E724 */  addiu      $a3, $a3, 0x8
/* 4BD04 8005B504 0000A48D */  lw         $a0, 0x0($t5)
/* 4BD08 8005B508 0000E28C */  lw         $v0, 0x0($a3)
/* 4BD0C 8005B50C 0000838C */  lw         $v1, 0x0($a0)
/* 4BD10 8005B510 24104E00 */  and        $v0, $v0, $t6
/* 4BD14 8005B514 24186800 */  and        $v1, $v1, $t0
/* 4BD18 8005B518 25104300 */  or         $v0, $v0, $v1
/* 4BD1C 8005B51C 0000E2AC */  sw         $v0, 0x0($a3)
/* 4BD20 8005B520 0000A48D */  lw         $a0, 0x0($t5)
/* 4BD24 8005B524 00000000 */  nop
/* 4BD28 8005B528 0000828C */  lw         $v0, 0x0($a0)
/* 4BD2C 8005B52C 2418E800 */  and        $v1, $a3, $t0
/* 4BD30 8005B530 24104E00 */  and        $v0, $v0, $t6
/* 4BD34 8005B534 25104300 */  or         $v0, $v0, $v1
/* 4BD38 8005B538 000082AC */  sw         $v0, 0x0($a0)
/* 4BD3C 8005B53C 0000A7AD */  sw         $a3, 0x0($t5)
.L8005B540:
/* 4BD40 8005B540 2130E001 */  addu       $a2, $t7, $zero
/* 4BD44 8005B544 0100023C */  lui        $v0, (0x10000 >> 16)
/* 4BD48 8005B548 2178E201 */  addu       $t7, $t7, $v0
/* 4BD4C 8005B54C 2128A900 */  addu       $a1, $a1, $t1
/* 4BD50 8005B550 10008C25 */  addiu      $t4, $t4, 0x10
/* 4BD54 8005B554 0000A48C */  lw         $a0, 0x0($a1)
/* 4BD58 8005B558 0000428D */  lw         $v0, 0x0($t2)
/* 4BD5C 8005B55C 0000838C */  lw         $v1, 0x0($a0)
/* 4BD60 8005B560 24104E00 */  and        $v0, $v0, $t6
/* 4BD64 8005B564 24186800 */  and        $v1, $v1, $t0
/* 4BD68 8005B568 25104300 */  or         $v0, $v0, $v1
/* 4BD6C 8005B56C 000042AD */  sw         $v0, 0x0($t2)
/* 4BD70 8005B570 0000A48C */  lw         $a0, 0x0($a1)
/* 4BD74 8005B574 03340600 */  sra        $a2, $a2, 16
/* 4BD78 8005B578 0000828C */  lw         $v0, 0x0($a0)
/* 4BD7C 8005B57C 24184801 */  and        $v1, $t2, $t0
/* 4BD80 8005B580 24104E00 */  and        $v0, $v0, $t6
/* 4BD84 8005B584 25104300 */  or         $v0, $v0, $v1
/* 4BD88 8005B588 000082AC */  sw         $v0, 0x0($a0)
/* 4BD8C 8005B58C 0000AAAC */  sw         $t2, 0x0($a1)
/* 4BD90 8005B590 28000286 */  lh         $v0, 0x28($s0)
/* 4BD94 8005B594 00000000 */  nop
/* 4BD98 8005B598 2A10C200 */  slt        $v0, $a2, $v0
/* 4BD9C 8005B59C CDFF4014 */  bnez       $v0, .L8005B4D4
/* 4BDA0 8005B5A0 14004A25 */   addiu     $t2, $t2, 0x14
.L8005B5A4:
/* 4BDA4 8005B5A4 00141900 */  sll        $v0, $t9, 16
/* 4BDA8 8005B5A8 035C0200 */  sra        $t3, $v0, 16
/* 4BDAC 8005B5AC 02006229 */  slti       $v0, $t3, 0x2
/* 4BDB0 8005B5B0 B7FF4014 */  bnez       $v0, .L8005B490
/* 4BDB4 8005B5B4 21482002 */   addu      $t1, $s1, $zero
/* 4BDB8 8005B5B8 0000048E */  lw         $a0, 0x0($s0)
/* 4BDBC 8005B5BC 9AC5000C */  jal        func_80031668
/* 4BDC0 8005B5C0 00000000 */   nop
/* 4BDC4 8005B5C4 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 4BDC8 8005B5C8 1800B28F */  lw         $s2, 0x18($sp)
/* 4BDCC 8005B5CC 1400B18F */  lw         $s1, 0x14($sp)
/* 4BDD0 8005B5D0 000000AE */  sw         $zero, 0x0($s0)
/* 4BDD4 8005B5D4 1000B08F */  lw         $s0, 0x10($sp)
/* 4BDD8 8005B5D8 0800E003 */  jr         $ra
/* 4BDDC 8005B5DC 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8005B254, . - func_8005B254

glabel func_8005B5E0
/* 4BDE0 8005B5E0 C0FFBD27 */  addiu      $sp, $sp, -0x40
/* 4BDE4 8005B5E4 3000B2AF */  sw         $s2, 0x30($sp)
/* 4BDE8 8005B5E8 2190A000 */  addu       $s2, $a1, $zero
/* 4BDEC 8005B5EC 21204002 */  addu       $a0, $s2, $zero
/* 4BDF0 8005B5F0 2800B0AF */  sw         $s0, 0x28($sp)
/* 4BDF4 8005B5F4 2180E000 */  addu       $s0, $a3, $zero
/* 4BDF8 8005B5F8 3C00BFAF */  sw         $ra, 0x3C($sp)
/* 4BDFC 8005B5FC 3800B4AF */  sw         $s4, 0x38($sp)
/* 4BE00 8005B600 3400B3AF */  sw         $s3, 0x34($sp)
/* 4BE04 8005B604 2C00B1AF */  sw         $s1, 0x2C($sp)
/* 4BE08 8005B608 0000028E */  lw         $v0, 0x0($s0)
/* 4BE0C 8005B60C 00000000 */  nop
/* 4BE10 8005B610 0000518C */  lw         $s1, 0x0($v0)
/* 4BE14 8005B614 A8F1000C */  jal        func_8003C6A0
/* 4BE18 8005B618 2128C000 */   addu      $a1, $a2, $zero
/* 4BE1C 8005B61C 21984000 */  addu       $s3, $v0, $zero
/* 4BE20 8005B620 65006012 */  beqz       $s3, .L8005B7B8
/* 4BE24 8005B624 00000000 */   nop
/* 4BE28 8005B628 0000648E */  lw         $a0, 0x0($s3)
/* 4BE2C 8005B62C A0F3000C */  jal        func_8003CE80
/* 4BE30 8005B630 21A00000 */   addu      $s4, $zero, $zero
/* 4BE34 8005B634 0000648E */  lw         $a0, 0x0($s3)
/* 4BE38 8005B638 83F3000C */  jal        func_8003CE0C
/* 4BE3C 8005B63C 00000000 */   nop
/* 4BE40 8005B640 86F3000C */  jal        func_8003CE18
/* 4BE44 8005B644 1000A427 */   addiu     $a0, $sp, 0x10
/* 4BE48 8005B648 28000386 */  lh         $v1, 0x28($s0)
/* 4BE4C 8005B64C 0C004496 */  lhu        $a0, 0xC($s2)
/* 4BE50 8005B650 00190300 */  sll        $v1, $v1, 4
/* 4BE54 8005B654 21187100 */  addu       $v1, $v1, $s1
/* 4BE58 8005B658 000064A4 */  sh         $a0, 0x0($v1)
/* 4BE5C 8005B65C 28000286 */  lh         $v0, 0x28($s0)
/* 4BE60 8005B660 0E004396 */  lhu        $v1, 0xE($s2)
/* 4BE64 8005B664 00110200 */  sll        $v0, $v0, 4
/* 4BE68 8005B668 21105100 */  addu       $v0, $v0, $s1
/* 4BE6C 8005B66C 020043A4 */  sh         $v1, 0x2($v0)
/* 4BE70 8005B670 1000A48F */  lw         $a0, 0x10($sp)
/* 4BE74 8005B674 1C00B28F */  lw         $s2, 0x1C($sp)
/* 4BE78 8005B678 03008430 */  andi       $a0, $a0, 0x3
/* 4BE7C 8005B67C 05008010 */  beqz       $a0, .L8005B694
/* 4BE80 8005B680 01000224 */   addiu     $v0, $zero, 0x1
/* 4BE84 8005B684 05008210 */  beq        $a0, $v0, .L8005B69C
/* 4BE88 8005B688 21280000 */   addu      $a1, $zero, $zero
/* 4BE8C 8005B68C A96D0108 */  j          .L8005B6A4
/* 4BE90 8005B690 00000000 */   nop
.L8005B694:
/* 4BE94 8005B694 A86D0108 */  j          .L8005B6A0
/* 4BE98 8005B698 02001424 */   addiu     $s4, $zero, 0x2
.L8005B69C:
/* 4BE9C 8005B69C 01001424 */  addiu      $s4, $zero, 0x1
.L8005B6A0:
/* 4BEA0 8005B6A0 21280000 */  addu       $a1, $zero, $zero
.L8005B6A4:
/* 4BEA4 8005B6A4 1000A48F */  lw         $a0, 0x10($sp)
/* 4BEA8 8005B6A8 02004796 */  lhu        $a3, 0x2($s2)
/* 4BEAC 8005B6AC 00004696 */  lhu        $a2, 0x0($s2)
/* 4BEB0 8005B6B0 03008430 */  andi       $a0, $a0, 0x3
/* 4BEB4 8005B6B4 0001E730 */  andi       $a3, $a3, 0x100
/* 4BEB8 8005B6B8 003C0700 */  sll        $a3, $a3, 16
/* 4BEBC 8005B6BC C003C630 */  andi       $a2, $a2, 0x3C0
/* 4BEC0 8005B6C0 9570000C */  jal        GetTPage
/* 4BEC4 8005B6C4 023C0700 */   srl       $a3, $a3, 16
/* 4BEC8 8005B6C8 28000386 */  lh         $v1, 0x28($s0)
/* 4BECC 8005B6CC 00000000 */  nop
/* 4BED0 8005B6D0 00190300 */  sll        $v1, $v1, 4
/* 4BED4 8005B6D4 21187100 */  addu       $v1, $v1, $s1
/* 4BED8 8005B6D8 0C0062A4 */  sh         $v0, 0xC($v1)
/* 4BEDC 8005B6DC 1400A28F */  lw         $v0, 0x14($sp)
/* 4BEE0 8005B6E0 00000000 */  nop
/* 4BEE4 8005B6E4 00004484 */  lh         $a0, 0x0($v0)
/* 4BEE8 8005B6E8 02004584 */  lh         $a1, 0x2($v0)
/* 4BEEC 8005B6EC A570000C */  jal        GetClut
/* 4BEF0 8005B6F0 00000000 */   nop
/* 4BEF4 8005B6F4 28000386 */  lh         $v1, 0x28($s0)
/* 4BEF8 8005B6F8 00000000 */  nop
/* 4BEFC 8005B6FC 00190300 */  sll        $v1, $v1, 4
/* 4BF00 8005B700 21187100 */  addu       $v1, $v1, $s1
/* 4BF04 8005B704 060062A4 */  sh         $v0, 0x6($v1)
/* 4BF08 8005B708 28000486 */  lh         $a0, 0x28($s0)
/* 4BF0C 8005B70C 00004296 */  lhu        $v0, 0x0($s2)
/* 4BF10 8005B710 00210400 */  sll        $a0, $a0, 4
/* 4BF14 8005B714 21209100 */  addu       $a0, $a0, $s1
/* 4BF18 8005B718 3F004230 */  andi       $v0, $v0, 0x3F
/* 4BF1C 8005B71C 04108202 */  sllv       $v0, $v0, $s4
/* 4BF20 8005B720 040082A0 */  sb         $v0, 0x4($a0)
/* 4BF24 8005B724 28000386 */  lh         $v1, 0x28($s0)
/* 4BF28 8005B728 02004292 */  lbu        $v0, 0x2($s2)
/* 4BF2C 8005B72C 00190300 */  sll        $v1, $v1, 4
/* 4BF30 8005B730 21187100 */  addu       $v1, $v1, $s1
/* 4BF34 8005B734 050062A0 */  sb         $v0, 0x5($v1)
/* 4BF38 8005B738 28000486 */  lh         $a0, 0x28($s0)
/* 4BF3C 8005B73C 04004286 */  lh         $v0, 0x4($s2)
/* 4BF40 8005B740 00210400 */  sll        $a0, $a0, 4
/* 4BF44 8005B744 21209100 */  addu       $a0, $a0, $s1
/* 4BF48 8005B748 04108202 */  sllv       $v0, $v0, $s4
/* 4BF4C 8005B74C FFFF4224 */  addiu      $v0, $v0, -0x1
/* 4BF50 8005B750 080082A4 */  sh         $v0, 0x8($a0)
/* 4BF54 8005B754 28000386 */  lh         $v1, 0x28($s0)
/* 4BF58 8005B758 06004296 */  lhu        $v0, 0x6($s2)
/* 4BF5C 8005B75C 00190300 */  sll        $v1, $v1, 4
/* 4BF60 8005B760 21187100 */  addu       $v1, $v1, $s1
/* 4BF64 8005B764 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 4BF68 8005B768 0A0062A4 */  sh         $v0, 0xA($v1)
/* 4BF6C 8005B76C 28000286 */  lh         $v0, 0x28($s0)
/* 4BF70 8005B770 00000000 */  nop
/* 4BF74 8005B774 07004010 */  beqz       $v0, .L8005B794
/* 4BF78 8005B778 00110200 */   sll       $v0, $v0, 4
/* 4BF7C 8005B77C 21105100 */  addu       $v0, $v0, $s1
/* 4BF80 8005B780 FCFF4494 */  lhu        $a0, -0x4($v0)
/* 4BF84 8005B784 0C004394 */  lhu        $v1, 0xC($v0)
/* 4BF88 8005B788 00000000 */  nop
/* 4BF8C 8005B78C 05008310 */  beq        $a0, $v1, .L8005B7A4
/* 4BF90 8005B790 00000000 */   nop
.L8005B794:
/* 4BF94 8005B794 2A000296 */  lhu        $v0, 0x2A($s0)
/* 4BF98 8005B798 00000000 */  nop
/* 4BF9C 8005B79C 01004224 */  addiu      $v0, $v0, 0x1
/* 4BFA0 8005B7A0 2A0002A6 */  sh         $v0, 0x2A($s0)
.L8005B7A4:
/* 4BFA4 8005B7A4 28000296 */  lhu        $v0, 0x28($s0)
/* 4BFA8 8005B7A8 21206002 */  addu       $a0, $s3, $zero
/* 4BFAC 8005B7AC 01004224 */  addiu      $v0, $v0, 0x1
/* 4BFB0 8005B7B0 C0F1000C */  jal        func_8003C700
/* 4BFB4 8005B7B4 280002A6 */   sh        $v0, 0x28($s0)
.L8005B7B8:
/* 4BFB8 8005B7B8 3C00BF8F */  lw         $ra, 0x3C($sp)
/* 4BFBC 8005B7BC 3800B48F */  lw         $s4, 0x38($sp)
/* 4BFC0 8005B7C0 3400B38F */  lw         $s3, 0x34($sp)
/* 4BFC4 8005B7C4 3000B28F */  lw         $s2, 0x30($sp)
/* 4BFC8 8005B7C8 2C00B18F */  lw         $s1, 0x2C($sp)
/* 4BFCC 8005B7CC 2800B08F */  lw         $s0, 0x28($sp)
/* 4BFD0 8005B7D0 0800E003 */  jr         $ra
/* 4BFD4 8005B7D4 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_8005B5E0, . - func_8005B5E0

glabel func_8005B7D8
/* 4BFD8 8005B7D8 2140A000 */  addu       $t0, $a1, $zero
/* 4BFDC 8005B7DC 21588000 */  addu       $t3, $a0, $zero
/* 4BFE0 8005B7E0 04006925 */  addiu      $t1, $t3, 0x4
/* 4BFE4 8005B7E4 02006295 */  lhu        $v0, 0x2($t3)
/* 4BFE8 8005B7E8 00000000 */  nop
/* 4BFEC 8005B7EC 12004010 */  beqz       $v0, .L8005B838
/* 4BFF0 8005B7F0 21500000 */   addu      $t2, $zero, $zero
.L8005B7F4:
/* 4BFF4 8005B7F4 0000258D */  lw         $a1, 0x0($t1)
/* 4BFF8 8005B7F8 00000295 */  lhu        $v0, 0x0($t0)
/* 4BFFC 8005B7FC 21282501 */  addu       $a1, $t1, $a1
/* 4C000 8005B800 25104700 */  or         $v0, $v0, $a3
/* 4C004 8005B804 0000A2AC */  sw         $v0, 0x0($a1)
/* 4C008 8005B808 02000395 */  lhu        $v1, 0x2($t0)
/* 4C00C 8005B80C 01004A25 */  addiu      $t2, $t2, 0x1
/* 4C010 8005B810 25186600 */  or         $v1, $v1, $a2
/* 4C014 8005B814 0400A3AC */  sw         $v1, 0x4($a1)
/* 4C018 8005B818 04000495 */  lhu        $a0, 0x4($t0)
/* 4C01C 8005B81C 04002925 */  addiu      $t1, $t1, 0x4
/* 4C020 8005B820 0800A4A4 */  sh         $a0, 0x8($a1)
/* 4C024 8005B824 02006295 */  lhu        $v0, 0x2($t3)
/* 4C028 8005B828 00000000 */  nop
/* 4C02C 8005B82C 2A104201 */  slt        $v0, $t2, $v0
/* 4C030 8005B830 F0FF4014 */  bnez       $v0, .L8005B7F4
/* 4C034 8005B834 08000825 */   addiu     $t0, $t0, 0x8
.L8005B838:
/* 4C038 8005B838 0800E003 */  jr         $ra
/* 4C03C 8005B83C 21100001 */   addu      $v0, $t0, $zero
.size func_8005B7D8, . - func_8005B7D8

glabel func_8005B840
/* 4C040 8005B840 2140A000 */  addu       $t0, $a1, $zero
/* 4C044 8005B844 21588000 */  addu       $t3, $a0, $zero
/* 4C048 8005B848 04006925 */  addiu      $t1, $t3, 0x4
/* 4C04C 8005B84C 02006295 */  lhu        $v0, 0x2($t3)
/* 4C050 8005B850 00000000 */  nop
/* 4C054 8005B854 12004010 */  beqz       $v0, .L8005B8A0
/* 4C058 8005B858 21500000 */   addu      $t2, $zero, $zero
.L8005B85C:
/* 4C05C 8005B85C 0000258D */  lw         $a1, 0x0($t1)
/* 4C060 8005B860 00000295 */  lhu        $v0, 0x0($t0)
/* 4C064 8005B864 21282501 */  addu       $a1, $t1, $a1
/* 4C068 8005B868 25104700 */  or         $v0, $v0, $a3
/* 4C06C 8005B86C 0000A2AC */  sw         $v0, 0x0($a1)
/* 4C070 8005B870 02000395 */  lhu        $v1, 0x2($t0)
/* 4C074 8005B874 01004A25 */  addiu      $t2, $t2, 0x1
/* 4C078 8005B878 25186600 */  or         $v1, $v1, $a2
/* 4C07C 8005B87C 0400A3AC */  sw         $v1, 0x4($a1)
/* 4C080 8005B880 0400048D */  lw         $a0, 0x4($t0)
/* 4C084 8005B884 04002925 */  addiu      $t1, $t1, 0x4
/* 4C088 8005B888 0800A4AC */  sw         $a0, 0x8($a1)
/* 4C08C 8005B88C 02006295 */  lhu        $v0, 0x2($t3)
/* 4C090 8005B890 00000000 */  nop
/* 4C094 8005B894 2A104201 */  slt        $v0, $t2, $v0
/* 4C098 8005B898 F0FF4014 */  bnez       $v0, .L8005B85C
/* 4C09C 8005B89C 08000825 */   addiu     $t0, $t0, 0x8
.L8005B8A0:
/* 4C0A0 8005B8A0 0800E003 */  jr         $ra
/* 4C0A4 8005B8A4 21100001 */   addu      $v0, $t0, $zero
.size func_8005B840, . - func_8005B840

glabel func_8005B8A8
/* 4C0A8 8005B8A8 2140A000 */  addu       $t0, $a1, $zero
/* 4C0AC 8005B8AC 21588000 */  addu       $t3, $a0, $zero
/* 4C0B0 8005B8B0 04006925 */  addiu      $t1, $t3, 0x4
/* 4C0B4 8005B8B4 02006295 */  lhu        $v0, 0x2($t3)
/* 4C0B8 8005B8B8 00000000 */  nop
/* 4C0BC 8005B8BC 15004010 */  beqz       $v0, .L8005B914
/* 4C0C0 8005B8C0 21500000 */   addu      $t2, $zero, $zero
.L8005B8C4:
/* 4C0C4 8005B8C4 0000258D */  lw         $a1, 0x0($t1)
/* 4C0C8 8005B8C8 00000395 */  lhu        $v1, 0x0($t0)
/* 4C0CC 8005B8CC 21282501 */  addu       $a1, $t1, $a1
/* 4C0D0 8005B8D0 25186700 */  or         $v1, $v1, $a3
/* 4C0D4 8005B8D4 0000A3AC */  sw         $v1, 0x0($a1)
/* 4C0D8 8005B8D8 02000295 */  lhu        $v0, 0x2($t0)
/* 4C0DC 8005B8DC 00000000 */  nop
/* 4C0E0 8005B8E0 25104600 */  or         $v0, $v0, $a2
/* 4C0E4 8005B8E4 0400A2AC */  sw         $v0, 0x4($a1)
/* 4C0E8 8005B8E8 04000395 */  lhu        $v1, 0x4($t0)
/* 4C0EC 8005B8EC 01004A25 */  addiu      $t2, $t2, 0x1
/* 4C0F0 8005B8F0 0800A3A4 */  sh         $v1, 0x8($a1)
/* 4C0F4 8005B8F4 06000495 */  lhu        $a0, 0x6($t0)
/* 4C0F8 8005B8F8 04002925 */  addiu      $t1, $t1, 0x4
/* 4C0FC 8005B8FC 0C00A4A4 */  sh         $a0, 0xC($a1)
/* 4C100 8005B900 02006295 */  lhu        $v0, 0x2($t3)
/* 4C104 8005B904 00000000 */  nop
/* 4C108 8005B908 2A104201 */  slt        $v0, $t2, $v0
/* 4C10C 8005B90C EDFF4014 */  bnez       $v0, .L8005B8C4
/* 4C110 8005B910 08000825 */   addiu     $t0, $t0, 0x8
.L8005B914:
/* 4C114 8005B914 0800E003 */  jr         $ra
/* 4C118 8005B918 21100001 */   addu      $v0, $t0, $zero
.size func_8005B8A8, . - func_8005B8A8

glabel func_8005B91C
/* 4C11C 8005B91C D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 4C120 8005B920 0780023C */  lui        $v0, %hi(D_80072AE4)
/* 4C124 8005B924 40180400 */  sll        $v1, $a0, 1
/* 4C128 8005B928 21186400 */  addu       $v1, $v1, $a0
/* 4C12C 8005B92C E42A448C */  lw         $a0, %lo(D_80072AE4)($v0)
/* 4C130 8005B930 C0180300 */  sll        $v1, $v1, 3
/* 4C134 8005B934 2000BFAF */  sw         $ra, 0x20($sp)
/* 4C138 8005B938 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 4C13C 8005B93C 1800B2AF */  sw         $s2, 0x18($sp)
/* 4C140 8005B940 1400B1AF */  sw         $s1, 0x14($sp)
/* 4C144 8005B944 21208300 */  addu       $a0, $a0, $v1
/* 4C148 8005B948 0E008010 */  beqz       $a0, .L8005B984
/* 4C14C 8005B94C 1000B0AF */   sw        $s0, 0x10($sp)
/* 4C150 8005B950 00008384 */  lh         $v1, 0x0($a0)
/* 4C154 8005B954 02000224 */  addiu      $v0, $zero, 0x2
/* 4C158 8005B958 41006214 */  bne        $v1, $v0, .L8005BA60
/* 4C15C 8005B95C 21100000 */   addu      $v0, $zero, $zero
/* 4C160 8005B960 0400838C */  lw         $v1, 0x4($a0)
/* 4C164 8005B964 00000000 */  nop
/* 4C168 8005B968 0000638C */  lw         $v1, 0x0($v1)
/* 4C16C 8005B96C 00000000 */  nop
/* 4C170 8005B970 1E006284 */  lh         $v0, 0x1E($v1)
/* 4C174 8005B974 00000000 */  nop
/* 4C178 8005B978 2B10A200 */  sltu       $v0, $a1, $v0
/* 4C17C 8005B97C 03004014 */  bnez       $v0, .L8005B98C
/* 4C180 8005B980 00000000 */   nop
.L8005B984:
/* 4C184 8005B984 986E0108 */  j          .L8005BA60
/* 4C188 8005B988 21100000 */   addu      $v0, $zero, $zero
.L8005B98C:
/* 4C18C 8005B98C 4000628C */  lw         $v0, 0x40($v1)
/* 4C190 8005B990 00000000 */  nop
/* 4C194 8005B994 21106200 */  addu       $v0, $v1, $v0
/* 4C198 8005B998 40180500 */  sll        $v1, $a1, 1
/* 4C19C 8005B99C 21186500 */  addu       $v1, $v1, $a1
/* 4C1A0 8005B9A0 80180300 */  sll        $v1, $v1, 2
/* 4C1A4 8005B9A4 21284300 */  addu       $a1, $v0, $v1
/* 4C1A8 8005B9A8 0200A484 */  lh         $a0, 0x2($a1)
/* 4C1AC 8005B9AC 00000000 */  nop
/* 4C1B0 8005B9B0 2B008610 */  beq        $a0, $a2, .L8005BA60
/* 4C1B4 8005B9B4 01000224 */   addiu     $v0, $zero, 0x1
/* 4C1B8 8005B9B8 0000A284 */  lh         $v0, 0x0($a1)
/* 4C1BC 8005B9BC 00000000 */  nop
/* 4C1C0 8005B9C0 2B10C200 */  sltu       $v0, $a2, $v0
/* 4C1C4 8005B9C4 26004010 */  beqz       $v0, .L8005BA60
/* 4C1C8 8005B9C8 21100000 */   addu      $v0, $zero, $zero
/* 4C1CC 8005B9CC 0400A38C */  lw         $v1, 0x4($a1)
/* 4C1D0 8005B9D0 0800A28C */  lw         $v0, 0x8($a1)
/* 4C1D4 8005B9D4 0200A6A4 */  sh         $a2, 0x2($a1)
/* 4C1D8 8005B9D8 2180A300 */  addu       $s0, $a1, $v1
/* 4C1DC 8005B9DC 2110A200 */  addu       $v0, $a1, $v0
/* 4C1E0 8005B9E0 C0180600 */  sll        $v1, $a2, 3
/* 4C1E4 8005B9E4 21104300 */  addu       $v0, $v0, $v1
/* 4C1E8 8005B9E8 0400448C */  lw         $a0, 0x4($v0)
/* 4C1EC 8005B9EC 00004394 */  lhu        $v1, 0x0($v0)
/* 4C1F0 8005B9F0 21284400 */  addu       $a1, $v0, $a0
/* 4C1F4 8005B9F4 00940300 */  sll        $s2, $v1, 16
/* 4C1F8 8005B9F8 02004494 */  lhu        $a0, 0x2($v0)
/* 4C1FC 8005B9FC 02000396 */  lhu        $v1, 0x2($s0)
/* 4C200 8005BA00 00000000 */  nop
/* 4C204 8005BA04 15006010 */  beqz       $v1, .L8005BA5C
/* 4C208 8005BA08 008C0400 */   sll       $s1, $a0, 16
/* 4C20C 8005BA0C 0780023C */  lui        $v0, %hi(D_8006A79C)
/* 4C210 8005BA10 9CA75324 */  addiu      $s3, $v0, %lo(D_8006A79C)
.L8005BA14:
/* 4C214 8005BA14 21200002 */  addu       $a0, $s0, $zero
/* 4C218 8005BA18 00000386 */  lh         $v1, 0x0($s0)
/* 4C21C 8005BA1C 21304002 */  addu       $a2, $s2, $zero
/* 4C220 8005BA20 80180300 */  sll        $v1, $v1, 2
/* 4C224 8005BA24 21187300 */  addu       $v1, $v1, $s3
/* 4C228 8005BA28 0000628C */  lw         $v0, 0x0($v1)
/* 4C22C 8005BA2C 00000000 */  nop
/* 4C230 8005BA30 09F84000 */  jalr       $v0
/* 4C234 8005BA34 21382002 */   addu      $a3, $s1, $zero
/* 4C238 8005BA38 02000396 */  lhu        $v1, 0x2($s0)
/* 4C23C 8005BA3C 00000000 */  nop
/* 4C240 8005BA40 80180300 */  sll        $v1, $v1, 2
/* 4C244 8005BA44 04006324 */  addiu      $v1, $v1, 0x4
/* 4C248 8005BA48 21800302 */  addu       $s0, $s0, $v1
/* 4C24C 8005BA4C 02000496 */  lhu        $a0, 0x2($s0)
/* 4C250 8005BA50 00000000 */  nop
/* 4C254 8005BA54 EFFF8014 */  bnez       $a0, .L8005BA14
/* 4C258 8005BA58 21284000 */   addu      $a1, $v0, $zero
.L8005BA5C:
/* 4C25C 8005BA5C 01000224 */  addiu      $v0, $zero, 0x1
.L8005BA60:
/* 4C260 8005BA60 2000BF8F */  lw         $ra, 0x20($sp)
/* 4C264 8005BA64 1C00B38F */  lw         $s3, 0x1C($sp)
/* 4C268 8005BA68 1800B28F */  lw         $s2, 0x18($sp)
/* 4C26C 8005BA6C 1400B18F */  lw         $s1, 0x14($sp)
/* 4C270 8005BA70 1000B08F */  lw         $s0, 0x10($sp)
/* 4C274 8005BA74 0800E003 */  jr         $ra
/* 4C278 8005BA78 2800BD27 */   addiu     $sp, $sp, 0x28
.size func_8005B91C, . - func_8005B91C
