.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel func_8003E5C4
/* 2EDC4 8003E5C4 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 2EDC8 8003E5C8 1800B2AF */  sw         $s2, 0x18($sp)
/* 2EDCC 8003E5CC 21908000 */  addu       $s2, $a0, $zero
/* 2EDD0 8003E5D0 0780023C */  lui        $v0, %hi(D_80077260)
/* 2EDD4 8003E5D4 60724524 */  addiu      $a1, $v0, %lo(D_80077260)
/* 2EDD8 8003E5D8 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 2EDDC 8003E5DC 1400B1AF */  sw         $s1, 0x14($sp)
/* 2EDE0 8003E5E0 1000B0AF */  sw         $s0, 0x10($sp)
/* 2EDE4 8003E5E4 E802A38C */  lw         $v1, 0x2E8($a1)
/* 2EDE8 8003E5E8 00000000 */  nop
/* 2EDEC 8003E5EC 44006010 */  beqz       $v1, .L8003E700
/* 2EDF0 8003E5F0 21884000 */   addu      $s1, $v0, $zero
/* 2EDF4 8003E5F4 6072248E */  lw         $a0, %lo(D_80077260)($s1)
/* 2EDF8 8003E5F8 00000000 */  nop
/* 2EDFC 8003E5FC 80008230 */  andi       $v0, $a0, 0x80
/* 2EE00 8003E600 3F004010 */  beqz       $v0, .L8003E700
/* 2EE04 8003E604 04008430 */   andi      $a0, $a0, 0x4
/* 2EE08 8003E608 0400A384 */  lh         $v1, 0x4($a1)
/* 2EE0C 8003E60C 00000000 */  nop
/* 2EE10 8003E610 80100300 */  sll        $v0, $v1, 2
/* 2EE14 8003E614 21104300 */  addu       $v0, $v0, $v1
/* 2EE18 8003E618 80100200 */  sll        $v0, $v0, 2
/* 2EE1C 8003E61C 21104300 */  addu       $v0, $v0, $v1
/* 2EE20 8003E620 00110200 */  sll        $v0, $v0, 4
/* 2EE24 8003E624 4800A324 */  addiu      $v1, $a1, 0x48
/* 2EE28 8003E628 08008010 */  beqz       $a0, .L8003E64C
/* 2EE2C 8003E62C 21104300 */   addu      $v0, $v0, $v1
/* 2EE30 8003E630 8DFC000C */  jal        func_8003F234
/* 2EE34 8003E634 60723026 */   addiu     $s0, $s1, %lo(D_80077260)
/* 2EE38 8003E638 6072228E */  lw         $v0, %lo(D_80077260)($s1)
/* 2EE3C 8003E63C FBFF0324 */  addiu      $v1, $zero, -0x5
/* 2EE40 8003E640 24104300 */  and        $v0, $v0, $v1
/* 2EE44 8003E644 96F90008 */  j          .L8003E658
/* 2EE48 8003E648 607222AE */   sw        $v0, %lo(D_80077260)($s1)
.L8003E64C:
/* 2EE4C 8003E64C BA58000C */  jal        PutDispEnv
/* 2EE50 8003E650 21204000 */   addu      $a0, $v0, $zero
/* 2EE54 8003E654 60723026 */  addiu      $s0, $s1, %lo(D_80077260)
.L8003E658:
/* 2EE58 8003E658 1000028E */  lw         $v0, 0x10($s0)
/* 2EE5C 8003E65C 1400038E */  lw         $v1, 0x14($s0)
/* 2EE60 8003E660 00000000 */  nop
/* 2EE64 8003E664 2B104300 */  sltu       $v0, $v0, $v1
/* 2EE68 8003E668 08004014 */  bnez       $v0, .L8003E68C
/* 2EE6C 8003E66C 0180043C */   lui       $a0, %hi(D_800123B4)
/* 2EE70 8003E670 B4238424 */  addiu      $a0, $a0, %lo(D_800123B4)
/* 2EE74 8003E674 0180053C */  lui        $a1, %hi(D_80012420)
/* 2EE78 8003E678 2024A524 */  addiu      $a1, $a1, %lo(D_80012420)
/* 2EE7C 8003E67C 9361000C */  jal        printf
/* 2EE80 8003E680 91010624 */   addiu     $a2, $zero, 0x191
/* 2EE84 8003E684 FFFF0324 */  addiu      $v1, $zero, -0x1
/* 2EE88 8003E688 010003AC */  sw         $v1, 0x1($zero)
.L8003E68C:
/* 2EE8C 8003E68C 19004012 */  beqz       $s2, .L8003E6F4
/* 2EE90 8003E690 60722326 */   addiu     $v1, $s1, %lo(D_80077260)
/* 2EE94 8003E694 6072228E */  lw         $v0, %lo(D_80077260)($s1)
/* 2EE98 8003E698 00000000 */  nop
/* 2EE9C 8003E69C 00014230 */  andi       $v0, $v0, 0x100
/* 2EEA0 8003E6A0 14004014 */  bnez       $v0, .L8003E6F4
/* 2EEA4 8003E6A4 00000000 */   nop
/* 2EEA8 8003E6A8 0C00048E */  lw         $a0, 0xC($s0)
/* 2EEAC 8003E6AC 2B58000C */  jal        DrawOTag
/* 2EEB0 8003E6B0 00000000 */   nop
/* 2EEB4 8003E6B4 04000296 */  lhu        $v0, 0x4($s0)
/* 2EEB8 8003E6B8 08000396 */  lhu        $v1, 0x8($s0)
/* 2EEBC 8003E6BC 01004238 */  xori       $v0, $v0, 0x1
/* 2EEC0 8003E6C0 01006324 */  addiu      $v1, $v1, 0x1
/* 2EEC4 8003E6C4 080003A6 */  sh         $v1, 0x8($s0)
/* 2EEC8 8003E6C8 001C0300 */  sll        $v1, $v1, 16
/* 2EECC 8003E6CC 040002A6 */  sh         $v0, 0x4($s0)
/* 2EED0 8003E6D0 0A000286 */  lh         $v0, 0xA($s0)
/* 2EED4 8003E6D4 031C0300 */  sra        $v1, $v1, 16
/* 2EED8 8003E6D8 2A186200 */  slt        $v1, $v1, $v0
/* 2EEDC 8003E6DC 05006014 */  bnez       $v1, .L8003E6F4
/* 2EEE0 8003E6E0 60722326 */   addiu     $v1, $s1, %lo(D_80077260)
/* 2EEE4 8003E6E4 06000296 */  lhu        $v0, 0x6($s0)
/* 2EEE8 8003E6E8 080000A6 */  sh         $zero, 0x8($s0)
/* 2EEEC 8003E6EC 01004238 */  xori       $v0, $v0, 0x1
/* 2EEF0 8003E6F0 060002A6 */  sh         $v0, 0x6($s0)
.L8003E6F4:
/* 2EEF4 8003E6F4 2800628C */  lw         $v0, 0x28($v1)
/* 2EEF8 8003E6F8 00000000 */  nop
/* 2EEFC 8003E6FC 240062AC */  sw         $v0, 0x24($v1)
.L8003E700:
/* 2EF00 8003E700 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 2EF04 8003E704 1800B28F */  lw         $s2, 0x18($sp)
/* 2EF08 8003E708 1400B18F */  lw         $s1, 0x14($sp)
/* 2EF0C 8003E70C 1000B08F */  lw         $s0, 0x10($sp)
/* 2EF10 8003E710 0800E003 */  jr         $ra
/* 2EF14 8003E714 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8003E5C4, . - func_8003E5C4

glabel func_8003E718
/* 2EF18 8003E718 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 2EF1C 8003E71C 1000BFAF */  sw         $ra, 0x10($sp)
/* 2EF20 8003E720 B5F8000C */  jal        func_8003E2D4
/* 2EF24 8003E724 00000000 */   nop
/* 2EF28 8003E728 67F9000C */  jal        func_8003E59C
/* 2EF2C 8003E72C 00000000 */   nop
/* 2EF30 8003E730 AE56000C */  jal        DrawSync
/* 2EF34 8003E734 03000424 */   addiu     $a0, $zero, 0x3
/* 2EF38 8003E738 71F9000C */  jal        func_8003E5C4
/* 2EF3C 8003E73C 01000424 */   addiu     $a0, $zero, 0x1
/* 2EF40 8003E740 1000BF8F */  lw         $ra, 0x10($sp)
/* 2EF44 8003E744 00000000 */  nop
/* 2EF48 8003E748 0800E003 */  jr         $ra
/* 2EF4C 8003E74C 1800BD27 */   addiu     $sp, $sp, 0x18
.size func_8003E718, . - func_8003E718

glabel func_8003E750
/* 2EF50 8003E750 0780053C */  lui        $a1, %hi(D_80077260)
/* 2EF54 8003E754 6072A324 */  addiu      $v1, $a1, %lo(D_80077260)
/* 2EF58 8003E758 280064AC */  sw         $a0, 0x28($v1)
/* 2EF5C 8003E75C 6072A28C */  lw         $v0, %lo(D_80077260)($a1)
/* 2EF60 8003E760 F7FF0324 */  addiu      $v1, $zero, -0x9
/* 2EF64 8003E764 24104300 */  and        $v0, $v0, $v1
/* 2EF68 8003E768 30004234 */  ori        $v0, $v0, 0x30
/* 2EF6C 8003E76C 0800E003 */  jr         $ra
/* 2EF70 8003E770 6072A2AC */   sw        $v0, %lo(D_80077260)($a1)
.size func_8003E750, . - func_8003E750

glabel func_8003E774
/* 2EF74 8003E774 00240400 */  sll        $a0, $a0, 16
/* 2EF78 8003E778 03240400 */  sra        $a0, $a0, 16
/* 2EF7C 8003E77C 0780023C */  lui        $v0, %hi(D_80077260)
/* 2EF80 8003E780 01000324 */  addiu      $v1, $zero, 0x1
/* 2EF84 8003E784 03008310 */  beq        $a0, $v1, .L8003E794
/* 2EF88 8003E788 60724224 */   addiu     $v0, $v0, %lo(D_80077260)
/* 2EF8C 8003E78C 0800E003 */  jr         $ra
/* 2EF90 8003E790 180044A4 */   sh        $a0, 0x18($v0)
.L8003E794:
/* 2EF94 8003E794 0800E003 */  jr         $ra
/* 2EF98 8003E798 180040A4 */   sh        $zero, 0x18($v0)
.size func_8003E774, . - func_8003E774

glabel func_8003E79C
/* 2EF9C 8003E79C 0780023C */  lui        $v0, %hi(D_80077260)
/* 2EFA0 8003E7A0 60724224 */  addiu      $v0, $v0, %lo(D_80077260)
/* 2EFA4 8003E7A4 340044A0 */  sb         $a0, 0x34($v0)
/* 2EFA8 8003E7A8 350045A0 */  sb         $a1, 0x35($v0)
/* 2EFAC 8003E7AC 0800E003 */  jr         $ra
/* 2EFB0 8003E7B0 360046A0 */   sb        $a2, 0x36($v0)
.size func_8003E79C, . - func_8003E79C

glabel func_8003E7B4
/* 2EFB4 8003E7B4 07008010 */  beqz       $a0, .L8003E7D4
/* 2EFB8 8003E7B8 0780023C */   lui       $v0, %hi(D_80077260)
/* 2EFBC 8003E7BC 0780033C */  lui        $v1, %hi(D_80077260)
/* 2EFC0 8003E7C0 6072628C */  lw         $v0, %lo(D_80077260)($v1)
/* 2EFC4 8003E7C4 00000000 */  nop
/* 2EFC8 8003E7C8 02004234 */  ori        $v0, $v0, 0x2
/* 2EFCC 8003E7CC 0800E003 */  jr         $ra
/* 2EFD0 8003E7D0 607262AC */   sw        $v0, %lo(D_80077260)($v1)
.L8003E7D4:
/* 2EFD4 8003E7D4 6072438C */  lw         $v1, %lo(D_80077260)($v0)
/* 2EFD8 8003E7D8 FDFF0424 */  addiu      $a0, $zero, -0x3
/* 2EFDC 8003E7DC 24186400 */  and        $v1, $v1, $a0
/* 2EFE0 8003E7E0 0800E003 */  jr         $ra
/* 2EFE4 8003E7E4 607243AC */   sw        $v1, %lo(D_80077260)($v0)
.size func_8003E7B4, . - func_8003E7B4

glabel func_8003E7E8
/* 2EFE8 8003E7E8 0780023C */  lui        $v0, %hi(D_80077260)
/* 2EFEC 8003E7EC 60724224 */  addiu      $v0, $v0, %lo(D_80077260)
/* 2EFF0 8003E7F0 380044A0 */  sb         $a0, 0x38($v0)
/* 2EFF4 8003E7F4 390045A0 */  sb         $a1, 0x39($v0)
/* 2EFF8 8003E7F8 0800E003 */  jr         $ra
/* 2EFFC 8003E7FC 3A0046A0 */   sb        $a2, 0x3A($v0)
.size func_8003E7E8, . - func_8003E7E8

glabel func_8003E800
/* 2F000 8003E800 07008010 */  beqz       $a0, .L8003E820
/* 2F004 8003E804 0780023C */   lui       $v0, %hi(D_80077260)
/* 2F008 8003E808 0780033C */  lui        $v1, %hi(D_80077260)
/* 2F00C 8003E80C 6072628C */  lw         $v0, %lo(D_80077260)($v1)
/* 2F010 8003E810 00000000 */  nop
/* 2F014 8003E814 01004234 */  ori        $v0, $v0, 0x1
/* 2F018 8003E818 0800E003 */  jr         $ra
/* 2F01C 8003E81C 607262AC */   sw        $v0, %lo(D_80077260)($v1)
.L8003E820:
/* 2F020 8003E820 6072438C */  lw         $v1, %lo(D_80077260)($v0)
/* 2F024 8003E824 FEFF0424 */  addiu      $a0, $zero, -0x2
/* 2F028 8003E828 24186400 */  and        $v1, $v1, $a0
/* 2F02C 8003E82C 0800E003 */  jr         $ra
/* 2F030 8003E830 607243AC */   sw        $v1, %lo(D_80077260)($v0)
.size func_8003E800, . - func_8003E800

glabel func_8003E834
/* 2F034 8003E834 F0FFBD27 */  addiu      $sp, $sp, -0x10
/* 2F038 8003E838 0780053C */  lui        $a1, %hi(D_80077260)
/* 2F03C 8003E83C 6072A924 */  addiu      $t1, $a1, %lo(D_80077260)
/* 2F040 8003E840 FFFF8A30 */  andi       $t2, $a0, 0xFFFF
/* 2F044 8003E844 03004331 */  andi       $v1, $t2, 0x3
/* 2F048 8003E848 0C00B1AF */  sw         $s1, 0xC($sp)
/* 2F04C 8003E84C 0800B0AF */  sw         $s0, 0x8($sp)
/* 2F050 8003E850 3C002295 */  lhu        $v0, 0x3C($t1)
/* 2F054 8003E854 00000000 */  nop
/* 2F058 8003E858 27100200 */  nor        $v0, $zero, $v0
/* 2F05C 8003E85C 24204201 */  and        $a0, $t2, $v0
/* 2F060 8003E860 03000224 */  addiu      $v0, $zero, 0x3
/* 2F064 8003E864 A2006214 */  bne        $v1, $v0, .L8003EAF0
/* 2F068 8003E868 2188A000 */   addu      $s1, $a1, $zero
/* 2F06C 8003E86C 10008330 */  andi       $v1, $a0, 0x10
/* 2F070 8003E870 426B0A00 */  srl        $t5, $t2, 13
/* 2F074 8003E874 C27B0A00 */  srl        $t7, $t2, 15
/* 2F078 8003E878 82CB0A00 */  srl        $t9, $t2, 14
/* 2F07C 8003E87C 6072228E */  lw         $v0, %lo(D_80077260)($s1)
/* 2F080 8003E880 02C30A00 */  srl        $t8, $t2, 12
/* 2F084 8003E884 04004234 */  ori        $v0, $v0, 0x4
/* 2F088 8003E888 19006010 */  beqz       $v1, .L8003E8F0
/* 2F08C 8003E88C 607222AE */   sw        $v0, %lo(D_80077260)($s1)
/* 2F090 8003E890 CCCC083C */  lui        $t0, (0xCCCCCCCD >> 16)
/* 2F094 8003E894 CDCC0835 */  ori        $t0, $t0, (0xCCCCCCCD & 0xFFFF)
/* 2F098 8003E898 0180023C */  lui        $v0, %hi(D_800123FA)
/* 2F09C 8003E89C FA234724 */  addiu      $a3, $v0, %lo(D_800123FA)
/* 2F0A0 8003E8A0 E0010624 */  addiu      $a2, $zero, 0x1E0
/* 2F0A4 8003E8A4 21282001 */  addu       $a1, $t1, $zero
/* 2F0A8 8003E8A8 4000A48C */  lw         $a0, 0x40($a1)
/* 2F0AC 8003E8AC 00000000 */  nop
/* 2F0B0 8003E8B0 01008424 */  addiu      $a0, $a0, 0x1
.L8003E8B4:
/* 2F0B4 8003E8B4 19008800 */  multu      $a0, $t0
/* 2F0B8 8003E8B8 10180000 */  mfhi       $v1
/* 2F0BC 8003E8BC C2180300 */  srl        $v1, $v1, 3
/* 2F0C0 8003E8C0 80100300 */  sll        $v0, $v1, 2
/* 2F0C4 8003E8C4 21104300 */  addu       $v0, $v0, $v1
/* 2F0C8 8003E8C8 40100200 */  sll        $v0, $v0, 1
/* 2F0CC 8003E8CC 23208200 */  subu       $a0, $a0, $v0
/* 2F0D0 8003E8D0 80180400 */  sll        $v1, $a0, 2
/* 2F0D4 8003E8D4 21186700 */  addu       $v1, $v1, $a3
/* 2F0D8 8003E8D8 00006284 */  lh         $v0, 0x0($v1)
/* 2F0DC 8003E8DC 00000000 */  nop
/* 2F0E0 8003E8E0 F4FF4610 */  beq        $v0, $a2, .L8003E8B4
/* 2F0E4 8003E8E4 01008424 */   addiu     $a0, $a0, 0x1
/* 2F0E8 8003E8E8 FFFF8424 */  addiu      $a0, $a0, -0x1
/* 2F0EC 8003E8EC 4000A4AC */  sw         $a0, 0x40($a1)
.L8003E8F0:
/* 2F0F0 8003E8F0 60722526 */  addiu      $a1, $s1, %lo(D_80077260)
/* 2F0F4 8003E8F4 4400AC24 */  addiu      $t4, $a1, 0x44
/* 2F0F8 8003E8F8 21580000 */  addu       $t3, $zero, $zero
/* 2F0FC 8003E8FC 00041024 */  addiu      $s0, $zero, 0x400
/* 2F100 8003E900 2170A000 */  addu       $t6, $a1, $zero
/* 2F104 8003E904 2148A003 */  addu       $t1, $sp, $zero
/* 2F108 8003E908 0100A231 */  andi       $v0, $t5, 0x1
/* 2F10C 8003E90C 23104F00 */  subu       $v0, $v0, $t7
/* 2F110 8003E910 01002333 */  andi       $v1, $t9, 0x1
/* 2F114 8003E914 0000A2A7 */  sh         $v0, 0x0($sp)
/* 2F118 8003E918 01000233 */  andi       $v0, $t8, 0x1
/* 2F11C 8003E91C 23186200 */  subu       $v1, $v1, $v0
/* 2F120 8003E920 0180023C */  lui        $v0, %hi(D_800123F8)
/* 2F124 8003E924 4000A48C */  lw         $a0, 0x40($a1)
/* 2F128 8003E928 F8234224 */  addiu      $v0, $v0, %lo(D_800123F8)
/* 2F12C 8003E92C 0200A3A7 */  sh         $v1, 0x2($sp)
/* 2F130 8003E930 80200400 */  sll        $a0, $a0, 2
/* 2F134 8003E934 21688200 */  addu       $t5, $a0, $v0
.L8003E938:
/* 2F138 8003E938 07207001 */  srav       $a0, $s0, $t3
/* 2F13C 8003E93C 0000A595 */  lhu        $a1, 0x0($t5)
/* 2F140 8003E940 00002685 */  lh         $a2, 0x0($t1)
/* 2F144 8003E944 00008785 */  lh         $a3, 0x0($t4)
/* 2F148 8003E948 00008895 */  lhu        $t0, 0x0($t4)
/* 2F14C 8003E94C 00140500 */  sll        $v0, $a1, 16
/* 2F150 8003E950 031C0200 */  sra        $v1, $v0, 16
/* 2F154 8003E954 C2170200 */  srl        $v0, $v0, 31
/* 2F158 8003E958 21186200 */  addu       $v1, $v1, $v0
/* 2F15C 8003E95C 43180300 */  sra        $v1, $v1, 1
/* 2F160 8003E960 23208300 */  subu       $a0, $a0, $v1
/* 2F164 8003E964 10008424 */  addiu      $a0, $a0, 0x10
/* 2F168 8003E968 1800C285 */  lh         $v0, 0x18($t6)
/* 2F16C 8003E96C 00000000 */  nop
/* 2F170 8003E970 0A004010 */  beqz       $v0, .L8003E99C
/* 2F174 8003E974 F0FF6324 */   addiu     $v1, $v1, -0x10
/* 2F178 8003E978 1800C200 */  mult       $a2, $v0
/* 2F17C 8003E97C 12100000 */  mflo       $v0
/* 2F180 8003E980 C0100200 */  sll        $v0, $v0, 3
/* 2F184 8003E984 2110E200 */  addu       $v0, $a3, $v0
/* 2F188 8003E988 2A104300 */  slt        $v0, $v0, $v1
/* 2F18C 8003E98C 08004014 */  bnez       $v0, .L8003E9B0
/* 2F190 8003E990 001C0500 */   sll       $v1, $a1, 16
/* 2F194 8003E994 73FA0008 */  j          .L8003E9CC
/* 2F198 8003E998 00140800 */   sll       $v0, $t0, 16
.L8003E99C:
/* 2F19C 8003E99C C0100600 */  sll        $v0, $a2, 3
/* 2F1A0 8003E9A0 2110E200 */  addu       $v0, $a3, $v0
/* 2F1A4 8003E9A4 2A104300 */  slt        $v0, $v0, $v1
/* 2F1A8 8003E9A8 07004010 */  beqz       $v0, .L8003E9C8
/* 2F1AC 8003E9AC 001C0500 */   sll       $v1, $a1, 16
.L8003E9B0:
/* 2F1B0 8003E9B0 03140300 */  sra        $v0, $v1, 16
/* 2F1B4 8003E9B4 C21F0300 */  srl        $v1, $v1, 31
/* 2F1B8 8003E9B8 21104300 */  addu       $v0, $v0, $v1
/* 2F1BC 8003E9BC 43100200 */  sra        $v0, $v0, 1
/* 2F1C0 8003E9C0 7BFA0008 */  j          .L8003E9EC
/* 2F1C4 8003E9C4 F0FF4224 */   addiu     $v0, $v0, -0x10
.L8003E9C8:
/* 2F1C8 8003E9C8 00140800 */  sll        $v0, $t0, 16
.L8003E9CC:
/* 2F1CC 8003E9CC 03340200 */  sra        $a2, $v0, 16
/* 2F1D0 8003E9D0 1800C385 */  lh         $v1, 0x18($t6)
/* 2F1D4 8003E9D4 00002285 */  lh         $v0, 0x0($t1)
/* 2F1D8 8003E9D8 09006010 */  beqz       $v1, .L8003EA00
/* 2F1DC 8003E9DC 18004300 */   mult      $v0, $v1
/* 2F1E0 8003E9E0 12100000 */  mflo       $v0
/* 2F1E4 8003E9E4 C0100200 */  sll        $v0, $v0, 3
/* 2F1E8 8003E9E8 2110C200 */  addu       $v0, $a2, $v0
.L8003E9EC:
/* 2F1EC 8003E9EC 2A104400 */  slt        $v0, $v0, $a0
/* 2F1F0 8003E9F0 08004014 */  bnez       $v0, .L8003EA14
/* 2F1F4 8003E9F4 00140800 */   sll       $v0, $t0, 16
/* 2F1F8 8003E9F8 AEFA0008 */  j          .L8003EAB8
/* 2F1FC 8003E9FC 07107001 */   srav      $v0, $s0, $t3
.L8003EA00:
/* 2F200 8003EA00 C0100200 */  sll        $v0, $v0, 3
/* 2F204 8003EA04 2110C200 */  addu       $v0, $a2, $v0
/* 2F208 8003EA08 2A104400 */  slt        $v0, $v0, $a0
/* 2F20C 8003EA0C 29004010 */  beqz       $v0, .L8003EAB4
/* 2F210 8003EA10 00140800 */   sll       $v0, $t0, 16
.L8003EA14:
/* 2F214 8003EA14 03340200 */  sra        $a2, $v0, 16
/* 2F218 8003EA18 001C0500 */  sll        $v1, $a1, 16
/* 2F21C 8003EA1C 03140300 */  sra        $v0, $v1, 16
/* 2F220 8003EA20 C21F0300 */  srl        $v1, $v1, 31
/* 2F224 8003EA24 21104300 */  addu       $v0, $v0, $v1
/* 2F228 8003EA28 43100200 */  sra        $v0, $v0, 1
/* 2F22C 8003EA2C F0FF4424 */  addiu      $a0, $v0, -0x10
/* 2F230 8003EA30 1800C385 */  lh         $v1, 0x18($t6)
/* 2F234 8003EA34 00002285 */  lh         $v0, 0x0($t1)
/* 2F238 8003EA38 09006010 */  beqz       $v1, .L8003EA60
/* 2F23C 8003EA3C 18004300 */   mult      $v0, $v1
/* 2F240 8003EA40 12100000 */  mflo       $v0
/* 2F244 8003EA44 C0100200 */  sll        $v0, $v0, 3
/* 2F248 8003EA48 2110C200 */  addu       $v0, $a2, $v0
/* 2F24C 8003EA4C 2A104400 */  slt        $v0, $v0, $a0
/* 2F250 8003EA50 08004014 */  bnez       $v0, .L8003EA74
/* 2F254 8003EA54 00140500 */   sll       $v0, $a1, 16
/* 2F258 8003EA58 A4FA0008 */  j          .L8003EA90
/* 2F25C 8003EA5C 00140800 */   sll       $v0, $t0, 16
.L8003EA60:
/* 2F260 8003EA60 C0100200 */  sll        $v0, $v0, 3
/* 2F264 8003EA64 2110C200 */  addu       $v0, $a2, $v0
/* 2F268 8003EA68 2A104400 */  slt        $v0, $v0, $a0
/* 2F26C 8003EA6C 07004010 */  beqz       $v0, .L8003EA8C
/* 2F270 8003EA70 00140500 */   sll       $v0, $a1, 16
.L8003EA74:
/* 2F274 8003EA74 031C0200 */  sra        $v1, $v0, 16
/* 2F278 8003EA78 C2170200 */  srl        $v0, $v0, 31
/* 2F27C 8003EA7C 21186200 */  addu       $v1, $v1, $v0
/* 2F280 8003EA80 43180300 */  sra        $v1, $v1, 1
/* 2F284 8003EA84 B5FA0008 */  j          .L8003EAD4
/* 2F288 8003EA88 F0FF6224 */   addiu     $v0, $v1, -0x10
.L8003EA8C:
/* 2F28C 8003EA8C 00140800 */  sll        $v0, $t0, 16
.L8003EA90:
/* 2F290 8003EA90 03240200 */  sra        $a0, $v0, 16
/* 2F294 8003EA94 1800C385 */  lh         $v1, 0x18($t6)
/* 2F298 8003EA98 00002285 */  lh         $v0, 0x0($t1)
/* 2F29C 8003EA9C 02006010 */  beqz       $v1, .L8003EAA8
/* 2F2A0 8003EAA0 18004300 */   mult      $v0, $v1
/* 2F2A4 8003EAA4 12100000 */  mflo       $v0
.L8003EAA8:
/* 2F2A8 8003EAA8 C0100200 */  sll        $v0, $v0, 3
/* 2F2AC 8003EAAC B5FA0008 */  j          .L8003EAD4
/* 2F2B0 8003EAB0 21108200 */   addu      $v0, $a0, $v0
.L8003EAB4:
/* 2F2B4 8003EAB4 07107001 */  srav       $v0, $s0, $t3
.L8003EAB8:
/* 2F2B8 8003EAB8 001C0500 */  sll        $v1, $a1, 16
/* 2F2BC 8003EABC 03240300 */  sra        $a0, $v1, 16
/* 2F2C0 8003EAC0 C21F0300 */  srl        $v1, $v1, 31
/* 2F2C4 8003EAC4 21208300 */  addu       $a0, $a0, $v1
/* 2F2C8 8003EAC8 43200400 */  sra        $a0, $a0, 1
/* 2F2CC 8003EACC 23104400 */  subu       $v0, $v0, $a0
/* 2F2D0 8003EAD0 10004224 */  addiu      $v0, $v0, 0x10
.L8003EAD4:
/* 2F2D4 8003EAD4 000082A5 */  sh         $v0, 0x0($t4)
/* 2F2D8 8003EAD8 02008C25 */  addiu      $t4, $t4, 0x2
/* 2F2DC 8003EADC 0200AD25 */  addiu      $t5, $t5, 0x2
/* 2F2E0 8003EAE0 01006B25 */  addiu      $t3, $t3, 0x1
/* 2F2E4 8003EAE4 02006229 */  slti       $v0, $t3, 0x2
/* 2F2E8 8003EAE8 93FF4014 */  bnez       $v0, .L8003E938
/* 2F2EC 8003EAEC 02002925 */   addiu     $t1, $t1, 0x2
.L8003EAF0:
/* 2F2F0 8003EAF0 60722326 */  addiu      $v1, $s1, %lo(D_80077260)
/* 2F2F4 8003EAF4 6072228E */  lw         $v0, %lo(D_80077260)($s1)
/* 2F2F8 8003EAF8 0C00B18F */  lw         $s1, 0xC($sp)
/* 2F2FC 8003EAFC 0800B08F */  lw         $s0, 0x8($sp)
/* 2F300 8003EB00 3C006AA4 */  sh         $t2, 0x3C($v1)
/* 2F304 8003EB04 82100200 */  srl        $v0, $v0, 2
/* 2F308 8003EB08 01004230 */  andi       $v0, $v0, 0x1
/* 2F30C 8003EB0C 0800E003 */  jr         $ra
/* 2F310 8003EB10 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_8003E834, . - func_8003E834

glabel func_8003EB14
/* 2F314 8003EB14 0780053C */  lui        $a1, %hi(D_80077260)
/* 2F318 8003EB18 6072A824 */  addiu      $t0, $a1, %lo(D_80077260)
/* 2F31C 8003EB1C 2800038D */  lw         $v1, 0x28($t0)
/* 2F320 8003EB20 21308000 */  addu       $a2, $a0, $zero
/* 2F324 8003EB24 0180023C */  lui        $v0, %hi(D_800123F8)
/* 2F328 8003EB28 F8234224 */  addiu      $v0, $v0, %lo(D_800123F8)
/* 2F32C 8003EB2C 80180300 */  sll        $v1, $v1, 2
/* 2F330 8003EB30 1C00C010 */  beqz       $a2, .L8003EBA4
/* 2F334 8003EB34 21386200 */   addu      $a3, $v1, $v0
/* 2F338 8003EB38 0000C284 */  lh         $v0, 0x0($a2)
/* 2F33C 8003EB3C 0400C484 */  lh         $a0, 0x4($a2)
/* 2F340 8003EB40 0000E384 */  lh         $v1, 0x0($a3)
/* 2F344 8003EB44 21104400 */  addu       $v0, $v0, $a0
/* 2F348 8003EB48 2A186200 */  slt        $v1, $v1, $v0
/* 2F34C 8003EB4C 15006014 */  bnez       $v1, .L8003EBA4
/* 2F350 8003EB50 00000000 */   nop
/* 2F354 8003EB54 0200C284 */  lh         $v0, 0x2($a2)
/* 2F358 8003EB58 0600C484 */  lh         $a0, 0x6($a2)
/* 2F35C 8003EB5C 0200E384 */  lh         $v1, 0x2($a3)
/* 2F360 8003EB60 21104400 */  addu       $v0, $v0, $a0
/* 2F364 8003EB64 2A186200 */  slt        $v1, $v1, $v0
/* 2F368 8003EB68 0E006014 */  bnez       $v1, .L8003EBA4
/* 2F36C 8003EB6C 00000000 */   nop
/* 2F370 8003EB70 0300C288 */  lwl        $v0, 0x3($a2)
/* 2F374 8003EB74 0000C298 */  lwr        $v0, 0x0($a2)
/* 2F378 8003EB78 0700C388 */  lwl        $v1, 0x7($a2)
/* 2F37C 8003EB7C 0400C398 */  lwr        $v1, 0x4($a2)
/* 2F380 8003EB80 2F0002A9 */  swl        $v0, 0x2F($t0)
/* 2F384 8003EB84 2C0002B9 */  swr        $v0, 0x2C($t0)
/* 2F388 8003EB88 330003A9 */  swl        $v1, 0x33($t0)
/* 2F38C 8003EB8C 300003B9 */  swr        $v1, 0x30($t0)
/* 2F390 8003EB90 6072A28C */  lw         $v0, %lo(D_80077260)($a1)
/* 2F394 8003EB94 00000000 */  nop
/* 2F398 8003EB98 38004234 */  ori        $v0, $v0, 0x38
/* 2F39C 8003EB9C 0800E003 */  jr         $ra
/* 2F3A0 8003EBA0 6072A2AC */   sw        $v0, %lo(D_80077260)($a1)
.L8003EBA4:
/* 2F3A4 8003EBA4 6072A28C */  lw         $v0, %lo(D_80077260)($a1)
/* 2F3A8 8003EBA8 F7FF0324 */  addiu      $v1, $zero, -0x9
/* 2F3AC 8003EBAC 30004234 */  ori        $v0, $v0, 0x30
/* 2F3B0 8003EBB0 24104300 */  and        $v0, $v0, $v1
/* 2F3B4 8003EBB4 0800E003 */  jr         $ra
/* 2F3B8 8003EBB8 6072A2AC */   sw        $v0, %lo(D_80077260)($a1)
.size func_8003EB14, . - func_8003EB14

glabel func_8003EBBC
/* 2F3BC 8003EBBC D0FFBD27 */  addiu      $sp, $sp, -0x30
/* 2F3C0 8003EBC0 1800B0AF */  sw         $s0, 0x18($sp)
/* 2F3C4 8003EBC4 0780103C */  lui        $s0, %hi(D_80077260)
/* 2F3C8 8003EBC8 60720326 */  addiu      $v1, $s0, %lo(D_80077260)
/* 2F3CC 8003EBCC 2400B3AF */  sw         $s3, 0x24($sp)
/* 2F3D0 8003EBD0 21988000 */  addu       $s3, $a0, $zero
/* 2F3D4 8003EBD4 2800BFAF */  sw         $ra, 0x28($sp)
/* 2F3D8 8003EBD8 2000B2AF */  sw         $s2, 0x20($sp)
/* 2F3DC 8003EBDC 1C00B1AF */  sw         $s1, 0x1C($sp)
/* 2F3E0 8003EBE0 1000728C */  lw         $s2, 0x10($v1)
/* 2F3E4 8003EBE4 2188A000 */  addu       $s1, $a1, $zero
/* 2F3E8 8003EBE8 0C004226 */  addiu      $v0, $s2, 0xC
/* 2F3EC 8003EBEC 7CFB000C */  jal        func_8003EDF0
/* 2F3F0 8003EBF0 100062AC */   sw        $v0, 0x10($v1)
/* 2F3F4 8003EBF4 2C002012 */  beqz       $s1, .L8003ECA8
/* 2F3F8 8003EBF8 21184000 */   addu      $v1, $v0, $zero
/* 2F3FC 8003EBFC 0300228A */  lwl        $v0, 0x3($s1)
/* 2F400 8003EC00 0000229A */  lwr        $v0, 0x0($s1)
/* 2F404 8003EC04 0700248A */  lwl        $a0, 0x7($s1)
/* 2F408 8003EC08 0400249A */  lwr        $a0, 0x4($s1)
/* 2F40C 8003EC0C 1300A2AB */  swl        $v0, 0x13($sp)
/* 2F410 8003EC10 1000A2BB */  swr        $v0, 0x10($sp)
/* 2F414 8003EC14 1700A4AB */  swl        $a0, 0x17($sp)
/* 2F418 8003EC18 1400A4BB */  swr        $a0, 0x14($sp)
/* 2F41C 8003EC1C 1000A587 */  lh         $a1, 0x10($sp)
/* 2F420 8003EC20 00006684 */  lh         $a2, 0x0($v1)
/* 2F424 8003EC24 1000A797 */  lhu        $a3, 0x10($sp)
/* 2F428 8003EC28 00006494 */  lhu        $a0, 0x0($v1)
/* 2F42C 8003EC2C 2A10A600 */  slt        $v0, $a1, $a2
/* 2F430 8003EC30 04004014 */  bnez       $v0, .L8003EC44
/* 2F434 8003EC34 00000000 */   nop
/* 2F438 8003EC38 1000A4A7 */  sh         $a0, 0x10($sp)
/* 2F43C 8003EC3C 18FB0008 */  j          .L8003EC60
/* 2F440 8003EC40 1400A0A7 */   sh        $zero, 0x14($sp)
.L8003EC44:
/* 2F444 8003EC44 1400A287 */  lh         $v0, 0x14($sp)
/* 2F448 8003EC48 00000000 */  nop
/* 2F44C 8003EC4C 2110A200 */  addu       $v0, $a1, $v0
/* 2F450 8003EC50 2A104600 */  slt        $v0, $v0, $a2
/* 2F454 8003EC54 02004014 */  bnez       $v0, .L8003EC60
/* 2F458 8003EC58 23108700 */   subu      $v0, $a0, $a3
/* 2F45C 8003EC5C 1400A2A7 */  sh         $v0, 0x14($sp)
.L8003EC60:
/* 2F460 8003EC60 1200A487 */  lh         $a0, 0x12($sp)
/* 2F464 8003EC64 02006584 */  lh         $a1, 0x2($v1)
/* 2F468 8003EC68 1200A697 */  lhu        $a2, 0x12($sp)
/* 2F46C 8003EC6C 02006394 */  lhu        $v1, 0x2($v1)
/* 2F470 8003EC70 2A108500 */  slt        $v0, $a0, $a1
/* 2F474 8003EC74 04004014 */  bnez       $v0, .L8003EC88
/* 2F478 8003EC78 00000000 */   nop
/* 2F47C 8003EC7C 1200A3A7 */  sh         $v1, 0x12($sp)
/* 2F480 8003EC80 32FB0008 */  j          .L8003ECC8
/* 2F484 8003EC84 1600A0A7 */   sh        $zero, 0x16($sp)
.L8003EC88:
/* 2F488 8003EC88 1600A287 */  lh         $v0, 0x16($sp)
/* 2F48C 8003EC8C 00000000 */  nop
/* 2F490 8003EC90 21108200 */  addu       $v0, $a0, $v0
/* 2F494 8003EC94 2A104500 */  slt        $v0, $v0, $a1
/* 2F498 8003EC98 0B004014 */  bnez       $v0, .L8003ECC8
/* 2F49C 8003EC9C 23106600 */   subu      $v0, $v1, $a2
/* 2F4A0 8003ECA0 32FB0008 */  j          .L8003ECC8
/* 2F4A4 8003ECA4 1600A2A7 */   sh        $v0, 0x16($sp)
.L8003ECA8:
/* 2F4A8 8003ECA8 1200A0A7 */  sh         $zero, 0x12($sp)
/* 2F4AC 8003ECAC 1000A0A7 */  sh         $zero, 0x10($sp)
/* 2F4B0 8003ECB0 00006294 */  lhu        $v0, 0x0($v1)
/* 2F4B4 8003ECB4 00000000 */  nop
/* 2F4B8 8003ECB8 1400A2A7 */  sh         $v0, 0x14($sp)
/* 2F4BC 8003ECBC 02006394 */  lhu        $v1, 0x2($v1)
/* 2F4C0 8003ECC0 00000000 */  nop
/* 2F4C4 8003ECC4 1600A3A7 */  sh         $v1, 0x16($sp)
.L8003ECC8:
/* 2F4C8 8003ECC8 0180033C */  lui        $v1, %hi(D_800123F8)
/* 2F4CC 8003ECCC 60721026 */  addiu      $s0, $s0, %lo(D_80077260)
/* 2F4D0 8003ECD0 F8236324 */  addiu      $v1, $v1, %lo(D_800123F8)
/* 2F4D4 8003ECD4 2800028E */  lw         $v0, 0x28($s0)
/* 2F4D8 8003ECD8 1200A587 */  lh         $a1, 0x12($sp)
/* 2F4DC 8003ECDC 80100200 */  sll        $v0, $v0, 2
/* 2F4E0 8003ECE0 21186200 */  addu       $v1, $v1, $v0
/* 2F4E4 8003ECE4 02006484 */  lh         $a0, 0x2($v1)
/* 2F4E8 8003ECE8 E0010224 */  addiu      $v0, $zero, 0x1E0
/* 2F4EC 8003ECEC 06008210 */  beq        $a0, $v0, .L8003ED08
/* 2F4F0 8003ECF0 21204002 */   addu      $a0, $s2, $zero
/* 2F4F4 8003ECF4 06000286 */  lh         $v0, 0x6($s0)
/* 2F4F8 8003ECF8 00000000 */  nop
/* 2F4FC 8003ECFC 02004010 */  beqz       $v0, .L8003ED08
/* 2F500 8003ED00 00000000 */   nop
/* 2F504 8003ED04 F000A524 */  addiu      $a1, $a1, 0xF0
.L8003ED08:
/* 2F508 8003ED08 1200A5A7 */  sh         $a1, 0x12($sp)
/* 2F50C 8003ED0C 115A000C */  jal        SetDrawArea
/* 2F510 8003ED10 1000A527 */   addiu     $a1, $sp, 0x10
/* 2F514 8003ED14 21206002 */  addu       $a0, $s3, $zero
/* 2F518 8003ED18 AD70000C */  jal        AddPrim
/* 2F51C 8003ED1C 21284002 */   addu      $a1, $s2, $zero
/* 2F520 8003ED20 2800BF8F */  lw         $ra, 0x28($sp)
/* 2F524 8003ED24 2400B38F */  lw         $s3, 0x24($sp)
/* 2F528 8003ED28 2000B28F */  lw         $s2, 0x20($sp)
/* 2F52C 8003ED2C 1C00B18F */  lw         $s1, 0x1C($sp)
/* 2F530 8003ED30 1800B08F */  lw         $s0, 0x18($sp)
/* 2F534 8003ED34 0800E003 */  jr         $ra
/* 2F538 8003ED38 3000BD27 */   addiu     $sp, $sp, 0x30
.size func_8003EBBC, . - func_8003EBBC

glabel func_8003ED3C
/* 2F53C 8003ED3C D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 2F540 8003ED40 0780023C */  lui        $v0, %hi(D_80077260)
/* 2F544 8003ED44 60724624 */  addiu      $a2, $v0, %lo(D_80077260)
/* 2F548 8003ED48 1C00B1AF */  sw         $s1, 0x1C($sp)
/* 2F54C 8003ED4C 21888000 */  addu       $s1, $a0, $zero
/* 2F550 8003ED50 2000BFAF */  sw         $ra, 0x20($sp)
/* 2F554 8003ED54 1800B0AF */  sw         $s0, 0x18($sp)
/* 2F558 8003ED58 1000D08C */  lw         $s0, 0x10($a2)
/* 2F55C 8003ED5C 0180033C */  lui        $v1, %hi(D_800123F8)
/* 2F560 8003ED60 1000A0A7 */  sh         $zero, 0x10($sp)
/* 2F564 8003ED64 0C000226 */  addiu      $v0, $s0, 0xC
/* 2F568 8003ED68 1000C2AC */  sw         $v0, 0x10($a2)
/* 2F56C 8003ED6C 2800C28C */  lw         $v0, 0x28($a2)
/* 2F570 8003ED70 F8236324 */  addiu      $v1, $v1, %lo(D_800123F8)
/* 2F574 8003ED74 80100200 */  sll        $v0, $v0, 2
/* 2F578 8003ED78 21186200 */  addu       $v1, $v1, $v0
/* 2F57C 8003ED7C 02006484 */  lh         $a0, 0x2($v1)
/* 2F580 8003ED80 E0010224 */  addiu      $v0, $zero, 0x1E0
/* 2F584 8003ED84 06008210 */  beq        $a0, $v0, .L8003EDA0
/* 2F588 8003ED88 21380000 */   addu      $a3, $zero, $zero
/* 2F58C 8003ED8C 0600C284 */  lh         $v0, 0x6($a2)
/* 2F590 8003ED90 00000000 */  nop
/* 2F594 8003ED94 02004010 */  beqz       $v0, .L8003EDA0
/* 2F598 8003ED98 00000000 */   nop
/* 2F59C 8003ED9C F0000724 */  addiu      $a3, $zero, 0xF0
.L8003EDA0:
/* 2F5A0 8003EDA0 0800A010 */  beqz       $a1, .L8003EDC4
/* 2F5A4 8003EDA4 1200A7A7 */   sh        $a3, 0x12($sp)
/* 2F5A8 8003EDA8 1000A297 */  lhu        $v0, 0x10($sp)
/* 2F5AC 8003EDAC 0000A494 */  lhu        $a0, 0x0($a1)
/* 2F5B0 8003EDB0 0200A394 */  lhu        $v1, 0x2($a1)
/* 2F5B4 8003EDB4 21104400 */  addu       $v0, $v0, $a0
/* 2F5B8 8003EDB8 2118E300 */  addu       $v1, $a3, $v1
/* 2F5BC 8003EDBC 1000A2A7 */  sh         $v0, 0x10($sp)
/* 2F5C0 8003EDC0 1200A3A7 */  sh         $v1, 0x12($sp)
.L8003EDC4:
/* 2F5C4 8003EDC4 21200002 */  addu       $a0, $s0, $zero
/* 2F5C8 8003EDC8 315A000C */  jal        SetDrawOffset
/* 2F5CC 8003EDCC 1000A527 */   addiu     $a1, $sp, 0x10
/* 2F5D0 8003EDD0 21202002 */  addu       $a0, $s1, $zero
/* 2F5D4 8003EDD4 AD70000C */  jal        AddPrim
/* 2F5D8 8003EDD8 21280002 */   addu      $a1, $s0, $zero
/* 2F5DC 8003EDDC 2000BF8F */  lw         $ra, 0x20($sp)
/* 2F5E0 8003EDE0 1C00B18F */  lw         $s1, 0x1C($sp)
/* 2F5E4 8003EDE4 1800B08F */  lw         $s0, 0x18($sp)
/* 2F5E8 8003EDE8 0800E003 */  jr         $ra
/* 2F5EC 8003EDEC 2800BD27 */   addiu     $sp, $sp, 0x28
.size func_8003ED3C, . - func_8003ED3C

glabel func_8003EDF0
/* 2F5F0 8003EDF0 0780033C */  lui        $v1, %hi(D_80077260)
/* 2F5F4 8003EDF4 6072628C */  lw         $v0, %lo(D_80077260)($v1)
/* 2F5F8 8003EDF8 00000000 */  nop
/* 2F5FC 8003EDFC 08004230 */  andi       $v0, $v0, 0x8
/* 2F600 8003EE00 07004014 */  bnez       $v0, .L8003EE20
/* 2F604 8003EE04 60726324 */   addiu     $v1, $v1, %lo(D_80077260)
/* 2F608 8003EE08 2800638C */  lw         $v1, 0x28($v1)
/* 2F60C 8003EE0C 0180023C */  lui        $v0, %hi(D_800123F8)
/* 2F610 8003EE10 F8234224 */  addiu      $v0, $v0, %lo(D_800123F8)
/* 2F614 8003EE14 80180300 */  sll        $v1, $v1, 2
/* 2F618 8003EE18 0800E003 */  jr         $ra
/* 2F61C 8003EE1C 21106200 */   addu      $v0, $v1, $v0
.L8003EE20:
/* 2F620 8003EE20 0800E003 */  jr         $ra
/* 2F624 8003EE24 30006224 */   addiu     $v0, $v1, 0x30
.size func_8003EDF0, . - func_8003EDF0

glabel func_8003EE28
/* 2F628 8003EE28 08008014 */  bnez       $a0, .L8003EE4C
/* 2F62C 8003EE2C 00000000 */   nop
/* 2F630 8003EE30 0780023C */  lui        $v0, %hi(D_80077284)
/* 2F634 8003EE34 8472438C */  lw         $v1, %lo(D_80077284)($v0)
/* 2F638 8003EE38 0180023C */  lui        $v0, %hi(D_800123F8)
/* 2F63C 8003EE3C F8234224 */  addiu      $v0, $v0, %lo(D_800123F8)
/* 2F640 8003EE40 80180300 */  sll        $v1, $v1, 2
/* 2F644 8003EE44 0800E003 */  jr         $ra
/* 2F648 8003EE48 21106200 */   addu      $v0, $v1, $v0
.L8003EE4C:
/* 2F64C 8003EE4C 0780023C */  lui        $v0, %hi(D_80077288)
/* 2F650 8003EE50 8872438C */  lw         $v1, %lo(D_80077288)($v0)
/* 2F654 8003EE54 0180023C */  lui        $v0, %hi(D_800123F8)
/* 2F658 8003EE58 F8234224 */  addiu      $v0, $v0, %lo(D_800123F8)
/* 2F65C 8003EE5C 80180300 */  sll        $v1, $v1, 2
/* 2F660 8003EE60 0800E003 */  jr         $ra
/* 2F664 8003EE64 21106200 */   addu      $v0, $v1, $v0
.size func_8003EE28, . - func_8003EE28

glabel func_8003EE68
/* 2F668 8003EE68 70FFBD27 */  addiu      $sp, $sp, -0x90
/* 2F66C 8003EE6C 8000B2AF */  sw         $s2, 0x80($sp)
/* 2F670 8003EE70 2190A000 */  addu       $s2, $a1, $zero
/* 2F674 8003EE74 7800B0AF */  sw         $s0, 0x78($sp)
/* 2F678 8003EE78 0780103C */  lui        $s0, %hi(D_80077260)
/* 2F67C 8003EE7C 60720226 */  addiu      $v0, $s0, %lo(D_80077260)
/* 2F680 8003EE80 7C00B1AF */  sw         $s1, 0x7C($sp)
/* 2F684 8003EE84 21888000 */  addu       $s1, $a0, $zero
/* 2F688 8003EE88 8400B3AF */  sw         $s3, 0x84($sp)
/* 2F68C 8003EE8C 2198C000 */  addu       $s3, $a2, $zero
/* 2F690 8003EE90 8800BFAF */  sw         $ra, 0x88($sp)
/* 2F694 8003EE94 2800458C */  lw         $a1, 0x28($v0)
/* 2F698 8003EE98 06004684 */  lh         $a2, 0x6($v0)
/* 2F69C 8003EE9C 6DFC000C */  jal        func_8003F1B4
/* 2F6A0 8003EEA0 1000A427 */   addiu     $a0, $sp, 0x10
/* 2F6A4 8003EEA4 10002012 */  beqz       $s1, .L8003EEE8
/* 2F6A8 8003EEA8 00000000 */   nop
/* 2F6AC 8003EEAC 1000A297 */  lhu        $v0, 0x10($sp)
/* 2F6B0 8003EEB0 00002396 */  lhu        $v1, 0x0($s1)
/* 2F6B4 8003EEB4 00000000 */  nop
/* 2F6B8 8003EEB8 21104300 */  addu       $v0, $v0, $v1
/* 2F6BC 8003EEBC 1200A397 */  lhu        $v1, 0x12($sp)
/* 2F6C0 8003EEC0 1000A2A7 */  sh         $v0, 0x10($sp)
/* 2F6C4 8003EEC4 02002596 */  lhu        $a1, 0x2($s1)
/* 2F6C8 8003EEC8 04002296 */  lhu        $v0, 0x4($s1)
/* 2F6CC 8003EECC 06002496 */  lhu        $a0, 0x6($s1)
/* 2F6D0 8003EED0 21186500 */  addu       $v1, $v1, $a1
/* 2F6D4 8003EED4 1200A3A7 */  sh         $v1, 0x12($sp)
/* 2F6D8 8003EED8 1400A2A7 */  sh         $v0, 0x14($sp)
/* 2F6DC 8003EEDC 1600A4A7 */  sh         $a0, 0x16($sp)
/* 2F6E0 8003EEE0 BBFB0008 */  j          .L8003EEEC
/* 2F6E4 8003EEE4 7200A5A7 */   sh        $a1, 0x72($sp)
.L8003EEE8:
/* 2F6E8 8003EEE8 7200A0A7 */  sh         $zero, 0x72($sp)
.L8003EEEC:
/* 2F6EC 8003EEEC 1000A297 */  lhu        $v0, 0x10($sp)
/* 2F6F0 8003EEF0 15006012 */  beqz       $s3, .L8003EF48
/* 2F6F4 8003EEF4 7000A2A7 */   sh        $v0, 0x70($sp)
/* 2F6F8 8003EEF8 60720426 */  addiu      $a0, $s0, %lo(D_80077260)
/* 2F6FC 8003EEFC 1000838C */  lw         $v1, 0x10($a0)
/* 2F700 8003EF00 00000000 */  nop
/* 2F704 8003EF04 10006224 */  addiu      $v0, $v1, 0x10
/* 2F708 8003EF08 100082AC */  sw         $v0, 0x10($a0)
/* 2F70C 8003EF0C 0000658E */  lw         $a1, 0x0($s3)
/* 2F710 8003EF10 03000224 */  addiu      $v0, $zero, 0x3
/* 2F714 8003EF14 030062A0 */  sb         $v0, 0x3($v1)
/* 2F718 8003EF18 60000224 */  addiu      $v0, $zero, 0x60
/* 2F71C 8003EF1C 080060A4 */  sh         $zero, 0x8($v1)
/* 2F720 8003EF20 0A0060A4 */  sh         $zero, 0xA($v1)
/* 2F724 8003EF24 040065AC */  sw         $a1, 0x4($v1)
/* 2F728 8003EF28 070062A0 */  sb         $v0, 0x7($v1)
/* 2F72C 8003EF2C 04002596 */  lhu        $a1, 0x4($s1)
/* 2F730 8003EF30 21204002 */  addu       $a0, $s2, $zero
/* 2F734 8003EF34 0C0065A4 */  sh         $a1, 0xC($v1)
/* 2F738 8003EF38 06002296 */  lhu        $v0, 0x6($s1)
/* 2F73C 8003EF3C 21286000 */  addu       $a1, $v1, $zero
/* 2F740 8003EF40 AD70000C */  jal        AddPrim
/* 2F744 8003EF44 0E0062A4 */   sh        $v0, 0xE($v1)
.L8003EF48:
/* 2F748 8003EF48 60721126 */  addiu      $s1, $s0, %lo(D_80077260)
/* 2F74C 8003EF4C 1000308E */  lw         $s0, 0x10($s1)
/* 2F750 8003EF50 01000524 */  addiu      $a1, $zero, 0x1
/* 2F754 8003EF54 21200002 */  addu       $a0, $s0, $zero
/* 2F758 8003EF58 0C000226 */  addiu      $v0, $s0, 0xC
/* 2F75C 8003EF5C C5FD000C */  jal        SetDrawStp
/* 2F760 8003EF60 100022AE */   sw        $v0, 0x10($s1)
/* 2F764 8003EF64 21204002 */  addu       $a0, $s2, $zero
/* 2F768 8003EF68 AD70000C */  jal        AddPrim
/* 2F76C 8003EF6C 21280002 */   addu      $a1, $s0, $zero
/* 2F770 8003EF70 21204002 */  addu       $a0, $s2, $zero
/* 2F774 8003EF74 4FFB000C */  jal        func_8003ED3C
/* 2F778 8003EF78 7000A527 */   addiu     $a1, $sp, 0x70
/* 2F77C 8003EF7C 1000308E */  lw         $s0, 0x10($s1)
/* 2F780 8003EF80 1000A527 */  addiu      $a1, $sp, 0x10
/* 2F784 8003EF84 21200002 */  addu       $a0, $s0, $zero
/* 2F788 8003EF88 40000226 */  addiu      $v0, $s0, 0x40
/* 2F78C 8003EF8C 415A000C */  jal        SetDrawEnv
/* 2F790 8003EF90 100022AE */   sw        $v0, 0x10($s1)
/* 2F794 8003EF94 21204002 */  addu       $a0, $s2, $zero
/* 2F798 8003EF98 AD70000C */  jal        AddPrim
/* 2F79C 8003EF9C 21280002 */   addu      $a1, $s0, $zero
/* 2F7A0 8003EFA0 8800BF8F */  lw         $ra, 0x88($sp)
/* 2F7A4 8003EFA4 8400B38F */  lw         $s3, 0x84($sp)
/* 2F7A8 8003EFA8 8000B28F */  lw         $s2, 0x80($sp)
/* 2F7AC 8003EFAC 7C00B18F */  lw         $s1, 0x7C($sp)
/* 2F7B0 8003EFB0 7800B08F */  lw         $s0, 0x78($sp)
/* 2F7B4 8003EFB4 0800E003 */  jr         $ra
/* 2F7B8 8003EFB8 9000BD27 */   addiu     $sp, $sp, 0x90
.size func_8003EE68, . - func_8003EE68

glabel func_8003EFBC
/* 2F7BC 8003EFBC D0FFBD27 */  addiu      $sp, $sp, -0x30
/* 2F7C0 8003EFC0 2000B0AF */  sw         $s0, 0x20($sp)
/* 2F7C4 8003EFC4 21808000 */  addu       $s0, $a0, $zero
/* 2F7C8 8003EFC8 1000A427 */  addiu      $a0, $sp, 0x10
/* 2F7CC 8003EFCC 2800BFAF */  sw         $ra, 0x28($sp)
/* 2F7D0 8003EFD0 D970000C */  jal        func_8001C364
/* 2F7D4 8003EFD4 2400B1AF */   sw        $s1, 0x24($sp)
/* 2F7D8 8003EFD8 08000012 */  beqz       $s0, .L8003EFFC
/* 2F7DC 8003EFDC 00000000 */   nop
/* 2F7E0 8003EFE0 00000292 */  lbu        $v0, 0x0($s0)
/* 2F7E4 8003EFE4 01000392 */  lbu        $v1, 0x1($s0)
/* 2F7E8 8003EFE8 02000492 */  lbu        $a0, 0x2($s0)
/* 2F7EC 8003EFEC 1400A2A3 */  sb         $v0, 0x14($sp)
/* 2F7F0 8003EFF0 1500A3A3 */  sb         $v1, 0x15($sp)
/* 2F7F4 8003EFF4 02FC0008 */  j          .L8003F008
/* 2F7F8 8003EFF8 1600A4A3 */   sb        $a0, 0x16($sp)
.L8003EFFC:
/* 2F7FC 8003EFFC 1400A0A3 */  sb         $zero, 0x14($sp)
/* 2F800 8003F000 1500A0A3 */  sb         $zero, 0x15($sp)
/* 2F804 8003F004 1600A0A3 */  sb         $zero, 0x16($sp)
.L8003F008:
/* 2F808 8003F008 1800A0A7 */  sh         $zero, 0x18($sp)
/* 2F80C 8003F00C 7CFB000C */  jal        func_8003EDF0
/* 2F810 8003F010 1A00A0A7 */   sh        $zero, 0x1A($sp)
/* 2F814 8003F014 21200000 */  addu       $a0, $zero, $zero
/* 2F818 8003F018 00004394 */  lhu        $v1, 0x0($v0)
/* 2F81C 8003F01C E0010224 */  addiu      $v0, $zero, 0x1E0
/* 2F820 8003F020 1E00A2A7 */  sh         $v0, 0x1E($sp)
/* 2F824 8003F024 AE56000C */  jal        DrawSync
/* 2F828 8003F028 1C00A3A7 */   sh        $v1, 0x1C($sp)
/* 2F82C 8003F02C 0780103C */  lui        $s0, %hi(D_80077260)
/* 2F830 8003F030 60721026 */  addiu      $s0, $s0, %lo(D_80077260)
/* 2F834 8003F034 5C001126 */  addiu      $s1, $s0, 0x5C
/* 2F838 8003F038 04000286 */  lh         $v0, 0x4($s0)
/* 2F83C 8003F03C 1000A527 */  addiu      $a1, $sp, 0x10
/* 2F840 8003F040 80200200 */  sll        $a0, $v0, 2
/* 2F844 8003F044 21208200 */  addu       $a0, $a0, $v0
/* 2F848 8003F048 80200400 */  sll        $a0, $a0, 2
/* 2F84C 8003F04C 21208200 */  addu       $a0, $a0, $v0
/* 2F850 8003F050 00210400 */  sll        $a0, $a0, 4
/* 2F854 8003F054 21209100 */  addu       $a0, $a0, $s1
/* 2F858 8003F058 AD70000C */  jal        AddPrim
/* 2F85C 8003F05C 1C008424 */   addiu     $a0, $a0, 0x1C
/* 2F860 8003F060 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 2F864 8003F064 04000286 */  lh         $v0, 0x4($s0)
/* 2F868 8003F068 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 2F86C 8003F06C 80200200 */  sll        $a0, $v0, 2
/* 2F870 8003F070 21208200 */  addu       $a0, $a0, $v0
/* 2F874 8003F074 80200400 */  sll        $a0, $a0, 2
/* 2F878 8003F078 21208200 */  addu       $a0, $a0, $v0
/* 2F87C 8003F07C 00210400 */  sll        $a0, $a0, 4
/* 2F880 8003F080 21209100 */  addu       $a0, $a0, $s1
/* 2F884 8003F084 1000A28F */  lw         $v0, 0x10($sp)
/* 2F888 8003F088 1C008424 */  addiu      $a0, $a0, 0x1C
/* 2F88C 8003F08C 25104300 */  or         $v0, $v0, $v1
/* 2F890 8003F090 3C61000C */  jal        DrawOTag2
/* 2F894 8003F094 1000A2AF */   sw        $v0, 0x10($sp)
/* 2F898 8003F098 AE56000C */  jal        DrawSync
/* 2F89C 8003F09C 21200000 */   addu      $a0, $zero, $zero
/* 2F8A0 8003F0A0 2800BF8F */  lw         $ra, 0x28($sp)
/* 2F8A4 8003F0A4 2400B18F */  lw         $s1, 0x24($sp)
/* 2F8A8 8003F0A8 2000B08F */  lw         $s0, 0x20($sp)
/* 2F8AC 8003F0AC 0800E003 */  jr         $ra
/* 2F8B0 8003F0B0 3000BD27 */   addiu     $sp, $sp, 0x30
.size func_8003EFBC, . - func_8003EFBC

glabel func_8003F0B4
/* 2F8B4 8003F0B4 07008010 */  beqz       $a0, .L8003F0D4
/* 2F8B8 8003F0B8 0780023C */   lui       $v0, %hi(D_80077260)
/* 2F8BC 8003F0BC 0780033C */  lui        $v1, %hi(D_80077260)
/* 2F8C0 8003F0C0 6072628C */  lw         $v0, %lo(D_80077260)($v1)
/* 2F8C4 8003F0C4 00000000 */  nop
/* 2F8C8 8003F0C8 40004234 */  ori        $v0, $v0, 0x40
/* 2F8CC 8003F0CC 0800E003 */  jr         $ra
/* 2F8D0 8003F0D0 607262AC */   sw        $v0, %lo(D_80077260)($v1)
.L8003F0D4:
/* 2F8D4 8003F0D4 6072438C */  lw         $v1, %lo(D_80077260)($v0)
/* 2F8D8 8003F0D8 BFFF0424 */  addiu      $a0, $zero, -0x41
/* 2F8DC 8003F0DC 24186400 */  and        $v1, $v1, $a0
/* 2F8E0 8003F0E0 0800E003 */  jr         $ra
/* 2F8E4 8003F0E4 607243AC */   sw        $v1, %lo(D_80077260)($v0)
.size func_8003F0B4, . - func_8003F0B4

glabel func_8003F0E8
/* 2F8E8 8003F0E8 07008010 */  beqz       $a0, .L8003F108
/* 2F8EC 8003F0EC 0780033C */   lui       $v1, %hi(D_80077260)
/* 2F8F0 8003F0F0 0780023C */  lui        $v0, %hi(D_80077260)
/* 2F8F4 8003F0F4 6072438C */  lw         $v1, %lo(D_80077260)($v0)
/* 2F8F8 8003F0F8 FFFE0424 */  addiu      $a0, $zero, -0x101
/* 2F8FC 8003F0FC 24186400 */  and        $v1, $v1, $a0
/* 2F900 8003F100 0800E003 */  jr         $ra
/* 2F904 8003F104 607243AC */   sw        $v1, %lo(D_80077260)($v0)
.L8003F108:
/* 2F908 8003F108 6072628C */  lw         $v0, %lo(D_80077260)($v1)
/* 2F90C 8003F10C 00000000 */  nop
/* 2F910 8003F110 00014234 */  ori        $v0, $v0, 0x100
/* 2F914 8003F114 0800E003 */  jr         $ra
/* 2F918 8003F118 607262AC */   sw        $v0, %lo(D_80077260)($v1)
.size func_8003F0E8, . - func_8003F0E8

glabel func_8003F11C
/* 2F91C 8003F11C 21388000 */  addu       $a3, $a0, $zero
/* 2F920 8003F120 2140A000 */  addu       $t0, $a1, $zero
/* 2F924 8003F124 00340600 */  sll        $a2, $a2, 16
/* 2F928 8003F128 03340600 */  sra        $a2, $a2, 16
/* 2F92C 8003F12C 0180053C */  lui        $a1, %hi(D_800123F8)
/* 2F930 8003F130 F823A224 */  addiu      $v0, $a1, %lo(D_800123F8)
/* 2F934 8003F134 80180800 */  sll        $v1, $t0, 2
/* 2F938 8003F138 21104300 */  addu       $v0, $v0, $v1
/* 2F93C 8003F13C 02004384 */  lh         $v1, 0x2($v0)
/* 2F940 8003F140 E0010424 */  addiu      $a0, $zero, 0x1E0
/* 2F944 8003F144 05006410 */  beq        $v1, $a0, .L8003F15C
/* 2F948 8003F148 0000E0A4 */   sh        $zero, 0x0($a3)
/* 2F94C 8003F14C 0300C014 */  bnez       $a2, .L8003F15C
/* 2F950 8003F150 F0000224 */   addiu     $v0, $zero, 0xF0
/* 2F954 8003F154 58FC0008 */  j          .L8003F160
/* 2F958 8003F158 0200E2A4 */   sh        $v0, 0x2($a3)
.L8003F15C:
/* 2F95C 8003F15C 0200E0A4 */  sh         $zero, 0x2($a3)
.L8003F160:
/* 2F960 8003F160 00010224 */  addiu      $v0, $zero, 0x100
/* 2F964 8003F164 F823A324 */  addiu      $v1, $a1, %lo(D_800123F8)
/* 2F968 8003F168 0C00E2A4 */  sh         $v0, 0xC($a3)
/* 2F96C 8003F16C 80100800 */  sll        $v0, $t0, 2
/* 2F970 8003F170 21204300 */  addu       $a0, $v0, $v1
/* 2F974 8003F174 21186200 */  addu       $v1, $v1, $v0
/* 2F978 8003F178 00008594 */  lhu        $a1, 0x0($a0)
/* 2F97C 8003F17C 02006294 */  lhu        $v0, 0x2($v1)
/* 2F980 8003F180 F0000424 */  addiu      $a0, $zero, 0xF0
/* 2F984 8003F184 0800E0A4 */  sh         $zero, 0x8($a3)
/* 2F988 8003F188 0A00E0A4 */  sh         $zero, 0xA($a3)
/* 2F98C 8003F18C 0E00E4A4 */  sh         $a0, 0xE($a3)
/* 2F990 8003F190 1100E0A0 */  sb         $zero, 0x11($a3)
/* 2F994 8003F194 0600E2A4 */  sh         $v0, 0x6($a3)
/* 2F998 8003F198 00140200 */  sll        $v0, $v0, 16
/* 2F99C 8003F19C 03140200 */  sra        $v0, $v0, 16
/* 2F9A0 8003F1A0 E0014238 */  xori       $v0, $v0, 0x1E0
/* 2F9A4 8003F1A4 0100422C */  sltiu      $v0, $v0, 0x1
/* 2F9A8 8003F1A8 0400E5A4 */  sh         $a1, 0x4($a3)
/* 2F9AC 8003F1AC 0800E003 */  jr         $ra
/* 2F9B0 8003F1B0 1000E2A0 */   sb        $v0, 0x10($a3)
.size func_8003F11C, . - func_8003F11C

glabel func_8003F1B4
/* 2F9B4 8003F1B4 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 2F9B8 8003F1B8 21400000 */  addu       $t0, $zero, $zero
/* 2F9BC 8003F1BC 21488000 */  addu       $t1, $a0, $zero
/* 2F9C0 8003F1C0 2138A000 */  addu       $a3, $a1, $zero
/* 2F9C4 8003F1C4 00340600 */  sll        $a2, $a2, 16
/* 2F9C8 8003F1C8 0180053C */  lui        $a1, %hi(D_800123F8)
/* 2F9CC 8003F1CC F823A224 */  addiu      $v0, $a1, %lo(D_800123F8)
/* 2F9D0 8003F1D0 80180700 */  sll        $v1, $a3, 2
/* 2F9D4 8003F1D4 21104300 */  addu       $v0, $v0, $v1
/* 2F9D8 8003F1D8 1800BFAF */  sw         $ra, 0x18($sp)
/* 2F9DC 8003F1DC 02004484 */  lh         $a0, 0x2($v0)
/* 2F9E0 8003F1E0 E0010324 */  addiu      $v1, $zero, 0x1E0
/* 2F9E4 8003F1E4 04008310 */  beq        $a0, $v1, .L8003F1F8
/* 2F9E8 8003F1E8 03340600 */   sra       $a2, $a2, 16
/* 2F9EC 8003F1EC 0300C010 */  beqz       $a2, .L8003F1FC
/* 2F9F0 8003F1F0 F823A424 */   addiu     $a0, $a1, %lo(D_800123F8)
/* 2F9F4 8003F1F4 F0000824 */  addiu      $t0, $zero, 0xF0
.L8003F1F8:
/* 2F9F8 8003F1F8 F823A424 */  addiu      $a0, $a1, %lo(D_800123F8)
.L8003F1FC:
/* 2F9FC 8003F1FC 80300700 */  sll        $a2, $a3, 2
/* 2FA00 8003F200 21108600 */  addu       $v0, $a0, $a2
/* 2FA04 8003F204 2130C400 */  addu       $a2, $a2, $a0
/* 2FA08 8003F208 21202001 */  addu       $a0, $t1, $zero
/* 2FA0C 8003F20C 21280000 */  addu       $a1, $zero, $zero
/* 2FA10 8003F210 02004384 */  lh         $v1, 0x2($v0)
/* 2FA14 8003F214 0000C784 */  lh         $a3, 0x0($a2)
/* 2FA18 8003F218 21300001 */  addu       $a2, $t0, $zero
/* 2FA1C 8003F21C 65FD000C */  jal        SetDefDrawEnv
/* 2FA20 8003F220 1000A3AF */   sw        $v1, 0x10($sp)
/* 2FA24 8003F224 1800BF8F */  lw         $ra, 0x18($sp)
/* 2FA28 8003F228 00000000 */  nop
/* 2FA2C 8003F22C 0800E003 */  jr         $ra
/* 2FA30 8003F230 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8003F1B4, . - func_8003F1B4

glabel func_8003F234
/* 2FA34 8003F234 C8FFBD27 */  addiu      $sp, $sp, -0x38
/* 2FA38 8003F238 0780093C */  lui        $t1, %hi(D_80077260)
/* 2FA3C 8003F23C 60722925 */  addiu      $t1, $t1, %lo(D_80077260)
/* 2FA40 8003F240 0180023C */  lui        $v0, %hi(D_800123F8)
/* 2FA44 8003F244 F8234224 */  addiu      $v0, $v0, %lo(D_800123F8)
/* 2FA48 8003F248 3000BFAF */  sw         $ra, 0x30($sp)
/* 2FA4C 8003F24C 4000238D */  lw         $v1, 0x40($t1)
/* 2FA50 8003F250 1800A427 */  addiu      $a0, $sp, 0x18
/* 2FA54 8003F254 80180300 */  sll        $v1, $v1, 2
/* 2FA58 8003F258 21186200 */  addu       $v1, $v1, $v0
/* 2FA5C 8003F25C 02006894 */  lhu        $t0, 0x2($v1)
/* 2FA60 8003F260 00006594 */  lhu        $a1, 0x0($v1)
/* 2FA64 8003F264 00440800 */  sll        $t0, $t0, 16
/* 2FA68 8003F268 03340800 */  sra        $a2, $t0, 16
/* 2FA6C 8003F26C 002C0500 */  sll        $a1, $a1, 16
/* 2FA70 8003F270 033C0500 */  sra        $a3, $a1, 16
/* 2FA74 8003F274 C22F0500 */  srl        $a1, $a1, 31
/* 2FA78 8003F278 2128E500 */  addu       $a1, $a3, $a1
/* 2FA7C 8003F27C 43280500 */  sra        $a1, $a1, 1
/* 2FA80 8003F280 C2470800 */  srl        $t0, $t0, 31
/* 2FA84 8003F284 1000A6AF */  sw         $a2, 0x10($sp)
/* 2FA88 8003F288 2130C800 */  addu       $a2, $a2, $t0
/* 2FA8C 8003F28C 43300600 */  sra        $a2, $a2, 1
/* 2FA90 8003F290 44002285 */  lh         $v0, 0x44($t1)
/* 2FA94 8003F294 46002385 */  lh         $v1, 0x46($t1)
/* 2FA98 8003F298 23284500 */  subu       $a1, $v0, $a1
/* 2FA9C 8003F29C 95FD000C */  jal        SetDefDispEnv
/* 2FAA0 8003F2A0 23306600 */   subu      $a2, $v1, $a2
/* 2FAA4 8003F2A4 BA58000C */  jal        PutDispEnv
/* 2FAA8 8003F2A8 1800A427 */   addiu     $a0, $sp, 0x18
/* 2FAAC 8003F2AC 3000BF8F */  lw         $ra, 0x30($sp)
/* 2FAB0 8003F2B0 00000000 */  nop
/* 2FAB4 8003F2B4 0800E003 */  jr         $ra
/* 2FAB8 8003F2B8 3800BD27 */   addiu     $sp, $sp, 0x38
.size func_8003F234, . - func_8003F234

glabel func_8003F2BC
/* 2FABC 8003F2BC E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 2FAC0 8003F2C0 1000B0AF */  sw         $s0, 0x10($sp)
/* 2FAC4 8003F2C4 21808000 */  addu       $s0, $a0, $zero
/* 2FAC8 8003F2C8 1400B1AF */  sw         $s1, 0x14($sp)
/* 2FACC 8003F2CC 0780113C */  lui        $s1, %hi(D_80077260)
/* 2FAD0 8003F2D0 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 2FAD4 8003F2D4 1800B2AF */  sw         $s2, 0x18($sp)
/* 2FAD8 8003F2D8 74000296 */  lhu        $v0, 0x74($s0)
/* 2FADC 8003F2DC 76000396 */  lhu        $v1, 0x76($s0)
/* 2FAE0 8003F2E0 60723126 */  addiu      $s1, $s1, %lo(D_80077260)
/* 2FAE4 8003F2E4 300100A6 */  sh         $zero, 0x130($s0)
/* 2FAE8 8003F2E8 320100A6 */  sh         $zero, 0x132($s0)
/* 2FAEC 8003F2EC 340102A6 */  sh         $v0, 0x134($s0)
/* 2FAF0 8003F2F0 360103A6 */  sh         $v1, 0x136($s0)
/* 2FAF4 8003F2F4 2C002296 */  lhu        $v0, 0x2C($s1)
/* 2FAF8 8003F2F8 00000000 */  nop
/* 2FAFC 8003F2FC 400102A6 */  sh         $v0, 0x140($s0)
/* 2FB00 8003F300 2E002396 */  lhu        $v1, 0x2E($s1)
/* 2FB04 8003F304 00000000 */  nop
/* 2FB08 8003F308 420103A6 */  sh         $v1, 0x142($s0)
/* 2FB0C 8003F30C 30002296 */  lhu        $v0, 0x30($s1)
/* 2FB10 8003F310 00000000 */  nop
/* 2FB14 8003F314 440102A6 */  sh         $v0, 0x144($s0)
/* 2FB18 8003F318 32002396 */  lhu        $v1, 0x32($s1)
/* 2FB1C 8003F31C CC001226 */  addiu      $s2, $s0, 0xCC
/* 2FB20 8003F320 460103A6 */  sh         $v1, 0x146($s0)
/* 2FB24 8003F324 2800258E */  lw         $a1, 0x28($s1)
/* 2FB28 8003F328 06002686 */  lh         $a2, 0x6($s1)
/* 2FB2C 8003F32C 6DFC000C */  jal        func_8003F1B4
/* 2FB30 8003F330 21204002 */   addu      $a0, $s2, $zero
/* 2FB34 8003F334 CC000296 */  lhu        $v0, 0xCC($s0)
/* 2FB38 8003F338 2C002396 */  lhu        $v1, 0x2C($s1)
/* 2FB3C 8003F33C 00000000 */  nop
/* 2FB40 8003F340 21104300 */  addu       $v0, $v0, $v1
/* 2FB44 8003F344 CE000396 */  lhu        $v1, 0xCE($s0)
/* 2FB48 8003F348 CC0002A6 */  sh         $v0, 0xCC($s0)
/* 2FB4C 8003F34C 2E002296 */  lhu        $v0, 0x2E($s1)
/* 2FB50 8003F350 00000000 */  nop
/* 2FB54 8003F354 21186200 */  addu       $v1, $v1, $v0
/* 2FB58 8003F358 CE0003A6 */  sh         $v1, 0xCE($s0)
/* 2FB5C 8003F35C 30002296 */  lhu        $v0, 0x30($s1)
/* 2FB60 8003F360 E8000426 */  addiu      $a0, $s0, 0xE8
/* 2FB64 8003F364 D00002A6 */  sh         $v0, 0xD0($s0)
/* 2FB68 8003F368 32002396 */  lhu        $v1, 0x32($s1)
/* 2FB6C 8003F36C 21284002 */  addu       $a1, $s2, $zero
/* 2FB70 8003F370 415A000C */  jal        SetDrawEnv
/* 2FB74 8003F374 D20003A6 */   sh        $v1, 0xD2($s0)
/* 2FB78 8003F378 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 2FB7C 8003F37C 1800B28F */  lw         $s2, 0x18($sp)
/* 2FB80 8003F380 1400B18F */  lw         $s1, 0x14($sp)
/* 2FB84 8003F384 1000B08F */  lw         $s0, 0x10($sp)
/* 2FB88 8003F388 0800E003 */  jr         $ra
/* 2FB8C 8003F38C 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_8003F2BC, . - func_8003F2BC

glabel func_8003F390
/* 2FB90 8003F390 C0FFBD27 */  addiu      $sp, $sp, -0x40
/* 2FB94 8003F394 0780053C */  lui        $a1, %hi(D_80077260)
/* 2FB98 8003F398 6072A524 */  addiu      $a1, $a1, %lo(D_80077260)
/* 2FB9C 8003F39C 3C00BFAF */  sw         $ra, 0x3C($sp)
/* 2FBA0 8003F3A0 3800BEAF */  sw         $fp, 0x38($sp)
/* 2FBA4 8003F3A4 3400B7AF */  sw         $s7, 0x34($sp)
/* 2FBA8 8003F3A8 3000B6AF */  sw         $s6, 0x30($sp)
/* 2FBAC 8003F3AC 2C00B5AF */  sw         $s5, 0x2C($sp)
/* 2FBB0 8003F3B0 2800B4AF */  sw         $s4, 0x28($sp)
/* 2FBB4 8003F3B4 2400B3AF */  sw         $s3, 0x24($sp)
/* 2FBB8 8003F3B8 2000B2AF */  sw         $s2, 0x20($sp)
/* 2FBBC 8003F3BC 1C00B1AF */  sw         $s1, 0x1C($sp)
/* 2FBC0 8003F3C0 1800B0AF */  sw         $s0, 0x18($sp)
/* 2FBC4 8003F3C4 0400A384 */  lh         $v1, 0x4($a1)
/* 2FBC8 8003F3C8 4800A524 */  addiu      $a1, $a1, 0x48
/* 2FBCC 8003F3CC 80100300 */  sll        $v0, $v1, 2
/* 2FBD0 8003F3D0 21104300 */  addu       $v0, $v0, $v1
/* 2FBD4 8003F3D4 80100200 */  sll        $v0, $v0, 2
/* 2FBD8 8003F3D8 21104300 */  addu       $v0, $v0, $v1
/* 2FBDC 8003F3DC 00110200 */  sll        $v0, $v0, 4
/* 2FBE0 8003F3E0 21B84500 */  addu       $s7, $v0, $a1
/* 2FBE4 8003F3E4 7000F326 */  addiu      $s3, $s7, 0x70
/* 2FBE8 8003F3E8 06006286 */  lh         $v0, 0x6($s3)
/* 2FBEC 8003F3EC 21900000 */  addu       $s2, $zero, $zero
/* 2FBF0 8003F3F0 5C004018 */  blez       $v0, .L8003F564
/* 2FBF4 8003F3F4 4000A4AF */   sw        $a0, 0x40($sp)
.L8003F3F8:
/* 2FBF8 8003F3F8 0200E286 */  lh         $v0, 0x2($s7)
/* 2FBFC 8003F3FC 00000000 */  nop
/* 2FC00 8003F400 21105200 */  addu       $v0, $v0, $s2
/* 2FC04 8003F404 FF005630 */  andi       $s6, $v0, 0xFF
/* 2FC08 8003F408 20004224 */  addiu      $v0, $v0, 0x20
/* 2FC0C 8003F40C FF004230 */  andi       $v0, $v0, 0xFF
/* 2FC10 8003F410 2A10C202 */  slt        $v0, $s6, $v0
/* 2FC14 8003F414 03004014 */  bnez       $v0, .L8003F424
/* 2FC18 8003F418 20000224 */   addiu     $v0, $zero, 0x20
/* 2FC1C 8003F41C 00010224 */  addiu      $v0, $zero, 0x100
/* 2FC20 8003F420 23105600 */  subu       $v0, $v0, $s6
.L8003F424:
/* 2FC24 8003F424 21A04000 */  addu       $s4, $v0, $zero
/* 2FC28 8003F428 06006386 */  lh         $v1, 0x6($s3)
/* 2FC2C 8003F42C 21104202 */  addu       $v0, $s2, $v0
/* 2FC30 8003F430 2A106200 */  slt        $v0, $v1, $v0
/* 2FC34 8003F434 02004010 */  beqz       $v0, .L8003F440
/* 2FC38 8003F438 21880000 */   addu      $s1, $zero, $zero
/* 2FC3C 8003F43C 23A07200 */  subu       $s4, $v1, $s2
.L8003F440:
/* 2FC40 8003F440 04006286 */  lh         $v0, 0x4($s3)
/* 2FC44 8003F444 21185402 */  addu       $v1, $s2, $s4
/* 2FC48 8003F448 40004018 */  blez       $v0, .L8003F54C
/* 2FC4C 8003F44C 1000A3AF */   sw        $v1, 0x10($sp)
/* 2FC50 8003F450 0780023C */  lui        $v0, %hi(D_80077260)
/* 2FC54 8003F454 60725524 */  addiu      $s5, $v0, %lo(D_80077260)
.L8003F458:
/* 2FC58 8003F458 1000B08E */  lw         $s0, 0x10($s5)
/* 2FC5C 8003F45C 00000000 */  nop
/* 2FC60 8003F460 14000226 */  addiu      $v0, $s0, 0x14
/* 2FC64 8003F464 1000A2AE */  sw         $v0, 0x10($s5)
/* 2FC68 8003F468 3F002232 */  andi       $v0, $s1, 0x3F
/* 2FC6C 8003F46C 0C0002A2 */  sb         $v0, 0xC($s0)
/* 2FC70 8003F470 20002226 */  addiu      $v0, $s1, 0x20
/* 2FC74 8003F474 080011A6 */  sh         $s1, 0x8($s0)
/* 2FC78 8003F478 0A0012A6 */  sh         $s2, 0xA($s0)
/* 2FC7C 8003F47C 0D0016A2 */  sb         $s6, 0xD($s0)
/* 2FC80 8003F480 04006386 */  lh         $v1, 0x4($s3)
/* 2FC84 8003F484 21F04000 */  addu       $fp, $v0, $zero
/* 2FC88 8003F488 2A186200 */  slt        $v1, $v1, $v0
/* 2FC8C 8003F48C 04006296 */  lhu        $v0, 0x4($s3)
/* 2FC90 8003F490 02006014 */  bnez       $v1, .L8003F49C
/* 2FC94 8003F494 23185100 */   subu      $v1, $v0, $s1
/* 2FC98 8003F498 20000324 */  addiu      $v1, $zero, 0x20
.L8003F49C:
/* 2FC9C 8003F49C 8080023C */  lui        $v0, (0x80808080 >> 16)
/* 2FCA0 8003F4A0 80804234 */  ori        $v0, $v0, (0x80808080 & 0xFFFF)
/* 2FCA4 8003F4A4 21200002 */  addu       $a0, $s0, $zero
/* 2FCA8 8003F4A8 100003A6 */  sh         $v1, 0x10($s0)
/* 2FCAC 8003F4AC 120014A6 */  sh         $s4, 0x12($s0)
/* 2FCB0 8003F4B0 B1FD000C */  jal        func_8003F6C4
/* 2FCB4 8003F4B4 040002AE */   sw        $v0, 0x4($s0)
/* 2FCB8 8003F4B8 21200002 */  addu       $a0, $s0, $zero
/* 2FCBC 8003F4BC A5FD000C */  jal        func_8003F694
/* 2FCC0 8003F4C0 21280000 */   addu      $a1, $zero, $zero
/* 2FCC4 8003F4C4 21200002 */  addu       $a0, $s0, $zero
/* 2FCC8 8003F4C8 C570000C */  jal        func_8001C314
/* 2FCCC 8003F4CC 01000524 */   addiu     $a1, $zero, 0x1
/* 2FCD0 8003F4D0 4000A48F */  lw         $a0, 0x40($sp)
/* 2FCD4 8003F4D4 AD70000C */  jal        AddPrim
/* 2FCD8 8003F4D8 21280002 */   addu      $a1, $s0, $zero
/* 2FCDC 8003F4DC 21280000 */  addu       $a1, $zero, $zero
/* 2FCE0 8003F4E0 1000B08E */  lw         $s0, 0x10($s5)
/* 2FCE4 8003F4E4 21300000 */  addu       $a2, $zero, $zero
/* 2FCE8 8003F4E8 08000226 */  addiu      $v0, $s0, 0x8
/* 2FCEC 8003F4EC 21200002 */  addu       $a0, $s0, $zero
/* 2FCF0 8003F4F0 1000A2AE */  sw         $v0, 0x10($s5)
/* 2FCF4 8003F4F4 0200E786 */  lh         $a3, 0x2($s7)
/* 2FCF8 8003F4F8 0000E286 */  lh         $v0, 0x0($s7)
/* 2FCFC 8003F4FC 2138F200 */  addu       $a3, $a3, $s2
/* 2FD00 8003F500 0001E330 */  andi       $v1, $a3, 0x100
/* 2FD04 8003F504 03190300 */  sra        $v1, $v1, 4
/* 2FD08 8003F508 21105100 */  addu       $v0, $v0, $s1
/* 2FD0C 8003F50C FF034230 */  andi       $v0, $v0, 0x3FF
/* 2FD10 8003F510 83110200 */  sra        $v0, $v0, 6
/* 2FD14 8003F514 00014234 */  ori        $v0, $v0, 0x100
/* 2FD18 8003F518 25186200 */  or         $v1, $v1, $v0
/* 2FD1C 8003F51C 0002E730 */  andi       $a3, $a3, 0x200
/* 2FD20 8003F520 80380700 */  sll        $a3, $a3, 2
/* 2FD24 8003F524 B9FD000C */  jal        SetDrawTPage
/* 2FD28 8003F528 25386700 */   or        $a3, $v1, $a3
/* 2FD2C 8003F52C 4000A48F */  lw         $a0, 0x40($sp)
/* 2FD30 8003F530 AD70000C */  jal        AddPrim
/* 2FD34 8003F534 21280002 */   addu      $a1, $s0, $zero
/* 2FD38 8003F538 04006286 */  lh         $v0, 0x4($s3)
/* 2FD3C 8003F53C 2188C003 */  addu       $s1, $fp, $zero
/* 2FD40 8003F540 2A102202 */  slt        $v0, $s1, $v0
/* 2FD44 8003F544 C4FF4014 */  bnez       $v0, .L8003F458
/* 2FD48 8003F548 00000000 */   nop
.L8003F54C:
/* 2FD4C 8003F54C 06006286 */  lh         $v0, 0x6($s3)
/* 2FD50 8003F550 1000B28F */  lw         $s2, 0x10($sp)
/* 2FD54 8003F554 00000000 */  nop
/* 2FD58 8003F558 2A104202 */  slt        $v0, $s2, $v0
/* 2FD5C 8003F55C A6FF4014 */  bnez       $v0, .L8003F3F8
/* 2FD60 8003F560 00000000 */   nop
.L8003F564:
/* 2FD64 8003F564 3C00BF8F */  lw         $ra, 0x3C($sp)
/* 2FD68 8003F568 3800BE8F */  lw         $fp, 0x38($sp)
/* 2FD6C 8003F56C 3400B78F */  lw         $s7, 0x34($sp)
/* 2FD70 8003F570 3000B68F */  lw         $s6, 0x30($sp)
/* 2FD74 8003F574 2C00B58F */  lw         $s5, 0x2C($sp)
/* 2FD78 8003F578 2800B48F */  lw         $s4, 0x28($sp)
/* 2FD7C 8003F57C 2400B38F */  lw         $s3, 0x24($sp)
/* 2FD80 8003F580 2000B28F */  lw         $s2, 0x20($sp)
/* 2FD84 8003F584 1C00B18F */  lw         $s1, 0x1C($sp)
/* 2FD88 8003F588 1800B08F */  lw         $s0, 0x18($sp)
/* 2FD8C 8003F58C 0800E003 */  jr         $ra
/* 2FD90 8003F590 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_8003F390, . - func_8003F390
