.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel _card_read
/* 4A42C 80059C2C B0000A24 */  addiu      $t2, $zero, 0xB0
/* 4A430 80059C30 08004001 */  jr         $t2
/* 4A434 80059C34 4F000924 */   addiu     $t1, $zero, 0x4F
/* 4A438 80059C38 00000000 */  nop
/* 4A43C 80059C3C 0800E003 */  jr         $ra
/* 4A440 80059C40 18010224 */   addiu     $v0, $zero, 0x118
.size _card_read, . - _card_read
