.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel EnterCriticalSection
/* 8E6C 8001866C 01000424 */  addiu      $a0, $zero, 0x1
/* 8E70 80018670 0C000000 */  syscall    0
/* 8E74 80018674 0800E003 */  jr         $ra
/* 8E78 80018678 00000000 */   nop
.size EnterCriticalSection, . - EnterCriticalSection
