.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel ChangeClearPAD
/* 90CC 800188CC B0000A24 */  addiu      $t2, $zero, 0xB0
/* 90D0 800188D0 08004001 */  jr         $t2
/* 90D4 800188D4 5B000924 */   addiu     $t1, $zero, 0x5B
/* 90D8 800188D8 00000000 */  nop
.size ChangeClearPAD, . - ChangeClearPAD
