.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel strncpy
/* 42864 80052064 A0000A24 */  addiu      $t2, $zero, 0xA0
/* 42868 80052068 08004001 */  jr         $t2
/* 4286C 8005206C 1A000924 */   addiu     $t1, $zero, 0x1A
/* 42870 80052070 00000000 */  nop
.size strncpy, . - strncpy
