.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel SetDefDrawEnv
/* 2FD94 8003F594 D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 2FD98 8003F598 1800B2AF */  sw         $s2, 0x18($sp)
/* 2FD9C 8003F59C 3800B28F */  lw         $s2, 0x38($sp)
/* 2FDA0 8003F5A0 1400B1AF */  sw         $s1, 0x14($sp)
/* 2FDA4 8003F5A4 21888000 */  addu       $s1, $a0, $zero
/* 2FDA8 8003F5A8 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 2FDAC 8003F5AC 2198A000 */  addu       $s3, $a1, $zero
/* 2FDB0 8003F5B0 2000B4AF */  sw         $s4, 0x20($sp)
/* 2FDB4 8003F5B4 21A0C000 */  addu       $s4, $a2, $zero
/* 2FDB8 8003F5B8 1000B0AF */  sw         $s0, 0x10($sp)
/* 2FDBC 8003F5BC 2400BFAF */  sw         $ra, 0x24($sp)
/* 2FDC0 8003F5C0 F464000C */  jal        func_800193D0
/* 2FDC4 8003F5C4 2180E000 */   addu      $s0, $a3, $zero
/* 2FDC8 8003F5C8 01000324 */  addiu      $v1, $zero, 0x1
/* 2FDCC 8003F5CC 000033A6 */  sh         $s3, 0x0($s1)
/* 2FDD0 8003F5D0 020034A6 */  sh         $s4, 0x2($s1)
/* 2FDD4 8003F5D4 040030A6 */  sh         $s0, 0x4($s1)
/* 2FDD8 8003F5D8 0C0020A6 */  sh         $zero, 0xC($s1)
/* 2FDDC 8003F5DC 0E0020A6 */  sh         $zero, 0xE($s1)
/* 2FDE0 8003F5E0 100020A6 */  sh         $zero, 0x10($s1)
/* 2FDE4 8003F5E4 120020A6 */  sh         $zero, 0x12($s1)
/* 2FDE8 8003F5E8 190020A2 */  sb         $zero, 0x19($s1)
/* 2FDEC 8003F5EC 1A0020A2 */  sb         $zero, 0x1A($s1)
/* 2FDF0 8003F5F0 1B0020A2 */  sb         $zero, 0x1B($s1)
/* 2FDF4 8003F5F4 160023A2 */  sb         $v1, 0x16($s1)
/* 2FDF8 8003F5F8 03004010 */  beqz       $v0, .L8003F608
/* 2FDFC 8003F5FC 060032A6 */   sh        $s2, 0x6($s1)
/* 2FE00 8003F600 83FD0008 */  j          E03_OBJ_78
/* 2FE04 8003F604 2101422A */   slti      $v0, $s2, 0x121
.L8003F608:
/* 2FE08 8003F608 0101422A */  slti       $v0, $s2, 0x101
.size SetDefDrawEnv, . - SetDefDrawEnv

glabel E03_OBJ_78
/* 2FE0C 8003F60C 170022A2 */  sb         $v0, 0x17($s1)
/* 2FE10 8003F610 21102002 */  addu       $v0, $s1, $zero
/* 2FE14 8003F614 0A000324 */  addiu      $v1, $zero, 0xA
/* 2FE18 8003F618 080053A4 */  sh         $s3, 0x8($v0)
/* 2FE1C 8003F61C 0A0054A4 */  sh         $s4, 0xA($v0)
/* 2FE20 8003F620 140043A4 */  sh         $v1, 0x14($v0)
/* 2FE24 8003F624 180040A0 */  sb         $zero, 0x18($v0)
/* 2FE28 8003F628 2400BF8F */  lw         $ra, 0x24($sp)
/* 2FE2C 8003F62C 2000B48F */  lw         $s4, 0x20($sp)
/* 2FE30 8003F630 1C00B38F */  lw         $s3, 0x1C($sp)
/* 2FE34 8003F634 1800B28F */  lw         $s2, 0x18($sp)
/* 2FE38 8003F638 1400B18F */  lw         $s1, 0x14($sp)
/* 2FE3C 8003F63C 1000B08F */  lw         $s0, 0x10($sp)
/* 2FE40 8003F640 0800E003 */  jr         $ra
/* 2FE44 8003F644 2800BD27 */   addiu     $sp, $sp, 0x28
/* 2FE48 8003F648 00000000 */  nop
/* 2FE4C 8003F64C 00000000 */  nop
/* 2FE50 8003F650 00000000 */  nop
.size E03_OBJ_78, . - E03_OBJ_78
