.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel PushCallbackFunc
/* 4759C 80056D9C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 475A0 80056DA0 1000BFAF */  sw         $ra, 0x10($sp)
/* 475A4 80056DA4 9C60010C */  jal        MemCardCallback
/* 475A8 80056DA8 21200000 */   addu      $a0, $zero, $zero
/* 475AC 80056DAC 0880013C */  lui        $at, %hi(D_800794A0)
/* 475B0 80056DB0 A09422AC */  sw         $v0, %lo(D_800794A0)($at)
/* 475B4 80056DB4 1000BF8F */  lw         $ra, 0x10($sp)
/* 475B8 80056DB8 1800BD27 */  addiu      $sp, $sp, 0x18
/* 475BC 80056DBC 0800E003 */  jr         $ra
/* 475C0 80056DC0 00000000 */   nop
.size PushCallbackFunc, . - PushCallbackFunc

glabel PullCallbackFunc
/* 475C4 80056DC4 0880043C */  lui        $a0, %hi(D_800794A0)
/* 475C8 80056DC8 A094848C */  lw         $a0, %lo(D_800794A0)($a0)
/* 475CC 80056DCC E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 475D0 80056DD0 1000BFAF */  sw         $ra, 0x10($sp)
/* 475D4 80056DD4 9C60010C */  jal        MemCardCallback
/* 475D8 80056DD8 00000000 */   nop
/* 475DC 80056DDC 1000BF8F */  lw         $ra, 0x10($sp)
/* 475E0 80056DE0 1800BD27 */  addiu      $sp, $sp, 0x18
/* 475E4 80056DE4 0800E003 */  jr         $ra
/* 475E8 80056DE8 00000000 */   nop
.size PullCallbackFunc, . - PullCallbackFunc

glabel McrdGetGlobalStructure
/* 475EC 80056DEC 0880023C */  lui        $v0, %hi(D_80079448)
/* 475F0 80056DF0 0800E003 */  jr         $ra
/* 475F4 80056DF4 48944224 */   addiu     $v0, $v0, %lo(D_80079448)
.size McrdGetGlobalStructure, . - McrdGetGlobalStructure

glabel MemCardStart
/* 475F8 80056DF8 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 475FC 80056DFC 1000B0AF */  sw         $s0, 0x10($sp)
/* 47600 80056E00 0880103C */  lui        $s0, %hi(D_80079448)
/* 47604 80056E04 48941026 */  addiu      $s0, $s0, %lo(D_80079448)
/* 47608 80056E08 1400BFAF */  sw         $ra, 0x14($sp)
/* 4760C 80056E0C 0C0000AE */  sw         $zero, 0xC($s0)
/* 47610 80056E10 7762010C */  jal        UserFuncInit
/* 47614 80056E14 440000AE */   sw        $zero, 0x44($s0)
/* 47618 80056E18 000000AE */  sw         $zero, 0x0($s0)
/* 4761C 80056E1C 040000AE */  sw         $zero, 0x4($s0)
/* 47620 80056E20 080000AE */  sw         $zero, 0x8($s0)
/* 47624 80056E24 540000AE */  sw         $zero, 0x54($s0)
/* 47628 80056E28 5400038E */  lw         $v1, 0x54($s0)
/* 4762C 80056E2C FFFF0224 */  addiu      $v0, $zero, -0x1
/* 47630 80056E30 140002AE */  sw         $v0, 0x14($s0)
/* 47634 80056E34 01000224 */  addiu      $v0, $zero, 0x1
/* 47638 80056E38 4C0002AE */  sw         $v0, 0x4C($s0)
/* 4763C 80056E3C 480002AE */  sw         $v0, 0x48($s0)
/* 47640 80056E40 EF62010C */  jal        _card_start
/* 47644 80056E44 500003AE */   sw        $v1, 0x50($s0)
/* 47648 80056E48 0680053C */  lui        $a1, %hi(LIBMCRD_OBJ_17C8)
/* 4764C 80056E4C 6485A524 */  addiu      $a1, $a1, %lo(LIBMCRD_OBJ_17C8)
/* 47650 80056E50 6C62000C */  jal        VSyncCallbacks
/* 47654 80056E54 07000424 */   addiu     $a0, $zero, 0x7
/* 47658 80056E58 1400BF8F */  lw         $ra, 0x14($sp)
/* 4765C 80056E5C 1000B08F */  lw         $s0, 0x10($sp)
/* 47660 80056E60 0800E003 */  jr         $ra
/* 47664 80056E64 1800BD27 */   addiu     $sp, $sp, 0x18
.size MemCardStart, . - MemCardStart

glabel MemCardStop
/* 47668 80056E68 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 4766C 80056E6C 0880033C */  lui        $v1, %hi(D_80079448)
/* 47670 80056E70 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 47674 80056E74 1000BFAF */  sw         $ra, 0x10($sp)
.L80056E78:
/* 47678 80056E78 0000628C */  lw         $v0, 0x0($v1)
/* 4767C 80056E7C 00000000 */  nop
/* 47680 80056E80 FDFF4014 */  bnez       $v0, .L80056E78
/* 47684 80056E84 07000424 */   addiu     $a0, $zero, 0x7
/* 47688 80056E88 6C62000C */  jal        VSyncCallbacks
/* 4768C 80056E8C 21280000 */   addu      $a1, $zero, $zero
/* 47690 80056E90 6E63010C */  jal        _card_stop
/* 47694 80056E94 00000000 */   nop
/* 47698 80056E98 1000BF8F */  lw         $ra, 0x10($sp)
/* 4769C 80056E9C 1800BD27 */  addiu      $sp, $sp, 0x18
/* 476A0 80056EA0 0800E003 */  jr         $ra
/* 476A4 80056EA4 00000000 */   nop
.size MemCardStop, . - MemCardStop

glabel MemCardExist
/* 476A8 80056EA8 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 476AC 80056EAC 0880033C */  lui        $v1, %hi(D_80079448)
/* 476B0 80056EB0 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 476B4 80056EB4 1000BFAF */  sw         $ra, 0x10($sp)
/* 476B8 80056EB8 0000628C */  lw         $v0, 0x0($v1)
/* 476BC 80056EBC 00000000 */  nop
/* 476C0 80056EC0 0B00401C */  bgtz       $v0, .L80056EF0
/* 476C4 80056EC4 21288000 */   addu      $a1, $a0, $zero
/* 476C8 80056EC8 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_174)
/* 476CC 80056ECC 106F8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_174)
/* 476D0 80056ED0 01000224 */  addiu      $v0, $zero, 0x1
/* 476D4 80056ED4 000062AC */  sw         $v0, 0x0($v1)
/* 476D8 80056ED8 040060AC */  sw         $zero, 0x4($v1)
/* 476DC 80056EDC 080060AC */  sw         $zero, 0x8($v1)
/* 476E0 80056EE0 7B62010C */  jal        UserFuncOpen
/* 476E4 80056EE4 100065AC */   sw        $a1, 0x10($v1)
/* 476E8 80056EE8 C05B0108 */  j          LIBMCRD_OBJ_164
/* 476EC 80056EEC 01000224 */   addiu     $v0, $zero, 0x1
.L80056EF0:
/* 476F0 80056EF0 0180043C */  lui        $a0, %hi(D_80012F68)
/* 476F4 80056EF4 9361000C */  jal        printf
/* 476F8 80056EF8 682F8424 */   addiu     $a0, $a0, %lo(D_80012F68)
/* 476FC 80056EFC 21100000 */  addu       $v0, $zero, $zero
.size MemCardExist, . - MemCardExist

glabel LIBMCRD_OBJ_164
/* 47700 80056F00 1000BF8F */  lw         $ra, 0x10($sp)
/* 47704 80056F04 1800BD27 */  addiu      $sp, $sp, 0x18
/* 47708 80056F08 0800E003 */  jr         $ra
/* 4770C 80056F0C 00000000 */   nop
.size LIBMCRD_OBJ_164, . - LIBMCRD_OBJ_164

glabel LIBMCRD_OBJ_174
/* 47710 80056F10 D8FFBD27 */  addiu      $sp, $sp, -0x28
/* 47714 80056F14 1000B0AF */  sw         $s0, 0x10($sp)
/* 47718 80056F18 21808000 */  addu       $s0, $a0, $zero
/* 4771C 80056F1C 2000BFAF */  sw         $ra, 0x20($sp)
/* 47720 80056F20 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 47724 80056F24 1800B2AF */  sw         $s2, 0x18($sp)
/* 47728 80056F28 1400B1AF */  sw         $s1, 0x14($sp)
/* 4772C 80056F2C 0000038E */  lw         $v1, 0x0($s0)
/* 47730 80056F30 0A001224 */  addiu      $s2, $zero, 0xA
/* 47734 80056F34 1D007210 */  beq        $v1, $s2, .L80056FAC
/* 47738 80056F38 0B006228 */   slti      $v0, $v1, 0xB
/* 4773C 80056F3C 05004010 */  beqz       $v0, .L80056F54
/* 47740 80056F40 0B000224 */   addiu     $v0, $zero, 0xB
/* 47744 80056F44 09006010 */  beqz       $v1, .L80056F6C
/* 47748 80056F48 00000000 */   nop
/* 4774C 80056F4C 805C0108 */  j          LIBMCRD_OBJ_464
/* 47750 80056F50 00000000 */   nop
.L80056F54:
/* 47754 80056F54 20006210 */  beq        $v1, $v0, .L80056FD8
/* 47758 80056F58 15000224 */   addiu     $v0, $zero, 0x15
/* 4775C 80056F5C A0006210 */  beq        $v1, $v0, .L800571E0
/* 47760 80056F60 00000000 */   nop
/* 47764 80056F64 805C0108 */  j          LIBMCRD_OBJ_464
/* 47768 80056F68 00000000 */   nop
.L80056F6C:
/* 4776C 80056F6C 0880023C */  lui        $v0, %hi(D_80079458)
/* 47770 80056F70 58944224 */  addiu      $v0, $v0, %lo(D_80079458)
/* 47774 80056F74 0880013C */  lui        $at, %hi(D_8007941C)
/* 47778 80056F78 1C9420AC */  sw         $zero, %lo(D_8007941C)($at)
/* 4777C 80056F7C 0880013C */  lui        $at, %hi(D_80079418)
/* 47780 80056F80 189420AC */  sw         $zero, %lo(D_80079418)($at)
/* 47784 80056F84 000012AE */  sw         $s2, 0x0($s0)
/* 47788 80056F88 0000438C */  lw         $v1, 0x0($v0)
/* 4778C 80056F8C 40004224 */  addiu      $v0, $v0, 0x40
/* 47790 80056F90 03190300 */  sra        $v1, $v1, 4
/* 47794 80056F94 80180300 */  sll        $v1, $v1, 2
/* 47798 80056F98 21186200 */  addu       $v1, $v1, $v0
/* 4779C 80056F9C 0000628C */  lw         $v0, 0x0($v1)
/* 477A0 80056FA0 000060AC */  sw         $zero, 0x0($v1)
/* 477A4 80056FA4 0780013C */  lui        $at, %hi(D_8006A29C)
/* 477A8 80056FA8 9CA222AC */  sw         $v0, %lo(D_8006A29C)($at)
.L80056FAC:
/* 477AC 80056FAC 9B63010C */  jal        _clr_card_event
/* 477B0 80056FB0 00000000 */   nop
/* 477B4 80056FB4 0880043C */  lui        $a0, %hi(D_80079458)
/* 477B8 80056FB8 5894848C */  lw         $a0, %lo(D_80079458)($a0)
/* 477BC 80056FBC 5762010C */  jal        _card_info
/* 477C0 80056FC0 00000000 */   nop
/* 477C4 80056FC4 0000028E */  lw         $v0, 0x0($s0)
/* 477C8 80056FC8 00000000 */  nop
/* 477CC 80056FCC 01004224 */  addiu      $v0, $v0, 0x1
/* 477D0 80056FD0 835C0108 */  j          LIBMCRD_OBJ_470
/* 477D4 80056FD4 000002AE */   sw        $v0, 0x0($s0)
.L80056FD8:
/* 477D8 80056FD8 4964010C */  jal        _chk_card_event
/* 477DC 80056FDC 00000000 */   nop
/* 477E0 80056FE0 8B004010 */  beqz       $v0, LIBMCRD_OBJ_474
/* 477E4 80056FE4 21100000 */   addu      $v0, $zero, $zero
/* 477E8 80056FE8 DD63010C */  jal        _get_card_event
/* 477EC 80056FEC 00000000 */   nop
/* 477F0 80056FF0 0880113C */  lui        $s1, %hi(D_80079458)
/* 477F4 80056FF4 58943126 */  addiu      $s1, $s1, %lo(D_80079458)
/* 477F8 80056FF8 38003326 */  addiu      $s3, $s1, 0x38
/* 477FC 80056FFC 0000278E */  lw         $a3, 0x0($s1)
/* 47800 80057000 21204000 */  addu       $a0, $v0, $zero
/* 47804 80057004 0880013C */  lui        $at, %hi(D_8007941C)
/* 47808 80057008 1C9422AC */  sw         $v0, %lo(D_8007941C)($at)
/* 4780C 8005700C 03190700 */  sra        $v1, $a3, 4
/* 47810 80057010 80180300 */  sll        $v1, $v1, 2
/* 47814 80057014 21287300 */  addu       $a1, $v1, $s3
/* 47818 80057018 0000A68C */  lw         $a2, 0x0($a1)
/* 4781C 8005701C 01000324 */  addiu      $v1, $zero, 0x1
/* 47820 80057020 0780013C */  lui        $at, %hi(D_8006A2A0)
/* 47824 80057024 A0A226AC */  sw         $a2, %lo(D_8006A2A0)($at)
/* 47828 80057028 47008310 */  beq        $a0, $v1, .L80057148
/* 4782C 8005702C 02008228 */   slti      $v0, $a0, 0x2
/* 47830 80057030 05004010 */  beqz       $v0, .L80057048
/* 47834 80057034 02000224 */   addiu     $v0, $zero, 0x2
/* 47838 80057038 27008010 */  beqz       $a0, .L800570D8
/* 4783C 8005703C 00000000 */   nop
/* 47840 80057040 695C0108 */  j          LIBMCRD_OBJ_408
/* 47844 80057044 00000000 */   nop
.L80057048:
/* 47848 80057048 2E008210 */  beq        $a0, $v0, .L80057104
/* 4784C 8005704C 04000224 */   addiu     $v0, $zero, 0x4
/* 47850 80057050 54008214 */  bne        $a0, $v0, LIBMCRD_OBJ_408
/* 47854 80057054 00000000 */   nop
/* 47858 80057058 0F00C014 */  bnez       $a2, .L80057098
/* 4785C 8005705C 00000000 */   nop
/* 47860 80057060 0780023C */  lui        $v0, %hi(D_8006A29C)
/* 47864 80057064 9CA2428C */  lw         $v0, %lo(D_8006A29C)($v0)
/* 47868 80057068 00000000 */  nop
/* 4786C 8005706C 8000422C */  sltiu      $v0, $v0, 0x80
/* 47870 80057070 09004010 */  beqz       $v0, .L80057098
/* 47874 80057074 00000000 */   nop
/* 47878 80057078 9B63010C */  jal        _clr_card_event
/* 4787C 8005707C 00000000 */   nop
/* 47880 80057080 0000248E */  lw         $a0, 0x0($s1)
/* 47884 80057084 5F62010C */  jal        _card_clear
/* 47888 80057088 00000000 */   nop
/* 4788C 8005708C 15000224 */  addiu      $v0, $zero, 0x15
/* 47890 80057090 835C0108 */  j          LIBMCRD_OBJ_470
/* 47894 80057094 000002AE */   sw        $v0, 0x0($s0)
.L80057098:
/* 47898 80057098 0880103C */  lui        $s0, %hi(D_80079458)
/* 4789C 8005709C 58941026 */  addiu      $s0, $s0, %lo(D_80079458)
/* 478A0 800570A0 01000324 */  addiu      $v1, $zero, 0x1
/* 478A4 800570A4 0000028E */  lw         $v0, 0x0($s0)
/* 478A8 800570A8 0880043C */  lui        $a0, %hi(D_8007941C)
/* 478AC 800570AC 1C94848C */  lw         $a0, %lo(D_8007941C)($a0)
/* 478B0 800570B0 03110200 */  sra        $v0, $v0, 4
/* 478B4 800570B4 80100200 */  sll        $v0, $v0, 2
/* 478B8 800570B8 21100202 */  addu       $v0, $s0, $v0
/* 478BC 800570BC 4461010C */  jal        LIBMCRD_OBJ_1774
/* 478C0 800570C0 380043AC */   sw        $v1, 0x38($v0)
/* 478C4 800570C4 21184000 */  addu       $v1, $v0, $zero
/* 478C8 800570C8 01000224 */  addiu      $v0, $zero, 0x1
/* 478CC 800570CC F0FF1026 */  addiu      $s0, $s0, -0x10
/* 478D0 800570D0 845C0108 */  j          LIBMCRD_OBJ_474
/* 478D4 800570D4 040003AE */   sw        $v1, 0x4($s0)
.L800570D8:
/* 478D8 800570D8 FCFF228E */  lw         $v0, -0x4($s1)
/* 478DC 800570DC 0418E300 */  sllv       $v1, $v1, $a3
/* 478E0 800570E0 24104300 */  and        $v0, $v0, $v1
/* 478E4 800570E4 03004014 */  bnez       $v0, .L800570F4
/* 478E8 800570E8 04000224 */   addiu     $v0, $zero, 0x4
/* 478EC 800570EC 0880013C */  lui        $at, %hi(D_8007941C)
/* 478F0 800570F0 1C9422AC */  sw         $v0, %lo(D_8007941C)($at)
.L800570F4:
/* 478F4 800570F4 0880043C */  lui        $a0, %hi(D_8007941C)
/* 478F8 800570F8 1C94848C */  lw         $a0, %lo(D_8007941C)($a0)
/* 478FC 800570FC 4B5C0108 */  j          LIBMCRD_OBJ_390
/* 47900 80057100 0000A0AC */   sw        $zero, 0x0($a1)
.L80057104:
/* 47904 80057104 0880023C */  lui        $v0, %hi(D_80079418)
/* 47908 80057108 1894428C */  lw         $v0, %lo(D_80079418)($v0)
/* 4790C 8005710C 00000000 */  nop
/* 47910 80057110 01004224 */  addiu      $v0, $v0, 0x1
/* 47914 80057114 0880013C */  lui        $at, %hi(D_80079418)
/* 47918 80057118 189422AC */  sw         $v0, %lo(D_80079418)($at)
/* 4791C 8005711C 03004228 */  slti       $v0, $v0, 0x3
/* 47920 80057120 12004014 */  bnez       $v0, .L8005716C
/* 47924 80057124 02000424 */   addiu     $a0, $zero, 0x2
/* 47928 80057128 0000A3AC */  sw         $v1, 0x0($a1)
.size LIBMCRD_OBJ_174, . - LIBMCRD_OBJ_174

glabel LIBMCRD_OBJ_390
/* 4792C 8005712C 4461010C */  jal        LIBMCRD_OBJ_1774
/* 47930 80057130 00000000 */   nop
/* 47934 80057134 21204000 */  addu       $a0, $v0, $zero
/* 47938 80057138 01000224 */  addiu      $v0, $zero, 0x1
/* 4793C 8005713C F0FF2326 */  addiu      $v1, $s1, -0x10
/* 47940 80057140 845C0108 */  j          LIBMCRD_OBJ_474
/* 47944 80057144 040064AC */   sw        $a0, 0x4($v1)
.L80057148:
/* 47948 80057148 0880023C */  lui        $v0, %hi(D_80079418)
/* 4794C 8005714C 1894428C */  lw         $v0, %lo(D_80079418)($v0)
/* 47950 80057150 00000000 */  nop
/* 47954 80057154 01004224 */  addiu      $v0, $v0, 0x1
/* 47958 80057158 0880013C */  lui        $at, %hi(D_80079418)
/* 4795C 8005715C 189422AC */  sw         $v0, %lo(D_80079418)($at)
/* 47960 80057160 11004228 */  slti       $v0, $v0, 0x11
/* 47964 80057164 03004010 */  beqz       $v0, .L80057174
/* 47968 80057168 00000000 */   nop
.L8005716C:
/* 4796C 8005716C 835C0108 */  j          LIBMCRD_OBJ_470
/* 47970 80057170 000012AE */   sw        $s2, 0x0($s0)
.L80057174:
/* 47974 80057174 4461010C */  jal        LIBMCRD_OBJ_1774
/* 47978 80057178 01000424 */   addiu     $a0, $zero, 0x1
/* 4797C 8005717C 21184000 */  addu       $v1, $v0, $zero
/* 47980 80057180 01000224 */  addiu      $v0, $zero, 0x1
/* 47984 80057184 0000248E */  lw         $a0, 0x0($s1)
/* 47988 80057188 F0FF2526 */  addiu      $a1, $s1, -0x10
/* 4798C 8005718C 0400A3AC */  sw         $v1, 0x4($a1)
/* 47990 80057190 03210400 */  sra        $a0, $a0, 4
/* 47994 80057194 80200400 */  sll        $a0, $a0, 2
/* 47998 80057198 21209300 */  addu       $a0, $a0, $s3
/* 4799C 8005719C 845C0108 */  j          LIBMCRD_OBJ_474
/* 479A0 800571A0 000080AC */   sw        $zero, 0x0($a0)
.size LIBMCRD_OBJ_390, . - LIBMCRD_OBJ_390

glabel LIBMCRD_OBJ_408
/* 479A4 800571A4 0880043C */  lui        $a0, %hi(D_8007941C)
/* 479A8 800571A8 1C94848C */  lw         $a0, %lo(D_8007941C)($a0)
/* 479AC 800571AC 4461010C */  jal        LIBMCRD_OBJ_1774
/* 479B0 800571B0 00000000 */   nop
/* 479B4 800571B4 21284000 */  addu       $a1, $v0, $zero
/* 479B8 800571B8 0880043C */  lui        $a0, %hi(D_80079448)
/* 479BC 800571BC 48948424 */  addiu      $a0, $a0, %lo(D_80079448)
/* 479C0 800571C0 1000838C */  lw         $v1, 0x10($a0)
/* 479C4 800571C4 01000224 */  addiu      $v0, $zero, 0x1
/* 479C8 800571C8 040085AC */  sw         $a1, 0x4($a0)
/* 479CC 800571CC 03190300 */  sra        $v1, $v1, 4
/* 479D0 800571D0 80180300 */  sll        $v1, $v1, 2
/* 479D4 800571D4 21208300 */  addu       $a0, $a0, $v1
/* 479D8 800571D8 845C0108 */  j          LIBMCRD_OBJ_474
/* 479DC 800571DC 480080AC */   sw        $zero, 0x48($a0)
.L800571E0:
/* 479E0 800571E0 5864010C */  jal        _chk_card_event_x
/* 479E4 800571E4 00000000 */   nop
/* 479E8 800571E8 09004010 */  beqz       $v0, LIBMCRD_OBJ_474
/* 479EC 800571EC 21100000 */   addu      $v0, $zero, $zero
/* 479F0 800571F0 1364010C */  jal        _get_card_event_x
/* 479F4 800571F4 00000000 */   nop
/* 479F8 800571F8 835C0108 */  j          LIBMCRD_OBJ_470
/* 479FC 800571FC 000000AE */   sw        $zero, 0x0($s0)
.size LIBMCRD_OBJ_408, . - LIBMCRD_OBJ_408

glabel LIBMCRD_OBJ_464
/* 47A00 80057200 0180043C */  lui        $a0, %hi(D_80012F90)
/* 47A04 80057204 9361000C */  jal        printf
/* 47A08 80057208 902F8424 */   addiu     $a0, $a0, %lo(D_80012F90)
.size LIBMCRD_OBJ_464, . - LIBMCRD_OBJ_464

glabel LIBMCRD_OBJ_470
/* 47A0C 8005720C 21100000 */  addu       $v0, $zero, $zero
glabel LIBMCRD_OBJ_474
/* 47A10 80057210 2000BF8F */  lw         $ra, 0x20($sp)
/* 47A14 80057214 1C00B38F */  lw         $s3, 0x1C($sp)
/* 47A18 80057218 1800B28F */  lw         $s2, 0x18($sp)
/* 47A1C 8005721C 1400B18F */  lw         $s1, 0x14($sp)
/* 47A20 80057220 1000B08F */  lw         $s0, 0x10($sp)
/* 47A24 80057224 0800E003 */  jr         $ra
/* 47A28 80057228 2800BD27 */   addiu     $sp, $sp, 0x28
.size LIBMCRD_OBJ_470, . - LIBMCRD_OBJ_470

glabel MemCardAccept
/* 47A2C 8005722C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 47A30 80057230 0880033C */  lui        $v1, %hi(D_80079448)
/* 47A34 80057234 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 47A38 80057238 1000BFAF */  sw         $ra, 0x10($sp)
/* 47A3C 8005723C 0000628C */  lw         $v0, 0x0($v1)
/* 47A40 80057240 00000000 */  nop
/* 47A44 80057244 0B00401C */  bgtz       $v0, .L80057274
/* 47A48 80057248 21288000 */   addu      $a1, $a0, $zero
/* 47A4C 8005724C 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_4F8)
/* 47A50 80057250 94728424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_4F8)
/* 47A54 80057254 02000224 */  addiu      $v0, $zero, 0x2
/* 47A58 80057258 000062AC */  sw         $v0, 0x0($v1)
/* 47A5C 8005725C 040060AC */  sw         $zero, 0x4($v1)
/* 47A60 80057260 080060AC */  sw         $zero, 0x8($v1)
/* 47A64 80057264 7B62010C */  jal        UserFuncOpen
/* 47A68 80057268 100065AC */   sw        $a1, 0x10($v1)
/* 47A6C 8005726C A15C0108 */  j          LIBMCRD_OBJ_4E8
/* 47A70 80057270 01000224 */   addiu     $v0, $zero, 0x1
.L80057274:
/* 47A74 80057274 0180043C */  lui        $a0, %hi(D_80012F68)
/* 47A78 80057278 9361000C */  jal        printf
/* 47A7C 8005727C 682F8424 */   addiu     $a0, $a0, %lo(D_80012F68)
/* 47A80 80057280 21100000 */  addu       $v0, $zero, $zero
.size MemCardAccept, . - MemCardAccept

glabel LIBMCRD_OBJ_4E8
/* 47A84 80057284 1000BF8F */  lw         $ra, 0x10($sp)
/* 47A88 80057288 1800BD27 */  addiu      $sp, $sp, 0x18
/* 47A8C 8005728C 0800E003 */  jr         $ra
/* 47A90 80057290 00000000 */   nop
.size LIBMCRD_OBJ_4E8, . - LIBMCRD_OBJ_4E8

glabel LIBMCRD_OBJ_4F8
/* 47A94 80057294 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 47A98 80057298 1000B0AF */  sw         $s0, 0x10($sp)
/* 47A9C 8005729C 21808000 */  addu       $s0, $a0, $zero
/* 47AA0 800572A0 1800BFAF */  sw         $ra, 0x18($sp)
/* 47AA4 800572A4 1400B1AF */  sw         $s1, 0x14($sp)
/* 47AA8 800572A8 0000038E */  lw         $v1, 0x0($s0)
/* 47AAC 800572AC 00000000 */  nop
/* 47AB0 800572B0 3300622C */  sltiu      $v0, $v1, 0x33
/* 47AB4 800572B4 9B004010 */  beqz       $v0, LIBMCRD_OBJ_788
/* 47AB8 800572B8 80100300 */   sll       $v0, $v1, 2
/* 47ABC 800572BC 0180013C */  lui        $at, %hi(jtbl_80012F98)
/* 47AC0 800572C0 21082200 */  addu       $at, $at, $v0
/* 47AC4 800572C4 982F228C */  lw         $v0, %lo(jtbl_80012F98)($at)
/* 47AC8 800572C8 00000000 */  nop
/* 47ACC 800572CC 08004000 */  jr         $v0
/* 47AD0 800572D0 00000000 */   nop
.size LIBMCRD_OBJ_4F8, . - LIBMCRD_OBJ_4F8

jlabel LIBMCRD_OBJ_538
/* 47AD4 800572D4 0880013C */  lui        $at, %hi(D_80079424)
/* 47AD8 800572D8 249420AC */  sw         $zero, %lo(D_80079424)($at)
/* 47ADC 800572DC 0880013C */  lui        $at, %hi(D_80079428)
/* 47AE0 800572E0 289420AC */  sw         $zero, %lo(D_80079428)($at)
/* 47AE4 800572E4 0880013C */  lui        $at, %hi(D_80079420)
/* 47AE8 800572E8 209420AC */  sw         $zero, %lo(D_80079420)($at)
/* 47AEC 800572EC 0880013C */  lui        $at, %hi(D_80079430)
/* 47AF0 800572F0 309420AC */  sw         $zero, %lo(D_80079430)($at)
/* 47AF4 800572F4 0880013C */  lui        $at, %hi(D_8007942C)
/* 47AF8 800572F8 2C9420AC */  sw         $zero, %lo(D_8007942C)($at)
/* 47AFC 800572FC 0000028E */  lw         $v0, 0x0($s0)
/* 47B00 80057300 00000000 */  nop
/* 47B04 80057304 01004224 */  addiu      $v0, $v0, 0x1
/* 47B08 80057308 000002AE */  sw         $v0, 0x0($s0)
.size LIBMCRD_OBJ_538, . - LIBMCRD_OBJ_538

glabel LIBMCRD_OBJ_570
/* 47B0C 8005730C 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_174)
/* 47B10 80057310 7B62010C */  jal        UserFuncOpen
/* 47B14 80057314 106F8424 */   addiu     $a0, $a0, %lo(LIBMCRD_OBJ_174)
/* 47B18 80057318 485D0108 */  j          LIBMCRD_OBJ_784
/* 47B1C 8005731C 0A000224 */   addiu     $v0, $zero, 0xA
.size LIBMCRD_OBJ_570, . - LIBMCRD_OBJ_570

glabel LIBMCRD_OBJ_584
/* 47B20 80057320 0880113C */  lui        $s1, %hi(D_8007944C)
/* 47B24 80057324 4C943126 */  addiu      $s1, $s1, %lo(D_8007944C)
/* 47B28 80057328 0000238E */  lw         $v1, 0x0($s1)
/* 47B2C 8005732C 01000524 */  addiu      $a1, $zero, 0x1
/* 47B30 80057330 4B006510 */  beq        $v1, $a1, .L80057460
/* 47B34 80057334 02006228 */   slti      $v0, $v1, 0x2
/* 47B38 80057338 05004010 */  beqz       $v0, LIBMCRD_OBJ_5B4
/* 47B3C 8005733C 03000224 */   addiu     $v0, $zero, 0x3
/* 47B40 80057340 13006010 */  beqz       $v1, .L80057390
/* 47B44 80057344 01000224 */   addiu     $v0, $zero, 0x1
/* 47B48 80057348 4A5D0108 */  j          LIBMCRD_OBJ_78C
/* 47B4C 8005734C 00000000 */   nop
.size LIBMCRD_OBJ_584, . - LIBMCRD_OBJ_584

glabel LIBMCRD_OBJ_5B4
/* 47B50 80057350 43006214 */  bne        $v1, $v0, .L80057460
/* 47B54 80057354 00000000 */   nop
/* 47B58 80057358 0C00228E */  lw         $v0, 0xC($s1)
/* 47B5C 8005735C 0800238E */  lw         $v1, 0x8($s1)
/* 47B60 80057360 FCFF2426 */  addiu      $a0, $s1, -0x4
/* 47B64 80057364 0880013C */  lui        $at, %hi(D_80079430)
/* 47B68 80057368 309425AC */  sw         $a1, %lo(D_80079430)($at)
/* 47B6C 8005736C 04104500 */  sllv       $v0, $a1, $v0
/* 47B70 80057370 25186200 */  or         $v1, $v1, $v0
/* 47B74 80057374 9B63010C */  jal        _clr_card_event
/* 47B78 80057378 0C0083AC */   sw        $v1, 0xC($a0)
/* 47B7C 8005737C 0C00248E */  lw         $a0, 0xC($s1)
/* 47B80 80057380 5F62010C */  jal        _card_clear
/* 47B84 80057384 00000000 */   nop
/* 47B88 80057388 485D0108 */  j          LIBMCRD_OBJ_784
/* 47B8C 8005738C 15000224 */   addiu     $v0, $zero, 0x15
.L80057390:
/* 47B90 80057390 485D0108 */  j          LIBMCRD_OBJ_784
/* 47B94 80057394 1E000224 */   addiu     $v0, $zero, 0x1E
.size LIBMCRD_OBJ_5B4, . - LIBMCRD_OBJ_5B4

glabel LIBMCRD_OBJ_5FC
/* 47B98 80057398 5864010C */  jal        _chk_card_event_x
/* 47B9C 8005739C 00000000 */   nop
/* 47BA0 800573A0 60004010 */  beqz       $v0, LIBMCRD_OBJ_788
/* 47BA4 800573A4 00000000 */   nop
/* 47BA8 800573A8 1364010C */  jal        _get_card_event_x
/* 47BAC 800573AC 00000000 */   nop
/* 47BB0 800573B0 1E000224 */  addiu      $v0, $zero, 0x1E
/* 47BB4 800573B4 000002AE */  sw         $v0, 0x0($s0)
.size LIBMCRD_OBJ_5FC, . - LIBMCRD_OBJ_5FC

glabel LIBMCRD_OBJ_61C
/* 47BB8 800573B8 9B63010C */  jal        _clr_card_event
/* 47BBC 800573BC 00000000 */   nop
/* 47BC0 800573C0 0880043C */  lui        $a0, %hi(D_80079458)
/* 47BC4 800573C4 5894848C */  lw         $a0, %lo(D_80079458)($a0)
/* 47BC8 800573C8 5B62010C */  jal        _card_load
/* 47BCC 800573CC 00000000 */   nop
/* 47BD0 800573D0 0000028E */  lw         $v0, 0x0($s0)
/* 47BD4 800573D4 485D0108 */  j          LIBMCRD_OBJ_784
/* 47BD8 800573D8 01004224 */   addiu     $v0, $v0, 0x1
.size LIBMCRD_OBJ_61C, . - LIBMCRD_OBJ_61C

glabel LIBMCRD_OBJ_640
/* 47BDC 800573DC 4964010C */  jal        _chk_card_event
/* 47BE0 800573E0 00000000 */   nop
/* 47BE4 800573E4 50004010 */  beqz       $v0, LIBMCRD_OBJ_78C
/* 47BE8 800573E8 21100000 */   addu      $v0, $zero, $zero
/* 47BEC 800573EC DD63010C */  jal        _get_card_event
/* 47BF0 800573F0 00000000 */   nop
/* 47BF4 800573F4 21184000 */  addu       $v1, $v0, $zero
/* 47BF8 800573F8 0880013C */  lui        $at, %hi(D_8007942C)
/* 47BFC 800573FC 2C9422AC */  sw         $v0, %lo(D_8007942C)($at)
/* 47C00 80057400 01000424 */  addiu      $a0, $zero, 0x1
/* 47C04 80057404 22006410 */  beq        $v1, $a0, .L80057490
/* 47C08 80057408 02006228 */   slti      $v0, $v1, 0x2
/* 47C0C 8005740C 05004010 */  beqz       $v0, .L80057424
/* 47C10 80057410 02000224 */   addiu     $v0, $zero, 0x2
/* 47C14 80057414 09006010 */  beqz       $v1, .L8005743C
/* 47C18 80057418 00000000 */   nop
/* 47C1C 8005741C 2D5D0108 */  j          LIBMCRD_OBJ_718
/* 47C20 80057420 00000000 */   nop
.L80057424:
/* 47C24 80057424 18006210 */  beq        $v1, $v0, .L80057488
/* 47C28 80057428 04000224 */   addiu     $v0, $zero, 0x4
/* 47C2C 8005742C 0E006210 */  beq        $v1, $v0, .L80057468
/* 47C30 80057430 00000000 */   nop
/* 47C34 80057434 2D5D0108 */  j          LIBMCRD_OBJ_718
/* 47C38 80057438 00000000 */   nop
.L8005743C:
/* 47C3C 8005743C 0880023C */  lui        $v0, %hi(D_80079430)
/* 47C40 80057440 3094428C */  lw         $v0, %lo(D_80079430)($v0)
/* 47C44 80057444 00000000 */  nop
/* 47C48 80057448 02004010 */  beqz       $v0, .L80057454
/* 47C4C 8005744C 21180000 */   addu      $v1, $zero, $zero
/* 47C50 80057450 03000324 */  addiu      $v1, $zero, 0x3
.L80057454:
/* 47C54 80057454 0880023C */  lui        $v0, %hi(D_80079448)
/* 47C58 80057458 48944224 */  addiu      $v0, $v0, %lo(D_80079448)
/* 47C5C 8005745C 040043AC */  sw         $v1, 0x4($v0)
.L80057460:
/* 47C60 80057460 4A5D0108 */  j          LIBMCRD_OBJ_78C
/* 47C64 80057464 01000224 */   addiu     $v0, $zero, 0x1
.L80057468:
/* 47C68 80057468 9B63010C */  jal        _clr_card_event
/* 47C6C 8005746C 00000000 */   nop
/* 47C70 80057470 0880043C */  lui        $a0, %hi(D_80079458)
/* 47C74 80057474 5894848C */  lw         $a0, %lo(D_80079458)($a0)
/* 47C78 80057478 5762010C */  jal        _card_info
/* 47C7C 8005747C 00000000 */   nop
/* 47C80 80057480 485D0108 */  j          LIBMCRD_OBJ_784
/* 47C84 80057484 32000224 */   addiu     $v0, $zero, 0x32
.L80057488:
/* 47C88 80057488 495D0108 */  j          LIBMCRD_OBJ_788
/* 47C8C 8005748C 000004AE */   sw        $a0, 0x0($s0)
.L80057490:
/* 47C90 80057490 0880023C */  lui        $v0, %hi(D_80079424)
/* 47C94 80057494 2494428C */  lw         $v0, %lo(D_80079424)($v0)
/* 47C98 80057498 00000000 */  nop
/* 47C9C 8005749C 01004224 */  addiu      $v0, $v0, 0x1
/* 47CA0 800574A0 0880013C */  lui        $at, %hi(D_80079424)
/* 47CA4 800574A4 249422AC */  sw         $v0, %lo(D_80079424)($at)
/* 47CA8 800574A8 11004228 */  slti       $v0, $v0, 0x11
/* 47CAC 800574AC 1C004014 */  bnez       $v0, LIBMCRD_OBJ_784
/* 47CB0 800574B0 1E000224 */   addiu     $v0, $zero, 0x1E
.size LIBMCRD_OBJ_640, . - LIBMCRD_OBJ_640

glabel LIBMCRD_OBJ_718
/* 47CB4 800574B4 0880043C */  lui        $a0, %hi(D_8007942C)
/* 47CB8 800574B8 2C94848C */  lw         $a0, %lo(D_8007942C)($a0)
/* 47CBC 800574BC 4461010C */  jal        LIBMCRD_OBJ_1774
/* 47CC0 800574C0 00000000 */   nop
/* 47CC4 800574C4 21204000 */  addu       $a0, $v0, $zero
/* 47CC8 800574C8 01000224 */  addiu      $v0, $zero, 0x1
/* 47CCC 800574CC 0880033C */  lui        $v1, %hi(D_80079448)
/* 47CD0 800574D0 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 47CD4 800574D4 4A5D0108 */  j          LIBMCRD_OBJ_78C
/* 47CD8 800574D8 040064AC */   sw        $a0, 0x4($v1)
.size LIBMCRD_OBJ_718, . - LIBMCRD_OBJ_718

glabel LIBMCRD_OBJ_740
/* 47CDC 800574DC 4964010C */  jal        _chk_card_event
/* 47CE0 800574E0 00000000 */   nop
/* 47CE4 800574E4 10004010 */  beqz       $v0, LIBMCRD_OBJ_78C
/* 47CE8 800574E8 21100000 */   addu      $v0, $zero, $zero
/* 47CEC 800574EC DD63010C */  jal        _get_card_event
/* 47CF0 800574F0 00000000 */   nop
/* 47CF4 800574F4 21184000 */  addu       $v1, $v0, $zero
/* 47CF8 800574F8 0880013C */  lui        $at, %hi(D_8007942C)
/* 47CFC 800574FC 2C9422AC */  sw         $v0, %lo(D_8007942C)($at)
/* 47D00 80057500 07006014 */  bnez       $v1, LIBMCRD_OBJ_784
/* 47D04 80057504 01000224 */   addiu     $v0, $zero, 0x1
/* 47D08 80057508 0880033C */  lui        $v1, %hi(D_80079448)
/* 47D0C 8005750C 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 47D10 80057510 04000224 */  addiu      $v0, $zero, 0x4
/* 47D14 80057514 040062AC */  sw         $v0, 0x4($v1)
/* 47D18 80057518 4A5D0108 */  j          LIBMCRD_OBJ_78C
/* 47D1C 8005751C 01000224 */   addiu     $v0, $zero, 0x1
.size LIBMCRD_OBJ_740, . - LIBMCRD_OBJ_740

glabel LIBMCRD_OBJ_784
/* 47D20 80057520 000002AE */  sw         $v0, 0x0($s0)
glabel LIBMCRD_OBJ_788
/* 47D24 80057524 21100000 */  addu       $v0, $zero, $zero
.size LIBMCRD_OBJ_784, . - LIBMCRD_OBJ_784

glabel LIBMCRD_OBJ_78C
/* 47D28 80057528 1800BF8F */  lw         $ra, 0x18($sp)
/* 47D2C 8005752C 1400B18F */  lw         $s1, 0x14($sp)
/* 47D30 80057530 1000B08F */  lw         $s0, 0x10($sp)
/* 47D34 80057534 0800E003 */  jr         $ra
/* 47D38 80057538 2000BD27 */   addiu     $sp, $sp, 0x20
.size LIBMCRD_OBJ_78C, . - LIBMCRD_OBJ_78C

glabel MemCardOpen
/* 47D3C 8005753C C8FFBD27 */  addiu      $sp, $sp, -0x38
/* 47D40 80057540 2400B3AF */  sw         $s3, 0x24($sp)
/* 47D44 80057544 21988000 */  addu       $s3, $a0, $zero
/* 47D48 80057548 2800B4AF */  sw         $s4, 0x28($sp)
/* 47D4C 8005754C 21A0A000 */  addu       $s4, $a1, $zero
/* 47D50 80057550 2C00B5AF */  sw         $s5, 0x2C($sp)
/* 47D54 80057554 21A8C000 */  addu       $s5, $a2, $zero
/* 47D58 80057558 1C00B1AF */  sw         $s1, 0x1C($sp)
/* 47D5C 8005755C 0880113C */  lui        $s1, %hi(D_8007945C)
/* 47D60 80057560 5C943126 */  addiu      $s1, $s1, %lo(D_8007945C)
/* 47D64 80057564 3000BFAF */  sw         $ra, 0x30($sp)
/* 47D68 80057568 2000B2AF */  sw         $s2, 0x20($sp)
/* 47D6C 8005756C 1800B0AF */  sw         $s0, 0x18($sp)
/* 47D70 80057570 0000228E */  lw         $v0, 0x0($s1)
/* 47D74 80057574 00000000 */  nop
/* 47D78 80057578 06004004 */  bltz       $v0, .L80057594
/* 47D7C 8005757C 21900000 */   addu      $s2, $zero, $zero
/* 47D80 80057580 0180043C */  lui        $a0, %hi(D_80013064)
/* 47D84 80057584 9361000C */  jal        printf
/* 47D88 80057588 64308424 */   addiu     $a0, $a0, %lo(D_80013064)
/* 47D8C 8005758C A85D0108 */  j          LIBMCRD_OBJ_904
/* 47D90 80057590 FFFF0224 */   addiu     $v0, $zero, -0x1
.L80057594:
/* 47D94 80057594 21206002 */  addu       $a0, $s3, $zero
/* 47D98 80057598 10003026 */  addiu      $s0, $s1, 0x10
/* 47D9C 8005759C 8461010C */  jal        LIBMCRD_OBJ_1874
/* 47DA0 800575A0 21280002 */   addu      $a1, $s0, $zero
/* 47DA4 800575A4 21200002 */  addu       $a0, $s0, $zero
/* 47DA8 800575A8 DBE3000C */  jal        strcat
/* 47DAC 800575AC 21288002 */   addu      $a1, $s4, $zero
/* 47DB0 800575B0 FCFF33AE */  sw         $s3, -0x4($s1)
/* 47DB4 800575B4 ECFF3426 */  addiu      $s4, $s1, -0x14
/* 47DB8 800575B8 02001124 */  addiu      $s1, $zero, 0x2
.L800575BC:
/* 47DBC 800575BC 21200002 */  addu       $a0, $s0, $zero
.L800575C0:
/* 47DC0 800575C0 9B61010C */  jal        open
/* 47DC4 800575C4 01000524 */   addiu     $a1, $zero, 0x1
/* 47DC8 800575C8 2C004104 */  bgez       $v0, .L8005767C
/* 47DCC 800575CC 00000000 */   nop
/* 47DD0 800575D0 9C60010C */  jal        MemCardCallback
/* 47DD4 800575D4 21200000 */   addu      $a0, $zero, $zero
/* 47DD8 800575D8 DCFF038E */  lw         $v1, -0x24($s0)
/* 47DDC 800575DC 0880013C */  lui        $at, %hi(D_800794A0)
/* 47DE0 800575E0 06006018 */  blez       $v1, .L800575FC
/* 47DE4 800575E4 A09422AC */   sw        $v0, %lo(D_800794A0)($at)
/* 47DE8 800575E8 0180043C */  lui        $a0, %hi(D_80012F68)
/* 47DEC 800575EC 9361000C */  jal        printf
/* 47DF0 800575F0 682F8424 */   addiu     $a0, $a0, %lo(D_80012F68)
/* 47DF4 800575F4 885D0108 */  j          LIBMCRD_OBJ_884
/* 47DF8 800575F8 21200000 */   addu      $a0, $zero, $zero
.L800575FC:
/* 47DFC 800575FC 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_4F8)
/* 47E00 80057600 94728424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_4F8)
/* 47E04 80057604 DCFF11AE */  sw         $s1, -0x24($s0)
/* 47E08 80057608 040080AE */  sw         $zero, 0x4($s4)
/* 47E0C 8005760C 080080AE */  sw         $zero, 0x8($s4)
/* 47E10 80057610 0880013C */  lui        $at, %hi(D_80079458)
/* 47E14 80057614 7B62010C */  jal        UserFuncOpen
/* 47E18 80057618 589433AC */   sw        $s3, %lo(D_80079458)($at)
/* 47E1C 8005761C 21200000 */  addu       $a0, $zero, $zero
.size MemCardOpen, . - MemCardOpen

glabel LIBMCRD_OBJ_884
/* 47E20 80057620 21280000 */  addu       $a1, $zero, $zero
/* 47E24 80057624 A160010C */  jal        MemCardSync
/* 47E28 80057628 1000A627 */   addiu     $a2, $sp, 0x10
/* 47E2C 8005762C 0880043C */  lui        $a0, %hi(D_800794A0)
/* 47E30 80057630 A094848C */  lw         $a0, %lo(D_800794A0)($a0)
/* 47E34 80057634 9C60010C */  jal        MemCardCallback
/* 47E38 80057638 00000000 */   nop
/* 47E3C 8005763C 1000A38F */  lw         $v1, 0x10($sp)
/* 47E40 80057640 03000224 */  addiu      $v0, $zero, 0x3
/* 47E44 80057644 DEFF6210 */  beq        $v1, $v0, .L800575C0
/* 47E48 80057648 21200002 */   addu      $a0, $s0, $zero
/* 47E4C 8005764C 05007114 */  bne        $v1, $s1, .L80057664
/* 47E50 80057650 00000000 */   nop
/* 47E54 80057654 01005226 */  addiu      $s2, $s2, 0x1
/* 47E58 80057658 0500422A */  slti       $v0, $s2, 0x5
/* 47E5C 8005765C D7FF4014 */  bnez       $v0, .L800575BC
/* 47E60 80057660 00000000 */   nop
.L80057664:
/* 47E64 80057664 02006014 */  bnez       $v1, .L80057670
/* 47E68 80057668 05000224 */   addiu     $v0, $zero, 0x5
/* 47E6C 8005766C 1000A2AF */  sw         $v0, 0x10($sp)
.L80057670:
/* 47E70 80057670 1000A28F */  lw         $v0, 0x10($sp)
/* 47E74 80057674 A85D0108 */  j          LIBMCRD_OBJ_904
/* 47E78 80057678 00000000 */   nop
.L8005767C:
/* 47E7C 8005767C A361010C */  jal        close
/* 47E80 80057680 21204000 */   addu      $a0, $v0, $zero
/* 47E84 80057684 9B63010C */  jal        _clr_card_event
/* 47E88 80057688 00000000 */   nop
/* 47E8C 8005768C 21200002 */  addu       $a0, $s0, $zero
/* 47E90 80057690 9B61010C */  jal        open
/* 47E94 80057694 0080A536 */   ori       $a1, $s5, 0x8000
/* 47E98 80057698 F0FF02AE */  sw         $v0, -0x10($s0)
/* 47E9C 8005769C 21100000 */  addu       $v0, $zero, $zero
.size LIBMCRD_OBJ_884, . - LIBMCRD_OBJ_884

glabel LIBMCRD_OBJ_904
/* 47EA0 800576A0 3000BF8F */  lw         $ra, 0x30($sp)
/* 47EA4 800576A4 2C00B58F */  lw         $s5, 0x2C($sp)
/* 47EA8 800576A8 2800B48F */  lw         $s4, 0x28($sp)
/* 47EAC 800576AC 2400B38F */  lw         $s3, 0x24($sp)
/* 47EB0 800576B0 2000B28F */  lw         $s2, 0x20($sp)
/* 47EB4 800576B4 1C00B18F */  lw         $s1, 0x1C($sp)
/* 47EB8 800576B8 1800B08F */  lw         $s0, 0x18($sp)
/* 47EBC 800576BC 0800E003 */  jr         $ra
/* 47EC0 800576C0 3800BD27 */   addiu     $sp, $sp, 0x38
.size LIBMCRD_OBJ_904, . - LIBMCRD_OBJ_904

glabel MemCardClose
/* 47EC4 800576C4 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 47EC8 800576C8 1000B0AF */  sw         $s0, 0x10($sp)
/* 47ECC 800576CC 0880103C */  lui        $s0, %hi(D_8007945C)
/* 47ED0 800576D0 5C941026 */  addiu      $s0, $s0, %lo(D_8007945C)
/* 47ED4 800576D4 1400BFAF */  sw         $ra, 0x14($sp)
/* 47ED8 800576D8 0000048E */  lw         $a0, 0x0($s0)
/* 47EDC 800576DC 00000000 */  nop
/* 47EE0 800576E0 05008004 */  bltz       $a0, .L800576F8
/* 47EE4 800576E4 00000000 */   nop
/* 47EE8 800576E8 A361010C */  jal        close
/* 47EEC 800576EC 00000000 */   nop
/* 47EF0 800576F0 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 47EF4 800576F4 000002AE */  sw         $v0, 0x0($s0)
.L800576F8:
/* 47EF8 800576F8 1400BF8F */  lw         $ra, 0x14($sp)
/* 47EFC 800576FC 1000B08F */  lw         $s0, 0x10($sp)
/* 47F00 80057700 0800E003 */  jr         $ra
/* 47F04 80057704 1800BD27 */   addiu     $sp, $sp, 0x18
.size MemCardClose, . - MemCardClose

glabel MemCardReadData
/* 47F08 80057708 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 47F0C 8005770C 0880073C */  lui        $a3, %hi(D_8007945C)
/* 47F10 80057710 5C94E724 */  addiu      $a3, $a3, %lo(D_8007945C)
/* 47F14 80057714 1000BFAF */  sw         $ra, 0x10($sp)
/* 47F18 80057718 0000E28C */  lw         $v0, 0x0($a3)
/* 47F1C 8005771C 00000000 */  nop
/* 47F20 80057720 04004104 */  bgez       $v0, .L80057734
/* 47F24 80057724 21408000 */   addu      $t0, $a0, $zero
/* 47F28 80057728 0180043C */  lui        $a0, %hi(D_8001308C)
/* 47F2C 8005772C E95D0108 */  j          LIBMCRD_OBJ_A08
/* 47F30 80057730 8C308424 */   addiu     $a0, $a0, %lo(D_8001308C)
.L80057734:
/* 47F34 80057734 ECFFE28C */  lw         $v0, -0x14($a3)
/* 47F38 80057738 00000000 */  nop
/* 47F3C 8005773C 04004018 */  blez       $v0, .L80057750
/* 47F40 80057740 ECFFE324 */   addiu     $v1, $a3, -0x14
/* 47F44 80057744 0180043C */  lui        $a0, %hi(D_80012F68)
/* 47F48 80057748 E95D0108 */  j          LIBMCRD_OBJ_A08
/* 47F4C 8005774C 682F8424 */   addiu     $a0, $a0, %lo(D_80012F68)
.L80057750:
/* 47F50 80057750 7F00C230 */  andi       $v0, $a2, 0x7F
/* 47F54 80057754 04004010 */  beqz       $v0, .L80057768
/* 47F58 80057758 7F00A230 */   andi      $v0, $a1, 0x7F
/* 47F5C 8005775C 0180043C */  lui        $a0, %hi(D_800130B0)
/* 47F60 80057760 E95D0108 */  j          LIBMCRD_OBJ_A08
/* 47F64 80057764 B0308424 */   addiu     $a0, $a0, %lo(D_800130B0)
.L80057768:
/* 47F68 80057768 0C004014 */  bnez       $v0, .L8005779C
/* 47F6C 8005776C 05000224 */   addiu     $v0, $zero, 0x5
/* 47F70 80057770 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_A24)
/* 47F74 80057774 C0778424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_A24)
/* 47F78 80057778 ECFFE2AC */  sw         $v0, -0x14($a3)
/* 47F7C 8005777C 040060AC */  sw         $zero, 0x4($v1)
/* 47F80 80057780 080060AC */  sw         $zero, 0x8($v1)
/* 47F84 80057784 180065AC */  sw         $a1, 0x18($v1)
/* 47F88 80057788 200068AC */  sw         $t0, 0x20($v1)
/* 47F8C 8005778C 7B62010C */  jal        UserFuncOpen
/* 47F90 80057790 1C0066AC */   sw        $a2, 0x1C($v1)
/* 47F94 80057794 EC5D0108 */  j          LIBMCRD_OBJ_A14
/* 47F98 80057798 01000224 */   addiu     $v0, $zero, 0x1
.L8005779C:
/* 47F9C 8005779C 0180043C */  lui        $a0, %hi(D_800130DC)
/* 47FA0 800577A0 DC308424 */  addiu      $a0, $a0, %lo(D_800130DC)
.size MemCardReadData, . - MemCardReadData

glabel LIBMCRD_OBJ_A08
/* 47FA4 800577A4 9361000C */  jal        printf
/* 47FA8 800577A8 00000000 */   nop
/* 47FAC 800577AC 21100000 */  addu       $v0, $zero, $zero
.size LIBMCRD_OBJ_A08, . - LIBMCRD_OBJ_A08

glabel LIBMCRD_OBJ_A14
/* 47FB0 800577B0 1000BF8F */  lw         $ra, 0x10($sp)
/* 47FB4 800577B4 1800BD27 */  addiu      $sp, $sp, 0x18
/* 47FB8 800577B8 0800E003 */  jr         $ra
/* 47FBC 800577BC 00000000 */   nop
.size LIBMCRD_OBJ_A14, . - LIBMCRD_OBJ_A14

glabel LIBMCRD_OBJ_A24
/* 47FC0 800577C0 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 47FC4 800577C4 1400B1AF */  sw         $s1, 0x14($sp)
/* 47FC8 800577C8 21888000 */  addu       $s1, $a0, $zero
/* 47FCC 800577CC 1800BFAF */  sw         $ra, 0x18($sp)
/* 47FD0 800577D0 1000B0AF */  sw         $s0, 0x10($sp)
/* 47FD4 800577D4 0000238E */  lw         $v1, 0x0($s1)
/* 47FD8 800577D8 0A001024 */  addiu      $s0, $zero, 0xA
/* 47FDC 800577DC 15007010 */  beq        $v1, $s0, .L80057834
/* 47FE0 800577E0 0B006228 */   slti      $v0, $v1, 0xB
/* 47FE4 800577E4 05004010 */  beqz       $v0, LIBMCRD_OBJ_A60
/* 47FE8 800577E8 1E000224 */   addiu     $v0, $zero, 0x1E
/* 47FEC 800577EC 09006010 */  beqz       $v1, .L80057814
/* 47FF0 800577F0 21100000 */   addu      $v0, $zero, $zero
/* 47FF4 800577F4 575E0108 */  j          LIBMCRD_OBJ_BC0
/* 47FF8 800577F8 00000000 */   nop
.size LIBMCRD_OBJ_A24, . - LIBMCRD_OBJ_A24

glabel LIBMCRD_OBJ_A60
/* 47FFC 800577FC 29006210 */  beq        $v1, $v0, .L800578A4
/* 48000 80057800 20000224 */   addiu     $v0, $zero, 0x20
/* 48004 80057804 4D006210 */  beq        $v1, $v0, .L8005793C
/* 48008 80057808 21100000 */   addu      $v0, $zero, $zero
/* 4800C 8005780C 575E0108 */  j          LIBMCRD_OBJ_BC0
/* 48010 80057810 00000000 */   nop
.L80057814:
/* 48014 80057814 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_174)
/* 48018 80057818 106F8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_174)
/* 4801C 8005781C 0780013C */  lui        $at, %hi(D_8006A2A4)
/* 48020 80057820 A4A220AC */  sw         $zero, %lo(D_8006A2A4)($at)
/* 48024 80057824 7B62010C */  jal        UserFuncOpen
/* 48028 80057828 000030AE */   sw        $s0, 0x0($s1)
/* 4802C 8005782C 575E0108 */  j          LIBMCRD_OBJ_BC0
/* 48030 80057830 21100000 */   addu      $v0, $zero, $zero
.L80057834:
/* 48034 80057834 0880043C */  lui        $a0, %hi(D_8007944C)
/* 48038 80057838 4C948424 */  addiu      $a0, $a0, %lo(D_8007944C)
/* 4803C 8005783C 0000828C */  lw         $v0, 0x0($a0)
/* 48040 80057840 00000000 */  nop
/* 48044 80057844 45004014 */  bnez       $v0, LIBMCRD_OBJ_BC0
/* 48048 80057848 01000224 */   addiu     $v0, $zero, 0x1
/* 4804C 8005784C 10009024 */  addiu      $s0, $a0, 0x10
.L80057850:
/* 48050 80057850 0000048E */  lw         $a0, 0x0($s0)
/* 48054 80057854 0400058E */  lw         $a1, 0x4($s0)
/* 48058 80057858 9F61010C */  jal        lseek
/* 4805C 8005785C 21300000 */   addu      $a2, $zero, $zero
/* 48060 80057860 0400038E */  lw         $v1, 0x4($s0)
/* 48064 80057864 00000000 */  nop
/* 48068 80057868 F9FF4314 */  bne        $v0, $v1, .L80057850
/* 4806C 8005786C 00000000 */   nop
/* 48070 80057870 9B63010C */  jal        _clr_card_event
/* 48074 80057874 00000000 */   nop
/* 48078 80057878 0880103C */  lui        $s0, %hi(D_8007945C)
/* 4807C 8005787C 5C941026 */  addiu      $s0, $s0, %lo(D_8007945C)
.L80057880:
/* 48080 80057880 0000048E */  lw         $a0, 0x0($s0)
/* 48084 80057884 0C00058E */  lw         $a1, 0xC($s0)
/* 48088 80057888 0800068E */  lw         $a2, 0x8($s0)
/* 4808C 8005788C 473E010C */  jal        read
/* 48090 80057890 00000000 */   nop
/* 48094 80057894 FAFF4014 */  bnez       $v0, .L80057880
/* 48098 80057898 1E000224 */   addiu     $v0, $zero, 0x1E
/* 4809C 8005789C 565E0108 */  j          LIBMCRD_OBJ_BBC
/* 480A0 800578A0 000022AE */   sw        $v0, 0x0($s1)
.L800578A4:
/* 480A4 800578A4 4964010C */  jal        _chk_card_event
/* 480A8 800578A8 00000000 */   nop
/* 480AC 800578AC 2B004010 */  beqz       $v0, LIBMCRD_OBJ_BC0
/* 480B0 800578B0 21100000 */   addu      $v0, $zero, $zero
/* 480B4 800578B4 DD63010C */  jal        _get_card_event
/* 480B8 800578B8 00000000 */   nop
/* 480BC 800578BC 21204000 */  addu       $a0, $v0, $zero
/* 480C0 800578C0 17008010 */  beqz       $a0, .L80057920
/* 480C4 800578C4 00000000 */   nop
/* 480C8 800578C8 0780023C */  lui        $v0, %hi(D_8006A2A4)
/* 480CC 800578CC A4A2428C */  lw         $v0, %lo(D_8006A2A4)($v0)
/* 480D0 800578D0 00000000 */  nop
/* 480D4 800578D4 01004224 */  addiu      $v0, $v0, 0x1
/* 480D8 800578D8 0780013C */  lui        $at, %hi(D_8006A2A4)
/* 480DC 800578DC A4A222AC */  sw         $v0, %lo(D_8006A2A4)($at)
/* 480E0 800578E0 04004228 */  slti       $v0, $v0, 0x4
/* 480E4 800578E4 03004010 */  beqz       $v0, .L800578F4
/* 480E8 800578E8 04000224 */   addiu     $v0, $zero, 0x4
/* 480EC 800578EC 565E0108 */  j          LIBMCRD_OBJ_BBC
/* 480F0 800578F0 000030AE */   sw        $s0, 0x0($s1)
.L800578F4:
/* 480F4 800578F4 0A008214 */  bne        $a0, $v0, .L80057920
/* 480F8 800578F8 00000000 */   nop
/* 480FC 800578FC 9B63010C */  jal        _clr_card_event
/* 48100 80057900 00000000 */   nop
/* 48104 80057904 0880043C */  lui        $a0, %hi(D_80079458)
/* 48108 80057908 5894848C */  lw         $a0, %lo(D_80079458)($a0)
/* 4810C 8005790C 5F62010C */  jal        _card_clear
/* 48110 80057910 00000000 */   nop
/* 48114 80057914 20000224 */  addiu      $v0, $zero, 0x20
/* 48118 80057918 565E0108 */  j          LIBMCRD_OBJ_BBC
/* 4811C 8005791C 000022AE */   sw        $v0, 0x0($s1)
.L80057920:
/* 48120 80057920 4461010C */  jal        LIBMCRD_OBJ_1774
/* 48124 80057924 00000000 */   nop
/* 48128 80057928 0880033C */  lui        $v1, %hi(D_80079448)
/* 4812C 8005792C 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 48130 80057930 040062AC */  sw         $v0, 0x4($v1)
/* 48134 80057934 575E0108 */  j          LIBMCRD_OBJ_BC0
/* 48138 80057938 01000224 */   addiu     $v0, $zero, 0x1
.L8005793C:
/* 4813C 8005793C 5864010C */  jal        _chk_card_event_x
/* 48140 80057940 00000000 */   nop
/* 48144 80057944 05004010 */  beqz       $v0, LIBMCRD_OBJ_BC0
/* 48148 80057948 21100000 */   addu      $v0, $zero, $zero
/* 4814C 8005794C 1364010C */  jal        _get_card_event_x
/* 48150 80057950 00000000 */   nop
/* 48154 80057954 000020AE */  sw         $zero, 0x0($s1)
.size LIBMCRD_OBJ_A60, . - LIBMCRD_OBJ_A60

glabel LIBMCRD_OBJ_BBC
/* 48158 80057958 21100000 */  addu       $v0, $zero, $zero
glabel LIBMCRD_OBJ_BC0
/* 4815C 8005795C 1800BF8F */  lw         $ra, 0x18($sp)
/* 48160 80057960 1400B18F */  lw         $s1, 0x14($sp)
/* 48164 80057964 1000B08F */  lw         $s0, 0x10($sp)
/* 48168 80057968 0800E003 */  jr         $ra
/* 4816C 8005796C 2000BD27 */   addiu     $sp, $sp, 0x20
.size LIBMCRD_OBJ_BBC, . - LIBMCRD_OBJ_BBC

glabel MemCardWriteData
/* 48170 80057970 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 48174 80057974 0880073C */  lui        $a3, %hi(D_8007945C)
/* 48178 80057978 5C94E724 */  addiu      $a3, $a3, %lo(D_8007945C)
/* 4817C 8005797C 1000BFAF */  sw         $ra, 0x10($sp)
/* 48180 80057980 0000E28C */  lw         $v0, 0x0($a3)
/* 48184 80057984 00000000 */  nop
/* 48188 80057988 04004104 */  bgez       $v0, .L8005799C
/* 4818C 8005798C 21408000 */   addu      $t0, $a0, $zero
/* 48190 80057990 0180043C */  lui        $a0, %hi(D_8001308C)
/* 48194 80057994 835E0108 */  j          LIBMCRD_OBJ_C70
/* 48198 80057998 8C308424 */   addiu     $a0, $a0, %lo(D_8001308C)
.L8005799C:
/* 4819C 8005799C ECFFE28C */  lw         $v0, -0x14($a3)
/* 481A0 800579A0 00000000 */  nop
/* 481A4 800579A4 04004018 */  blez       $v0, .L800579B8
/* 481A8 800579A8 ECFFE324 */   addiu     $v1, $a3, -0x14
/* 481AC 800579AC 0180043C */  lui        $a0, %hi(D_80012F68)
/* 481B0 800579B0 835E0108 */  j          LIBMCRD_OBJ_C70
/* 481B4 800579B4 682F8424 */   addiu     $a0, $a0, %lo(D_80012F68)
.L800579B8:
/* 481B8 800579B8 7F00C230 */  andi       $v0, $a2, 0x7F
/* 481BC 800579BC 04004010 */  beqz       $v0, .L800579D0
/* 481C0 800579C0 7F00A230 */   andi      $v0, $a1, 0x7F
/* 481C4 800579C4 0180043C */  lui        $a0, %hi(D_800130B0)
/* 481C8 800579C8 835E0108 */  j          LIBMCRD_OBJ_C70
/* 481CC 800579CC B0308424 */   addiu     $a0, $a0, %lo(D_800130B0)
.L800579D0:
/* 481D0 800579D0 0C004014 */  bnez       $v0, .L80057A04
/* 481D4 800579D4 06000224 */   addiu     $v0, $zero, 0x6
/* 481D8 800579D8 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_C8C)
/* 481DC 800579DC 287A8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_C8C)
/* 481E0 800579E0 ECFFE2AC */  sw         $v0, -0x14($a3)
/* 481E4 800579E4 040060AC */  sw         $zero, 0x4($v1)
/* 481E8 800579E8 080060AC */  sw         $zero, 0x8($v1)
/* 481EC 800579EC 180065AC */  sw         $a1, 0x18($v1)
/* 481F0 800579F0 200068AC */  sw         $t0, 0x20($v1)
/* 481F4 800579F4 7B62010C */  jal        UserFuncOpen
/* 481F8 800579F8 1C0066AC */   sw        $a2, 0x1C($v1)
/* 481FC 800579FC 865E0108 */  j          LIBMCRD_OBJ_C7C
/* 48200 80057A00 01000224 */   addiu     $v0, $zero, 0x1
.L80057A04:
/* 48204 80057A04 0180043C */  lui        $a0, %hi(D_800130DC)
/* 48208 80057A08 DC308424 */  addiu      $a0, $a0, %lo(D_800130DC)
.size MemCardWriteData, . - MemCardWriteData

glabel LIBMCRD_OBJ_C70
/* 4820C 80057A0C 9361000C */  jal        printf
/* 48210 80057A10 00000000 */   nop
/* 48214 80057A14 21100000 */  addu       $v0, $zero, $zero
.size LIBMCRD_OBJ_C70, . - LIBMCRD_OBJ_C70

glabel LIBMCRD_OBJ_C7C
/* 48218 80057A18 1000BF8F */  lw         $ra, 0x10($sp)
/* 4821C 80057A1C 1800BD27 */  addiu      $sp, $sp, 0x18
/* 48220 80057A20 0800E003 */  jr         $ra
/* 48224 80057A24 00000000 */   nop
.size LIBMCRD_OBJ_C7C, . - LIBMCRD_OBJ_C7C

glabel LIBMCRD_OBJ_C8C
/* 48228 80057A28 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 4822C 80057A2C 1400B1AF */  sw         $s1, 0x14($sp)
/* 48230 80057A30 21888000 */  addu       $s1, $a0, $zero
/* 48234 80057A34 1800BFAF */  sw         $ra, 0x18($sp)
/* 48238 80057A38 1000B0AF */  sw         $s0, 0x10($sp)
/* 4823C 80057A3C 0000238E */  lw         $v1, 0x0($s1)
/* 48240 80057A40 0A001024 */  addiu      $s0, $zero, 0xA
/* 48244 80057A44 14007010 */  beq        $v1, $s0, .L80057A98
/* 48248 80057A48 0B006228 */   slti      $v0, $v1, 0xB
/* 4824C 80057A4C 05004010 */  beqz       $v0, .L80057A64
/* 48250 80057A50 1E000224 */   addiu     $v0, $zero, 0x1E
/* 48254 80057A54 09006010 */  beqz       $v1, .L80057A7C
/* 48258 80057A58 21100000 */   addu      $v0, $zero, $zero
/* 4825C 80057A5C F05E0108 */  j          LIBMCRD_OBJ_E24
/* 48260 80057A60 00000000 */   nop
.L80057A64:
/* 48264 80057A64 28006210 */  beq        $v1, $v0, .L80057B08
/* 48268 80057A68 20000224 */   addiu     $v0, $zero, 0x20
/* 4826C 80057A6C 4C006210 */  beq        $v1, $v0, .L80057BA0
/* 48270 80057A70 21100000 */   addu      $v0, $zero, $zero
/* 48274 80057A74 F05E0108 */  j          LIBMCRD_OBJ_E24
/* 48278 80057A78 00000000 */   nop
.L80057A7C:
/* 4827C 80057A7C 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_174)
/* 48280 80057A80 106F8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_174)
/* 48284 80057A84 0780013C */  lui        $at, %hi(D_8006A2A8)
/* 48288 80057A88 7B62010C */  jal        UserFuncOpen
/* 4828C 80057A8C A8A220AC */   sw        $zero, %lo(D_8006A2A8)($at)
/* 48290 80057A90 EF5E0108 */  j          LIBMCRD_OBJ_E20
/* 48294 80057A94 000030AE */   sw        $s0, 0x0($s1)
.L80057A98:
/* 48298 80057A98 0880043C */  lui        $a0, %hi(D_8007944C)
/* 4829C 80057A9C 4C948424 */  addiu      $a0, $a0, %lo(D_8007944C)
/* 482A0 80057AA0 0000828C */  lw         $v0, 0x0($a0)
/* 482A4 80057AA4 00000000 */  nop
/* 482A8 80057AA8 45004014 */  bnez       $v0, LIBMCRD_OBJ_E24
/* 482AC 80057AAC 01000224 */   addiu     $v0, $zero, 0x1
/* 482B0 80057AB0 10009024 */  addiu      $s0, $a0, 0x10
.L80057AB4:
/* 482B4 80057AB4 0000048E */  lw         $a0, 0x0($s0)
/* 482B8 80057AB8 0400058E */  lw         $a1, 0x4($s0)
/* 482BC 80057ABC 9F61010C */  jal        lseek
/* 482C0 80057AC0 21300000 */   addu      $a2, $zero, $zero
/* 482C4 80057AC4 0400038E */  lw         $v1, 0x4($s0)
/* 482C8 80057AC8 00000000 */  nop
/* 482CC 80057ACC F9FF4314 */  bne        $v0, $v1, .L80057AB4
/* 482D0 80057AD0 00000000 */   nop
/* 482D4 80057AD4 9B63010C */  jal        _clr_card_event
/* 482D8 80057AD8 00000000 */   nop
/* 482DC 80057ADC 0880103C */  lui        $s0, %hi(D_8007945C)
/* 482E0 80057AE0 5C941026 */  addiu      $s0, $s0, %lo(D_8007945C)
.L80057AE4:
/* 482E4 80057AE4 0000048E */  lw         $a0, 0x0($s0)
/* 482E8 80057AE8 0C00058E */  lw         $a1, 0xC($s0)
/* 482EC 80057AEC 0800068E */  lw         $a2, 0x8($s0)
/* 482F0 80057AF0 4B3E010C */  jal        write
/* 482F4 80057AF4 00000000 */   nop
/* 482F8 80057AF8 FAFF4014 */  bnez       $v0, .L80057AE4
/* 482FC 80057AFC 1E000224 */   addiu     $v0, $zero, 0x1E
/* 48300 80057B00 EF5E0108 */  j          LIBMCRD_OBJ_E20
/* 48304 80057B04 000022AE */   sw        $v0, 0x0($s1)
.L80057B08:
/* 48308 80057B08 4964010C */  jal        _chk_card_event
/* 4830C 80057B0C 00000000 */   nop
/* 48310 80057B10 2B004010 */  beqz       $v0, LIBMCRD_OBJ_E24
/* 48314 80057B14 21100000 */   addu      $v0, $zero, $zero
/* 48318 80057B18 DD63010C */  jal        _get_card_event
/* 4831C 80057B1C 00000000 */   nop
/* 48320 80057B20 21204000 */  addu       $a0, $v0, $zero
/* 48324 80057B24 17008010 */  beqz       $a0, .L80057B84
/* 48328 80057B28 00000000 */   nop
/* 4832C 80057B2C 0780023C */  lui        $v0, %hi(D_8006A2A8)
/* 48330 80057B30 A8A2428C */  lw         $v0, %lo(D_8006A2A8)($v0)
/* 48334 80057B34 00000000 */  nop
/* 48338 80057B38 01004224 */  addiu      $v0, $v0, 0x1
/* 4833C 80057B3C 0780013C */  lui        $at, %hi(D_8006A2A8)
/* 48340 80057B40 A8A222AC */  sw         $v0, %lo(D_8006A2A8)($at)
/* 48344 80057B44 04004228 */  slti       $v0, $v0, 0x4
/* 48348 80057B48 03004010 */  beqz       $v0, .L80057B58
/* 4834C 80057B4C 04000224 */   addiu     $v0, $zero, 0x4
/* 48350 80057B50 EF5E0108 */  j          LIBMCRD_OBJ_E20
/* 48354 80057B54 000030AE */   sw        $s0, 0x0($s1)
.L80057B58:
/* 48358 80057B58 0A008214 */  bne        $a0, $v0, .L80057B84
/* 4835C 80057B5C 00000000 */   nop
/* 48360 80057B60 9B63010C */  jal        _clr_card_event
/* 48364 80057B64 00000000 */   nop
/* 48368 80057B68 0880043C */  lui        $a0, %hi(D_80079458)
/* 4836C 80057B6C 5894848C */  lw         $a0, %lo(D_80079458)($a0)
/* 48370 80057B70 5F62010C */  jal        _card_clear
/* 48374 80057B74 00000000 */   nop
/* 48378 80057B78 20000224 */  addiu      $v0, $zero, 0x20
/* 4837C 80057B7C EF5E0108 */  j          LIBMCRD_OBJ_E20
/* 48380 80057B80 000022AE */   sw        $v0, 0x0($s1)
.L80057B84:
/* 48384 80057B84 4461010C */  jal        LIBMCRD_OBJ_1774
/* 48388 80057B88 00000000 */   nop
/* 4838C 80057B8C 0880033C */  lui        $v1, %hi(D_80079448)
/* 48390 80057B90 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 48394 80057B94 040062AC */  sw         $v0, 0x4($v1)
/* 48398 80057B98 F05E0108 */  j          LIBMCRD_OBJ_E24
/* 4839C 80057B9C 01000224 */   addiu     $v0, $zero, 0x1
.L80057BA0:
/* 483A0 80057BA0 5864010C */  jal        _chk_card_event_x
/* 483A4 80057BA4 00000000 */   nop
/* 483A8 80057BA8 05004010 */  beqz       $v0, LIBMCRD_OBJ_E24
/* 483AC 80057BAC 21100000 */   addu      $v0, $zero, $zero
/* 483B0 80057BB0 1364010C */  jal        _get_card_event_x
/* 483B4 80057BB4 00000000 */   nop
/* 483B8 80057BB8 000020AE */  sw         $zero, 0x0($s1)
.size LIBMCRD_OBJ_C8C, . - LIBMCRD_OBJ_C8C

glabel LIBMCRD_OBJ_E20
/* 483BC 80057BBC 21100000 */  addu       $v0, $zero, $zero
glabel LIBMCRD_OBJ_E24
/* 483C0 80057BC0 1800BF8F */  lw         $ra, 0x18($sp)
/* 483C4 80057BC4 1400B18F */  lw         $s1, 0x14($sp)
/* 483C8 80057BC8 1000B08F */  lw         $s0, 0x10($sp)
/* 483CC 80057BCC 0800E003 */  jr         $ra
/* 483D0 80057BD0 2000BD27 */   addiu     $sp, $sp, 0x20
.size LIBMCRD_OBJ_E20, . - LIBMCRD_OBJ_E20

glabel MemCardReadFile
/* 483D4 80057BD4 D0FFBD27 */  addiu      $sp, $sp, -0x30
/* 483D8 80057BD8 2000B4AF */  sw         $s4, 0x20($sp)
/* 483DC 80057BDC 21A08000 */  addu       $s4, $a0, $zero
/* 483E0 80057BE0 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 483E4 80057BE4 2198A000 */  addu       $s3, $a1, $zero
/* 483E8 80057BE8 2400B5AF */  sw         $s5, 0x24($sp)
/* 483EC 80057BEC 21A8C000 */  addu       $s5, $a2, $zero
/* 483F0 80057BF0 1800B2AF */  sw         $s2, 0x18($sp)
/* 483F4 80057BF4 2190E000 */  addu       $s2, $a3, $zero
/* 483F8 80057BF8 1400B1AF */  sw         $s1, 0x14($sp)
/* 483FC 80057BFC 0880113C */  lui        $s1, %hi(D_80079448)
/* 48400 80057C00 48943126 */  addiu      $s1, $s1, %lo(D_80079448)
/* 48404 80057C04 2C00BFAF */  sw         $ra, 0x2C($sp)
/* 48408 80057C08 2800B6AF */  sw         $s6, 0x28($sp)
/* 4840C 80057C0C 1000B0AF */  sw         $s0, 0x10($sp)
/* 48410 80057C10 0000228E */  lw         $v0, 0x0($s1)
/* 48414 80057C14 4000B68F */  lw         $s6, 0x40($sp)
/* 48418 80057C18 04004018 */  blez       $v0, .L80057C2C
/* 4841C 80057C1C 00000000 */   nop
/* 48420 80057C20 0180043C */  lui        $a0, %hi(D_8001310C)
/* 48424 80057C24 2E5F0108 */  j          LIBMCRD_OBJ_F1C
/* 48428 80057C28 0C318424 */   addiu     $a0, $a0, %lo(D_8001310C)
.L80057C2C:
/* 4842C 80057C2C 1400228E */  lw         $v0, 0x14($s1)
/* 48430 80057C30 00000000 */  nop
/* 48434 80057C34 04004004 */  bltz       $v0, .L80057C48
/* 48438 80057C38 7F00C232 */   andi      $v0, $s6, 0x7F
/* 4843C 80057C3C 0180043C */  lui        $a0, %hi(D_80013064)
/* 48440 80057C40 2E5F0108 */  j          LIBMCRD_OBJ_F1C
/* 48444 80057C44 64308424 */   addiu     $a0, $a0, %lo(D_80013064)
.L80057C48:
/* 48448 80057C48 04004010 */  beqz       $v0, .L80057C5C
/* 4844C 80057C4C 7F004232 */   andi      $v0, $s2, 0x7F
/* 48450 80057C50 0180043C */  lui        $a0, %hi(D_800130B0)
/* 48454 80057C54 2E5F0108 */  j          LIBMCRD_OBJ_F1C
/* 48458 80057C58 B0308424 */   addiu     $a0, $a0, %lo(D_800130B0)
.L80057C5C:
/* 4845C 80057C5C 14004014 */  bnez       $v0, .L80057CB0
/* 48460 80057C60 21208002 */   addu      $a0, $s4, $zero
/* 48464 80057C64 24003026 */  addiu      $s0, $s1, 0x24
/* 48468 80057C68 8461010C */  jal        LIBMCRD_OBJ_1874
/* 4846C 80057C6C 21280002 */   addu      $a1, $s0, $zero
/* 48470 80057C70 21200002 */  addu       $a0, $s0, $zero
/* 48474 80057C74 DBE3000C */  jal        strcat
/* 48478 80057C78 21286002 */   addu      $a1, $s3, $zero
/* 4847C 80057C7C 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_F50)
/* 48480 80057C80 EC7C8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_F50)
/* 48484 80057C84 03000224 */  addiu      $v0, $zero, 0x3
/* 48488 80057C88 000022AE */  sw         $v0, 0x0($s1)
/* 4848C 80057C8C 040020AE */  sw         $zero, 0x4($s1)
/* 48490 80057C90 080020AE */  sw         $zero, 0x8($s1)
/* 48494 80057C94 180032AE */  sw         $s2, 0x18($s1)
/* 48498 80057C98 200035AE */  sw         $s5, 0x20($s1)
/* 4849C 80057C9C 1C0036AE */  sw         $s6, 0x1C($s1)
/* 484A0 80057CA0 7B62010C */  jal        UserFuncOpen
/* 484A4 80057CA4 100034AE */   sw        $s4, 0x10($s1)
/* 484A8 80057CA8 315F0108 */  j          LIBMCRD_OBJ_F28
/* 484AC 80057CAC 01000224 */   addiu     $v0, $zero, 0x1
.L80057CB0:
/* 484B0 80057CB0 0180043C */  lui        $a0, %hi(D_800130DC)
/* 484B4 80057CB4 DC308424 */  addiu      $a0, $a0, %lo(D_800130DC)
.size MemCardReadFile, . - MemCardReadFile

glabel LIBMCRD_OBJ_F1C
/* 484B8 80057CB8 9361000C */  jal        printf
/* 484BC 80057CBC 00000000 */   nop
/* 484C0 80057CC0 21100000 */  addu       $v0, $zero, $zero
.size LIBMCRD_OBJ_F1C, . - LIBMCRD_OBJ_F1C

glabel LIBMCRD_OBJ_F28
/* 484C4 80057CC4 2C00BF8F */  lw         $ra, 0x2C($sp)
/* 484C8 80057CC8 2800B68F */  lw         $s6, 0x28($sp)
/* 484CC 80057CCC 2400B58F */  lw         $s5, 0x24($sp)
/* 484D0 80057CD0 2000B48F */  lw         $s4, 0x20($sp)
/* 484D4 80057CD4 1C00B38F */  lw         $s3, 0x1C($sp)
/* 484D8 80057CD8 1800B28F */  lw         $s2, 0x18($sp)
/* 484DC 80057CDC 1400B18F */  lw         $s1, 0x14($sp)
/* 484E0 80057CE0 1000B08F */  lw         $s0, 0x10($sp)
/* 484E4 80057CE4 0800E003 */  jr         $ra
/* 484E8 80057CE8 3000BD27 */   addiu     $sp, $sp, 0x30
.size LIBMCRD_OBJ_F28, . - LIBMCRD_OBJ_F28

glabel LIBMCRD_OBJ_F50
/* 484EC 80057CEC E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 484F0 80057CF0 1400B1AF */  sw         $s1, 0x14($sp)
/* 484F4 80057CF4 21888000 */  addu       $s1, $a0, $zero
/* 484F8 80057CF8 1800BFAF */  sw         $ra, 0x18($sp)
/* 484FC 80057CFC 1000B0AF */  sw         $s0, 0x10($sp)
/* 48500 80057D00 0000238E */  lw         $v1, 0x0($s1)
/* 48504 80057D04 0A001024 */  addiu      $s0, $zero, 0xA
/* 48508 80057D08 14007010 */  beq        $v1, $s0, .L80057D5C
/* 4850C 80057D0C 0B006228 */   slti      $v0, $v1, 0xB
/* 48510 80057D10 05004010 */  beqz       $v0, .L80057D28
/* 48514 80057D14 0B000224 */   addiu     $v0, $zero, 0xB
/* 48518 80057D18 09006010 */  beqz       $v1, .L80057D40
/* 4851C 80057D1C 21100000 */   addu      $v0, $zero, $zero
/* 48520 80057D20 785F0108 */  j          LIBMCRD_OBJ_1044
/* 48524 80057D24 00000000 */   nop
.L80057D28:
/* 48528 80057D28 1C006210 */  beq        $v1, $v0, LIBMCRD_OBJ_1000
/* 4852C 80057D2C 14000224 */   addiu     $v0, $zero, 0x14
/* 48530 80057D30 21006210 */  beq        $v1, $v0, .L80057DB8
/* 48534 80057D34 21100000 */   addu      $v0, $zero, $zero
/* 48538 80057D38 785F0108 */  j          LIBMCRD_OBJ_1044
/* 4853C 80057D3C 00000000 */   nop
.L80057D40:
/* 48540 80057D40 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_174)
/* 48544 80057D44 106F8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_174)
/* 48548 80057D48 0780013C */  lui        $at, %hi(D_8006A2AC)
/* 4854C 80057D4C 7B62010C */  jal        UserFuncOpen
/* 48550 80057D50 ACA220AC */   sw        $zero, %lo(D_8006A2AC)($at)
/* 48554 80057D54 775F0108 */  j          LIBMCRD_OBJ_1040
/* 48558 80057D58 000030AE */   sw        $s0, 0x0($s1)
.L80057D5C:
/* 4855C 80057D5C 0880103C */  lui        $s0, %hi(D_8007944C)
/* 48560 80057D60 4C941026 */  addiu      $s0, $s0, %lo(D_8007944C)
/* 48564 80057D64 0000028E */  lw         $v0, 0x0($s0)
/* 48568 80057D68 00000000 */  nop
/* 4856C 80057D6C 1C004014 */  bnez       $v0, LIBMCRD_OBJ_1044
/* 48570 80057D70 01000224 */   addiu     $v0, $zero, 0x1
/* 48574 80057D74 20000426 */  addiu      $a0, $s0, 0x20
/* 48578 80057D78 9B61010C */  jal        open
/* 4857C 80057D7C 01800534 */   ori       $a1, $zero, 0x8001
/* 48580 80057D80 06004104 */  bgez       $v0, LIBMCRD_OBJ_1000
/* 48584 80057D84 100002AE */   sw        $v0, 0x10($s0)
/* 48588 80057D88 FCFF0326 */  addiu      $v1, $s0, -0x4
/* 4858C 80057D8C 05000224 */  addiu      $v0, $zero, 0x5
/* 48590 80057D90 040062AC */  sw         $v0, 0x4($v1)
/* 48594 80057D94 785F0108 */  j          LIBMCRD_OBJ_1044
/* 48598 80057D98 01000224 */   addiu     $v0, $zero, 0x1
.size LIBMCRD_OBJ_F50, . - LIBMCRD_OBJ_F50

glabel LIBMCRD_OBJ_1000
/* 4859C 80057D9C 14000224 */  addiu      $v0, $zero, 0x14
/* 485A0 80057DA0 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_A24)
/* 485A4 80057DA4 C0778424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_A24)
/* 485A8 80057DA8 7B62010C */  jal        UserFuncOpen
/* 485AC 80057DAC 000022AE */   sw        $v0, 0x0($s1)
/* 485B0 80057DB0 785F0108 */  j          LIBMCRD_OBJ_1044
/* 485B4 80057DB4 21100000 */   addu      $v0, $zero, $zero
.L80057DB8:
/* 485B8 80057DB8 0880103C */  lui        $s0, %hi(D_8007945C)
/* 485BC 80057DBC 5C941026 */  addiu      $s0, $s0, %lo(D_8007945C)
/* 485C0 80057DC0 0000048E */  lw         $a0, 0x0($s0)
/* 485C4 80057DC4 A361010C */  jal        close
/* 485C8 80057DC8 00000000 */   nop
/* 485CC 80057DCC 01000224 */  addiu      $v0, $zero, 0x1
/* 485D0 80057DD0 FFFF0324 */  addiu      $v1, $zero, -0x1
/* 485D4 80057DD4 785F0108 */  j          LIBMCRD_OBJ_1044
/* 485D8 80057DD8 000003AE */   sw        $v1, 0x0($s0)
.size LIBMCRD_OBJ_1000, . - LIBMCRD_OBJ_1000

glabel LIBMCRD_OBJ_1040
/* 485DC 80057DDC 21100000 */  addu       $v0, $zero, $zero
glabel LIBMCRD_OBJ_1044
/* 485E0 80057DE0 1800BF8F */  lw         $ra, 0x18($sp)
/* 485E4 80057DE4 1400B18F */  lw         $s1, 0x14($sp)
/* 485E8 80057DE8 1000B08F */  lw         $s0, 0x10($sp)
/* 485EC 80057DEC 0800E003 */  jr         $ra
/* 485F0 80057DF0 2000BD27 */   addiu     $sp, $sp, 0x20
.size LIBMCRD_OBJ_1040, . - LIBMCRD_OBJ_1040

glabel MemCardWriteFile
/* 485F4 80057DF4 D0FFBD27 */  addiu      $sp, $sp, -0x30
/* 485F8 80057DF8 2000B4AF */  sw         $s4, 0x20($sp)
/* 485FC 80057DFC 21A08000 */  addu       $s4, $a0, $zero
/* 48600 80057E00 1C00B3AF */  sw         $s3, 0x1C($sp)
/* 48604 80057E04 2198A000 */  addu       $s3, $a1, $zero
/* 48608 80057E08 2400B5AF */  sw         $s5, 0x24($sp)
/* 4860C 80057E0C 21A8C000 */  addu       $s5, $a2, $zero
/* 48610 80057E10 1800B2AF */  sw         $s2, 0x18($sp)
/* 48614 80057E14 2190E000 */  addu       $s2, $a3, $zero
/* 48618 80057E18 1400B1AF */  sw         $s1, 0x14($sp)
/* 4861C 80057E1C 0880113C */  lui        $s1, %hi(D_80079448)
/* 48620 80057E20 48943126 */  addiu      $s1, $s1, %lo(D_80079448)
/* 48624 80057E24 2C00BFAF */  sw         $ra, 0x2C($sp)
/* 48628 80057E28 2800B6AF */  sw         $s6, 0x28($sp)
/* 4862C 80057E2C 1000B0AF */  sw         $s0, 0x10($sp)
/* 48630 80057E30 0000228E */  lw         $v0, 0x0($s1)
/* 48634 80057E34 4000B68F */  lw         $s6, 0x40($sp)
/* 48638 80057E38 04004018 */  blez       $v0, .L80057E4C
/* 4863C 80057E3C 00000000 */   nop
/* 48640 80057E40 0180043C */  lui        $a0, %hi(D_8001310C)
/* 48644 80057E44 B65F0108 */  j          LIBMCRD_OBJ_113C
/* 48648 80057E48 0C318424 */   addiu     $a0, $a0, %lo(D_8001310C)
.L80057E4C:
/* 4864C 80057E4C 1400228E */  lw         $v0, 0x14($s1)
/* 48650 80057E50 00000000 */  nop
/* 48654 80057E54 04004004 */  bltz       $v0, .L80057E68
/* 48658 80057E58 7F00C232 */   andi      $v0, $s6, 0x7F
/* 4865C 80057E5C 0180043C */  lui        $a0, %hi(D_80013064)
/* 48660 80057E60 B65F0108 */  j          LIBMCRD_OBJ_113C
/* 48664 80057E64 64308424 */   addiu     $a0, $a0, %lo(D_80013064)
.L80057E68:
/* 48668 80057E68 04004010 */  beqz       $v0, .L80057E7C
/* 4866C 80057E6C 7F004232 */   andi      $v0, $s2, 0x7F
/* 48670 80057E70 0180043C */  lui        $a0, %hi(D_800130B0)
/* 48674 80057E74 B65F0108 */  j          LIBMCRD_OBJ_113C
/* 48678 80057E78 B0308424 */   addiu     $a0, $a0, %lo(D_800130B0)
.L80057E7C:
/* 4867C 80057E7C 14004014 */  bnez       $v0, .L80057ED0
/* 48680 80057E80 21208002 */   addu      $a0, $s4, $zero
/* 48684 80057E84 24003026 */  addiu      $s0, $s1, 0x24
/* 48688 80057E88 8461010C */  jal        LIBMCRD_OBJ_1874
/* 4868C 80057E8C 21280002 */   addu      $a1, $s0, $zero
/* 48690 80057E90 21200002 */  addu       $a0, $s0, $zero
/* 48694 80057E94 DBE3000C */  jal        strcat
/* 48698 80057E98 21286002 */   addu      $a1, $s3, $zero
/* 4869C 80057E9C 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_1170)
/* 486A0 80057EA0 0C7F8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_1170)
/* 486A4 80057EA4 04000224 */  addiu      $v0, $zero, 0x4
/* 486A8 80057EA8 000022AE */  sw         $v0, 0x0($s1)
/* 486AC 80057EAC 040020AE */  sw         $zero, 0x4($s1)
/* 486B0 80057EB0 080020AE */  sw         $zero, 0x8($s1)
/* 486B4 80057EB4 180032AE */  sw         $s2, 0x18($s1)
/* 486B8 80057EB8 200035AE */  sw         $s5, 0x20($s1)
/* 486BC 80057EBC 1C0036AE */  sw         $s6, 0x1C($s1)
/* 486C0 80057EC0 7B62010C */  jal        UserFuncOpen
/* 486C4 80057EC4 100034AE */   sw        $s4, 0x10($s1)
/* 486C8 80057EC8 B95F0108 */  j          LIBMCRD_OBJ_1148
/* 486CC 80057ECC 01000224 */   addiu     $v0, $zero, 0x1
.L80057ED0:
/* 486D0 80057ED0 0180043C */  lui        $a0, %hi(D_800130DC)
/* 486D4 80057ED4 DC308424 */  addiu      $a0, $a0, %lo(D_800130DC)
.size MemCardWriteFile, . - MemCardWriteFile

glabel LIBMCRD_OBJ_113C
/* 486D8 80057ED8 9361000C */  jal        printf
/* 486DC 80057EDC 00000000 */   nop
/* 486E0 80057EE0 21100000 */  addu       $v0, $zero, $zero
.size LIBMCRD_OBJ_113C, . - LIBMCRD_OBJ_113C

glabel LIBMCRD_OBJ_1148
/* 486E4 80057EE4 2C00BF8F */  lw         $ra, 0x2C($sp)
/* 486E8 80057EE8 2800B68F */  lw         $s6, 0x28($sp)
/* 486EC 80057EEC 2400B58F */  lw         $s5, 0x24($sp)
/* 486F0 80057EF0 2000B48F */  lw         $s4, 0x20($sp)
/* 486F4 80057EF4 1C00B38F */  lw         $s3, 0x1C($sp)
/* 486F8 80057EF8 1800B28F */  lw         $s2, 0x18($sp)
/* 486FC 80057EFC 1400B18F */  lw         $s1, 0x14($sp)
/* 48700 80057F00 1000B08F */  lw         $s0, 0x10($sp)
/* 48704 80057F04 0800E003 */  jr         $ra
/* 48708 80057F08 3000BD27 */   addiu     $sp, $sp, 0x30
.size LIBMCRD_OBJ_1148, . - LIBMCRD_OBJ_1148

glabel LIBMCRD_OBJ_1170
/* 4870C 80057F0C E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 48710 80057F10 1400B1AF */  sw         $s1, 0x14($sp)
/* 48714 80057F14 21888000 */  addu       $s1, $a0, $zero
/* 48718 80057F18 1800BFAF */  sw         $ra, 0x18($sp)
/* 4871C 80057F1C 1000B0AF */  sw         $s0, 0x10($sp)
/* 48720 80057F20 0000238E */  lw         $v1, 0x0($s1)
/* 48724 80057F24 0A001024 */  addiu      $s0, $zero, 0xA
/* 48728 80057F28 14007010 */  beq        $v1, $s0, .L80057F7C
/* 4872C 80057F2C 0B006228 */   slti      $v0, $v1, 0xB
/* 48730 80057F30 05004010 */  beqz       $v0, .L80057F48
/* 48734 80057F34 0B000224 */   addiu     $v0, $zero, 0xB
/* 48738 80057F38 09006010 */  beqz       $v1, .L80057F60
/* 4873C 80057F3C 21100000 */   addu      $v0, $zero, $zero
/* 48740 80057F40 00600108 */  j          LIBMCRD_OBJ_1264
/* 48744 80057F44 00000000 */   nop
.L80057F48:
/* 48748 80057F48 1C006210 */  beq        $v1, $v0, .L80057FBC
/* 4874C 80057F4C 14000224 */   addiu     $v0, $zero, 0x14
/* 48750 80057F50 21006210 */  beq        $v1, $v0, .L80057FD8
/* 48754 80057F54 21100000 */   addu      $v0, $zero, $zero
/* 48758 80057F58 00600108 */  j          LIBMCRD_OBJ_1264
/* 4875C 80057F5C 00000000 */   nop
.L80057F60:
/* 48760 80057F60 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_174)
/* 48764 80057F64 106F8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_174)
/* 48768 80057F68 0780013C */  lui        $at, %hi(D_8006A2B0)
/* 4876C 80057F6C 7B62010C */  jal        UserFuncOpen
/* 48770 80057F70 B0A220AC */   sw        $zero, %lo(D_8006A2B0)($at)
/* 48774 80057F74 FF5F0108 */  j          LIBMCRD_OBJ_1260
/* 48778 80057F78 000030AE */   sw        $s0, 0x0($s1)
.L80057F7C:
/* 4877C 80057F7C 0880103C */  lui        $s0, %hi(D_8007944C)
/* 48780 80057F80 4C941026 */  addiu      $s0, $s0, %lo(D_8007944C)
/* 48784 80057F84 0000028E */  lw         $v0, 0x0($s0)
/* 48788 80057F88 00000000 */  nop
/* 4878C 80057F8C 1C004014 */  bnez       $v0, LIBMCRD_OBJ_1264
/* 48790 80057F90 01000224 */   addiu     $v0, $zero, 0x1
/* 48794 80057F94 20000426 */  addiu      $a0, $s0, 0x20
/* 48798 80057F98 9B61010C */  jal        open
/* 4879C 80057F9C 01800534 */   ori       $a1, $zero, 0x8001
/* 487A0 80057FA0 06004104 */  bgez       $v0, .L80057FBC
/* 487A4 80057FA4 100002AE */   sw        $v0, 0x10($s0)
/* 487A8 80057FA8 FCFF0326 */  addiu      $v1, $s0, -0x4
/* 487AC 80057FAC 05000224 */  addiu      $v0, $zero, 0x5
/* 487B0 80057FB0 040062AC */  sw         $v0, 0x4($v1)
/* 487B4 80057FB4 00600108 */  j          LIBMCRD_OBJ_1264
/* 487B8 80057FB8 01000224 */   addiu     $v0, $zero, 0x1
.L80057FBC:
/* 487BC 80057FBC 14000224 */  addiu      $v0, $zero, 0x14
/* 487C0 80057FC0 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_C8C)
/* 487C4 80057FC4 287A8424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_C8C)
/* 487C8 80057FC8 7B62010C */  jal        UserFuncOpen
/* 487CC 80057FCC 000022AE */   sw        $v0, 0x0($s1)
/* 487D0 80057FD0 00600108 */  j          LIBMCRD_OBJ_1264
/* 487D4 80057FD4 21100000 */   addu      $v0, $zero, $zero
.L80057FD8:
/* 487D8 80057FD8 0880103C */  lui        $s0, %hi(D_8007945C)
/* 487DC 80057FDC 5C941026 */  addiu      $s0, $s0, %lo(D_8007945C)
/* 487E0 80057FE0 0000048E */  lw         $a0, 0x0($s0)
/* 487E4 80057FE4 A361010C */  jal        close
/* 487E8 80057FE8 00000000 */   nop
/* 487EC 80057FEC 01000224 */  addiu      $v0, $zero, 0x1
/* 487F0 80057FF0 FFFF0324 */  addiu      $v1, $zero, -0x1
/* 487F4 80057FF4 00600108 */  j          LIBMCRD_OBJ_1264
/* 487F8 80057FF8 000003AE */   sw        $v1, 0x0($s0)
.size LIBMCRD_OBJ_1170, . - LIBMCRD_OBJ_1170

glabel LIBMCRD_OBJ_1260
/* 487FC 80057FFC 21100000 */  addu       $v0, $zero, $zero
glabel LIBMCRD_OBJ_1264
/* 48800 80058000 1800BF8F */  lw         $ra, 0x18($sp)
/* 48804 80058004 1400B18F */  lw         $s1, 0x14($sp)
/* 48808 80058008 1000B08F */  lw         $s0, 0x10($sp)
/* 4880C 8005800C 0800E003 */  jr         $ra
/* 48810 80058010 2000BD27 */   addiu     $sp, $sp, 0x20
.size LIBMCRD_OBJ_1260, . - LIBMCRD_OBJ_1260

glabel MemCardGetDirentry
/* 48814 80058014 70FFBD27 */  addiu      $sp, $sp, -0x90
/* 48818 80058018 8000B6AF */  sw         $s6, 0x80($sp)
/* 4881C 8005801C 21B08000 */  addu       $s6, $a0, $zero
/* 48820 80058020 6C00B1AF */  sw         $s1, 0x6C($sp)
/* 48824 80058024 2188A000 */  addu       $s1, $a1, $zero
/* 48828 80058028 8400B7AF */  sw         $s7, 0x84($sp)
/* 4882C 8005802C 21B8C000 */  addu       $s7, $a2, $zero
/* 48830 80058030 6800B0AF */  sw         $s0, 0x68($sp)
/* 48834 80058034 0880103C */  lui        $s0, %hi(D_80079448)
/* 48838 80058038 48941026 */  addiu      $s0, $s0, %lo(D_80079448)
/* 4883C 8005803C 8C00BFAF */  sw         $ra, 0x8C($sp)
/* 48840 80058040 8800BEAF */  sw         $fp, 0x88($sp)
/* 48844 80058044 7C00B5AF */  sw         $s5, 0x7C($sp)
/* 48848 80058048 7800B4AF */  sw         $s4, 0x78($sp)
/* 4884C 8005804C 7400B3AF */  sw         $s3, 0x74($sp)
/* 48850 80058050 7000B2AF */  sw         $s2, 0x70($sp)
/* 48854 80058054 5C00A7AF */  sw         $a3, 0x5C($sp)
/* 48858 80058058 0000028E */  lw         $v0, 0x0($s0)
/* 4885C 8005805C A000BE8F */  lw         $fp, 0xA0($sp)
/* 48860 80058060 06004010 */  beqz       $v0, .L8005807C
/* 48864 80058064 2120C002 */   addu      $a0, $s6, $zero
/* 48868 80058068 0180043C */  lui        $a0, %hi(D_8001310C)
/* 4886C 8005806C 9361000C */  jal        printf
/* 48870 80058070 0C318424 */   addiu     $a0, $a0, %lo(D_8001310C)
/* 48874 80058074 90600108 */  j          LIBMCRD_OBJ_14A4
/* 48878 80058078 FFFF0224 */   addiu     $v0, $zero, -0x1
.L8005807C:
/* 4887C 8005807C 8461010C */  jal        LIBMCRD_OBJ_1874
/* 48880 80058080 1000A527 */   addiu     $a1, $sp, 0x10
/* 48884 80058084 1000A427 */  addiu      $a0, $sp, 0x10
/* 48888 80058088 DBE3000C */  jal        strcat
/* 4888C 8005808C 21282002 */   addu      $a1, $s1, $zero
/* 48890 80058090 21900000 */  addu       $s2, $zero, $zero
/* 48894 80058094 21880000 */  addu       $s1, $zero, $zero
/* 48898 80058098 01000224 */  addiu      $v0, $zero, 0x1
/* 4889C 8005809C 5800A0AF */  sw         $zero, 0x58($sp)
/* 488A0 800580A0 0C00038E */  lw         $v1, 0xC($s0)
/* 488A4 800580A4 0410C202 */  sllv       $v0, $v0, $s6
/* 488A8 800580A8 25186200 */  or         $v1, $v1, $v0
/* 488AC 800580AC 0C0003AE */  sw         $v1, 0xC($s0)
/* 488B0 800580B0 A400A88F */  lw         $t0, 0xA4($sp)
/* 488B4 800580B4 00000000 */  nop
/* 488B8 800580B8 2110C803 */  addu       $v0, $fp, $t0
/* 488BC 800580BC 5B004018 */  blez       $v0, .L8005822C
/* 488C0 800580C0 21A80000 */   addu      $s5, $zero, $zero
/* 488C4 800580C4 21980002 */  addu       $s3, $s0, $zero
/* 488C8 800580C8 5000A827 */  addiu      $t0, $sp, 0x50
/* 488CC 800580CC 6000A8AF */  sw         $t0, 0x60($sp)
/* 488D0 800580D0 21A00000 */  addu       $s4, $zero, $zero
.L800580D4:
/* 488D4 800580D4 32002016 */  bnez       $s1, .L800581A0
/* 488D8 800580D8 00000000 */   nop
.L800580DC:
/* 488DC 800580DC 9B63010C */  jal        _clr_card_event
/* 488E0 800580E0 00000000 */   nop
/* 488E4 800580E4 1000A427 */  addiu      $a0, $sp, 0x10
/* 488E8 800580E8 AB61010C */  jal        firstfile
/* 488EC 800580EC 3000A527 */   addiu     $a1, $sp, 0x30
/* 488F0 800580F0 21804000 */  addu       $s0, $v0, $zero
/* 488F4 800580F4 2F000016 */  bnez       $s0, .L800581B4
/* 488F8 800580F8 2A103E02 */   slt       $v0, $s1, $fp
/* 488FC 800580FC 1364010C */  jal        _get_card_event_x
/* 48900 80058100 00000000 */   nop
/* 48904 80058104 4461010C */  jal        LIBMCRD_OBJ_1774
/* 48908 80058108 21204000 */   addu      $a0, $v0, $zero
/* 4890C 8005810C 27004010 */  beqz       $v0, .L800581AC
/* 48910 80058110 5800A2AF */   sw        $v0, 0x58($sp)
/* 48914 80058114 01005226 */  addiu      $s2, $s2, 0x1
/* 48918 80058118 0400422A */  slti       $v0, $s2, 0x4
/* 4891C 8005811C EFFF4014 */  bnez       $v0, .L800580DC
/* 48920 80058120 00000000 */   nop
/* 48924 80058124 9C60010C */  jal        MemCardCallback
/* 48928 80058128 21200000 */   addu      $a0, $zero, $zero
/* 4892C 8005812C 0000638E */  lw         $v1, 0x0($s3)
/* 48930 80058130 0880013C */  lui        $at, %hi(D_800794A0)
/* 48934 80058134 A09422AC */  sw         $v0, %lo(D_800794A0)($at)
/* 48938 80058138 06006018 */  blez       $v1, .L80058154
/* 4893C 8005813C 02000824 */   addiu     $t0, $zero, 0x2
/* 48940 80058140 0180043C */  lui        $a0, %hi(D_80012F68)
/* 48944 80058144 9361000C */  jal        printf
/* 48948 80058148 682F8424 */   addiu     $a0, $a0, %lo(D_80012F68)
/* 4894C 8005814C 5E600108 */  j          LIBMCRD_OBJ_13DC
/* 48950 80058150 21200000 */   addu      $a0, $zero, $zero
.L80058154:
/* 48954 80058154 0580043C */  lui        $a0, %hi(LIBMCRD_OBJ_4F8)
/* 48958 80058158 94728424 */  addiu      $a0, $a0, %lo(LIBMCRD_OBJ_4F8)
/* 4895C 8005815C 000068AE */  sw         $t0, 0x0($s3)
/* 48960 80058160 040060AE */  sw         $zero, 0x4($s3)
/* 48964 80058164 080060AE */  sw         $zero, 0x8($s3)
/* 48968 80058168 0880013C */  lui        $at, %hi(D_80079458)
/* 4896C 8005816C 7B62010C */  jal        UserFuncOpen
/* 48970 80058170 589436AC */   sw        $s6, %lo(D_80079458)($at)
/* 48974 80058174 21200000 */  addu       $a0, $zero, $zero
.size MemCardGetDirentry, . - MemCardGetDirentry

glabel LIBMCRD_OBJ_13DC
/* 48978 80058178 21280000 */  addu       $a1, $zero, $zero
/* 4897C 8005817C A160010C */  jal        MemCardSync
/* 48980 80058180 5800A627 */   addiu     $a2, $sp, 0x58
/* 48984 80058184 0880043C */  lui        $a0, %hi(D_800794A0)
/* 48988 80058188 A094848C */  lw         $a0, %lo(D_800794A0)($a0)
/* 4898C 8005818C 9C60010C */  jal        MemCardCallback
/* 48990 80058190 00000000 */   nop
/* 48994 80058194 5800A28F */  lw         $v0, 0x58($sp)
/* 48998 80058198 90600108 */  j          LIBMCRD_OBJ_14A4
/* 4899C 8005819C 00000000 */   nop
.L800581A0:
/* 489A0 800581A0 A761010C */  jal        nextfile
/* 489A4 800581A4 3000A427 */   addiu     $a0, $sp, 0x30
/* 489A8 800581A8 21804000 */  addu       $s0, $v0, $zero
.L800581AC:
/* 489AC 800581AC 1F000012 */  beqz       $s0, .L8005822C
/* 489B0 800581B0 2A103E02 */   slt       $v0, $s1, $fp
.L800581B4:
/* 489B4 800581B4 17004014 */  bnez       $v0, .L80058214
/* 489B8 800581B8 00000000 */   nop
/* 489BC 800581BC 1500E012 */  beqz       $s7, .L80058214
/* 489C0 800581C0 21389702 */   addu      $a3, $s4, $s7
/* 489C4 800581C4 3000A627 */  addiu      $a2, $sp, 0x30
.L800581C8:
/* 489C8 800581C8 0000C28C */  lw         $v0, 0x0($a2)
/* 489CC 800581CC 0400C38C */  lw         $v1, 0x4($a2)
/* 489D0 800581D0 0800C48C */  lw         $a0, 0x8($a2)
/* 489D4 800581D4 0C00C58C */  lw         $a1, 0xC($a2)
/* 489D8 800581D8 0000E2AC */  sw         $v0, 0x0($a3)
/* 489DC 800581DC 0400E3AC */  sw         $v1, 0x4($a3)
/* 489E0 800581E0 0800E4AC */  sw         $a0, 0x8($a3)
/* 489E4 800581E4 0C00E5AC */  sw         $a1, 0xC($a3)
/* 489E8 800581E8 1000C624 */  addiu      $a2, $a2, 0x10
/* 489EC 800581EC 6000A88F */  lw         $t0, 0x60($sp)
/* 489F0 800581F0 00000000 */  nop
/* 489F4 800581F4 F4FFC814 */  bne        $a2, $t0, .L800581C8
/* 489F8 800581F8 1000E724 */   addiu     $a3, $a3, 0x10
/* 489FC 800581FC 0000C28C */  lw         $v0, 0x0($a2)
/* 48A00 80058200 0400C38C */  lw         $v1, 0x4($a2)
/* 48A04 80058204 0000E2AC */  sw         $v0, 0x0($a3)
/* 48A08 80058208 0400E3AC */  sw         $v1, 0x4($a3)
/* 48A0C 8005820C 28009426 */  addiu      $s4, $s4, 0x28
/* 48A10 80058210 0100B526 */  addiu      $s5, $s5, 0x1
.L80058214:
/* 48A14 80058214 A400A88F */  lw         $t0, 0xA4($sp)
/* 48A18 80058218 01003126 */  addiu      $s1, $s1, 0x1
/* 48A1C 8005821C 2110C803 */  addu       $v0, $fp, $t0
/* 48A20 80058220 2A102202 */  slt        $v0, $s1, $v0
/* 48A24 80058224 ABFF4014 */  bnez       $v0, .L800580D4
/* 48A28 80058228 00000000 */   nop
.L8005822C:
/* 48A2C 8005822C 5C00A88F */  lw         $t0, 0x5C($sp)
/* 48A30 80058230 00000000 */  nop
/* 48A34 80058234 02000011 */  beqz       $t0, LIBMCRD_OBJ_14A4
/* 48A38 80058238 21100000 */   addu      $v0, $zero, $zero
/* 48A3C 8005823C 000015AD */  sw         $s5, 0x0($t0)
.size LIBMCRD_OBJ_13DC, . - LIBMCRD_OBJ_13DC

glabel LIBMCRD_OBJ_14A4
/* 48A40 80058240 8C00BF8F */  lw         $ra, 0x8C($sp)
/* 48A44 80058244 8800BE8F */  lw         $fp, 0x88($sp)
/* 48A48 80058248 8400B78F */  lw         $s7, 0x84($sp)
/* 48A4C 8005824C 8000B68F */  lw         $s6, 0x80($sp)
/* 48A50 80058250 7C00B58F */  lw         $s5, 0x7C($sp)
/* 48A54 80058254 7800B48F */  lw         $s4, 0x78($sp)
/* 48A58 80058258 7400B38F */  lw         $s3, 0x74($sp)
/* 48A5C 8005825C 7000B28F */  lw         $s2, 0x70($sp)
/* 48A60 80058260 6C00B18F */  lw         $s1, 0x6C($sp)
/* 48A64 80058264 6800B08F */  lw         $s0, 0x68($sp)
/* 48A68 80058268 0800E003 */  jr         $ra
/* 48A6C 8005826C 9000BD27 */   addiu     $sp, $sp, 0x90
.size LIBMCRD_OBJ_14A4, . - LIBMCRD_OBJ_14A4

glabel MemCardCallback
/* 48A70 80058270 0880033C */  lui        $v1, %hi(D_8007948C)
/* 48A74 80058274 8C946324 */  addiu      $v1, $v1, %lo(D_8007948C)
/* 48A78 80058278 0000628C */  lw         $v0, 0x0($v1)
/* 48A7C 8005827C 0800E003 */  jr         $ra
/* 48A80 80058280 000064AC */   sw        $a0, 0x0($v1)
.size MemCardCallback, . - MemCardCallback

glabel MemCardSync
/* 48A84 80058284 0880033C */  lui        $v1, %hi(D_80079448)
/* 48A88 80058288 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 48A8C 8005828C 0000628C */  lw         $v0, 0x0($v1)
/* 48A90 80058290 00000000 */  nop
/* 48A94 80058294 05004014 */  bnez       $v0, .L800582AC
/* 48A98 80058298 00000000 */   nop
/* 48A9C 8005829C 0800628C */  lw         $v0, 0x8($v1)
/* 48AA0 800582A0 00000000 */  nop
/* 48AA4 800582A4 3C004010 */  beqz       $v0, LIBMCRD_OBJ_15FC
/* 48AA8 800582A8 FFFF0224 */   addiu     $v0, $zero, -0x1
.L800582AC:
/* 48AAC 800582AC 0000688C */  lw         $t0, 0x0($v1)
/* 48AB0 800582B0 0400678C */  lw         $a3, 0x4($v1)
/* 48AB4 800582B4 1D008014 */  bnez       $a0, .L8005832C
/* 48AB8 800582B8 00000000 */   nop
/* 48ABC 800582BC 0800628C */  lw         $v0, 0x8($v1)
/* 48AC0 800582C0 00000000 */  nop
/* 48AC4 800582C4 06004014 */  bnez       $v0, .L800582E0
/* 48AC8 800582C8 00000000 */   nop
/* 48ACC 800582CC 08006324 */  addiu      $v1, $v1, 0x8
.L800582D0:
/* 48AD0 800582D0 0000628C */  lw         $v0, 0x0($v1)
/* 48AD4 800582D4 00000000 */  nop
/* 48AD8 800582D8 FDFF4010 */  beqz       $v0, .L800582D0
/* 48ADC 800582DC 00000000 */   nop
.L800582E0:
/* 48AE0 800582E0 0600C010 */  beqz       $a2, .L800582FC
/* 48AE4 800582E4 00000000 */   nop
/* 48AE8 800582E8 0880023C */  lui        $v0, %hi(D_8007943C)
/* 48AEC 800582EC 3C944224 */  addiu      $v0, $v0, %lo(D_8007943C)
/* 48AF0 800582F0 0000428C */  lw         $v0, 0x0($v0)
/* 48AF4 800582F4 00000000 */  nop
/* 48AF8 800582F8 0000C2AC */  sw         $v0, 0x0($a2)
.L800582FC:
/* 48AFC 800582FC 0600A010 */  beqz       $a1, .L80058318
/* 48B00 80058300 00000000 */   nop
/* 48B04 80058304 0880023C */  lui        $v0, %hi(D_80079438)
/* 48B08 80058308 38944224 */  addiu      $v0, $v0, %lo(D_80079438)
/* 48B0C 8005830C 0000428C */  lw         $v0, 0x0($v0)
/* 48B10 80058310 00000000 */  nop
/* 48B14 80058314 0000A2AC */  sw         $v0, 0x0($a1)
.L80058318:
/* 48B18 80058318 0880023C */  lui        $v0, %hi(D_80079448)
/* 48B1C 8005831C 48944224 */  addiu      $v0, $v0, %lo(D_80079448)
/* 48B20 80058320 080040AC */  sw         $zero, 0x8($v0)
/* 48B24 80058324 E6600108 */  j          LIBMCRD_OBJ_15FC
/* 48B28 80058328 01000224 */   addiu     $v0, $zero, 0x1
.L8005832C:
/* 48B2C 8005832C 0800628C */  lw         $v0, 0x8($v1)
/* 48B30 80058330 00000000 */  nop
/* 48B34 80058334 08004014 */  bnez       $v0, .L80058358
/* 48B38 80058338 00000000 */   nop
/* 48B3C 8005833C 0200C010 */  beqz       $a2, .L80058348
/* 48B40 80058340 00000000 */   nop
/* 48B44 80058344 0000C7AC */  sw         $a3, 0x0($a2)
.L80058348:
/* 48B48 80058348 1300A010 */  beqz       $a1, LIBMCRD_OBJ_15FC
/* 48B4C 8005834C 21100000 */   addu      $v0, $zero, $zero
/* 48B50 80058350 E6600108 */  j          LIBMCRD_OBJ_15FC
/* 48B54 80058354 0000A8AC */   sw        $t0, 0x0($a1)
.L80058358:
/* 48B58 80058358 0600C010 */  beqz       $a2, LIBMCRD_OBJ_15D8
/* 48B5C 8005835C 00000000 */   nop
/* 48B60 80058360 0880023C */  lui        $v0, %hi(D_8007943C)
/* 48B64 80058364 3C944224 */  addiu      $v0, $v0, %lo(D_8007943C)
/* 48B68 80058368 0000428C */  lw         $v0, 0x0($v0)
/* 48B6C 8005836C 00000000 */  nop
/* 48B70 80058370 0000C2AC */  sw         $v0, 0x0($a2)
.size MemCardSync, . - MemCardSync

glabel LIBMCRD_OBJ_15D8
/* 48B74 80058374 0600A010 */  beqz       $a1, .L80058390
/* 48B78 80058378 00000000 */   nop
/* 48B7C 8005837C 0880023C */  lui        $v0, %hi(D_80079438)
/* 48B80 80058380 38944224 */  addiu      $v0, $v0, %lo(D_80079438)
/* 48B84 80058384 0000428C */  lw         $v0, 0x0($v0)
/* 48B88 80058388 00000000 */  nop
/* 48B8C 8005838C 0000A2AC */  sw         $v0, 0x0($a1)
.L80058390:
/* 48B90 80058390 080060AC */  sw         $zero, 0x8($v1)
/* 48B94 80058394 01000224 */  addiu      $v0, $zero, 0x1
.size LIBMCRD_OBJ_15D8, . - LIBMCRD_OBJ_15D8

glabel LIBMCRD_OBJ_15FC
/* 48B98 80058398 0800E003 */  jr         $ra
/* 48B9C 8005839C 00000000 */   nop
.size LIBMCRD_OBJ_15FC, . - LIBMCRD_OBJ_15FC

glabel MemCardCreateFile
/* 48BA0 800583A0 B8FFBD27 */  addiu      $sp, $sp, -0x48
/* 48BA4 800583A4 3000B0AF */  sw         $s0, 0x30($sp)
/* 48BA8 800583A8 21808000 */  addu       $s0, $a0, $zero
/* 48BAC 800583AC 3400B1AF */  sw         $s1, 0x34($sp)
/* 48BB0 800583B0 2188A000 */  addu       $s1, $a1, $zero
/* 48BB4 800583B4 3800B2AF */  sw         $s2, 0x38($sp)
/* 48BB8 800583B8 0880123C */  lui        $s2, %hi(D_80079448)
/* 48BBC 800583BC 48945226 */  addiu      $s2, $s2, %lo(D_80079448)
/* 48BC0 800583C0 4000BFAF */  sw         $ra, 0x40($sp)
/* 48BC4 800583C4 3C00B3AF */  sw         $s3, 0x3C($sp)
/* 48BC8 800583C8 0000428E */  lw         $v0, 0x0($s2)
/* 48BCC 800583CC 00000000 */  nop
/* 48BD0 800583D0 0C004010 */  beqz       $v0, .L80058404
/* 48BD4 800583D4 2198C000 */   addu      $s3, $a2, $zero
/* 48BD8 800583D8 0180043C */  lui        $a0, %hi(D_8001310C)
/* 48BDC 800583DC 9361000C */  jal        printf
/* 48BE0 800583E0 0C318424 */   addiu     $a0, $a0, %lo(D_8001310C)
/* 48BE4 800583E4 20610108 */  j          LIBMCRD_OBJ_16E4
/* 48BE8 800583E8 FFFF0224 */   addiu     $v0, $zero, -0x1
.L800583EC:
/* 48BEC 800583EC 20610108 */  j          LIBMCRD_OBJ_16E4
/* 48BF0 800583F0 07000224 */   addiu     $v0, $zero, 0x7
.L800583F4:
/* 48BF4 800583F4 20610108 */  j          LIBMCRD_OBJ_16E4
/* 48BF8 800583F8 04000224 */   addiu     $v0, $zero, 0x4
.L800583FC:
/* 48BFC 800583FC 20610108 */  j          LIBMCRD_OBJ_16E4
/* 48C00 80058400 06000224 */   addiu     $v0, $zero, 0x6
.L80058404:
/* 48C04 80058404 21200002 */  addu       $a0, $s0, $zero
/* 48C08 80058408 8461010C */  jal        LIBMCRD_OBJ_1874
/* 48C0C 8005840C 1000A527 */   addiu     $a1, $sp, 0x10
/* 48C10 80058410 1000A427 */  addiu      $a0, $sp, 0x10
/* 48C14 80058414 DBE3000C */  jal        strcat
/* 48C18 80058418 21282002 */   addu      $a1, $s1, $zero
/* 48C1C 8005841C 01000224 */  addiu      $v0, $zero, 0x1
/* 48C20 80058420 0C00438E */  lw         $v1, 0xC($s2)
/* 48C24 80058424 04100202 */  sllv       $v0, $v0, $s0
/* 48C28 80058428 25186200 */  or         $v1, $v1, $v0
/* 48C2C 8005842C 0C0043AE */  sw         $v1, 0xC($s2)
/* 48C30 80058430 21200002 */  addu       $a0, $s0, $zero
/* 48C34 80058434 21282002 */  addu       $a1, $s1, $zero
/* 48C38 80058438 5B65010C */  jal        _card_create2
/* 48C3C 8005843C 21306002 */   addu      $a2, $s3, $zero
/* 48C40 80058440 21204000 */  addu       $a0, $v0, $zero
/* 48C44 80058444 0D008010 */  beqz       $a0, .L8005847C
/* 48C48 80058448 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 48C4C 8005844C E7FF8210 */  beq        $a0, $v0, .L800583EC
/* 48C50 80058450 FEFF0224 */   addiu     $v0, $zero, -0x2
/* 48C54 80058454 E7FF8210 */  beq        $a0, $v0, .L800583F4
/* 48C58 80058458 FDFF0224 */   addiu     $v0, $zero, -0x3
/* 48C5C 8005845C E7FF8210 */  beq        $a0, $v0, .L800583FC
/* 48C60 80058460 04000224 */   addiu     $v0, $zero, 0x4
/* 48C64 80058464 06008210 */  beq        $a0, $v0, LIBMCRD_OBJ_16E4
/* 48C68 80058468 02000224 */   addiu     $v0, $zero, 0x2
/* 48C6C 8005846C 4461010C */  jal        LIBMCRD_OBJ_1774
/* 48C70 80058470 00000000 */   nop
/* 48C74 80058474 20610108 */  j          LIBMCRD_OBJ_16E4
/* 48C78 80058478 00000000 */   nop
.L8005847C:
/* 48C7C 8005847C 21100000 */  addu       $v0, $zero, $zero
.size MemCardCreateFile, . - MemCardCreateFile

glabel LIBMCRD_OBJ_16E4
/* 48C80 80058480 4000BF8F */  lw         $ra, 0x40($sp)
/* 48C84 80058484 3C00B38F */  lw         $s3, 0x3C($sp)
/* 48C88 80058488 3800B28F */  lw         $s2, 0x38($sp)
/* 48C8C 8005848C 3400B18F */  lw         $s1, 0x34($sp)
/* 48C90 80058490 3000B08F */  lw         $s0, 0x30($sp)
/* 48C94 80058494 0800E003 */  jr         $ra
/* 48C98 80058498 4800BD27 */   addiu     $sp, $sp, 0x48
.size LIBMCRD_OBJ_16E4, . - LIBMCRD_OBJ_16E4

glabel MemCardFormat
/* 48C9C 8005849C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 48CA0 800584A0 0880023C */  lui        $v0, %hi(D_80079448)
/* 48CA4 800584A4 48944224 */  addiu      $v0, $v0, %lo(D_80079448)
/* 48CA8 800584A8 1000BFAF */  sw         $ra, 0x10($sp)
/* 48CAC 800584AC 0000428C */  lw         $v0, 0x0($v0)
/* 48CB0 800584B0 00000000 */  nop
/* 48CB4 800584B4 06004010 */  beqz       $v0, .L800584D0
/* 48CB8 800584B8 00000000 */   nop
/* 48CBC 800584BC 0180043C */  lui        $a0, %hi(D_8001310C)
/* 48CC0 800584C0 9361000C */  jal        printf
/* 48CC4 800584C4 0C318424 */   addiu     $a0, $a0, %lo(D_8001310C)
/* 48CC8 800584C8 40610108 */  j          LIBMCRD_OBJ_1764
/* 48CCC 800584CC FFFF0224 */   addiu     $v0, $zero, -0x1
.L800584D0:
/* 48CD0 800584D0 6764010C */  jal        _card_format2
/* 48CD4 800584D4 00000000 */   nop
/* 48CD8 800584D8 21204000 */  addu       $a0, $v0, $zero
/* 48CDC 800584DC 07008010 */  beqz       $a0, .L800584FC
/* 48CE0 800584E0 04000224 */   addiu     $v0, $zero, 0x4
/* 48CE4 800584E4 06008210 */  beq        $a0, $v0, LIBMCRD_OBJ_1764
/* 48CE8 800584E8 02000224 */   addiu     $v0, $zero, 0x2
/* 48CEC 800584EC 4461010C */  jal        LIBMCRD_OBJ_1774
/* 48CF0 800584F0 00000000 */   nop
/* 48CF4 800584F4 40610108 */  j          LIBMCRD_OBJ_1764
/* 48CF8 800584F8 00000000 */   nop
.L800584FC:
/* 48CFC 800584FC 21100000 */  addu       $v0, $zero, $zero
.size MemCardFormat, . - MemCardFormat

glabel LIBMCRD_OBJ_1764
/* 48D00 80058500 1000BF8F */  lw         $ra, 0x10($sp)
/* 48D04 80058504 1800BD27 */  addiu      $sp, $sp, 0x18
/* 48D08 80058508 0800E003 */  jr         $ra
/* 48D0C 8005850C 00000000 */   nop
.size LIBMCRD_OBJ_1764, . - LIBMCRD_OBJ_1764

glabel LIBMCRD_OBJ_1774
/* 48D10 80058510 01000224 */  addiu      $v0, $zero, 0x1
/* 48D14 80058514 10008210 */  beq        $a0, $v0, .L80058558
/* 48D18 80058518 21180000 */   addu      $v1, $zero, $zero
/* 48D1C 8005851C 02008228 */  slti       $v0, $a0, 0x2
/* 48D20 80058520 05004010 */  beqz       $v0, .L80058538
/* 48D24 80058524 00000000 */   nop
/* 48D28 80058528 0C008010 */  beqz       $a0, LIBMCRD_OBJ_17C0
/* 48D2C 8005852C 00000000 */   nop
/* 48D30 80058530 57610108 */  j          LIBMCRD_OBJ_17C0
/* 48D34 80058534 00808334 */   ori       $v1, $a0, 0x8000
.L80058538:
/* 48D38 80058538 02000224 */  addiu      $v0, $zero, 0x2
/* 48D3C 8005853C 07008210 */  beq        $a0, $v0, LIBMCRD_OBJ_17C0
/* 48D40 80058540 01000324 */   addiu     $v1, $zero, 0x1
/* 48D44 80058544 04000224 */  addiu      $v0, $zero, 0x4
/* 48D48 80058548 04008214 */  bne        $a0, $v0, LIBMCRD_OBJ_17C0
/* 48D4C 8005854C 00808334 */   ori       $v1, $a0, 0x8000
/* 48D50 80058550 57610108 */  j          LIBMCRD_OBJ_17C0
/* 48D54 80058554 03000324 */   addiu     $v1, $zero, 0x3
.L80058558:
/* 48D58 80058558 02000324 */  addiu      $v1, $zero, 0x2
.size LIBMCRD_OBJ_1774, . - LIBMCRD_OBJ_1774

glabel LIBMCRD_OBJ_17C0
/* 48D5C 8005855C 0800E003 */  jr         $ra
/* 48D60 80058560 21106000 */   addu      $v0, $v1, $zero
.size LIBMCRD_OBJ_17C0, . - LIBMCRD_OBJ_17C0

glabel LIBMCRD_OBJ_17C8
/* 48D64 80058564 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 48D68 80058568 1000BFAF */  sw         $ra, 0x10($sp)
/* 48D6C 8005856C B562010C */  jal        UserFuncComplete
/* 48D70 80058570 00000000 */   nop
/* 48D74 80058574 18004014 */  bnez       $v0, .L800585D8
/* 48D78 80058578 00000000 */   nop
/* 48D7C 8005857C 9A62010C */  jal        UserFuncExecute
/* 48D80 80058580 00000000 */   nop
/* 48D84 80058584 B562010C */  jal        UserFuncComplete
/* 48D88 80058588 00000000 */   nop
/* 48D8C 8005858C 12004010 */  beqz       $v0, .L800585D8
/* 48D90 80058590 01000224 */   addiu     $v0, $zero, 0x1
/* 48D94 80058594 0880033C */  lui        $v1, %hi(D_80079448)
/* 48D98 80058598 48946324 */  addiu      $v1, $v1, %lo(D_80079448)
/* 48D9C 8005859C 080062AC */  sw         $v0, 0x8($v1)
/* 48DA0 800585A0 0000628C */  lw         $v0, 0x0($v1)
/* 48DA4 800585A4 0880053C */  lui        $a1, %hi(D_80079438)
/* 48DA8 800585A8 3894A524 */  addiu      $a1, $a1, %lo(D_80079438)
/* 48DAC 800585AC 0000A2AC */  sw         $v0, 0x0($a1)
/* 48DB0 800585B0 0400628C */  lw         $v0, 0x4($v1)
/* 48DB4 800585B4 4400668C */  lw         $a2, 0x44($v1)
/* 48DB8 800585B8 0400A2AC */  sw         $v0, 0x4($a1)
/* 48DBC 800585BC 000060AC */  sw         $zero, 0x0($v1)
/* 48DC0 800585C0 0500C010 */  beqz       $a2, .L800585D8
/* 48DC4 800585C4 040060AC */   sw        $zero, 0x4($v1)
/* 48DC8 800585C8 0000A48C */  lw         $a0, 0x0($a1)
/* 48DCC 800585CC 0400A58C */  lw         $a1, 0x4($a1)
/* 48DD0 800585D0 09F8C000 */  jalr       $a2
/* 48DD4 800585D4 00000000 */   nop
.L800585D8:
/* 48DD8 800585D8 0880023C */  lui        $v0, %hi(D_80079448)
/* 48DDC 800585DC 48944224 */  addiu      $v0, $v0, %lo(D_80079448)
/* 48DE0 800585E0 5000438C */  lw         $v1, 0x50($v0)
/* 48DE4 800585E4 00000000 */  nop
/* 48DE8 800585E8 01006324 */  addiu      $v1, $v1, 0x1
/* 48DEC 800585EC 500043AC */  sw         $v1, 0x50($v0)
/* 48DF0 800585F0 5400438C */  lw         $v1, 0x54($v0)
/* 48DF4 800585F4 00000000 */  nop
/* 48DF8 800585F8 01006324 */  addiu      $v1, $v1, 0x1
/* 48DFC 800585FC 540043AC */  sw         $v1, 0x54($v0)
/* 48E00 80058600 1000BF8F */  lw         $ra, 0x10($sp)
/* 48E04 80058604 1800BD27 */  addiu      $sp, $sp, 0x18
/* 48E08 80058608 0800E003 */  jr         $ra
/* 48E0C 8005860C 00000000 */   nop
.size LIBMCRD_OBJ_17C8, . - LIBMCRD_OBJ_17C8

glabel LIBMCRD_OBJ_1874
/* 48E10 80058610 21308000 */  addu       $a2, $a0, $zero
/* 48E14 80058614 2138A000 */  addu       $a3, $a1, $zero
/* 48E18 80058618 0180053C */  lui        $a1, %hi(D_8001312C)
/* 48E1C 8005861C 2C31A524 */  addiu      $a1, $a1, %lo(D_8001312C)
/* 48E20 80058620 0300A288 */  lwl        $v0, 0x3($a1)
/* 48E24 80058624 0000A298 */  lwr        $v0, 0x0($a1)
/* 48E28 80058628 0400A380 */  lb         $v1, 0x4($a1)
/* 48E2C 8005862C 0500A480 */  lb         $a0, 0x5($a1)
/* 48E30 80058630 0300E2A8 */  swl        $v0, 0x3($a3)
/* 48E34 80058634 0000E2B8 */  swr        $v0, 0x0($a3)
/* 48E38 80058638 0400E3A0 */  sb         $v1, 0x4($a3)
/* 48E3C 8005863C 0500E4A0 */  sb         $a0, 0x5($a3)
/* 48E40 80058640 0200C104 */  bgez       $a2, .L8005864C
/* 48E44 80058644 2110C000 */   addu      $v0, $a2, $zero
/* 48E48 80058648 0F00C224 */  addiu      $v0, $a2, 0xF
.L8005864C:
/* 48E4C 8005864C 03110200 */  sra        $v0, $v0, 4
/* 48E50 80058650 30004324 */  addiu      $v1, $v0, 0x30
/* 48E54 80058654 00110200 */  sll        $v0, $v0, 4
/* 48E58 80058658 2310C200 */  subu       $v0, $a2, $v0
/* 48E5C 8005865C 30004224 */  addiu      $v0, $v0, 0x30
/* 48E60 80058660 0200E3A0 */  sb         $v1, 0x2($a3)
/* 48E64 80058664 0800E003 */  jr         $ra
/* 48E68 80058668 0300E2A0 */   sb        $v0, 0x3($a3)
.size LIBMCRD_OBJ_1874, . - LIBMCRD_OBJ_1874
