.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.16.1.dev0 */

glabel UserFuncInit
/* 491DC 800589DC FFFF0224 */  addiu      $v0, $zero, -0x1
/* 491E0 800589E0 0780013C */  lui        $at, %hi(D_8006A2BC)
/* 491E4 800589E4 0800E003 */  jr         $ra
/* 491E8 800589E8 BCA222AC */   sw        $v0, %lo(D_8006A2BC)($at)
.size UserFuncInit, . - UserFuncInit

glabel UserFuncOpen
/* 491EC 800589EC 0780023C */  lui        $v0, %hi(D_8006A2BC)
/* 491F0 800589F0 BCA2428C */  lw         $v0, %lo(D_8006A2BC)($v0)
/* 491F4 800589F4 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 491F8 800589F8 01004624 */  addiu      $a2, $v0, 0x1
/* 491FC 800589FC 0400C228 */  slti       $v0, $a2, 0x4
/* 49200 80058A00 06004014 */  bnez       $v0, .L80058A1C
/* 49204 80058A04 1000BFAF */   sw        $ra, 0x10($sp)
/* 49208 80058A08 0180043C */  lui        $a0, %hi(D_80013138)
/* 4920C 80058A0C 9361000C */  jal        printf
/* 49210 80058A10 38318424 */   addiu     $a0, $a0, %lo(D_80013138)
/* 49214 80058A14 96620108 */  j          USERFUNC_OBJ_7C
/* 49218 80058A18 00000000 */   nop
.L80058A1C:
/* 4921C 80058A1C 03000524 */  addiu      $a1, $zero, 0x3
/* 49220 80058A20 00110600 */  sll        $v0, $a2, 4
/* 49224 80058A24 0880033C */  lui        $v1, %hi(D_800794E4)
/* 49228 80058A28 E4946324 */  addiu      $v1, $v1, %lo(D_800794E4)
/* 4922C 80058A2C 21184300 */  addu       $v1, $v0, $v1
/* 49230 80058A30 80100600 */  sll        $v0, $a2, 2
/* 49234 80058A34 0780013C */  lui        $at, %hi(D_8006A2BC)
/* 49238 80058A38 BCA226AC */  sw         $a2, %lo(D_8006A2BC)($at)
/* 4923C 80058A3C 0880013C */  lui        $at, %hi(D_80079518)
/* 49240 80058A40 21082200 */  addu       $at, $at, $v0
/* 49244 80058A44 189524AC */  sw         $a0, %lo(D_80079518)($at)
.L80058A48:
/* 49248 80058A48 000060AC */  sw         $zero, 0x0($v1)
/* 4924C 80058A4C FFFFA524 */  addiu      $a1, $a1, -0x1
/* 49250 80058A50 FDFFA104 */  bgez       $a1, .L80058A48
/* 49254 80058A54 FCFF6324 */   addiu     $v1, $v1, -0x4
.size UserFuncOpen, . - UserFuncOpen

glabel USERFUNC_OBJ_7C
/* 49258 80058A58 1000BF8F */  lw         $ra, 0x10($sp)
/* 4925C 80058A5C 1800BD27 */  addiu      $sp, $sp, 0x18
/* 49260 80058A60 0800E003 */  jr         $ra
/* 49264 80058A64 00000000 */   nop
.size USERFUNC_OBJ_7C, . - USERFUNC_OBJ_7C

glabel UserFuncExecute
/* 49268 80058A68 0780033C */  lui        $v1, %hi(D_8006A2BC)
/* 4926C 80058A6C BCA2638C */  lw         $v1, %lo(D_8006A2BC)($v1)
/* 49270 80058A70 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 49274 80058A74 13006004 */  bltz       $v1, .L80058AC4
/* 49278 80058A78 1000BFAF */   sw        $ra, 0x10($sp)
/* 4927C 80058A7C 80100300 */  sll        $v0, $v1, 2
/* 49280 80058A80 00190300 */  sll        $v1, $v1, 4
/* 49284 80058A84 0880043C */  lui        $a0, %hi(D_800794D8)
/* 49288 80058A88 D8948424 */  addiu      $a0, $a0, %lo(D_800794D8)
/* 4928C 80058A8C 0880013C */  lui        $at, %hi(D_80079518)
/* 49290 80058A90 21082200 */  addu       $at, $at, $v0
/* 49294 80058A94 1895228C */  lw         $v0, %lo(D_80079518)($at)
/* 49298 80058A98 00000000 */  nop
/* 4929C 80058A9C 09F84000 */  jalr       $v0
/* 492A0 80058AA0 21206400 */   addu      $a0, $v1, $a0
/* 492A4 80058AA4 07004010 */  beqz       $v0, .L80058AC4
/* 492A8 80058AA8 00000000 */   nop
/* 492AC 80058AAC 0780023C */  lui        $v0, %hi(D_8006A2BC)
/* 492B0 80058AB0 BCA2428C */  lw         $v0, %lo(D_8006A2BC)($v0)
/* 492B4 80058AB4 00000000 */  nop
/* 492B8 80058AB8 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 492BC 80058ABC 0780013C */  lui        $at, %hi(D_8006A2BC)
/* 492C0 80058AC0 BCA222AC */  sw         $v0, %lo(D_8006A2BC)($at)
.L80058AC4:
/* 492C4 80058AC4 1000BF8F */  lw         $ra, 0x10($sp)
/* 492C8 80058AC8 1800BD27 */  addiu      $sp, $sp, 0x18
/* 492CC 80058ACC 0800E003 */  jr         $ra
/* 492D0 80058AD0 00000000 */   nop
.size UserFuncExecute, . - UserFuncExecute

glabel UserFuncComplete
/* 492D4 80058AD4 0780023C */  lui        $v0, %hi(D_8006A2BC)
/* 492D8 80058AD8 BCA2428C */  lw         $v0, %lo(D_8006A2BC)($v0)
/* 492DC 80058ADC 0800E003 */  jr         $ra
/* 492E0 80058AE0 C2170200 */   srl       $v0, $v0, 31
/* 492E4 80058AE4 00000000 */  nop
/* 492E8 80058AE8 00000000 */  nop
.size UserFuncComplete, . - UserFuncComplete
